### PR TITLE
release-21.2: backup: fix backup during 21.2 upgrade

### LINKED ISSUE #72839: backupccl: backups fail during upgrade to v21.2.0
Observed by @adwittumuluri on CockroachCloud:

We're seeing errors like the following for clusters that have been recently upgraded from 21.1 to 21.2:
```
1I211116 20:33:07.555036 43 backupper/main.go:286  sleeping 20m0s {"loop_iteration":"2021-11-16T20:33:06.948Z"}
2I211116 20:53:07.555181 43 backupper/backup.go:66  started backup runner for auto backup {"loop_iteration":"2021-11-16T20:53:07.555Z"}
3I211116 20:53:07.555214 43 backupper/backup.go:208  running a full backup {"loop_iteration":"2021-11-16T20:53:07.555Z"}
4I211116 20:53:08.084279 43 backupper/backup.go:258  finished full backup {"loop_iteration":"2021-11-16T20:53:07.555Z","elapsed_time":0.529054056}
5E211116 20:53:08.084330 43 backupper/backup.go:127  failed backup run {error 25 0  pq: internal error: backup-lookup-tenants: descriptor not found} {"loop_iteration":"2021-11-16T20:53:07.555Z"}
6I211116 20:53:08.180094 43 backupper/main.go:286  sleeping 20m0s {"loop_iteration":"2021-11-16T20:53:07.555Z"}
7I211116 21:13:08.180241 43 backupper/backup.go:66  started backup runner for auto backup {"loop_iteration":"2021-11-16T21:13:08.180Z"}
8I211116 21:13:08.180273 43 backupper/backup.go:208  running a full backup {"loop_iteration":"2021-11-16T21:13:08.180Z"}
9I211116 21:13:08.700771 43 backupper/backup.go:258  finished full backup {"loop_iteration":"2021-11-16T21:13:08.180Z","elapsed_time":0.520495416}
10E211116 21:13:08.700820 43 backupper/backup.go:127  failed backup run {error 25 0  pq: internal error: backup-lookup-tenants: descriptor not found} {"loop_iteration":"2021-11-16T21:13:08.180Z"}
11I211116 21:13:08.778906 43 backupper/main.go:286  sleeping 20m0s {"loop_iteration":"2021-11-16T21:13:08.180Z”}
```

This `backup-lookup-tenants: descriptor not found` are happening for both full and incremental backups.

Diagnosis from @ajwerner:

https://github.com/cockroachdb/cockroach/blob/b664bd9c327b5e56e8ccdce114878ec96c129eb0/pkg/ccl/backupccl/backup_planning_tenant.go#L23-L35 was updated to join against the tenant usage table which is added as a part of a migration. This breaks backups in the mixed-version state.

Likely impact is that backups will fail while the upgrade process is running, but not yet finalized.

### PR DESCRIPTION
**Pull request by RaduBerinde**
The part of the backup code that retrieves the tenant metadata was
updated in #70778. The new code depends on the `system.tenant_usage`
table which is not present in 21.1.

Consequently, this query fails when running 21.2 code on a cluster
that was not finalized to 21.2 version.

This change fixes this by adding an alternate variant of the query
when the tenant usage table is not present (according to the cluster
version).

Fixes #72839.

Release note (bug fix): Fixes "backup-lookup-tenants: descriptor not
found" when doing full cluster backup while upgrading from 21.1 to 21.2.

CC @cockroachdb/release

### CODE REVIEW

**Comment by RaduBerinde** [comment]
I tested manually in a mixed-version roachprod cluster (BACKUP works with and without tenants).

**Review by ajwerner — APPROVED** [review]
For a test, you thinking a mixed-version roachtest? Should be easy to just add a backup stage. In retrospect, a little crazy we don't have more features exercised there. 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72840#-:-MoewTKY736232gQfGlP:bhe70gc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @RaduBerinde, and @stevendanna)

___
*[pkg/ccl/backupccl/backup_planning_tenant.go, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72840#-MoewtFJDhHujGvpDXMC:-MoewtFJDhHujGvpDXMD:b9etyqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/da2617afdbae4dca14290824516bf3b200073d6a/pkg/ccl/backupccl/backup_planning_tenant.go#L54)):*
> ```Go
>   tenants.active,   /* 1 */
>   tenants.info,     /* 2 */
> 	NULL,             /* 3 */
> ```

nit: weird indentation
___
*[pkg/ccl/backupccl/backup_planning_tenant.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72840#-MoexG5yAYonVS7LWBYQ:-Moewz9EDBxXKvbyZIOX:br0nwbj) ([raw file](https://github.com/cockroachdb/cockroach/blob/da2617afdbae4dca14290824516bf3b200073d6a/pkg/ccl/backupccl/backup_planning_tenant.go#L111)):*
> ```Go
> 	row, err := ie.QueryRow(
> 		ctx, "backup-lookup-tenant", txn,
> 		tenantMetadataQuery(ctx, settings)+` WHERE id = $1`,
> ```

I think I have a modest preference for plumbing this as a boolean or something to to the function which constructs the query string so I don't have to think here whether the query is going to be sound, but it's not a very strong preference.

**Review by RaduBerinde — COMMENTED** [review]
Looking into adding a roachtest.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72840#-:-MoezjWo86BjrOTRcpKJ:b-nf66p9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @RaduBerinde, and @stevendanna)

___
*[pkg/ccl/backupccl/backup_planning_tenant.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72840#-MoexG5yAYonVS7LWBYQ:-Moezcte8mmos8zMRNP-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/da2617afdbae4dca14290824516bf3b200073d6a/pkg/ccl/backupccl/backup_planning_tenant.go#L111)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think I have a modest preference for plumbing this as a boolean or something to to the function which constructs the query string so I don't have to think here whether the query is going to be sound, but it's not a very strong preference.
</blockquote></details>

Done.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72840#-:-Mof-2t39mEaClKU2_ai:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @stevendanna)

File: pkg/ccl/backupccl/backup_planning_tenant.go [hunk 1]
```diff
@@ -11,16 +11,33 @@ package backupccl
...
 	"github.com/cockroachdb/errors"
 )
 
-const tenantMetadataQuery = `
+// tenantMetadataQuery returns a query used to retrieve the tenant metadata.
+//
+// If filterByID is true, the query contains a `WHERE id = $1` clause.
+func tenantMetadataQuery(ctx context.Context, settings *cluster.Settings, filterByID bool) string {
+	query := tenantMetadataQueryWithTenantUsageTable
+	if !settings.Version.IsActive(ctx, clusterversion.TenantUsageTable) {
```
Comment (stevendanna) [inline pkg/ccl/backupccl/backup_planning_tenant.go:30]: We also depend on the `TenantUsageSingleConsumptionColumn`, but the window between these two migrations should be incredibly small I imagine.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72840)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @dt, and @stevendanna)

___
*[pkg/ccl/backupccl/backup_planning_tenant.go, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72840#-MoevgCD3tZn1hjtMCwN-r2-30:-MofNcVk2LxrRDzZ0o-L:b-ep1is5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1b27e258ceaccb9b8823edd7dfd7e6f5d73bedb/pkg/ccl/backupccl/backup_planning_tenant.go#L30)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

We also depend on the `TenantUsageSingleConsumptionColumn` migration, but the window between these two migrations should be incredibly small I imagine.
</blockquote></details>

Interesting catch. Added the check, can't hurt. I believe that the tenant table gets created with the updated schema directly in `TenantUsageTable` migration; the `TenantUsageSingleConsumptionColumn` should be a no-op unless you used some 21.2.beta.

**Review by stevendanna — APPROVED** [review]

File: pkg/ccl/backupccl/backup_planning_tenant.go [hunk 2]
```diff
@@ -11,16 +11,34 @@ package backupccl
...
 )
 
-const tenantMetadataQuery = `
+// tenantMetadataQuery returns a query used to retrieve the tenant metadata.
+//
+// If filterByID is true, the query contains a `WHERE id = $1` clause.
+func tenantMetadataQuery(ctx context.Context, settings *cluster.Settings, filterByID bool) string {
+	query := tenantMetadataQueryWithTenantUsageTable
+	if !settings.Version.IsActive(ctx, clusterversion.TenantUsageTable) ||
+		!settings.Version.IsActive(ctx, clusterversion.TenantUsageSingleConsumptionColumn) {
```
Comment (dt) [inline pkg/ccl/backupccl/backup_planning_tenant.go:31]: technically I think you only need the second one, since `!TenantUsageSingleConsumptionColumn` implies `!TenantUsageTable`, but correct either way

**Review by dt — APPROVED** [review]

File: pkg/ccl/backupccl/backup_planning_tenant.go (hunk 2 above)
Comment (RaduBerinde) [reply pkg/ccl/backupccl/backup_planning_tenant.go:31]: Good point. I think I want to leave the explicit mention anyway because it's really the `TenantUsageTable` migration that was the issue.

**Comment by RaduBerinde** [comment]
Done, I stressed the test with 1m timeout and didn't see any issues (`1121 runs so far, 0 failures, over 5m5s`).
