### PR TITLE
backup: compactions can now trigger more compactions after completion

### LINKED ISSUE #157110: roachtest: restore/online/workload=false/tpcc-5k/gce/nodes=4/cpus=8 failed
roachtest.restore/online/workload=false/tpcc-5k/gce/nodes=4/cpus=8 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20714731?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20714731?buildTab=artifacts#/restore/online/workload=false/tpcc-5k/gce/nodes=4/cpus=8) on master @ [ddeef368172658dddb47811fe0fcdcaf5abbe8ee](https://github.com/cockroachdb/cockroach/commits/ddeef368172658dddb47811fe0fcdcaf5abbe8ee):

```
(assertions.go:369).Fail: 
	Error Trace:	pkg/cmd/roachtest/tests/online_restore.go:692
	            				pkg/cmd/roachtest/tests/online_restore.go:304
	            				pkg/cmd/roachtest/test_runner.go:1537
	            				src/runtime/asm_amd64.s:1693
	Error:      	Received unexpected error:
	            	pq: experimental online restore: too many incremental layers 12 (from backup) > 10 (limit)
	Test:       	restore/online/workload=false/tpcc-5k/gce/nodes=4/cpus=8
	Messages:   	failed to execute restore phase
(require.go:1357).NoError: FailNow called
test artifacts and logs in: /artifacts/restore/online/workload=false/tpcc-5k/gce/nodes=4/cpus=8/cpu_arch=arm64/run_1
```

Parameters:
 - <code>arch=arm64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=8</code>
 - <code>encrypted=false</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20714731/restore-online-workload-false-tpcc-5k-gce-nodes-4-cpus-8/1762686258798/1762686509684)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*restore/online/workload=false/tpcc-5k/gce/nodes=4/cpus=8.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-56364

### LINKED ISSUE #157912: roachtest: restore/online/workload=true/tpcc-5k/gce/fullOnly/nodes=4/cpus=8 failed
roachtest.restore/online/workload=true/tpcc-5k/gce/fullOnly/nodes=4/cpus=8 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20740795?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20740795?buildTab=artifacts#/restore/online/workload=true/tpcc-5k/gce/fullOnly/nodes=4/cpus=8) on master @ [6816c43040b24bb221d00717c91f6a68a1a8e191](https://github.com/cockroachdb/cockroach/commits/6816c43040b24bb221d00717c91f6a68a1a8e191):

```
(assertions.go:369).Fail: 
	Error Trace:	pkg/cmd/roachtest/tests/online_restore.go:692
	            				pkg/cmd/roachtest/tests/online_restore.go:304
	            				pkg/cmd/roachtest/test_runner.go:1537
	            				src/runtime/asm_amd64.s:1693
	Error:      	Received unexpected error:
	            	pq: experimental online restore: too many incremental layers 13 (from backup) > 10 (limit)
	Test:       	restore/online/workload=true/tpcc-5k/gce/fullOnly/nodes=4/cpus=8
	Messages:   	failed to execute restore phase
(require.go:1357).NoError: FailNow called
test artifacts and logs in: /artifacts/restore/online/workload=true/tpcc-5k/gce/fullOnly/nodes=4/cpus=8/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=8</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=false</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20740795/restore-online-workload-true-tpcc-5k-gce-fullonly-nodes-4-cpus/1763387381459/1763387616436)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*restore/online/workload=true/tpcc-5k/gce/fullOnly/nodes=4/cpus=8.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-57015

### LINKED ISSUE #157913: roachtest: restore/online/workload=true/tpcc-5k/gce/nodes=4/cpus=8 failed
roachtest.restore/online/workload=true/tpcc-5k/gce/nodes=4/cpus=8 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20740795?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20740795?buildTab=artifacts#/restore/online/workload=true/tpcc-5k/gce/nodes=4/cpus=8) on master @ [6816c43040b24bb221d00717c91f6a68a1a8e191](https://github.com/cockroachdb/cockroach/commits/6816c43040b24bb221d00717c91f6a68a1a8e191):

```
(assertions.go:369).Fail: 
	Error Trace:	pkg/cmd/roachtest/tests/online_restore.go:692
	            				pkg/cmd/roachtest/tests/online_restore.go:304
	            				pkg/cmd/roachtest/test_runner.go:1537
	            				src/runtime/asm_amd64.s:1693
	Error:      	Received unexpected error:
	            	pq: experimental online restore: too many incremental layers 13 (from backup) > 10 (limit)
	Test:       	restore/online/workload=true/tpcc-5k/gce/nodes=4/cpus=8
	Messages:   	failed to execute restore phase
(require.go:1357).NoError: FailNow called
test artifacts and logs in: /artifacts/restore/online/workload=true/tpcc-5k/gce/nodes=4/cpus=8/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=8</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=false</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20740795/restore-online-workload-true-tpcc-5k-gce-nodes-4-cpus-8/1763387471640/1763387701041)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*restore/online/workload=true/tpcc-5k/gce/nodes=4/cpus=8.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-57016

### LINKED ISSUE #161353: roachtest: backupFixture/tpcc/warehouses=30000/incrementals=400 failed
roachtest.backupFixture/tpcc/warehouses=30000/incrementals=400 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyBazel/20992936?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyBazel/20992936?buildTab=artifacts#/backupFixture/tpcc/warehouses=30000/incrementals=400) on master @ [377adba1a7814b2b18b3ad19462efbd9c8226b98](https://github.com/cockroachdb/cockroach/commits/377adba1a7814b2b18b3ad19462efbd9c8226b98):

Failed with:

```
(assertions.go:369).Fail: 
	Error Trace:	pkg/cmd/roachtest/tests/backup_fixtures.go:696
	            				pkg/cmd/roachtest/test_runner.go:1546
	            				src/runtime/asm_amd64.s:1693
	Error:      	Received unexpected error:
	            	error starting restore job: pq: experimental online restore: too many incremental layers 22 (from backup) > 10 (limit)
	            	(1) attached stack trace
	            	  -- stack trace:
	            	  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*backupDriver).checkRestorability
	            	  | 	pkg/cmd/roachtest/tests/backup_fixtures.go:456
	            	  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerBackupFixtures.func1
	            	  | 	pkg/cmd/roachtest/tests/backup_fixtures.go:696
	            	  | main.(*testRunner).runTest.func2
	            	  | 	pkg/cmd/roachtest/test_runner.go:1546
	            	  | runtime.goexit
	            	  | 	src/runtime/asm_amd64.s:1693
	            	Wraps: (2) error starting restore job
	            	Wraps: (3) pq: experimental online restore: too many incremental layers 22 (from backup) > 10 (limit)
	            	Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *pq.Error
	Test:       	backupFixture/tpcc/warehouses=30000/incrementals=400
(require.go:1357).NoError: FailNow called
test artifacts and logs in: /artifacts/backupFixture/tpcc/warehouses=30000/incrementals=400/run_1
```
Cluster Node to Ip Mapping:
| Node | Public IP | Private IP |
| --- | --- | --- |
| teamcity-20992936-1768632694-29-n10cpu16-0001 | 34.138.16.158 | 10.142.1.176 |
| teamcity-20992936-1768632694-29-n10cpu16-0002 | 34.23.41.126 | 10.142.1.244 |
| teamcity-20992936-1768632694-29-n10cpu16-0003 | 35.196.172.201 | 10.142.0.127 |
| teamcity-20992936-1768632694-29-n10cpu16-0004 | 34.26.185.131 | 10.142.3.32 |
| teamcity-20992936-1768632694-29-n10cpu16-0005 | 34.75.101.206 | 10.142.1.155 |
| teamcity-20992936-1768632694-29-n10cpu16-0006 | 35.227.22.13 | 10.142.1.249 |
| teamcity-20992936-1768632694-29-n10cpu16-0007 | 35.237.143.64 | 10.142.1.141 |
| teamcity-20992936-1768632694-29-n10cpu16-0008 | 34.23.77.120 | 10.142.2.44 |
| teamcity-20992936-1768632694-29-n10cpu16-0009 | 34.148.141.158 | 10.142.3.245 |
| teamcity-20992936-1768632694-29-n10cpu16-0010 | 104.196.40.205 | 10.142.15.201 |

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=16</code>
 - <code>diskCount=0</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=false</code>
 - <code>runtimeAssertionsBuild=false</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20992936/backupfixture-tpcc-warehouses-30000-incrementals-400/1768640078553/1768670246630)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backupFixture/tpcc/warehouses=30000/incrementals=400.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-58816

### LINKED ISSUE #161373: roachtest: backupFixture/tpcc/warehouses=300000/incrementals=400 failed
roachtest.backupFixture/tpcc/warehouses=300000/incrementals=400 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyBazel/20992936?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyBazel/20992936?buildTab=artifacts#/backupFixture/tpcc/warehouses=300000/incrementals=400) on master @ [377adba1a7814b2b18b3ad19462efbd9c8226b98](https://github.com/cockroachdb/cockroach/commits/377adba1a7814b2b18b3ad19462efbd9c8226b98):

Failed with:

```
(assertions.go:369).Fail: 
	Error Trace:	pkg/cmd/roachtest/tests/backup_fixtures.go:696
	            				pkg/cmd/roachtest/test_runner.go:1546
	            				src/runtime/asm_amd64.s:1693
	Error:      	Received unexpected error:
	            	error starting restore job: pq: experimental online restore: too many incremental layers 13 (from backup) > 10 (limit)
	            	(1) attached stack trace
	            	  -- stack trace:
	            	  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*backupDriver).checkRestorability
	            	  | 	pkg/cmd/roachtest/tests/backup_fixtures.go:456
	            	  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerBackupFixtures.func1
	            	  | 	pkg/cmd/roachtest/tests/backup_fixtures.go:696
	            	  | main.(*testRunner).runTest.func2
	            	  | 	pkg/cmd/roachtest/test_runner.go:1546
	            	  | runtime.goexit
	            	  | 	src/runtime/asm_amd64.s:1693
	            	Wraps: (2) error starting restore job
	            	Wraps: (3) pq: experimental online restore: too many incremental layers 13 (from backup) > 10 (limit)
	            	Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *pq.Error
	Test:       	backupFixture/tpcc/warehouses=300000/incrementals=400
(require.go:1357).NoError: FailNow called
test artifacts and logs in: /artifacts/backupFixture/tpcc/warehouses=300000/incrementals=400/run_1
```
Cluster Node to Ip Mapping:
| Node | Public IP | Private IP |
| --- | --- | --- |
| teamcity-20992936-1768632694-99-n10cpu32-0001 | 35.229.35.150 | 10.142.0.16 |
| teamcity-20992936-1768632694-99-n10cpu32-0002 | 35.185.35.35 | 10.142.0.53 |
| teamcity-20992936-1768632694-99-n10cpu32-0003 | 34.75.52.69 | 10.142.0.24 |
| teamcity-20992936-1768632694-99-n10cpu32-0004 | 35.229.74.190 | 10.142.0.101 |
| teamcity-20992936-1768632694-99-n10cpu32-0005 | 34.23.40.149 | 10.142.0.102 |
| teamcity-20992936-1768632694-99-n10cpu32-0006 | 34.139.169.247 | 10.142.0.25 |
| teamcity-20992936-1768632694-99-n10cpu32-0007 | 34.75.81.248 | 10.142.0.162 |
| teamcity-20992936-1768632694-99-n10cpu32-0008 | 34.26.204.131 | 10.142.0.112 |
| teamcity-20992936-1768632694-99-n10cpu32-0009 | 34.139.180.231 | 10.142.0.99 |
| teamcity-20992936-1768632694-99-n10cpu32-0010 | 34.74.160.194 | 10.142.0.199 |

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=32</code>
 - <code>diskCount=0</code>
 - <code>encrypted=true</code>
 - <code>fs=ext4</code>
 - <code>localSSD=false</code>
 - <code>metamorphicWriteBuffering=true</code>
 - <code>runtimeAssertionsBuild=false</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20992936/backupfixture-tpcc-warehouses-300000-incrementals-400/1768686937809/1768788027812)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backupFixture/tpcc/warehouses=300000/incrementals=400.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-58832

### PR DESCRIPTION
**Pull request by kev-cao**
This teaches backup compactions to potentially trigger another compaction job after completion. This contrasts against the current implementation where we must wait until the next run of the schedule. This means that during the downtime in between backups, compactions can gradually repair the chain.

Epic: None

Fixes: #161373

Fixes: #161353 

Fixes: #157913

Fixes: #157912

Fixes: #157110

Release note: None

### CODE REVIEW

File: pkg/backup/compaction_job.go [hunk 1]
```diff
@@ -959,6 +991,44 @@ func getScheduledExecutionArgsAndCheckCompactionLock(
...
+
+	if indexExists, err := backupinfo.IndexExists(
+		ctx, rootStore, details.Destination.Subdir,
+	); err != nil {
+		return hlc.Timestamp{}, err
+	} else if !indexExists {
+		return hlc.Timestamp{}, errors.New("no backup indexes found in backup collection")
+	}
+
+	indexes, err := backupinfo.ListIndexes(
```
Comment (msbutler) [inline pkg/backup/compaction_job.go]: why not use `backupinfo.FindLatestBackup`? I think that would prevent you from making all those other changes to `ListIndexes`

Comment (kev-cao) [reply pkg/backup/compaction_job.go]: `FindLatestBackup` gives you the latest backup in the entire collection, so it's not necessarily the same backup chain.

Comment (msbutler) [reply pkg/backup/compaction_job.go]: wait, why can't we just pass maxHLC as the end time, given that we pass tiggerjob's subdir, guaranteeing that we're working on the same chain?

Comment (msbutler) [reply pkg/backup/compaction_job.go]: currently, i feel like the complexity this PR introduces, outweighs the benefits, so i'm trying to see if there's a simpler fix here.

Comment (kev-cao) [reply pkg/backup/compaction_job.go]: > why can't we just pass maxHLC as the end time

Oh actually, taking a look at `ResolveBackupManifests`, we could pass in an empty HLC timestamp, in which case it'll assume you want the entire chain.

I can update that — also I'll add a comment to the docstring for `ResolveBackupManifests` and `ValidateEndTimeAndTruncate` about it.

Comment (msbutler) [reply pkg/backup/compaction_job.go]: looks much simpler! but now i'm wondering if it can go further: why in the og compaction do we need to pass an explicit end time?

Comment (kev-cao) [reply pkg/backup/compaction_job.go]: I think it was just carryover from the fact that the builtin takes in an explicit end time, but there isn't a real reason why `maybeStartCompactions` should require an explicit end time.

File: pkg/backup/compaction_job.go [hunk 2]
```diff
@@ -116,8 +115,13 @@ func maybeStartCompactionJob(
 	}
 
 	chain, _, _, _, err := getBackupChain(
```
Comment (msbutler) [inline pkg/backup/compaction_job.go:117]: you could remove the endtime arg from getBackupChain if you wanted to as well.

**Review by msbutler — APPROVED** [review]
So clean!

File: pkg/backup/compaction_job.go (hunk 2 above)
Comment (kev-cao) [reply pkg/backup/compaction_job.go:117]: Oh keeping this just because during the compaction job, it fetches the chain again, but at that point we've already decided what we're compacting up to, so no need to fetch the entire chain.
