### PR TITLE
kvserver: prevent recursive Replica.mu.RLock

### LINKED ISSUE #96931: kv/kvserver: TestStoreAddRemoveRanges failed
kv/kvserver.TestStoreAddRemoveRanges [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/8657152?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/8657152?buildTab=artifacts#/) on master @ [9ea0ef2f6a8e31e22c7350de5cacd9c5992d07a0](https://github.com/cockroachdb/cockroach/commits/9ea0ef2f6a8e31e22c7350de5cacd9c5992d07a0):

```

goroutine 118907905 lock 0xc014e24460
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/metrics.go:2110 kvserver.(*TenantsStorageMetrics).acquireTenant ??? <<<<<
github.com/sasha-s/go-deadlock/external/com_github_sasha_s_go_deadlock/deadlock.go:84 go-deadlock.(*Mutex).Lock ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/metrics_test.go:79 kvserver.TestTenantsStorageMetricsConcurrency.func2 ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/metrics_test.go:91 kvserver.TestTenantsStorageMetricsConcurrency.func3 ???

goroutine 118907733 lock 0xc01bdc1ea0
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/metrics.go:2110 kvserver.(*TenantsStorageMetrics).acquireTenant ??? <<<<<
github.com/sasha-s/go-deadlock/external/com_github_sasha_s_go_deadlock/deadlock.go:84 go-deadlock.(*Mutex).Lock ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/metrics_test.go:79 kvserver.TestTenantsStorageMetricsConcurrency.func2 ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/metrics_test.go:91 kvserver.TestTenantsStorageMetricsConcurrency.func3 ???

goroutine 118907850 lock 0xc01c898d20
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/metrics.go:2110 kvserver.(*TenantsStorageMetrics).acquireTenant ??? <<<<<
github.com/sasha-s/go-deadlock/external/com_github_sasha_s_go_deadlock/deadlock.go:84 go-deadlock.(*Mutex).Lock ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/metrics_test.go:79 kvserver.TestTenantsStorageMetricsConcurrency.func2 ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/metrics_test.go:91 kvserver.TestTenantsStorageMetricsConcurrency.func3 ???

goroutine 118907884 lock 0xc02497c1e0
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/metrics.go:2110 kvserver.(*TenantsStorageMetrics).acquireTenant ??? <<<<<
github.com/sasha-s/go-deadlock/external/com_github_sasha_s_go_deadlock/deadlock.go:84 go-deadlock.(*Mutex).Lock ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/metrics_test.go:79 kvserver.TestTenantsStorageMetricsConcurrency.func2 ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/metrics_test.go:91 kvserver.TestTenantsStorageMetricsConcurrency.func3 ???

goroutine 118907754 lock 0xc01f42fcc0
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/metrics.go:2110 kvserver.(*TenantsStorageMetrics).acquireTenant ??? <<<<<
github.com/sasha-s/go-deadlock/external/com_github_sasha_s_go_deadlock/deadlock.go:84 go-deadlock.(*Mutex).Lock ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/metrics_test.go:79 kvserver.TestTenantsStorageMetricsConcurrency.func2 ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/metrics_test.go:91 kvserver.TestTenantsStorageMetricsConcurrency.func3 ???

goroutine 118907898 lock 0xc02105f180
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/metrics.go:2110 kvserver.(*TenantsStorageMetrics).acquireTenant ??? <<<<<
github.com/sasha-s/go-deadlock/external/com_github_sasha_s_go_deadlock/deadlock.go:84 go-deadlock.(*Mutex).Lock ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/metrics_test.go:79 kvserver.TestTenantsStorageMetricsConcurrency.func2 ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/metrics_test.go:91 kvserver.TestTenantsStorageMetricsConcurrency.func3 ???

goroutine 118907674 lock 0xc01db9d360
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/metrics.go:2110 kvserver.(*TenantsStorageMetrics).acquireTenant ??? <<<<<
github.com/sasha-s/go-deadlock/external/com_github_sasha_s_go_deadlock/deadlock.go:84 go-deadlock.(*Mutex).Lock ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/metrics_test.go:79 kvserver.TestTenantsStorageMetricsConcurrency.func2 ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/metrics_test.go:91 kvserver.TestTenantsStorageMetricsConcurrency.func3 ???

goroutine 118907736 lock 0xc01db9d680
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/metrics.go:2110 kvserver.(*TenantsStorageMetrics).acquireTenant ??? <<<<<
github.com/sasha-s/go-deadlock/external/com_github_sasha_s_go_deadlock/deadlock.go:84 go-deadlock.(*Mutex).Lock ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/metrics_test.go:79 kvserver.TestTenantsStorageMetricsConcurrency.func2 ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/metrics_test.go:91 kvserver.TestTenantsStorageMetricsConcurrency.func3 ???


```
<p>Parameters: <code>TAGS=bazel,gss,deadlock</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestStoreAddRemoveRanges.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-24414

### PR DESCRIPTION
**Pull request by pav-kv**
Previously, we were passing an RLocked Replica to addToReplicasByKeyLocked.
That method internally visits the descriptors in replicasByKey, which calls
Desc() that may cause a recursive call to RLock if the added replica intersects
itself. This is only possible in tests which try to reinsert the Replica to the
map; in prod code each Replica is inserted to replicasByKey only once.

This PR avoids the possibility of this deadlock by shifting the responsibility
of locking to the caller.

Fixes #96931

Release note: none
Epic: none

### CODE REVIEW

File: pkg/kv/kvserver/store_create_replica.go [hunk 1]
```diff
@@ -252,12 +252,12 @@ func fromReplicaIsTooOldRLocked(toReplica *Replica, fromReplica *roachpb.Replica
...
-// addToReplicasByKeyLockedReplicaRLocked adds the replica to the replicasByKey
-// btree. The replica must already be in replicasByRangeID. Returns an error if
-// a different replica with the same range ID, or an overlapping replica or
-// placeholder exists in this Store. Replica.mu must be at least read-locked.
-func (s *Store) addToReplicasByKeyLockedReplicaRLocked(repl *Replica) error {
-	desc := repl.descRLocked()
+// addToReplicasByKeyLocked adds the replica to the replicasByKey btree. The
+// replica must already be in replicasByRangeID. Returns an error if a different
+// replica with the same range ID, or an overlapping replica or placeholder
+// exists in this Store.
```
Comment (tbg) [inline pkg/kv/kvserver/store_create_replica.go:258]: > `repl.mu` must be unlocked

You can sort of "assert" that it is by adding `repl.mu.Lock(); repl.mu.Unlock()` at the top of this method.

Comment (tbg) [reply pkg/kv/kvserver/store_create_replica.go:258]: Or maybe we can push this into `addToReplicasByKeyLocked`, which has multiple callers. Do none of them hold a lock on the repl?

**Review by tbg — APPROVED** [review]
Commit message would be helpful:

> Previously, we were passing an RLocked `*Replica` to `(*Store).addToReplicasByKeyLocked`. That method internally visits the descriptors and called `Desc()`, which would constitute a recursive call to `RLock` (caught by the deadlock detector due to the risk of a deadlock in case of an interleaving exclusive lock attempt to the mutex). <explain here how it can happen that while inserting a replica we're visiting the same replica? Was this a split? Or just a test doing funky things?>

File: pkg/kv/kvserver/store_create_replica.go [hunk 2]
```diff
@@ -252,12 +252,12 @@ func fromReplicaIsTooOldRLocked(toReplica *Replica, fromReplica *roachpb.Replica
...
+func (s *Store) addToReplicasByKeyLocked(repl *Replica) error {
+	desc := repl.Desc()
```
Comment (pavelkalinnikov) [inline pkg/kv/kvserver/store_create_replica.go:260]: Now this line deadlocks through `applySnapshot` -> `r.mu.Lock()` -> `markReplicaInitializedLockedReplLocked` -> `addToReplicasByKeyLocked` -> `repl.Desc()` -> `repl.mu.RLock()`.

File: pkg/kv/kvserver/store_create_replica.go (hunk 1 above)
Comment (pavelkalinnikov) [reply pkg/kv/kvserver/store_create_replica.go:258]: There is one caller who holds a lock (`applySnapshot`). This caused a deadlock in this PR.

File: pkg/kv/kvserver/store_create_replica.go (hunk 2 above)
Comment (pavelkalinnikov) [reply pkg/kv/kvserver/store_create_replica.go]: Fixed.

File: pkg/kv/kvserver/store_create_replica.go (hunk 1 above)
Comment (pavelkalinnikov) [reply pkg/kv/kvserver/store_create_replica.go:258]: Fixed.

**Comment by pavelkalinnikov** [comment]
@tbg Could you take another look. The previous version of this PR was deadlock-full. I fixed the deadlock at the cost of some duplication: the caller now passes the replica's `Desc()` or `descRLocked()` depending on the locking state.

**Review by tbg — APPROVED** [review]
👍🏽 
also 😬 at this locking in general

**Comment by pavelkalinnikov** [comment]
bors r=tbg

**Comment by pavelkalinnikov** [comment]
bors cancel

**Comment by pavelkalinnikov** [comment]
bors r=tbg
