### PR TITLE
backupccl: make backup and restore more defensive to stats collections failures

### LINKED ISSUE #61199: backupccl: make BACKUPs more defensive on stats collection failures
We should not be failing the BACKUP if we run into an error computing table stats right at the end of job execution. More likely than not, the customer would like their data to be backed up, and are okay with an expensive stats recomputation on RESTORE. We should log a warning instead.

### PR DESCRIPTION
**Pull request by adityamaru**
Release justification: low risk, high benefit change to existing functionality.

Release note: None

Fixes: #61199

### CODE REVIEW

**Comment by adityamaru** [comment]
Stats collection in restore also happens during job execution as a result of which we cannot send back a notice to the user.

File: pkg/ccl/backupccl/backup_job.go [hunk 1]
```diff
@@ -331,7 +331,16 @@ func backup(
...
 			tableStatisticsAcc, err := statsCache.GetTableStats(ctx, tableDesc.GetID())
 			if err != nil {
-				return RowCount{}, err
+				// Successfully backed up data is more valuable than table stats that can
+				// be recomputed on restore, and so if we fail to collect the stats of a
+				// table we do not want to mark the job as failed.
+				// The lack of stats on restore could lead to suboptimal performance when
+				// reading/writing to this table until the stats have been recomputed.
+				wrappedErr := errors.Wrap(err,
+					fmt.Sprintf("failed to collect stats for table %d during a backup",
```
Comment (pbardea) [inline pkg/ccl/backupccl/backup_job.go:340]: nit: Let's also include the table name here for readability (in addition to the table ID)

File: pkg/ccl/backupccl/restore_job.go [hunk 2]
```diff
@@ -754,18 +754,33 @@ func getStatisticsFromBackup(
...
 			relevantTableStatistics = append(relevantTableStatistics, stat)
 		}
 	}
 
+	// Check if we are missing stats for any table that is being restored. This
+	// could be because we ran into an error when computing stats during the
+	// backup.
+	for _, desc := range tableDescs {
+		if _, ok := tableHasStatsInBackup[desc.GetID()]; !ok {
+			log.Warningf(ctx, "statistics for table %d not found in the backup. "+
```
Comment (pbardea) [inline pkg/ccl/backupccl/restore_job.go:779]: I think you're missing the table ID after this formatted string, but let's also log the table name for readability.

File: pkg/ccl/backupccl/backup_job.go [hunk 3]
```diff
@@ -331,7 +331,16 @@ func backup(
 			// Collect all the table stats for this table.
 			tableStatisticsAcc, err := statsCache.GetTableStats(ctx, tableDesc.GetID())
 			if err != nil {
-				return RowCount{}, err
+				// Successfully backed up data is more valuable than table stats that can
+				// be recomputed on restore, and so if we fail to collect the stats of a
```
Comment (pbardea) [inline pkg/ccl/backupccl/backup_job.go:335]: nit: s/on restore/after restore/

File: pkg/ccl/backupccl/backup_test.go [hunk 4]
```diff
@@ -5602,6 +5602,39 @@ func TestBackupRestoreSubsetCreatedStats(t *testing.T) {
...
+	sqlDB.Exec(t, `ALTER TABLE foo ADD COLUMN t VARCHAR`)
+	sqlDB.Exec(t, `ALTER TABLE foo DROP COLUMN t_old`)
+	sqlDB.Exec(t, `DROP TYPE greeting`)
+
+	// Prior to the fix mentioned above, the stats cache would attempt to resolve
+	// the dropped type when computing the stats for foo at the end of the backup
+	// job. This would result in a `descriptor not found` error.
+
+	// Ensure a full backup completes successfully.
+	sqlDB.Exec(t, `BACKUP foo TO $1`, dest)
```
Comment (pbardea) [inline pkg/ccl/backupccl/backup_test.go:5632]: Since the stats were made to be more resilient, would this test pass before this change anyway?

**Comment by pbardea** [comment]
> Stats collection in restore also happens during job execution as a result of which we cannot send back a notice to the user.

I think that we can check if stats _exist_ in the backup during planning time (we don't today, but we can add that check). If there are no stats included in the backup at all, that means that we won't restore any.

File: pkg/ccl/backupccl/backup_job.go (hunk 3 above)
Comment (adityamaru) [reply pkg/ccl/backupccl/backup_job.go]: done.

File: pkg/ccl/backupccl/restore_job.go (hunk 2 above)
Comment (adityamaru) [reply pkg/ccl/backupccl/restore_job.go]: done.

File: pkg/ccl/backupccl/backup_job.go (hunk 1 above)
Comment (adityamaru) [reply pkg/ccl/backupccl/backup_job.go]: done.

**Comment by adityamaru** [comment]
The notice still looks wonky even though I'm using the method just like other places are. I suspect it's something to do with planHooks, I'm still looking into it.

I also made restores not fail when they are unable to open the stats file for any reason, and added a test to verify this.

Screen Shot 2021-03-04 at 9 31 34 AM

File: pkg/ccl/backupccl/backup_test.go (hunk 4 above)
Comment (adityamaru) [reply pkg/ccl/backupccl/backup_test.go:5633]: Yeah it would, i went back and forth on the relevance of the test after that fix. I'm onboard with deleting it if you feel like it's not lending us any protection from a regression.

Comment (pbardea) [reply pkg/ccl/backupccl/backup_test.go:5633]: I think it's fine to keep this as a regression test to ensure that both backup and stats remain defensive about this particular issue.

**Comment by adityamaru** [comment]
Filed a CLI issue - https://github.com/cockroachdb/cockroach/issues/61516. It seems like the issue is on the client-side where we flush notices at the wrong time. I'll split the notice part of this PR out to another one, which can be checked in after the issue is resolved.

**Review by pbardea — APPROVED** [review]

**Comment by adityamaru** [comment]
@dt just putting this on your radar for a stamp 🙂

File: pkg/sql/planhook.go [hunk 5]
```diff
@@ -99,6 +100,7 @@ type PlanHookState interface {
 	CreateSchemaNamespaceEntry(ctx context.Context, schemaNameKey roachpb.Key,
 		schemaID descpb.ID) error
 	MigrationJobDeps() migration.JobDeps
+	BufferClientNotice(ctx context.Context, notice pgnotice.Notice)
```
Comment (dt) [inline pkg/sql/planhook.go:103]: Are we actually using this?

Comment (adityamaru) [reply pkg/sql/planhook.go:103]: oops, not yet. Once the CLI issue is resolved we'll need it. Removing!

**Review by dt — APPROVED** [review]

**Comment by adityamaru** [comment]
TFTR!

bors r+

**Comment by adityamaru** [comment]
flake on unrelated test.

bors r+
