### PR TITLE
kvcoord: Fix error handling and retries in mux rangefeed client

### LINKED ISSUE #96630: kv/kvserver: TestDecommission failed
kv/kvserver.TestDecommission [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/8595286?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/8595286?buildTab=artifacts#/) on release-22.1 @ [8816f14ae071d448d74c35e51c26690e91519f74](https://github.com/cockroachdb/cockroach/commits/8816f14ae071d448d74c35e51c26690e91519f74):

```
=== RUN   TestDecommission
    test_log_scope.go:79: test logs captured to: /artifacts/tmp/_tmp/751d67000aac5f3394c2369309253f02/logTestDecommission1782102708
    test_log_scope.go:80: use -show-logs to present logs inline
```
<p>Parameters: <code>TAGS=bazel,gss</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestDecommission.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-24248

### LINKED ISSUE #100783: rangefeed: mux rangefeeds failing in metamorphic test builds
During investigation of #99207, it was discovered that whenever mux range feeds were enabled in metamorphic test runs, the test would fail, the kvserver test `TestReplicateQueueDecommissioningNonVoters/remove` would fail, observing the following messages in the logs:

```
I230405 23:35:41.812451 205024 kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:212 ⋮ [T1,n1,rangefeed=‹spanconfig-subscriber›] 308544  MuxRangeFeed starting for range ‹/Table/47/{1-2}›@1680737707.726498812,0 (rangeID 49, attempt 0)
I230405 23:35:41.812503 205378 kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:212 ⋮ [T1,n1,rangefeed=‹tenant-settings-watcher›] 308546  MuxRangeFeed starting for range ‹/Table/5{0-1}›@1680737700.374403140,0 (rangeID 51, attempt 0)
I230405 23:35:41.812503 205363 kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:212 ⋮ [T1,n1,job=‹AUTO SPAN CONFIG RECONCILIATION id=854154456477892609›,rangefeed=‹sql-watcher-protected-ts-records-rangefeed›] 308547  MuxRangeFeed starting for range ‹/Table/3{2-3}›@1680737704.854354224,0 (rangeID 34, attempt 0)
I230405 23:35:41.812527 205359 kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:471 ⋮ [T1,n3,rangefeed=‹tenant-settings-watcher›] 308548  RangeFeed ‹/Table/5{0-1}›@1680737734.040746992,0 disconnected with last checkpoint 466871h35m41.81252653s ago: r51 was not found on s3
I230405 23:35:41.812551 204734 kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:471 ⋮ [T1,n1,rangefeed=‹spanconfig-subscriber›] 308549  RangeFeed ‹/Table/47/{1-2}›@1680737707.726498812,0 disconnected with last checkpoint 466871h35m41.81255031s ago: r49 was not found on s1
I230405 23:35:41.812574 205379 kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:471 ⋮ [T1,n1,rangefeed=‹tenant-settings-watcher›] 308550  RangeFeed ‹/Table/5{0-1}›@1680737700.374403140,0 disconnected with last checkpoint 466871h35m41.812573013s ago: r51 was not found on s1
I230405 23:35:41.812574 205364 kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:471 ⋮ [T1,n1,job=‹AUTO SPAN CONFIG RECONCILIATION id=854154456477892609›,rangefeed=‹sql-watcher-protected-ts-records-rangefeed›] 308551  RangeFeed ‹/Table/3{2-3}›@1680737704.854354224,0 disconnected with last checkpoint 466871h35m41.812572923s ago: r34 was not found on s1
```

It seems that when the metamorphic test enabled mux rangefeeds, there were frequent errors likely due to the failure to apply the updated span config received from the rangefeed.  This error was seen as follows:

```
=== RUN   TestReplicateQueueDecommissioningNonVoters/remove
    replicate_queue_test.go:793: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/kv/kvserver_test/pkg/kv/kvserver/replicate_queue_test.go:793
        	Error:      	Condition never satisfied
        	Test:       	TestReplicateQueueDecommissioningNonVoters/remove
    --- FAIL: TestReplicateQueueDecommissioningNonVoters/remove (68.62s)
```

This ticket is to resolve these errors, as well as to reenable `TestReplicateQueueDecommissioningNonVoters` (and/or any others) under metamorphic builds.

Jira issue: CRDB-26619

### PR DESCRIPTION
**Pull request by miretskiy**
Fix error handling and retries when restarting rangefeeds. A big difference between regular rangefeed, and mux rangefeed, is regular rangefeed has a dedicated go routine per range. This go routine is responsible for running a rangefeed, handling its errors, management of state pertaining to the RPC call (transport, retry information, routing information, etc), and restarting rangefeed with backoff as needed.

Mux rangefeed, on the other hand, is not "loop" based.  Prior to this PR, mux rangefeed, when it encountered a transient error, would loose a lot of the restart state mentioned above.  For example, it would loose the transport information, so that the restart would run against the same node as before, resulting, potentially, in busy loops.  Those busy loops (where the RPC call is restarted against the same node/replica that just experienced an error), would tend to make test flaky since they would take longer time to converge to the state expected by the tests (such as `TestDecommission`) test.

This PR fixes this loss of state pertaining to single range restart by associating this state with the long lived `activeMuxRangeFeed` state.

Fixes #96630
Fixes #100783
Informs #99631
Informs #101614

Release note: None

### CODE REVIEW

**Comment by erikgrinaker** [comment]
I'll be busy with L2 today. @aliher1911 @pavelkalinnikov can you have a look?

File: pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go [hunk 1]
```diff
@@ -128,16 +128,25 @@ type muxStreamOrError struct {
...
+	transport Transport
 }
 
 func (a *activeMuxRangeFeed) release() {
 	a.activeRangeFeed.release()
 	if a.catchupRes != nil {
 		a.catchupRes.Release()
 	}
+	if a.transport != nil {
+		a.transport.Release()
```
[the remark this answers is not in the document]
Comment (miretskiy) [reply pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:148]: Sure.

File: pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go [hunk 2]
```diff
@@ -205,38 +213,48 @@ func (m *rangefeedMuxer) startSingleRangeFeed(
 				}
 				continue
 			}
-			token = ri
+			stream.token = ri
+			stream.transport = nil
```
[the remark this answers is not in the document]
Comment (miretskiy) [reply pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:217]: good catch; it should be released.

File: pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go [hunk 3]
```diff
@@ -205,38 +213,48 @@ func (m *rangefeedMuxer) startSingleRangeFeed(
...
+			stream.ReplicaDescriptor = args.Replica
+			rpcClient, err := stream.transport.NextInternalClient(ctx)
 			if err != nil {
-				log.VErrEventf(ctx, 0, "RPC error connecting to replica %s: %s", args.Replica, err)
+				log.VErrEventf(ctx, 1, "RPC error connecting to replica %s: %s", args.Replica, err)
 				continue
 			}
 
+			log.VEventf(ctx, 1,
+				"MuxRangeFeed starting for range %s@%s (rangeID %d, replica %s, attempt %d)",
```
[the remark this answers is not in the document]
Comment (miretskiy) [reply pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:243]: Done

File: pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go [hunk 4]
```diff
@@ -191,12 +198,13 @@ func (m *rangefeedMuxer) startSingleRangeFeed(
 	}()
 
 	// Start a retry loop for sending the batch to the range.
-	for r := retry.StartWithCtx(ctx, m.ds.rpcRetryOptions); r.Next(); {
-		maybeReleaseTransport()
-
+	for stream.retry.Next() {
```
[the remark this answers is not in the document]
Comment (miretskiy) [reply pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:201]: added large comment next to the structure; hope it makes it better.

File: pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go [hunk 5]
```diff
@@ -191,12 +221,13 @@ func (m *rangefeedMuxer) startSingleRangeFeed(
...
 		// If we've cleared the descriptor on failure, re-lookup.
-		if !token.Valid() {
-			var err error
+		if !stream.token.Valid() {
```
Comment (pavelkalinnikov) [inline pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:226]: Most of this loop checks and modifies `stream.Something` fields. This suggests that much of this code logically belongs to the `stream` type, rather than muxer. Could this be encapsulated in the `stream` as a few stream lifecycle methods, and the muxer would just orchestrate?

Comment (miretskiy) [reply pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:226]: Perhaps it can; it's more of a result of inheriting "dna" from regular rangefeed;
Do you feel strongly that such refactoring should be done right now?

File: pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go [hunk 6]
```diff
@@ -179,7 +202,14 @@ func (m *rangefeedMuxer) startSingleRangeFeed(
...
 		token:           token,
+		retry:           retry.StartWithCtx(ctx, m.ds.rpcRetryOptions),
 	}
+	return m.startActiveRangeFeed(ctx, stream)
+}
+
+func (m *rangefeedMuxer) startActiveRangeFeed(
+	ctx context.Context, stream *activeMuxRangeFeed,
+) error {
 	streamID := atomic.AddInt64(&m.seqID, 1)
```
Comment (pavelkalinnikov) [inline pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:213]: What is the relation between `streamID` and the `stream` parameter? It feels counter-intuitive that the ID for a stream is decided after it has been passed in, and then it's passed along with the `stream` (e.g. in `startRangeFeed` method).

Can the ID change during the lifetime of the `stream`? If not, should it just be a field like `stream.ID`?

Comment (miretskiy) [reply pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:213]: Not only that, we want to change the stream id every time we restart range feed; it uniquely ties the server side w/ client side...

**Comment by miretskiy** [comment]
> Not strongly, but I feel it would improve understanding of this code. It wouldn't be a large refactoring I think. Instead of rangefeedMuxer.startActiveRangeFeed(stream), it would be a activeMuxRangeFeed.start() method which would otherwise do the same thing?

I misunderstood; this of course is no big deal to do.  I'm not sure that moving this logic to start() would be better necessarily.  Even though startActiveRangeFeed operates mostly on "activeMuxRangeFeed" structure -- that's not the only  thing that's happening; there are many dependencies on "rangefeedMuxer" -- establishing rpc connection to the node, access to many members of rangefeedMuxer.

File: pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go (hunk 6 above)
Comment (pavelkalinnikov) [reply pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:213]: Do I still read it correctly that a single `activeMuxRangeFeed` object can be associated only with a single `streamID`? When a rangefeed is restarted, it gets a brand new `activeMuxRangeFeed` with a new ID.

Comment (miretskiy) [reply pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:213]: yes.

**Comment by miretskiy** [comment]
> As a small example, in this PR some fields of `activeMuxRangeFeed` (transport and token) are released directly, but in addition there is the `activeMuxRangeFeed.release()` method. As a user of this type, how would I know when I need to call `release()` or when I need to manually access the fields?

As you say: things are not simple.  Multiple go routines are involved; resources acquired at one point on 1 go routine (catchup scan) and are released on another go routine (which manages many range feeds).
Sometimes, you need to release transport and sometimes you dont.  Sometimes you need to evict routine token and sometimes you don't.  There is *a lot* of complexity here -- and similar complexity exists in the existing range feed implementation.  Similar split exists there (partial rangefeed runs the loop/handles errors; singleRangeFeed also handles errors, may or may not release catchup reservation; does some retries of its own).

I've introduce `start` method as you suggested. Also added resetRouting to help management of routing token/transport.

**Review by pav-kv — COMMENTED** [review]
@miretskiy Thanks for adding the diagram! It helped me to understand this design a bit better. Looks like a bunch of streams that used to be in their own goroutines, flattened into one goroutine? With a few signals that drive it, primarily the events loop.

I've brushed up the diagram a bit, see the suggestions.

I'll make another pass tomorrow morning. I see the benefit of this fix, but hopefully in the morning I'll have a better focus on nitty-gritty details.

File: pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go [hunk 7]
```diff
@@ -205,50 +246,53 @@ func (m *rangefeedMuxer) startSingleRangeFeed(
...
+				err = conn.startRangeFeed(streamID, s, &args)
 			}
 
-			if err := conn.startRangeFeed(streamID, stream, &args); err != nil {
-				log.VErrEventf(ctx, 0,
-					"RPC error establishing mux rangefeed to replica %s: %s", args.Replica, err)
+			if err != nil {
+				log.VErrEventf(ctx, 1,
+					"RPC error establishing mux rangefeed to r%d, replica %s: %s", args.RangeID, args.Replica, err)
+				if grpcutil.IsAuthError(err) {
```
[the remark this answers is not in the document]
Comment (miretskiy) [reply pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:286]: No, not exactly; but I did notice that those checks were missing -- so, I wouldn't be surprised if some other test out there failed because of those missing checks.

File: pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go [hunk 8]
```diff
@@ -467,12 +511,19 @@ func (m *rangefeedMuxer) restartActiveRangeFeed(
...
+
+	doRelease := true
+	defer func() {
+		if doRelease {
+			active.release()
+		}
+	}()
 
 	errInfo, err := handleRangefeedError(ctx, reason)
 	if err != nil {
```
[the remark this answers is not in the document]
Comment (miretskiy) [reply pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:532]: Ack.

**Comment by miretskiy** [comment]
> 



> Thanks for adding the diagram! It helped me to understand this design a bit better. Looks like a bunch of streams that used to be in their own goroutines, flattened into one goroutine? With a few signals that drive it, primarily the events loop.

Exactly right; we are replacing N go routines with ... N go routines where N is the number of nodes as opposed to the number of ranges.

File: pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go [hunk 9]
```diff
@@ -179,24 +218,30 @@ func (m *rangefeedMuxer) startSingleRangeFeed(
...
+	return nil
+}
 
+// start begins execution of activeMuxRangeFeed.
+// Backoff is applied if same stream restarts.
+func (s *activeMuxRangeFeed) start(ctx context.Context, m *rangefeedMuxer) error {
+	streamID := atomic.AddInt64(&m.seqID, 1)
+
+	// Start a retry loop for sending the batch to the range.
+	for s.retry.Next() {
```
Comment (pavelkalinnikov) [inline pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:238]: Carrying the `transport`, `token` and friends seems beneficial.

I'm not sure that reusing the `retry` state across starts is great, if I understand this implementation. Say, `start` succeeds, and we run the `activeMuxRangeFeed` for a while. Then a transient error happens during the event handling loop, we try to restart the feed. Why would we use the same `retry` state that we used to start the feed in the first place?

The delay in `retry` will keep growing. So, with every transient error we will be starting the feed slower and slower. I think we should sometimes (when things are going smoothly again) decrease the delay, or reset the state of `retry`. For example, if the time after the last successful start is more than a threshold, then we `s.retry.Reset()` here.

File: pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go [hunk 10]
```diff
@@ -179,24 +218,30 @@ func (m *rangefeedMuxer) startSingleRangeFeed(
...
 		// If we've cleared the descriptor on failure, re-lookup.
-		if !token.Valid() {
-			var err error
+		if !s.token.Valid() {
+			rs, err := keys.SpanAddr(s.Span)
+			if err != nil {
+				return err
+			}
 			ri, err := m.ds.getRoutingInfo(ctx, rs.Key, rangecache.EvictionToken{}, false)
```
[the remark this answers is not in the document]
Comment (miretskiy) [reply pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:245]: yeah; it's a bit messy for sure; newActiveRangeFeed needs span; the rest of the code needs rSpan... Added rs to activeMuxRangeFeed struct.

File: pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (miretskiy) [reply pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:533]: Nah; it's correct.  Every time we evict token, we re-resolve it and recreate transport.

File: pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go (hunk 9 above)
Comment (miretskiy) [reply pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:238]: It's not that bad since the backoff is bound by 1 sec; but I was thinking the same, just wanted to keep things
as close to existing impl as possible.  Having said that, since you're voicing the same concern I had, I removed retry state from the activeMux.  No need to reset it.  Basically, if you were able to establish node connection, plus send an initial request, then you've done enough work -- and retry can happen immediately.

Verified this fix is fine with decommission test.

File: pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go [hunk 11]
```diff
@@ -179,24 +218,30 @@ func (m *rangefeedMuxer) startSingleRangeFeed(
...
 
-	// Start a retry loop for sending the batch to the range.
-	for r := retry.StartWithCtx(ctx, m.ds.rpcRetryOptions); r.Next(); {
-		maybeReleaseTransport()
+	return nil
+}
 
+// start begins execution of activeMuxRangeFeed.
+// Backoff is applied if same stream restarts.
+func (s *activeMuxRangeFeed) start(ctx context.Context, m *rangefeedMuxer) error {
```
[the remark this answers is not in the document]
Comment (miretskiy) [reply pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:234]: Comment added to this function and to the catchupRes member field to describe catchupRes lifetime.

File: pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go [hunk 12]
```diff
@@ -126,20 +125,73 @@ type muxStreamOrError struct {
...
 	startAfter hlc.Timestamp
+
+	// cathchupRes is the catchup scan quota acquired upon the
+	// start of rangefeed.
+	// It is released when this stream receives first non-empty checkpoint
+	// (meaning: catchup scan completes).
 	catchupRes catchupAlloc
+
+	// State pertaining to execution of rangefeed call, along with
+	// the state needed to manage retries.
```
Comment (pavelkalinnikov) [inline pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:168]:
```suggestion
	// State pertaining to execution of rangefeed call.
```

File: pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go [hunk 13]
```diff
@@ -176,79 +219,93 @@ func (m *rangefeedMuxer) startSingleRangeFeed(
...
+}
+
+// start begins execution of activeMuxRangeFeed.
+// This method uses the routine and transport information associated with this active stream,
+// to find the node that hosts range replica, establish MuxRangeFeed RPC stream
+// with the node, and then establish rangefeed for the span with that node.
+// If the routine/transport information are not valid, performs lookup to refresh this
+// information.
+// Transient errors while establishing RPCs are retried with backoff.
+// Certain non-recoverable errors (such as  grpcutil.IsAuthError(err)) are propagated to the
```
Comment (pavelkalinnikov) [inline pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:243]:
```suggestion
// Certain non-recoverable errors (such as grpcutil.IsAuthError(err)) are propagated to the
```

File: pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go [hunk 14]
```diff
@@ -176,79 +219,93 @@ func (m *rangefeedMuxer) startSingleRangeFeed(
...
+// caller and will cause the whole rangefeed to terminate.
+// Upon successfully establishing RPC stream, the ownership of the activeMuxRangeFeed
+// gets transferred to the node event loop go routine (receiveEventsFromNode).
```
Comment (pavelkalinnikov) [inline pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:246]:
```suggestion
// gets transferred to the node event loop goroutine (receiveEventsFromNode).
```

File: pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go [hunk 15]
```diff
@@ -126,20 +125,73 @@ type muxStreamOrError struct {
 }
 
 // activeMuxRangeFeed augments activeRangeFeed with additional state.
+// This is a long-lived data structure representing the lifetime of a single
+// range feed.
+// The lifetime of a single range feed is as follows:
+//
+// ┌─* muxRangeFeed
+// ┌───►├─► divideSpanOnRangeBoundaries
```
Comment (pavelkalinnikov) [inline pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:133]:
```suggestion
//      ┌─* muxRangeFeed
// ┌───►├─► divideSpanOnRangeBoundaries
```

**Review by pav-kv — APPROVED** [review]
CI seems unhappy, please fix.

File: pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go (hunk 14 above)
Comment (miretskiy) [reply pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:246]: Done here and throughout this file.
