### PR TITLE
server: deflake TestAdminAPITableStats

### LINKED ISSUE #25831: github.com/cockroachdb/cockroach/pkg/server: TestAdminAPITableStats failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/5bc5488c856b8a8b618c239c6616b45be6a1942a

Parameters:
```
TAGS=
GOFLAGS=
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=673629&tab=buildLog

```
I180523 05:47:22.525350 50728 storage/replica_raftstorage.go:730  [n3,s3,r3/2:{-}] applying Raft snapshot at index 24 (id=d87b7c18, encoded size=6238, 1 rocksdb batches, 14 log entries)
I180523 05:47:22.525660 50728 storage/replica_raftstorage.go:736  [n3,s3,r3/2:/System/NodeLiveness{-Max}] applied Raft snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.528923 49773 storage/replica.go:3320  [n1,s1,r20/1:/Table/{23-50}] proposing ADD_REPLICA((n2,s2):2): updated=[(n1,s1):1 (n2,s2):2] next=3
I180523 05:47:22.529419 49773 storage/replica_raftstorage.go:520  [replicate,n1,s1,r21/1:/Table/5{0-1}] generated preemptive snapshot 06bfeed4 at index 15
I180523 05:47:22.530448 49773 storage/store_snapshot.go:605  [replicate,n1,s1,r21/1:/Table/5{0-1}] streamed snapshot to (n3,s3):?: kv pairs: 7, log entries: 5, rate-limit: 8.0 MiB/sec, 1ms
I180523 05:47:22.531084 50661 storage/replica_raftstorage.go:730  [n3,s3,r21/?:{-}] applying preemptive snapshot at index 15 (id=06bfeed4, encoded size=1919, 1 rocksdb batches, 5 log entries)
I180523 05:47:22.531441 50661 storage/replica_raftstorage.go:736  [n3,s3,r21/?:/Table/5{0-1}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.531821 49773 storage/replica_command.go:1777  [replicate,n1,s1,r21/1:/Table/5{0-1}] change replicas (ADD_REPLICA (n3,s3):2): read existing descriptor r21:/Table/5{0-1} [(n1,s1):1, next=2]
I180523 05:47:22.533919 50696 storage/store.go:2492  [replicaGC,n3,s3,r21/?:/Table/5{0-1}] removing replica
I180523 05:47:22.534082 50696 storage/replica.go:829  [replicaGC,n3,s3,r21/?:/Table/5{0-1}] removed 5 (0+5) keys in 0ms [clear=0ms commit=0ms]
I180523 05:47:22.535208 49773 storage/replica.go:3320  [n1,s1,r21/1:/Table/5{0-1}] proposing ADD_REPLICA((n3,s3):2): updated=[(n1,s1):1 (n3,s3):2] next=3
I180523 05:47:22.536335 49773 storage/replica_raftstorage.go:520  [replicate,n1,s1,r8/1:/Table/1{1-2}] generated preemptive snapshot 709863a4 at index 17
I180523 05:47:22.537101 49773 storage/store_snapshot.go:605  [replicate,n1,s1,r8/1:/Table/1{1-2}] streamed snapshot to (n3,s3):?: kv pairs: 7, log entries: 7, rate-limit: 8.0 MiB/sec, 1ms
I180523 05:47:22.537669 50665 storage/replica_raftstorage.go:730  [n3,s3,r8/?:{-}] applying preemptive snapshot at index 17 (id=709863a4, encoded size=3415, 1 rocksdb batches, 7 log entries)
I180523 05:47:22.537915 50665 storage/replica_raftstorage.go:736  [n3,s3,r8/?:/Table/1{1-2}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.538394 49773 storage/replica_command.go:1777  [replicate,n1,s1,r8/1:/Table/1{1-2}] change replicas (ADD_REPLICA (n3,s3):2): read existing descriptor r8:/Table/1{1-2} [(n1,s1):1, next=2]
I180523 05:47:22.538532 50760 storage/replica_raftstorage.go:520  [raftsnapshot,n1,s1,r21/1:/Table/5{0-1}] generated Raft snapshot 70ae1ca1 at index 17
I180523 05:47:22.539404 50760 storage/store_snapshot.go:605  [raftsnapshot,n1,s1,r21/1:/Table/5{0-1}] streamed snapshot to (n3,s3):2: kv pairs: 9, log entries: 7, rate-limit: 8.0 MiB/sec, 1ms
I180523 05:47:22.540327 50619 storage/replica_raftstorage.go:730  [n3,s3,r21/2:{-}] applying Raft snapshot at index 17 (id=70ae1ca1, encoded size=3278, 1 rocksdb batches, 7 log entries)
I180523 05:47:22.540635 50619 storage/replica_raftstorage.go:736  [n3,s3,r21/2:/Table/5{0-1}] applied Raft snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.565912 50698 storage/store.go:2492  [replicaGC,n3,s3,r8/?:/Table/1{1-2}] removing replica
I180523 05:47:22.566079 50698 storage/replica.go:829  [replicaGC,n3,s3,r8/?:/Table/1{1-2}] removed 5 (0+5) keys in 0ms [clear=0ms commit=0ms]
I180523 05:47:22.567368 49773 storage/replica.go:3320  [n1,s1,r8/1:/Table/1{1-2}] proposing ADD_REPLICA((n3,s3):2): updated=[(n1,s1):1 (n3,s3):2] next=3
I180523 05:47:22.569136 49773 storage/replica_raftstorage.go:520  [replicate,n1,s1,r10/1:/Table/1{3-4}] generated preemptive snapshot 4699bab1 at index 49
I180523 05:47:22.570903 49773 storage/store_snapshot.go:605  [replicate,n1,s1,r10/1:/Table/1{3-4}] streamed snapshot to (n3,s3):?: kv pairs: 168, log entries: 39, rate-limit: 8.0 MiB/sec, 1ms
I180523 05:47:22.570920 50666 storage/replica_raftstorage.go:520  [raftsnapshot,n1,s1,r8/1:/Table/1{1-2}] generated Raft snapshot 0e3b14bf at index 19
I180523 05:47:22.571594 50666 storage/store_snapshot.go:605  [raftsnapshot,n1,s1,r8/1:/Table/1{1-2}] streamed snapshot to (n3,s3):2: kv pairs: 9, log entries: 9, rate-limit: 8.0 MiB/sec, 1ms
I180523 05:47:22.571751 50747 storage/replica_raftstorage.go:730  [n3,s3,r10/?:{-}] applying preemptive snapshot at index 49 (id=4699bab1, encoded size=48335, 1 rocksdb batches, 39 log entries)
I180523 05:47:22.572080 50700 storage/replica_raftstorage.go:730  [n3,s3,r8/2:{-}] applying Raft snapshot at index 19 (id=0e3b14bf, encoded size=4774, 1 rocksdb batches, 9 log entries)
I180523 05:47:22.572369 50747 storage/replica_raftstorage.go:736  [n3,s3,r10/?:/Table/1{3-4}] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.572497 50700 storage/replica_raftstorage.go:736  [n3,s3,r8/2:/Table/1{1-2}] applied Raft snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.573050 49773 storage/replica_command.go:1777  [replicate,n1,s1,r10/1:/Table/1{3-4}] change replicas (ADD_REPLICA (n3,s3):2): read existing descriptor r10:/Table/1{3-4} [(n1,s1):1, next=2]
I180523 05:47:22.574050 50588 storage/store.go:2492  [replicaGC,n3,s3,r10/?:/Table/1{3-4}] removing replica
I180523 05:47:22.574233 50588 storage/replica.go:829  [replicaGC,n3,s3,r10/?:/Table/1{3-4}] removed 161 (156+5) keys in 0ms [clear=0ms commit=0ms]
I180523 05:47:22.576902 49773 storage/replica.go:3320  [n1,s1,r10/1:/Table/1{3-4}] proposing ADD_REPLICA((n3,s3):2): updated=[(n1,s1):1 (n3,s3):2] next=3
I180523 05:47:22.578958 49773 storage/replica_raftstorage.go:520  [replicate,n1,s1,r16/1:/Table/{19-20}] generated preemptive snapshot ddb998f1 at index 15
I180523 05:47:22.579162 50701 storage/replica_raftstorage.go:520  [raftsnapshot,n1,s1,r10/1:/Table/1{3-4}] generated Raft snapshot 8994ede5 at index 53
I180523 05:47:22.579578 49773 storage/store_snapshot.go:605  [replicate,n1,s1,r16/1:/Table/{19-20}] streamed snapshot to (n3,s3):?: kv pairs: 7, log entries: 5, rate-limit: 8.0 MiB/sec, 1ms
I180523 05:47:22.580349 50701 storage/store_snapshot.go:605  [raftsnapshot,n1,s1,r10/1:/Table/1{3-4}] streamed snapshot to (n3,s3):2: kv pairs: 170, log entries: 43, rate-limit: 8.0 MiB/sec, 1ms
I180523 05:47:22.580972 50786 storage/replica_raftstorage.go:730  [n3,s3,r16/?:{-}] applying preemptive snapshot at index 15 (id=ddb998f1, encoded size=1946, 1 rocksdb batches, 5 log entries)
I180523 05:47:22.581237 50786 storage/replica_raftstorage.go:736  [n3,s3,r16/?:/Table/{19-20}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.581589 49773 storage/replica_command.go:1777  [replicate,n1,s1,r16/1:/Table/{19-20}] change replicas (ADD_REPLICA (n3,s3):2): read existing descriptor r16:/Table/{19-20} [(n1,s1):1, next=2]
I180523 05:47:22.581846 50704 storage/replica_raftstorage.go:730  [n3,s3,r10/2:{-}] applying Raft snapshot at index 53 (id=8994ede5, encoded size=52546, 1 rocksdb batches, 43 log entries)
I180523 05:47:22.582739 50704 storage/replica_raftstorage.go:736  [n3,s3,r10/2:/Table/1{3-4}] applied Raft snapshot in 1ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.584940 49773 storage/replica.go:3320  [n1,s1,r16/1:/Table/{19-20}] proposing ADD_REPLICA((n3,s3):2): updated=[(n1,s1):1 (n3,s3):2] next=3
I180523 05:47:22.586363 49773 storage/replica_raftstorage.go:520  [replicate,n1,s1,r18/1:/Table/2{1-2}] generated preemptive snapshot 10858f78 at index 15
I180523 05:47:22.589627 49773 storage/store_snapshot.go:605  [replicate,n1,s1,r18/1:/Table/2{1-2}] streamed snapshot to (n2,s2):?: kv pairs: 7, log entries: 5, rate-limit: 8.0 MiB/sec, 3ms
I180523 05:47:22.590288 50765 storage/replica_raftstorage.go:730  [n2,s2,r18/?:{-}] applying preemptive snapshot at index 15 (id=10858f78, encoded size=2115, 1 rocksdb batches, 5 log entries)
I180523 05:47:22.590511 50765 storage/replica_raftstorage.go:736  [n2,s2,r18/?:/Table/2{1-2}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.590629 49511 testutils/testcluster/testcluster.go:536  [n1,s1] has 22 underreplicated ranges
I180523 05:47:22.590767 49773 storage/replica_command.go:1777  [replicate,n1,s1,r18/1:/Table/2{1-2}] change replicas (ADD_REPLICA (n2,s2):2): read existing descriptor r18:/Table/2{1-2} [(n1,s1):1, next=2]
I180523 05:47:22.593663 49773 storage/replica.go:3320  [n1,s1,r18/1:/Table/2{1-2}] proposing ADD_REPLICA((n2,s2):2): updated=[(n1,s1):1 (n2,s2):2] next=3
I180523 05:47:22.595300 49773 storage/replica_raftstorage.go:520  [replicate,n1,s1,r11/1:/Table/1{4-5}] generated preemptive snapshot 5882c2ed at index 15
I180523 05:47:22.596401 49773 storage/store_snapshot.go:605  [replicate,n1,s1,r11/1:/Table/1{4-5}] streamed snapshot to (n2,s2):?: kv pairs: 7, log entries: 5, rate-limit: 8.0 MiB/sec, 1ms
I180523 05:47:22.596754 50749 storage/replica_raftstorage.go:730  [n2,s2,r11/?:{-}] applying preemptive snapshot at index 15 (id=5882c2ed, encoded size=1940, 1 rocksdb batches, 5 log entries)
I180523 05:47:22.596965 50749 storage/replica_raftstorage.go:736  [n2,s2,r11/?:/Table/1{4-5}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.597457 49773 storage/replica_command.go:1777  [replicate,n1,s1,r11/1:/Table/1{4-5}] change replicas (ADD_REPLICA (n2,s2):2): read existing descriptor r11:/Table/1{4-5} [(n1,s1):1, next=2]
I180523 05:47:22.600717 49773 storage/replica.go:3320  [n1,s1,r11/1:/Table/1{4-5}] proposing ADD_REPLICA((n2,s2):2): updated=[(n1,s1):1 (n2,s2):2] next=3
I180523 05:47:22.601192 49773 storage/replica_raftstorage.go:520  [replicate,n1,s1,r13/1:/Table/1{6-7}] generated preemptive snapshot ff9f1f5c at index 15
I180523 05:47:22.602272 49773 storage/store_snapshot.go:605  [replicate,n1,s1,r13/1:/Table/1{6-7}] streamed snapshot to (n2,s2):?: kv pairs: 7, log entries: 5, rate-limit: 8.0 MiB/sec, 1ms
I180523 05:47:22.602725 50820 storage/replica_raftstorage.go:730  [n2,s2,r13/?:{-}] applying preemptive snapshot at index 15 (id=ff9f1f5c, encoded size=2115, 1 rocksdb batches, 5 log entries)
I180523 05:47:22.602924 50820 storage/replica_raftstorage.go:736  [n2,s2,r13/?:/Table/1{6-7}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.608888 49773 storage/replica_command.go:1777  [replicate,n1,s1,r13/1:/Table/1{6-7}] change replicas (ADD_REPLICA (n2,s2):2): read existing descriptor r13:/Table/1{6-7} [(n1,s1):1, next=2]
I180523 05:47:22.609973 50822 storage/store.go:2492  [replicaGC,n2,s2,r13/?:/Table/1{6-7}] removing replica
I180523 05:47:22.610139 50822 storage/replica.go:829  [replicaGC,n2,s2,r13/?:/Table/1{6-7}] removed 5 (0+5) keys in 0ms [clear=0ms commit=0ms]
I180523 05:47:22.623657 49773 storage/replica.go:3320  [n1,s1,r13/1:/Table/1{6-7}] proposing ADD_REPLICA((n2,s2):2): updated=[(n1,s1):1 (n2,s2):2] next=3
I180523 05:47:22.624180 49773 storage/replica_raftstorage.go:520  [replicate,n1,s1,r4/1:/System/{NodeLive…-tsd}] generated preemptive snapshot ae39217f at index 40
I180523 05:47:22.626710 50774 storage/replica_raftstorage.go:520  [raftsnapshot,n1,s1,r13/1:/Table/1{6-7}] generated Raft snapshot 59b1bc95 at index 17
I180523 05:47:22.632285 50774 storage/store_snapshot.go:605  [raftsnapshot,n1,s1,r13/1:/Table/1{6-7}] streamed snapshot to (n2,s2):2: kv pairs: 9, log entries: 7, rate-limit: 8.0 MiB/sec, 1ms
I180523 05:47:22.632769 49773 storage/store_snapshot.go:605  [replicate,n1,s1,r4/1:/System/{NodeLive…-tsd}] streamed snapshot to (n3,s3):?: kv pairs: 37, log entries: 30, rate-limit: 8.0 MiB/sec, 1ms
I180523 05:47:22.634534 50623 storage/replica_raftstorage.go:730  [n2,s2,r13/2:{-}] applying Raft snapshot at index 17 (id=59b1bc95, encoded size=3474, 1 rocksdb batches, 7 log entries)
I180523 05:47:22.634794 50623 storage/replica_raftstorage.go:736  [n2,s2,r13/2:/Table/1{6-7}] applied Raft snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.641221 50836 storage/replica_raftstorage.go:730  [n3,s3,r4/?:{-}] applying preemptive snapshot at index 40 (id=ae39217f, encoded size=111349, 1 rocksdb batches, 30 log entries)
I180523 05:47:22.642625 50836 storage/replica_raftstorage.go:736  [n3,s3,r4/?:/System/{NodeLive…-tsd}] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=1ms commit=0ms]
I180523 05:47:22.643674 49773 storage/replica_command.go:1777  [replicate,n1,s1,r4/1:/System/{NodeLive…-tsd}] change replicas (ADD_REPLICA (n3,s3):2): read existing descriptor r4:/System/{NodeLivenessMax-tsd} [(n1,s1):1, next=2]
I180523 05:47:22.674517 50624 storage/store.go:2492  [replicaGC,n3,s3,r4/?:/System/{NodeLive…-tsd}] removing replica
I180523 05:47:22.674916 50624 storage/replica.go:829  [replicaGC,n3,s3,r4/?:/System/{NodeLive…-tsd}] removed 26 (19+7) keys in 0ms [clear=0ms commit=0ms]
I180523 05:47:22.675434 49773 storage/replica.go:3320  [n1,s1,r4/1:/System/{NodeLive…-tsd}] proposing ADD_REPLICA((n3,s3):2): updated=[(n1,s1):1 (n3,s3):2] next=3
I180523 05:47:22.677602 50808 storage/replica_raftstorage.go:520  [replicate,n1,s1,r2/1:/System/{-NodeLive…}] generated preemptive snapshot 9fd42c3a at index 22
I180523 05:47:22.678638 50808 storage/store_snapshot.go:605  [replicate,n1,s1,r2/1:/System/{-NodeLive…}] streamed snapshot to (n2,s2):?: kv pairs: 10, log entries: 12, rate-limit: 8.0 MiB/sec, 1ms
I180523 05:47:22.678990 50850 storage/replica_raftstorage.go:520  [raftsnapshot,n1,s1,r4/1:/System/{NodeLive…-tsd}] generated Raft snapshot 68866aed at index 42
I180523 05:47:22.681338 50826 storage/replica_raftstorage.go:730  [n2,s2,r2/?:{-}] applying preemptive snapshot at index 22 (id=9fd42c3a, encoded size=4980, 1 rocksdb batches, 12 log entries)
I180523 05:47:22.681729 50826 storage/replica_raftstorage.go:736  [n2,s2,r2/?:/System/{-NodeLive…}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.682051 50850 storage/store_snapshot.go:605  [raftsnapshot,n1,s1,r4/1:/System/{NodeLive…-tsd}] streamed snapshot to (n3,s3):2: kv pairs: 39, log entries: 32, rate-limit: 8.0 MiB/sec, 3ms
I180523 05:47:22.682223 50808 storage/replica_command.go:1777  [replicate,n1,s1,r2/1:/System/{-NodeLive…}] change replicas (ADD_REPLICA (n2,s2):3): read existing descriptor r2:/System/{-NodeLiveness} [(n1,s1):1, (n3,s3):2, next=3]
I180523 05:47:22.682688 50828 storage/replica_raftstorage.go:730  [n3,s3,r4/2:{-}] applying Raft snapshot at index 42 (id=68866aed, encoded size=112909, 1 rocksdb batches, 32 log entries)
I180523 05:47:22.683697 50828 storage/replica_raftstorage.go:736  [n3,s3,r4/2:/System/{NodeLive…-tsd}] applied Raft snapshot in 1ms [clear=0ms batch=0ms entries=0ms commit=1ms]
I180523 05:47:22.684021 50810 storage/store.go:2492  [replicaGC,n2,s2,r2/?:/System/{-NodeLive…}] removing replica
I180523 05:47:22.684165 50810 storage/replica.go:829  [replicaGC,n2,s2,r2/?:/System/{-NodeLive…}] removed 7 (0+7) keys in 0ms [clear=0ms commit=0ms]
I180523 05:47:22.687627 50808 storage/replica.go:3320  [n1,s1,r2/1:/System/{-NodeLive…}] proposing ADD_REPLICA((n2,s2):3): updated=[(n1,s1):1 (n3,s3):2 (n2,s2):3] next=4
I180523 05:47:22.689018 49773 storage/replica_raftstorage.go:520  [replicate,n1,s1,r12/1:/Table/1{5-6}] generated preemptive snapshot 65271ff8 at index 15
I180523 05:47:22.689217 49511 testutils/testcluster/testcluster.go:536  [n1,s1] has 21 underreplicated ranges
I180523 05:47:22.691161 50832 storage/replica_raftstorage.go:520  [raftsnapshot,n1,s1,r2/1:/System/{-NodeLive…}] generated Raft snapshot 2e89b45e at index 25
I180523 05:47:22.691192 49773 storage/store_snapshot.go:605  [replicate,n1,s1,r12/1:/Table/1{5-6}] streamed snapshot to (n3,s3):?: kv pairs: 7, log entries: 5, rate-limit: 8.0 MiB/sec, 2ms
I180523 05:47:22.691765 50832 storage/store_snapshot.go:605  [raftsnapshot,n1,s1,r2/1:/System/{-NodeLive…}] streamed snapshot to (n2,s2):3: kv pairs: 11, log entries: 15, rate-limit: 8.0 MiB/sec, 1ms
I180523 05:47:22.691782 50855 storage/replica_raftstorage.go:730  [n3,s3,r12/?:{-}] applying preemptive snapshot at index 15 (id=65271ff8, encoded size=2111, 1 rocksdb batches, 5 log entries)
I180523 05:47:22.692012 50855 storage/replica_raftstorage.go:736  [n3,s3,r12/?:/Table/1{5-6}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.692038 50857 storage/replica_raftstorage.go:730  [n2,s2,r2/3:{-}] applying Raft snapshot at index 25 (id=2e89b45e, encoded size=6198, 1 rocksdb batches, 15 log entries)
I180523 05:47:22.692323 50857 storage/replica_raftstorage.go:736  [n2,s2,r2/3:/System/{-NodeLive…}] applied Raft snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.692367 49773 storage/replica_command.go:1777  [replicate,n1,s1,r12/1:/Table/1{5-6}] change replicas (ADD_REPLICA (n3,s3):2): read existing descriptor r12:/Table/1{5-6} [(n1,s1):1, next=2]
I180523 05:47:22.696811 49773 storage/replica.go:3320  [n1,s1,r12/1:/Table/1{5-6}] proposing ADD_REPLICA((n3,s3):2): updated=[(n1,s1):1 (n3,s3):2] next=3
I180523 05:47:22.697421 49773 storage/replica_raftstorage.go:520  [replicate,n1,s1,r14/1:/Table/1{7-8}] generated preemptive snapshot 2e241d5e at index 15
I180523 05:47:22.702285 49773 storage/store_snapshot.go:605  [replicate,n1,s1,r14/1:/Table/1{7-8}] streamed snapshot to (n3,s3):?: kv pairs: 7, log entries: 5, rate-limit: 8.0 MiB/sec, 5ms
I180523 05:47:22.705834 50862 storage/replica_raftstorage.go:730  [n3,s3,r14/?:{-}] applying preemptive snapshot at index 15 (id=2e241d5e, encoded size=1950, 1 rocksdb batches, 5 log entries)
I180523 05:47:22.706056 50862 storage/replica_raftstorage.go:736  [n3,s3,r14/?:/Table/1{7-8}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.706404 49773 storage/replica_command.go:1777  [replicate,n1,s1,r14/1:/Table/1{7-8}] change replicas (ADD_REPLICA (n3,s3):2): read existing descriptor r14:/Table/1{7-8} [(n1,s1):1, next=2]
I180523 05:47:22.714349 50866 storage/store.go:2492  [replicaGC,n3,s3,r14/?:/Table/1{7-8}] removing replica
I180523 05:47:22.714516 50866 storage/replica.go:829  [replicaGC,n3,s3,r14/?:/Table/1{7-8}] removed 5 (0+5) keys in 0ms [clear=0ms commit=0ms]
I180523 05:47:22.717864 49773 storage/replica.go:3320  [n1,s1,r14/1:/Table/1{7-8}] proposing ADD_REPLICA((n3,s3):2): updated=[(n1,s1):1 (n3,s3):2] next=3
I180523 05:47:22.718387 49773 storage/replica_raftstorage.go:520  [replicate,n1,s1,r17/1:/Table/2{0-1}] generated preemptive snapshot f0bf65ae at index 16
I180523 05:47:22.718914 49773 storage/store_snapshot.go:605  [replicate,n1,s1,r17/1:/Table/2{0-1}] streamed snapshot to (n3,s3):?: kv pairs: 8, log entries: 6, rate-limit: 8.0 MiB/sec, 0ms
I180523 05:47:22.721772 50776 storage/replica_raftstorage.go:730  [n3,s3,r17/?:{-}] applying preemptive snapshot at index 16 (id=f0bf65ae, encoded size=2423, 1 rocksdb batches, 6 log entries)
I180523 05:47:22.721986 50776 storage/replica_raftstorage.go:736  [n3,s3,r17/?:/Table/2{0-1}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.722314 49773 storage/replica_command.go:1777  [replicate,n1,s1,r17/1:/Table/2{0-1}] change replicas (ADD_REPLICA (n3,s3):2): read existing descriptor r17:/Table/2{0-1} [(n1,s1):1, next=2]
I180523 05:47:22.722997 50777 storage/replica_raftstorage.go:520  [raftsnapshot,n1,s1,r14/1:/Table/1{7-8}] generated Raft snapshot c98ee743 at index 17
I180523 05:47:22.723636 50777 storage/store_snapshot.go:605  [raftsnapshot,n1,s1,r14/1:/Table/1{7-8}] streamed snapshot to (n3,s3):2: kv pairs: 9, log entries: 7, rate-limit: 8.0 MiB/sec, 1ms
I180523 05:47:22.724028 50780 storage/replica_raftstorage.go:730  [n3,s3,r14/2:{-}] applying Raft snapshot at index 17 (id=c98ee743, encoded size=3309, 1 rocksdb batches, 7 log entries)
I180523 05:47:22.724345 50780 storage/replica_raftstorage.go:736  [n3,s3,r14/2:/Table/1{7-8}] applied Raft snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.725488 49773 storage/replica.go:3320  [n1,s1,r17/1:/Table/2{0-1}] proposing ADD_REPLICA((n3,s3):2): updated=[(n1,s1):1 (n3,s3):2] next=3
I180523 05:47:22.726001 49773 storage/replica_raftstorage.go:520  [replicate,n1,s1,r7/1:/Table/{SystemCon…-11}] generated preemptive snapshot f809d0ec at index 30
I180523 05:47:22.727237 49773 storage/store_snapshot.go:605  [replicate,n1,s1,r7/1:/Table/{SystemCon…-11}] streamed snapshot to (n2,s2):?: kv pairs: 57, log entries: 20, rate-limit: 8.0 MiB/sec, 1ms
I180523 05:47:22.727718 50797 storage/replica_raftstorage.go:730  [n2,s2,r7/?:{-}] applying preemptive snapshot at index 30 (id=f809d0ec, encoded size=15856, 1 rocksdb batches, 20 log entries)
I180523 05:47:22.728128 50797 storage/replica_raftstorage.go:736  [n2,s2,r7/?:/Table/{SystemCon…-11}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.732527 49773 storage/replica_command.go:1777  [replicate,n1,s1,r7/1:/Table/{SystemCon…-11}] change replicas (ADD_REPLICA (n2,s2):2): read existing descriptor r7:/Table/{SystemConfigSpan/Start-11} [(n1,s1):1, next=2]
I180523 05:47:22.732624 50783 storage/store.go:2492  [replicaGC,n2,s2,r7/?:/Table/{SystemCon…-11}] removing replica
I180523 05:47:22.732880 50783 storage/replica.go:829  [replicaGC,n2,s2,r7/?:/Table/{SystemCon…-11}] removed 54 (48+6) keys in 0ms [clear=0ms commit=0ms]
I180523 05:47:22.736435 49773 storage/replica.go:3320  [n1,s1,r7/1:/Table/{SystemCon…-11}] proposing ADD_REPLICA((n2,s2):2): updated=[(n1,s1):1 (n2,s2):2] next=3
I180523 05:47:22.736934 49773 storage/replica_raftstorage.go:520  [replicate,n1,s1,r1/1:/{Min-System/}] generated preemptive snapshot c7143d77 at index 114
I180523 05:47:22.738608 49773 storage/store_snapshot.go:605  [replicate,n1,s1,r1/1:/{Min-System/}] streamed snapshot to (n2,s2):?: kv pairs: 75, log entries: 52, rate-limit: 8.0 MiB/sec, 2ms
I180523 05:47:22.739036 50889 storage/replica_raftstorage.go:730  [n2,s2,r1/?:{-}] applying preemptive snapshot at index 114 (id=c7143d77, encoded size=13229, 1 rocksdb batches, 52 log entries)
I180523 05:47:22.739460 50889 storage/replica_raftstorage.go:736  [n2,s2,r1/?:/{Min-System/}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.739792 49773 storage/replica_command.go:1777  [replicate,n1,s1,r1/1:/{Min-System/}] change replicas (ADD_REPLICA (n2,s2):2): read existing descriptor r1:/{Min-System/} [(n1,s1):1, next=2]
I180523 05:47:22.739821 50798 storage/replica_raftstorage.go:520  [raftsnapshot,n1,s1,r7/1:/Table/{SystemCon…-11}] generated Raft snapshot 90c5e4ce at index 32
I180523 05:47:22.743481 50798 storage/store_snapshot.go:605  [raftsnapshot,n1,s1,r7/1:/Table/{SystemCon…-11}] streamed snapshot to (n2,s2):2: kv pairs: 59, log entries: 22, rate-limit: 8.0 MiB/sec, 4ms
I180523 05:47:22.743635 49773 storage/replica.go:3320  [n1,s1,r1/1:/{Min-System/}] proposing ADD_REPLICA((n2,s2):2): updated=[(n1,s1):1 (n2,s2):2] next=3
I180523 05:47:22.743911 50914 storage/replica_raftstorage.go:730  [n2,s2,r7/2:{-}] applying Raft snapshot at index 32 (id=90c5e4ce, encoded size=17215, 1 rocksdb batches, 22 log entries)
I180523 05:47:22.745058 50914 storage/replica_raftstorage.go:736  [n2,s2,r7/2:/Table/{SystemCon…-11}] applied Raft snapshot in 1ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.745469 50784 storage/store.go:2492  [replicaGC,n2,s2,r1/?:/{Min-System/}] removing replica
I180523 05:47:22.745654 49773 storage/replica_raftstorage.go:520  [replicate,n1,s1,r15/1:/Table/1{8-9}] generated preemptive snapshot 47c9ff8c at index 16
I180523 05:47:22.746632 50784 storage/replica.go:829  [replicaGC,n2,s2,r1/?:/{Min-System/}] removed 33 (23+10) keys in 1ms [clear=0ms commit=1ms]
I180523 05:47:22.748257 50840 storage/replica_raftstorage.go:520  [raftsnapshot,n1,s1,r1/1:/{Min-System/}] generated Raft snapshot 703c9ff8 at index 117
I180523 05:47:22.748726 49773 storage/store_snapshot.go:605  [replicate,n1,s1,r15/1:/Table/1{8-9}] streamed snapshot to (n2,s2):?: kv pairs: 8, log entries: 6, rate-limit: 8.0 MiB/sec, 3ms
I180523 05:47:22.749335 50948 storage/replica_raftstorage.go:730  [n2,s2,r15/?:{-}] applying preemptive snapshot at index 16 (id=47c9ff8c, encoded size=2262, 1 rocksdb batches, 6 log entries)
I180523 05:47:22.749602 50948 storage/replica_raftstorage.go:736  [n2,s2,r15/?:/Table/1{8-9}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.750285 49773 storage/replica_command.go:1777  [replicate,n1,s1,r15/1:/Table/1{8-9}] change replicas (ADD_REPLICA (n2,s2):2): read existing descriptor r15:/Table/1{8-9} [(n1,s1):1, next=2]
I180523 05:47:22.754607 50891 storage/replica_raftstorage.go:730  [n2,s2,r1/2:{-}] applying Raft snapshot at index 117 (id=703c9ff8, encoded size=15015, 1 rocksdb batches, 55 log entries)
I180523 05:47:22.755277 50891 storage/replica_raftstorage.go:736  [n2,s2,r1/2:/{Min-System/}] applied Raft snapshot in 1ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.755584 50840 storage/store_snapshot.go:605  [raftsnapshot,n1,s1,r1/1:/{Min-System/}] streamed snapshot to (n2,s2):2: kv pairs: 78, log entries: 55, rate-limit: 8.0 MiB/sec, 6ms
I180523 05:47:22.758138 49773 storage/replica.go:3320  [n1,s1,r15/1:/Table/1{8-9}] proposing ADD_REPLICA((n2,s2):2): updated=[(n1,s1):1 (n2,s2):2] next=3
I180523 05:47:22.758652 49773 storage/replica_raftstorage.go:520  [replicate,n1,s1,r19/1:/Table/2{2-3}] generated preemptive snapshot a73d9bad at index 15
I180523 05:47:22.762219 49773 storage/store_snapshot.go:605  [replicate,n1,s1,r19/1:/Table/2{2-3}] streamed snapshot to (n2,s2):?: kv pairs: 7, log entries: 5, rate-limit: 8.0 MiB/sec, 1ms
I180523 05:47:22.762708 50875 storage/replica_raftstorage.go:730  [n2,s2,r19/?:{-}] applying preemptive snapshot at index 15 (id=a73d9bad, encoded size=1950, 1 rocksdb batches, 5 log entries)
I180523 05:47:22.762987 50875 storage/replica_raftstorage.go:736  [n2,s2,r19/?:/Table/2{2-3}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.763538 49773 storage/replica_command.go:1777  [replicate,n1,s1,r19/1:/Table/2{2-3}] change replicas (ADD_REPLICA (n2,s2):2): read existing descriptor r19:/Table/2{2-3} [(n1,s1):1, next=2]
I180523 05:47:22.768778 50938 storage/store.go:2492  [replicaGC,n2,s2,r19/?:/Table/2{2-3}] removing replica
I180523 05:47:22.768956 50938 storage/replica.go:829  [replicaGC,n2,s2,r19/?:/Table/2{2-3}] removed 5 (0+5) keys in 0ms [clear=0ms commit=0ms]
I180523 05:47:22.769809 49773 storage/replica.go:3320  [n1,s1,r19/1:/Table/2{2-3}] proposing ADD_REPLICA((n2,s2):2): updated=[(n1,s1):1 (n2,s2):2] next=3
I180523 05:47:22.770533 49773 storage/replica_raftstorage.go:520  [replicate,n1,s1,r9/1:/Table/1{2-3}] generated preemptive snapshot 727616b1 at index 28
I180523 05:47:22.772634 50815 storage/replica_raftstorage.go:520  [raftsnapshot,n1,s1,r19/1:/Table/2{2-3}] generated Raft snapshot c9aaced5 at index 17
I180523 05:47:22.773006 49773 storage/store_snapshot.go:605  [replicate,n1,s1,r9/1:/Table/1{2-3}] streamed snapshot to (n3,s3):?: kv pairs: 52, log entries: 18, rate-limit: 8.0 MiB/sec, 1ms
I180523 05:47:22.773312 50815 storage/store_snapshot.go:605  [raftsnapshot,n1,s1,r19/1:/Table/2{2-3}] streamed snapshot to (n2,s2):2: kv pairs: 9, log entries: 7, rate-limit: 8.0 MiB/sec, 1ms
I180523 05:47:22.773556 50978 storage/replica_raftstorage.go:730  [n2,s2,r19/2:{-}] applying Raft snapshot at index 17 (id=c9aaced5, encoded size=3309, 1 rocksdb batches, 7 log entries)
I180523 05:47:22.773757 50944 storage/replica_raftstorage.go:730  [n3,s3,r9/?:{-}] applying preemptive snapshot at index 28 (id=727616b1, encoded size=16611, 1 rocksdb batches, 18 log entries)
I180523 05:47:22.773874 50978 storage/replica_raftstorage.go:736  [n2,s2,r19/2:/Table/2{2-3}] applied Raft snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.774234 50944 storage/replica_raftstorage.go:736  [n3,s3,r9/?:/Table/1{2-3}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.774586 49773 storage/replica_command.go:1777  [replicate,n1,s1,r9/1:/Table/1{2-3}] change replicas (ADD_REPLICA (n3,s3):2): read existing descriptor r9:/Table/1{2-3} [(n1,s1):1, next=2]
I180523 05:47:22.781254 49773 storage/replica.go:3320  [n1,s1,r9/1:/Table/1{2-3}] proposing ADD_REPLICA((n3,s3):2): updated=[(n1,s1):1 (n3,s3):2] next=3
I180523 05:47:22.783784 49773 storage/replica_raftstorage.go:520  [replicate,n1,s1,r5/1:/System/ts{d-e}] generated preemptive snapshot 833f3351 at index 20
I180523 05:47:22.789318 49773 storage/store_snapshot.go:605  [replicate,n1,s1,r5/1:/System/ts{d-e}] streamed snapshot to (n3,s3):?: kv pairs: 965, log entries: 2, rate-limit: 8.0 MiB/sec, 5ms
I180523 05:47:22.790184 50994 storage/replica_raftstorage.go:730  [n3,s3,r5/?:{-}] applying preemptive snapshot at index 20 (id=833f3351, encoded size=131044, 1 rocksdb batches, 2 log entries)
I180523 05:47:22.791961 50994 storage/replica_raftstorage.go:736  [n3,s3,r5/?:/System/ts{d-e}] applied preemptive snapshot in 2ms [clear=0ms batch=0ms entries=0ms commit=1ms]
I180523 05:47:22.792404 49773 storage/replica_command.go:1777  [replicate,n1,s1,r5/1:/System/ts{d-e}] change replicas (ADD_REPLICA (n3,s3):2): read existing descriptor r5:/System/ts{d-e} [(n1,s1):1, next=2]
I180523 05:47:22.794038 49511 testutils/testcluster/testcluster.go:536  [n1,s1] has 21 underreplicated ranges
I180523 05:47:22.810843 49773 storage/replica.go:3320  [n1,s1,r5/1:/System/ts{d-e}] proposing ADD_REPLICA((n3,s3):2): updated=[(n1,s1):1 (n3,s3):2] next=3
I180523 05:47:22.811445 49773 storage/replica_raftstorage.go:520  [replicate,n1,s1,r22/1:/{Table/51-Max}] generated preemptive snapshot fe8ef260 at index 11
I180523 05:47:22.813672 49773 storage/store_snapshot.go:605  [replicate,n1,s1,r22/1:/{Table/51-Max}] streamed snapshot to (n3,s3):?: kv pairs: 6, log entries: 1, rate-limit: 8.0 MiB/sec, 2ms
I180523 05:47:22.815308 50929 storage/replica_raftstorage.go:730  [n3,s3,r22/?:{-}] applying preemptive snapshot at index 11 (id=fe8ef260, encoded size=300, 1 rocksdb batches, 1 log entries)
I180523 05:47:22.815536 50929 storage/replica_raftstorage.go:736  [n3,s3,r22/?:/{Table/51-Max}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.815984 49773 storage/replica_command.go:1777  [replicate,n1,s1,r22/1:/{Table/51-Max}] change replicas (ADD_REPLICA (n3,s3):2): read existing descriptor r22:/{Table/51-Max} [(n1,s1):1, next=2]
I180523 05:47:22.835263 49773 storage/replica.go:3320  [n1,s1,r22/1:/{Table/51-Max}] proposing ADD_REPLICA((n3,s3):2): updated=[(n1,s1):1 (n3,s3):2] next=3
I180523 05:47:22.835597 49773 storage/queue.go:864  [n1,replicate] purgatory is now empty
I180523 05:47:22.835865 50954 storage/replica_raftstorage.go:520  [replicate,n1,s1,r4/1:/System/{NodeLive…-tsd}] generated preemptive snapshot 864d5659 at index 43
I180523 05:47:22.838378 50954 storage/store_snapshot.go:605  [replicate,n1,s1,r4/1:/System/{NodeLive…-tsd}] streamed snapshot to (n2,s2):?: kv pairs: 38, log entries: 33, rate-limit: 8.0 MiB/sec, 2ms
I180523 05:47:22.839304 50959 storage/replica_raftstorage.go:730  [n2,s2,r4/?:{-}] applying preemptive snapshot at index 43 (id=864d5659, encoded size=112664, 1 rocksdb batches, 33 log entries)
I180523 05:47:22.840014 50959 storage/replica_raftstorage.go:736  [n2,s2,r4/?:/System/{NodeLive…-tsd}] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.850948 50954 storage/replica_command.go:1777  [replicate,n1,s1,r4/1:/System/{NodeLive…-tsd}] change replicas (ADD_REPLICA (n2,s2):3): read existing descriptor r4:/System/{NodeLivenessMax-tsd} [(n1,s1):1, (n3,s3):2, next=3]
I180523 05:47:22.860618 50954 storage/replica.go:3320  [n1,s1,r4/1:/System/{NodeLive…-tsd}] proposing ADD_REPLICA((n2,s2):3): updated=[(n1,s1):1 (n3,s3):2 (n2,s2):3] next=4
I180523 05:47:22.862009 50990 storage/replica_raftstorage.go:520  [replicate,n1,s1,r22/1:/{Table/51-Max}] generated preemptive snapshot 87631847 at index 14
I180523 05:47:22.863145 50990 storage/store_snapshot.go:605  [replicate,n1,s1,r22/1:/{Table/51-Max}] streamed snapshot to (n2,s2):?: kv pairs: 7, log entries: 4, rate-limit: 8.0 MiB/sec, 1ms
I180523 05:47:22.876319 51027 storage/replica_raftstorage.go:730  [n2,s2,r22/?:{-}] applying preemptive snapshot at index 14 (id=87631847, encoded size=1334, 1 rocksdb batches, 4 log entries)
I180523 05:47:22.876520 51027 storage/replica_raftstorage.go:736  [n2,s2,r22/?:/{Table/51-Max}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.876890 50990 storage/replica_command.go:1777  [replicate,n1,s1,r22/1:/{Table/51-Max}] change replicas (ADD_REPLICA (n2,s2):3): read existing descriptor r22:/{Table/51-Max} [(n1,s1):1, (n3,s3):2, next=3]
I180523 05:47:22.886111 50990 storage/replica.go:3320  [n1,s1,r22/1:/{Table/51-Max}] proposing ADD_REPLICA((n2,s2):3): updated=[(n1,s1):1 (n3,s3):2 (n2,s2):3] next=4
I180523 05:47:22.890390 49511 testutils/testcluster/testcluster.go:536  [n1,s1] has 19 underreplicated ranges
I180523 05:47:22.892779 51074 storage/replica_raftstorage.go:520  [replicate,n1,s1,r6/1:/{System/tse-Table/System…}] generated preemptive snapshot fc388376 at index 24
I180523 05:47:22.894269 51074 storage/store_snapshot.go:605  [replicate,n1,s1,r6/1:/{System/tse-Table/System…}] streamed snapshot to (n3,s3):?: kv pairs: 9, log entries: 14, rate-limit: 8.0 MiB/sec, 1ms
I180523 05:47:22.894802 51021 storage/replica_raftstorage.go:730  [n3,s3,r6/?:{-}] applying preemptive snapshot at index 24 (id=fc388376, encoded size=6576, 1 rocksdb batches, 14 log entries)
I180523 05:47:22.895094 51021 storage/replica_raftstorage.go:736  [n3,s3,r6/?:/{System/tse-Table/System…}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.895433 51074 storage/replica_command.go:1777  [replicate,n1,s1,r6/1:/{System/tse-Table/System…}] change replicas (ADD_REPLICA (n3,s3):3): read existing descriptor r6:/{System/tse-Table/SystemConfigSpan/Start} [(n1,s1):1, (n2,s2):2, next=3]
I180523 05:47:22.903686 51030 storage/store.go:2492  [replicaGC,n3,s3,r6/?:/{System/tse-Table/System…}] removing replica
I180523 05:47:22.903876 51030 storage/replica.go:829  [replicaGC,n3,s3,r6/?:/{System/tse-Table/System…}] removed 6 (0+6) keys in 0ms [clear=0ms commit=0ms]
I180523 05:47:22.908685 51074 storage/replica.go:3320  [n1,s1,r6/1:/{System/tse-Table/System…}] proposing ADD_REPLICA((n3,s3):3): updated=[(n1,s1):1 (n2,s2):2 (n3,s3):3] next=4
I180523 05:47:22.909859 51063 storage/replica_raftstorage.go:520  [replicate,n1,s1,r20/1:/Table/{23-50}] generated preemptive snapshot 33aa827d at index 18
I180523 05:47:22.910954 51063 storage/store_snapshot.go:605  [replicate,n1,s1,r20/1:/Table/{23-50}] streamed snapshot to (n3,s3):?: kv pairs: 12, log entries: 8, rate-limit: 8.0 MiB/sec, 1ms
I180523 05:47:22.911457 51091 storage/replica_raftstorage.go:730  [n3,s3,r20/?:{-}] applying preemptive snapshot at index 18 (id=33aa827d, encoded size=3106, 1 rocksdb batches, 8 log entries)
I180523 05:47:22.911707 51091 storage/replica_raftstorage.go:736  [n3,s3,r20/?:/Table/{23-50}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.912161 51063 storage/replica_command.go:1777  [replicate,n1,s1,r20/1:/Table/{23-50}] change replicas (ADD_REPLICA (n3,s3):3): read existing descriptor r20:/Table/{23-50} [(n1,s1):1, (n2,s2):2, next=3]
I180523 05:47:22.914614 51009 storage/replica_raftstorage.go:520  [raftsnapshot,n1,s1,r6/1:/{System/tse-Table/System…}] generated Raft snapshot 7dfc9b59 at index 27
I180523 05:47:22.915266 51009 storage/store_snapshot.go:605  [raftsnapshot,n1,s1,r6/1:/{System/tse-Table/System…}] streamed snapshot to (n3,s3):3: kv pairs: 10, log entries: 17, rate-limit: 8.0 MiB/sec, 1ms
I180523 05:47:22.915411 51065 storage/store.go:2492  [replicaGC,n3,s3,r20/?:/Table/{23-50}] removing replica
I180523 05:47:22.915527 51108 storage/replica_raftstorage.go:730  [n3,s3,r6/3:{-}] applying Raft snapshot at index 27 (id=7dfc9b59, encoded size=7792, 1 rocksdb batches, 17 log entries)
I180523 05:47:22.916087 51065 storage/replica.go:829  [replicaGC,n3,s3,r20/?:/Table/{23-50}] removed 9 (4+5) keys in 0ms [clear=0ms commit=0ms]
I180523 05:47:22.916168 51108 storage/replica_raftstorage.go:736  [n3,s3,r6/3:/{System/tse-Table/System…}] applied Raft snapshot in 1ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.921397 51033 storage/replica.go:3320  [n1,s1,r20/1:/Table/{23-50}] proposing ADD_REPLICA((n3,s3):3): updated=[(n1,s1):1 (n2,s2):2 (n3,s3):3] next=4
I180523 05:47:22.922515 51077 storage/replica_raftstorage.go:520  [replicate,n1,s1,r16/1:/Table/{19-20}] generated preemptive snapshot a17749ea at index 18
I180523 05:47:22.923632 51077 storage/store_snapshot.go:605  [replicate,n1,s1,r16/1:/Table/{19-20}] streamed snapshot to (n2,s2):?: kv pairs: 8, log entries: 8, rate-limit: 8.0 MiB/sec, 1ms
I180523 05:47:22.924097 51080 storage/replica_raftstorage.go:730  [n2,s2,r16/?:{-}] applying preemptive snapshot at index 18 (id=a17749ea, encoded size=2974, 1 rocksdb batches, 8 log entries)
I180523 05:47:22.924317 51080 storage/replica_raftstorage.go:736  [n2,s2,r16/?:/Table/{19-20}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.924687 51077 storage/replica_command.go:1777  [replicate,n1,s1,r16/1:/Table/{19-20}] change replicas (ADD_REPLICA (n2,s2):3): read existing descriptor r16:/Table/{19-20} [(n1,s1):1, (n3,s3):2, next=3]
I180523 05:47:22.929065 51077 storage/replica.go:3320  [n1,s1,r16/1:/Table/{19-20}] proposing ADD_REPLICA((n2,s2):3): updated=[(n1,s1):1 (n3,s3):2 (n2,s2):3] next=4
I180523 05:47:22.930310 51082 storage/replica_raftstorage.go:520  [replicate,n1,s1,r7/1:/Table/{SystemCon…-11}] generated preemptive snapshot d8d2736d at index 33
I180523 05:47:22.932961 51082 storage/store_snapshot.go:605  [replicate,n1,s1,r7/1:/Table/{SystemCon…-11}] streamed snapshot to (n3,s3):?: kv pairs: 58, log entries: 23, rate-limit: 8.0 MiB/sec, 3ms
I180523 05:47:22.933782 51070 storage/replica_raftstorage.go:730  [n3,s3,r7/?:{-}] applying preemptive snapshot at index 33 (id=d8d2736d, encoded size=16984, 1 rocksdb batches, 23 log entries)
I180523 05:47:22.934108 51070 storage/replica_raftstorage.go:736  [n3,s3,r7/?:/Table/{SystemCon…-11}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.934511 51082 storage/replica_command.go:1777  [replicate,n1,s1,r7/1:/Table/{SystemCon…-11}] change replicas (ADD_REPLICA (n3,s3):3): read existing descriptor r7:/Table/{SystemConfigSpan/Start-11} [(n1,s1):1, (n2,s2):2, next=3]
I180523 05:47:22.936286 51035 storage/replica_raftstorage.go:520  [raftsnapshot,n1,s1,r20/1:/Table/{23-50}] generated Raft snapshot 8925ce9a at index 20
I180523 05:47:22.939604 51082 storage/replica.go:3320  [n1,s1,r7/1:/Table/{SystemCon…-11}] proposing ADD_REPLICA((n3,s3):3): updated=[(n1,s1):1 (n2,s2):2 (n3,s3):3] next=4
I180523 05:47:22.940476 51121 storage/replica_raftstorage.go:520  [replicate,n1,s1,r1/1:/{Min-System/}] generated preemptive snapshot aaa45d89 at index 139
I180523 05:47:22.944816 51121 storage/store_snapshot.go:605  [replicate,n1,s1,r1/1:/{Min-System/}] streamed snapshot to (n3,s3):?: kv pairs: 89, log entries: 77, rate-limit: 8.0 MiB/sec, 4ms
I180523 05:47:22.945513 51038 storage/replica_raftstorage.go:730  [n3,s3,r1/?:{-}] applying preemptive snapshot at index 139 (id=aaa45d89, encoded size=18986, 1 rocksdb batches, 77 log entries)
I180523 05:47:22.946213 51038 storage/replica_raftstorage.go:736  [n3,s3,r1/?:/{Min-System/}] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.946796 51121 storage/replica_command.go:1777  [replicate,n1,s1,r1/1:/{Min-System/}] change replicas (ADD_REPLICA (n3,s3):3): read existing descriptor r1:/{Min-System/} [(n1,s1):1, (n2,s2):2, next=3]
I180523 05:47:22.947322 51035 storage/store_snapshot.go:605  [raftsnapshot,n1,s1,r20/1:/Table/{23-50}] streamed snapshot to (n3,s3):3: kv pairs: 14, log entries: 10, rate-limit: 8.0 MiB/sec, 8ms
I180523 05:47:22.947556 50971 storage/replica_raftstorage.go:730  [n3,s3,r20/3:{-}] applying Raft snapshot at index 20 (id=8925ce9a, encoded size=4505, 1 rocksdb batches, 10 log entries)
I180523 05:47:22.947823 50971 storage/replica_raftstorage.go:736  [n3,s3,r20/3:/Table/{23-50}] applied Raft snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.950796 50972 storage/replica.go:3320  [n1,s1,r1/1:/{Min-System/}] proposing ADD_REPLICA((n3,s3):3): updated=[(n1,s1):1 (n2,s2):2 (n3,s3):3] next=4
I180523 05:47:22.951747 50975 storage/replica_raftstorage.go:520  [replicate,n1,s1,r18/1:/Table/2{1-2}] generated preemptive snapshot 74239f48 at index 18
I180523 05:47:22.953484 51041 storage/replica_raftstorage.go:730  [n3,s3,r18/?:{-}] applying preemptive snapshot at index 18 (id=74239f48, encoded size=3143, 1 rocksdb batches, 8 log entries)
I180523 05:47:22.953704 51041 storage/replica_raftstorage.go:736  [n3,s3,r18/?:/Table/2{1-2}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.953841 50975 storage/store_snapshot.go:605  [replicate,n1,s1,r18/1:/Table/2{1-2}] streamed snapshot to (n3,s3):?: kv pairs: 8, log entries: 8, rate-limit: 8.0 MiB/sec, 1ms
I180523 05:47:22.954107 50975 storage/replica_command.go:1777  [replicate,n1,s1,r18/1:/Table/2{1-2}] change replicas (ADD_REPLICA (n3,s3):3): read existing descriptor r18:/Table/2{1-2} [(n1,s1):1, (n2,s2):2, next=3]
I180523 05:47:22.958011 50975 storage/replica.go:3320  [n1,s1,r18/1:/Table/2{1-2}] proposing ADD_REPLICA((n3,s3):3): updated=[(n1,s1):1 (n2,s2):2 (n3,s3):3] next=4
I180523 05:47:22.963971 51186 storage/replica_raftstorage.go:520  [replicate,n1,s1,r15/1:/Table/1{8-9}] generated preemptive snapshot 2cb84ff9 at index 19
I180523 05:47:22.966574 51186 storage/store_snapshot.go:605  [replicate,n1,s1,r15/1:/Table/1{8-9}] streamed snapshot to (n3,s3):?: kv pairs: 9, log entries: 9, rate-limit: 8.0 MiB/sec, 1ms
I180523 05:47:22.967000 51173 storage/replica_raftstorage.go:730  [n3,s3,r15/?:{-}] applying preemptive snapshot at index 19 (id=2cb84ff9, encoded size=3290, 1 rocksdb batches, 9 log entries)
I180523 05:47:22.967260 51173 storage/replica_raftstorage.go:736  [n3,s3,r15/?:/Table/1{8-9}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.967797 51186 storage/replica_command.go:1777  [replicate,n1,s1,r15/1:/Table/1{8-9}] change replicas (ADD_REPLICA (n3,s3):3): read existing descriptor r15:/Table/1{8-9} [(n1,s1):1, (n2,s2):2, next=3]
I180523 05:47:22.972947 51161 storage/store.go:2492  [replicaGC,n3,s3,r15/?:/Table/1{8-9}] removing replica
I180523 05:47:22.973109 51161 storage/replica.go:829  [replicaGC,n3,s3,r15/?:/Table/1{8-9}] removed 6 (0+6) keys in 0ms [clear=0ms commit=0ms]
I180523 05:47:22.974528 51186 storage/replica.go:3320  [n1,s1,r15/1:/Table/1{8-9}] proposing ADD_REPLICA((n3,s3):3): updated=[(n1,s1):1 (n2,s2):2 (n3,s3):3] next=4
I180523 05:47:22.976238 51127 storage/replica_raftstorage.go:520  [replicate,n1,s1,r19/1:/Table/2{2-3}] generated preemptive snapshot e1f7c8ae at index 18
I180523 05:47:22.982285 51047 storage/replica_raftstorage.go:520  [raftsnapshot,n1,s1,r15/1:/Table/1{8-9}] generated Raft snapshot 12ba8bfc at index 21
I180523 05:47:22.982569 51127 storage/store_snapshot.go:605  [replicate,n1,s1,r19/1:/Table/2{2-3}] streamed snapshot to (n3,s3):?: kv pairs: 8, log entries: 8, rate-limit: 8.0 MiB/sec, 6ms
I180523 05:47:22.982935 51047 storage/store_snapshot.go:605  [raftsnapshot,n1,s1,r15/1:/Table/1{8-9}] streamed snapshot to (n3,s3):3: kv pairs: 11, log entries: 11, rate-limit: 8.0 MiB/sec, 1ms
I180523 05:47:22.982975 51202 storage/replica_raftstorage.go:730  [n3,s3,r19/?:{-}] applying preemptive snapshot at index 18 (id=e1f7c8ae, encoded size=3078, 1 rocksdb batches, 8 log entries)
I180523 05:47:22.983188 51202 storage/replica_raftstorage.go:736  [n3,s3,r19/?:/Table/2{2-3}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.983531 51166 storage/replica_raftstorage.go:730  [n3,s3,r15/3:{-}] applying Raft snapshot at index 21 (id=12ba8bfc, encoded size=4689, 1 rocksdb batches, 11 log entries)
I180523 05:47:22.983810 51166 storage/replica_raftstorage.go:736  [n3,s3,r15/3:/Table/1{8-9}] applied Raft snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:22.984990 51127 storage/replica_command.go:1777  [replicate,n1,s1,r19/1:/Table/2{2-3}] change replicas (ADD_REPLICA (n3,s3):3): read existing descriptor r19:/Table/2{2-3} [(n1,s1):1, (n2,s2):2, next=3]
I180523 05:47:23.000017 49511 testutils/testcluster/testcluster.go:536  [n1,s1] has 12 underreplicated ranges
I180523 05:47:23.003324 51224 storage/store.go:2492  [replicaGC,n3,s3,r19/?:/Table/2{2-3}] removing replica
I180523 05:47:23.003504 51224 storage/replica.go:829  [replicaGC,n3,s3,r19/?:/Table/2{2-3}] removed 5 (0+5) keys in 0ms [clear=0ms commit=0ms]
I180523 05:47:23.004527 51127 storage/replica.go:3320  [n1,s1,r19/1:/Table/2{2-3}] proposing ADD_REPLICA((n3,s3):3): updated=[(n1,s1):1 (n2,s2):2 (n3,s3):3] next=4
I180523 05:47:23.007421 51192 storage/replica_raftstorage.go:520  [raftsnapshot,n1,s1,r19/1:/Table/2{2-3}] generated Raft snapshot 40a079d2 at index 21
I180523 05:47:23.008138 51192 storage/store_snapshot.go:605  [raftsnapshot,n1,s1,r19/1:/Table/2{2-3}] streamed snapshot to (n3,s3):3: kv pairs: 9, log entries: 11, rate-limit: 8.0 MiB/sec, 1ms
I180523 05:47:23.008361 51130 storage/replica_raftstorage.go:730  [n3,s3,r19/3:{-}] applying Raft snapshot at index 21 (id=40a079d2, encoded size=4246, 1 rocksdb batches, 11 log entries)
I180523 05:47:23.008729 51130 storage/replica_raftstorage.go:736  [n3,s3,r19/3:/Table/2{2-3}] applied Raft snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:23.009725 51051 storage/replica_raftstorage.go:520  [replicate,n1,s1,r21/1:/Table/5{0-1}] generated preemptive snapshot 6f95dcba at index 18
I180523 05:47:23.013581 51051 storage/store_snapshot.go:605  [replicate,n1,s1,r21/1:/Table/5{0-1}] streamed snapshot to (n2,s2):?: kv pairs: 8, log entries: 8, rate-limit: 8.0 MiB/sec, 4ms
I180523 05:47:23.014053 51132 storage/replica_raftstorage.go:730  [n2,s2,r21/?:{-}] applying preemptive snapshot at index 18 (id=6f95dcba, encoded size=3047, 1 rocksdb batches, 8 log entries)
I180523 05:47:23.014457 51132 storage/replica_raftstorage.go:736  [n2,s2,r21/?:/Table/5{0-1}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:23.014955 51051 storage/replica_command.go:1777  [replicate,n1,s1,r21/1:/Table/5{0-1}] change replicas (ADD_REPLICA (n2,s2):3): read existing descriptor r21:/Table/5{0-1} [(n1,s1):1, (n3,s3):2, next=3]
I180523 05:47:23.020012 51237 storage/replica.go:3320  [n1,s1,r21/1:/Table/5{0-1}] proposing ADD_REPLICA((n2,s2):3): updated=[(n1,s1):1 (n3,s3):2 (n2,s2):3] next=4
I180523 05:47:23.021137 51134 storage/replica_raftstorage.go:520  [replicate,n1,s1,r11/1:/Table/1{4-5}] generated preemptive snapshot 0e1cd99e at index 18
I180523 05:47:23.022796 51134 storage/store_snapshot.go:605  [replicate,n1,s1,r11/1:/Table/1{4-5}] streamed snapshot to (n3,s3):?: kv pairs: 8, log entries: 8, rate-limit: 8.0 MiB/sec, 1ms
I180523 05:47:23.036467 51137 storage/replica_raftstorage.go:730  [n3,s3,r11/?:{-}] applying preemptive snapshot at index 18 (id=0e1cd99e, encoded size=2968, 1 rocksdb batches, 8 log entries)
I180523 05:47:23.036809 51137 storage/replica_raftstorage.go:736  [n3,s3,r11/?:/Table/1{4-5}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:23.037429 51134 storage/replica_command.go:1777  [replicate,n1,s1,r11/1:/Table/1{4-5}] change replicas (ADD_REPLICA (n3,s3):3): read existing descriptor r11:/Table/1{4-5} [(n1,s1):1, (n2,s2):2, next=3]
I180523 05:47:23.045691 51134 storage/replica.go:3320  [n1,s1,r11/1:/Table/1{4-5}] proposing ADD_REPLICA((n3,s3):3): updated=[(n1,s1):1 (n2,s2):2 (n3,s3):3] next=4
I180523 05:47:23.047135 51056 storage/replica_raftstorage.go:520  [replicate,n1,s1,r9/1:/Table/1{2-3}] generated preemptive snapshot 114be705 at index 31
I180523 05:47:23.065781 51056 storage/store_snapshot.go:605  [replicate,n1,s1,r9/1:/Table/1{2-3}] streamed snapshot to (n2,s2):?: kv pairs: 53, log entries: 21, rate-limit: 8.0 MiB/sec, 19ms
I180523 05:47:23.069212 51267 storage/replica_raftstorage.go:730  [n2,s2,r9/?:{-}] applying preemptive snapshot at index 31 (id=114be705, encoded size=17639, 1 rocksdb batches, 21 log entries)
I180523 05:47:23.070233 51267 storage/replica_raftstorage.go:736  [n2,s2,r9/?:/Table/1{2-3}] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:23.070616 51056 storage/replica_command.go:1777  [replicate,n1,s1,r9/1:/Table/1{2-3}] change replicas (ADD_REPLICA (n2,s2):3): read existing descriptor r9:/Table/1{2-3} [(n1,s1):1, (n3,s3):2, next=3]
I180523 05:47:23.076369 51056 storage/replica.go:3320  [n1,s1,r9/1:/Table/1{2-3}] proposing ADD_REPLICA((n2,s2):3): updated=[(n1,s1):1 (n3,s3):2 (n2,s2):3] next=4
I180523 05:47:23.086508 51212 storage/replica_raftstorage.go:520  [replicate,n1,s1,r5/1:/System/ts{d-e}] generated preemptive snapshot af3eaa98 at index 23
I180523 05:47:23.094292 51212 storage/store_snapshot.go:605  [replicate,n1,s1,r5/1:/System/ts{d-e}] streamed snapshot to (n2,s2):?: kv pairs: 966, log entries: 5, rate-limit: 8.0 MiB/sec, 8ms
I180523 05:47:23.095211 51197 storage/replica_raftstorage.go:730  [n2,s2,r5/?:{-}] applying preemptive snapshot at index 23 (id=af3eaa98, encoded size=132123, 1 rocksdb batches, 5 log entries)
I180523 05:47:23.096742 51197 storage/replica_raftstorage.go:736  [n2,s2,r5/?:/System/ts{d-e}] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=0ms commit=1ms]
I180523 05:47:23.097768 51212 storage/replica_command.go:1777  [replicate,n1,s1,r5/1:/System/ts{d-e}] change replicas (ADD_REPLICA (n2,s2):3): read existing descriptor r5:/System/ts{d-e} [(n1,s1):1, (n3,s3):2, next=3]
I180523 05:47:23.098196 51269 storage/store.go:2492  [replicaGC,n2,s2,r5/?:/System/ts{d-e}] removing replica
I180523 05:47:23.098364 51269 storage/replica.go:829  [replicaGC,n2,s2,r5/?:/System/ts{d-e}] removed 437 (431+6) keys in 0ms [clear=0ms commit=0ms]
I180523 05:47:23.106884 51212 storage/replica.go:3320  [n1,s1,r5/1:/System/ts{d-e}] proposing ADD_REPLICA((n2,s2):3): updated=[(n1,s1):1 (n3,s3):2 (n2,s2):3] next=4
I180523 05:47:23.112726 51148 storage/replica_raftstorage.go:520  [raftsnapshot,n1,s1,r5/1:/System/ts{d-e}] generated Raft snapshot 00bb6796 at index 26
I180523 05:47:23.115199 49511 testutils/testcluster/testcluster.go:536  [n1,s1] has 7 underreplicated ranges
I180523 05:47:23.118456 51148 storage/store_snapshot.go:605  [raftsnapshot,n1,s1,r5/1:/System/ts{d-e}] streamed snapshot to (n2,s2):3: kv pairs: 967, log entries: 8, rate-limit: 8.0 MiB/sec, 6ms
I180523 05:47:23.119132 51151 storage/replica_raftstorage.go:730  [n2,s2,r5/3:{-}] applying Raft snapshot at index 26 (id=00bb6796, encoded size=133354, 1 rocksdb batches, 8 log entries)
I180523 05:47:23.119817 51201 storage/replica_raftstorage.go:520  [replicate,n1,s1,r13/1:/Table/1{6-7}] generated preemptive snapshot 78b7f0c9 at index 18
I180523 05:47:23.121248 51201 storage/store_snapshot.go:605  [replicate,n1,s1,r13/1:/Table/1{6-7}] streamed snapshot to (n3,s3):?: kv pairs: 8, log entries: 8, rate-limit: 8.0 MiB/sec, 1ms
I180523 05:47:23.123354 51215 storage/replica_raftstorage.go:730  [n3,s3,r13/?:{-}] applying preemptive snapshot at index 18 (id=78b7f0c9, encoded size=3243, 1 rocksdb batches, 8 log entries)
I180523 05:47:23.123596 51215 storage/replica_raftstorage.go:736  [n3,s3,r13/?:/Table/1{6-7}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:23.124946 51201 storage/replica_command.go:1777  [replicate,n1,s1,r13/1:/Table/1{6-7}] change replicas (ADD_REPLICA (n3,s3):3): read existing descriptor r13:/Table/1{6-7} [(n1,s1):1, (n2,s2):2, next=3]
I180523 05:47:23.128663 51216 storage/store.go:2492  [replicaGC,n3,s3,r13/?:/Table/1{6-7}] removing replica
I180523 05:47:23.129657 51216 storage/replica.go:829  [replicaGC,n3,s3,r13/?:/Table/1{6-7}] removed 5 (0+5) keys in 0ms [clear=0ms commit=0ms]
I180523 05:47:23.129887 51151 storage/replica_raftstorage.go:736  [n2,s2,r5/3:/System/ts{d-e}] applied Raft snapshot in 11ms [clear=0ms batch=1ms entries=0ms commit=9ms]
I180523 05:47:23.137566 51201 storage/replica.go:3320  [n1,s1,r13/1:/Table/1{6-7}] proposing ADD_REPLICA((n3,s3):3): updated=[(n1,s1):1 (n2,s2):2 (n3,s3):3] next=4
I180523 05:47:23.144050 51174 storage/replica_raftstorage.go:520  [raftsnapshot,n1,s1,r13/1:/Table/1{6-7}] generated Raft snapshot 52a94636 at index 21
I180523 05:47:23.144730 51174 storage/store_snapshot.go:605  [raftsnapshot,n1,s1,r13/1:/Table/1{6-7}] streamed snapshot to (n3,s3):3: kv pairs: 9, log entries: 11, rate-limit: 8.0 MiB/sec, 1ms
I180523 05:47:23.144969 51177 storage/replica_raftstorage.go:730  [n3,s3,r13/3:{-}] applying Raft snapshot at index 21 (id=52a94636, encoded size=4411, 1 rocksdb batches, 11 log entries)
I180523 05:47:23.145335 51177 storage/replica_raftstorage.go:736  [n3,s3,r13/3:/Table/1{6-7}] applied Raft snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:23.158578 51314 storage/replica_raftstorage.go:520  [replicate,n1,s1,r3/1:/System/NodeLiveness{-Max}] generated preemptive snapshot 392988ce at index 25
I180523 05:47:23.159334 51314 storage/store_snapshot.go:605  [replicate,n1,s1,r3/1:/System/NodeLiveness{-Max}] streamed snapshot to (n2,s2):?: kv pairs: 13, log entries: 15, rate-limit: 8.0 MiB/sec, 1ms
I180523 05:47:23.159756 51275 storage/replica_raftstorage.go:730  [n2,s2,r3/?:{-}] applying preemptive snapshot at index 25 (id=392988ce, encoded size=5986, 1 rocksdb batches, 15 log entries)
I180523 05:47:23.160079 51275 storage/replica_raftstorage.go:736  [n2,s2,r3/?:/System/NodeLiveness{-Max}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:23.160482 51314 storage/replica_command.go:1777  [replicate,n1,s1,r3/1:/System/NodeLiveness{-Max}] change replicas (ADD_REPLICA (n2,s2):3): read existing descriptor r3:/System/NodeLiveness{-Max} [(n1,s1):1, (n3,s3):2, next=3]
I180523 05:47:23.164962 51301 storage/store.go:2492  [replicaGC,n2,s2,r3/?:/System/NodeLiveness{-Max}] removing replica
I180523 05:47:23.165220 51301 storage/replica.go:829  [replicaGC,n2,s2,r3/?:/System/NodeLiveness{-Max}] removed 10 (3+7) keys in 0ms [clear=0ms commit=0ms]
I180523 05:47:23.172208 51314 storage/replica.go:3320  [n1,s1,r3/1:/System/NodeLiveness{-Max}] proposing ADD_REPLICA((n2,s2):3): updated=[(n1,s1):1 (n3,s3):2 (n2,s2):3] next=4
I180523 05:47:23.174011 51277 storage/replica_raftstorage.go:520  [replicate,n1,s1,r8/1:/Table/1{1-2}] generated preemptive snapshot 9e0e0a3a at index 20
I180523 05:47:23.177949 51277 storage/store_snapshot.go:605  [replicate,n1,s1,r8/1:/Table/1{1-2}] streamed snapshot to (n2,s2):?: kv pairs: 8, log entries: 10, rate-limit: 8.0 MiB/sec, 4ms
I180523 05:47:23.178405 51330 storage/replica_raftstorage.go:730  [n2,s2,r8/?:{-}] applying preemptive snapshot at index 20 (id=9e0e0a3a, encoded size=4543, 1 rocksdb batches, 10 log entries)
I180523 05:47:23.178690 51330 storage/replica_raftstorage.go:736  [n2,s2,r8/?:/Table/1{1-2}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:23.179011 51277 storage/replica_command.go:1777  [replicate,n1,s1,r8/1:/Table/1{1-2}] change replicas (ADD_REPLICA (n2,s2):3): read existing descriptor r8:/Table/1{1-2} [(n1,s1):1, (n3,s3):2, next=3]
I180523 05:47:23.186069 51318 storage/replica_raftstorage.go:520  [raftsnapshot,n1,s1,r3/1:/System/NodeLiveness{-Max}] generated Raft snapshot 56d95117 at index 28
I180523 05:47:23.187122 51318 storage/store_snapshot.go:605  [raftsnapshot,n1,s1,r3/1:/System/NodeLiveness{-Max}] streamed snapshot to (n2,s2):3: kv pairs: 14, log entries: 18, rate-limit: 8.0 MiB/sec, 1ms
I180523 05:47:23.187378 51321 storage/replica_raftstorage.go:730  [n2,s2,r3/3:{-}] applying Raft snapshot at index 28 (id=56d95117, encoded size=7376, 1 rocksdb batches, 18 log entries)
I180523 05:47:23.187637 51321 storage/replica_raftstorage.go:736  [n2,s2,r3/3:/System/NodeLiveness{-Max}] applied Raft snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:23.188536 51277 storage/replica.go:3320  [n1,s1,r8/1:/Table/1{1-2}] proposing ADD_REPLICA((n2,s2):3): updated=[(n1,s1):1 (n3,s3):2 (n2,s2):3] next=4
I180523 05:47:23.189686 51334 storage/replica_raftstorage.go:520  [replicate,n1,s1,r12/1:/Table/1{5-6}] generated preemptive snapshot c3aec4f3 at index 18
I180523 05:47:23.197292 51334 storage/store_snapshot.go:605  [replicate,n1,s1,r12/1:/Table/1{5-6}] streamed snapshot to (n2,s2):?: kv pairs: 8, log entries: 8, rate-limit: 8.0 MiB/sec, 8ms
I180523 05:47:23.199240 51257 storage/replica_raftstorage.go:730  [n2,s2,r12/?:{-}] applying preemptive snapshot at index 18 (id=c3aec4f3, encoded size=3139, 1 rocksdb batches, 8 log entries)
I180523 05:47:23.209290 51257 storage/replica_raftstorage.go:736  [n2,s2,r12/?:/Table/1{5-6}] applied preemptive snapshot in 10ms [clear=0ms batch=2ms entries=0ms commit=7ms]
I180523 05:47:23.210372 51334 storage/replica_command.go:1777  [replicate,n1,s1,r12/1:/Table/1{5-6}] change replicas (ADD_REPLICA (n2,s2):3): read existing descriptor r12:/Table/1{5-6} [(n1,s1):1, (n3,s3):2, next=3]
I180523 05:47:23.223134 51334 storage/replica.go:3320  [n1,s1,r12/1:/Table/1{5-6}] proposing ADD_REPLICA((n2,s2):3): updated=[(n1,s1):1 (n3,s3):2 (n2,s2):3] next=4
I180523 05:47:23.224183 51288 storage/replica_raftstorage.go:520  [replicate,n1,s1,r10/1:/Table/1{3-4}] generated preemptive snapshot 4145cb87 at index 122
I180523 05:47:23.229301 51288 storage/store_snapshot.go:605  [replicate,n1,s1,r10/1:/Table/1{3-4}] streamed snapshot to (n2,s2):?: kv pairs: 344, log entries: 38, rate-limit: 8.0 MiB/sec, 5ms
I180523 05:47:23.230095 51259 storage/replica_raftstorage.go:730  [n2,s2,r10/?:{-}] applying preemptive snapshot at index 122 (id=4145cb87, encoded size=68953, 1 rocksdb batches, 38 log entries)
I180523 05:47:23.230798 51259 storage/replica_raftstorage.go:736  [n2,s2,r10/?:/Table/1{3-4}] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:23.232406 49511 testutils/testcluster/testcluster.go:536  [n1,s1] has 3 underreplicated ranges
I180523 05:47:23.233313 51288 storage/replica_command.go:1777  [replicate,n1,s1,r10/1:/Table/1{3-4}] change replicas (ADD_REPLICA (n2,s2):3): read existing descriptor r10:/Table/1{3-4} [(n1,s1):1, (n3,s3):2, next=3]
I180523 05:47:23.236944 51288 storage/replica.go:3320  [n1,s1,r10/1:/Table/1{3-4}] proposing ADD_REPLICA((n2,s2):3): updated=[(n1,s1):1 (n3,s3):2 (n2,s2):3] next=4
I180523 05:47:23.238053 51307 storage/replica_raftstorage.go:520  [replicate,n1,s1,r14/1:/Table/1{7-8}] generated preemptive snapshot 497fb6fe at index 18
I180523 05:47:23.239786 51307 storage/store_snapshot.go:605  [replicate,n1,s1,r14/1:/Table/1{7-8}] streamed snapshot to (n2,s2):?: kv pairs: 8, log entries: 8, rate-limit: 8.0 MiB/sec, 2ms
I180523 05:47:23.240286 51292 storage/replica_raftstorage.go:730  [n2,s2,r14/?:{-}] applying preemptive snapshot at index 18 (id=497fb6fe, encoded size=3078, 1 rocksdb batches, 8 log entries)
I180523 05:47:23.240518 51292 storage/replica_raftstorage.go:736  [n2,s2,r14/?:/Table/1{7-8}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:23.240978 51307 storage/replica_command.go:1777  [replicate,n1,s1,r14/1:/Table/1{7-8}] change replicas (ADD_REPLICA (n2,s2):3): read existing descriptor r14:/Table/1{7-8} [(n1,s1):1, (n3,s3):2, next=3]
I180523 05:47:23.275326 51307 storage/replica.go:3320  [n1,s1,r14/1:/Table/1{7-8}] proposing ADD_REPLICA((n2,s2):3): updated=[(n1,s1):1 (n3,s3):2 (n2,s2):3] next=4
I180523 05:47:23.279409 51352 storage/replica_raftstorage.go:520  [replicate,n1,s1,r17/1:/Table/2{0-1}] generated preemptive snapshot d31447b0 at index 19
I180523 05:47:23.284104 51352 storage/store_snapshot.go:605  [replicate,n1,s1,r17/1:/Table/2{0-1}] streamed snapshot to (n2,s2):?: kv pairs: 9, log entries: 9, rate-limit: 8.0 MiB/sec, 5ms
I180523 05:47:23.284627 51355 storage/replica_raftstorage.go:730  [n2,s2,r17/?:{-}] applying preemptive snapshot at index 19 (id=d31447b0, encoded size=3451, 1 rocksdb batches, 9 log entries)
I180523 05:47:23.284874 51355 storage/replica_raftstorage.go:736  [n2,s2,r17/?:/Table/2{0-1}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:23.285518 51352 storage/replica_command.go:1777  [replicate,n1,s1,r17/1:/Table/2{0-1}] change replicas (ADD_REPLICA (n2,s2):3): read existing descriptor r17:/Table/2{0-1} [(n1,s1):1, (n3,s3):2, next=3]
I180523 05:47:23.293302 51363 storage/store.go:2492  [replicaGC,n2,s2,r17/?:/Table/2{0-1}] removing replica
I180523 05:47:23.293486 51363 storage/replica.go:829  [replicaGC,n2,s2,r17/?:/Table/2{0-1}] removed 6 (0+6) keys in 0ms [clear=0ms commit=0ms]
I180523 05:47:23.319016 51352 storage/replica.go:3320  [n1,s1,r17/1:/Table/2{0-1}] proposing ADD_REPLICA((n2,s2):3): updated=[(n1,s1):1 (n3,s3):2 (n2,s2):3] next=4
I180523 05:47:23.322133 50528 storage/replica_proposal.go:202  [n3,s3,r14/2:/Table/1{7-8}] new range lease repl=(n3,s3):2 seq=3 start=1527054443.319975137,0 epo=1 pro=1527054443.319978130,0 following repl=(n1,s1):1 seq=2 start=1527054441.759312318,0 exp=1527054450.759930795,0 pro=1527054441.759949472,0
I180523 05:47:23.323105 51247 storage/replica_raftstorage.go:520  [raftsnapshot,n1,s1,r17/1:/Table/2{0-1}] generated Raft snapshot 71952cb4 at index 21
I180523 05:47:23.324290 51247 storage/store_snapshot.go:605  [raftsnapshot,n1,s1,r17/1:/Table/2{0-1}] streamed snapshot to (n2,s2):3: kv pairs: 11, log entries: 11, rate-limit: 8.0 MiB/sec, 1ms
I180523 05:47:23.324515 51367 storage/replica_raftstorage.go:730  [n2,s2,r17/3:{-}] applying Raft snapshot at index 21 (id=71952cb4, encoded size=4850, 1 rocksdb batches, 11 log entries)
I180523 05:47:23.324790 51367 storage/replica_raftstorage.go:736  [n2,s2,r17/3:/Table/2{0-1}] applied Raft snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180523 05:47:23.360299 51382 storage/raft_transport.go:459  [n3] raft transport stream to node 2 established
I180523 05:47:23.360773 51359 storage/raft_transport.go:459  [n2] raft transport stream to node 3 established
I180523 05:47:23.462882 51435 util/mon/bytes_usage.go:576  [intExec=create-auth-session] txn: bytes usage increases to 1.3 MiB (+1290240)
I180523 05:47:23.513492 51448 sql/event_log.go:124  [n1,client=127.0.0.1:47854,user=root] Event: "create_database", target: 52, info: {DatabaseName:"test test" Statement:CREATE DATABASE "test test" User:root}
I180523 05:47:23.514127 51438 storage/replica_command.go:863  [split,n1,s1,r22/1:/{Table/51-Max}] initiating a split of this range at key /Table/52 [r23]
I180523 05:47:23.532819 51448 sql/event_log.go:124  [n1,client=127.0.0.1:47854,user=root] Event: "create_table", target: 53, info: {TableName:"test test".public."foo foo" Statement:CREATE TABLE "test test".public."foo foo" (id INT PRIMARY KEY, val STRING) User:root}
I180523 05:47:23.537565 51388 storage/replica_command.go:863  [split,n1,s1,r23/1:/{Table/52-Max}] initiating a split of this range at key /Table/53 [r24]
I180523 05:47:23.574841 51390 storage/replica_raftstorage.go:520  [raftsnapshot,n1,s1,r24/1:/{Table/53-Max}] generated Raft snapshot 7983ed44 at index 15
E180523 05:47:23.575534 51390 storage/queue.go:778  [raftsnapshot,n1,s1,r24/1:/{Table/53-Max}] snapshot failed: (n3,s3):2: remote couldn't accept snapshot with error: [n3,s3],r24: cannot apply snapshot: snapshot intersects existing range [n3,s3,r23/2:/{Table/52-Max}]
W180523 05:47:23.603313 50653 storage/raft_transport.go:465  [n3] raft transport stream to node 1 failed: rpc error: code = FailedPrecondition desc = grpc: the client connection is closing
W180523 05:47:23.603473 50740 storage/raft_transport.go:465  [n2] raft transport stream to node 1 failed: rpc error: code = FailedPrecondition desc = grpc: the client connection is closing
W180523 05:47:23.603514 51382 storage/raft_transport.go:465  [n3] raft transport stream to node 2 failed: rpc error: code = Unavailable desc = transport is closing
W180523 05:47:23.603609 51359 storage/raft_transport.go:465  [n2] raft transport stream to node 3 failed: rpc error: code = FailedPrecondition desc = grpc: the client connection is closing
	admin_cluster_test.go:110: expected at least 20 total keys, found 19
```

### PR DESCRIPTION
**Pull request by tbg**
The test writes 10 keys and wants to check that they are fully
replicated, i.e. that there are at least 20 keys across the replicas.
But if the first couple of keys are written before the range has
upreplicated in the first place, numbers smaller than 20 are possible.
Instead, retry the condition until the writes are fully replicated, i.e.
30 keys are visible.

Fixes #25831.

Release note: None

### CODE REVIEW

File: pkg/server/admin_cluster_test.go [hunk 1]
```diff
@@ -88,7 +88,7 @@ func TestAdminAPITableStats(t *testing.T) {
 	// this to occur, and for full replication.
 	testutils.SucceedsSoon(t, func() error {
 		if err := httputil.GetJSON(client, url, &tsResponse); err != nil {
-			return err
+			t.Fatal(err)
```
Comment (a-robinson) [inline pkg/server/admin_cluster_test.go]: Why? On the off chance that we do somehow get an error here, wouldn't we legitimately rather retry than deal with a test flake?

**Review by a-robinson — APPROVED** [review]
LGTM

File: pkg/server/admin_cluster_test.go (hunk 1 above)
Comment (tschottdorf) [reply pkg/server/admin_cluster_test.go]: I'll take my chances. There shouldn't be a way to get a legit error here, should there? It's a common anti pattern to put "too much" into the SucceedsSoon, and I like to clean it up when I drive by. Might regret it. 😄

**Comment by tschottdorf** [comment]
TFTR! TC flake is https://github.com/cockroachdb/cockroach/pull/27740, so going to ignore that.

bors r=a-robinson
