### PR TITLE
server: fix negative iops in progress

### LINKED ISSUE #27906: ui: negative disk iops in progress
Saw this when running the `clearrange` roachtest (`roachtest run clearrange`) at SHA 8779a311c500601cbec8b85acffd1dd0e03dc6eb:

screen shot 2018-07-24 at 8 56 26 pm

### PR DESCRIPTION
**Pull request by vilterp**
We record most metrics as differences from their values at the beginning
of the cockroach process, so that IO before the process started and
between runs doesn't create large spikes when we take the metric's
derivative for charts. Iops was also being recorded as a difference
which was wrong because we always want to just record its current value.

Additionally, some of the unit tests weren't actually testing anything.

Fixes #27906

Release note: None

### CODE REVIEW

File: pkg/server/status/runtime.go [hunk 1]
```diff
@@ -551,8 +551,6 @@ func subtractDiskCounters(from *diskStats, sub diskStats) {
 	from.readCount -= sub.readCount
 	from.readTimeMs -= sub.readTimeMs
 	from.readBytes -= sub.readBytes
-
-	from.iopsInProgress -= sub.iopsInProgress
```
Comment (couchand) [inline pkg/server/status/runtime.go]: I'd be inclined to rename the method now, but I can't think of a great name immediately.

**Review by couchand — APPROVED** [review]
LGTM

File: pkg/server/status/runtime.go (hunk 1 above)
Comment (vilterp) [reply pkg/server/status/runtime.go]: yeah idk. NormalizeWithRespectToStartingValues or something

Comment (couchand) [reply pkg/server/status/runtime.go]: tare :balance_scale:
