### PR TITLE
storage: Send preemptive snapshots synchronously

### LINKED ISSUE #7819: storage: preemptive snapshots
Preemptive snapshots were disabled due to raft corruption issues. With #7619 fixed we should revisit. 

The lack of preemptive snapshots makes the replica reservation system a lot less useful. We can see this in `TestMultinodeCockroach` which usually finishes within a few seconds, but sometimes takes 30-40s. The slow runs are caused by a declined reservation due to there being to many outstanding reservations. The default max outstanding reservations is `5` and `TestMultinodeCockroach` creates `6` ranges. The lack of preemptive snapshots causes `replicateQueue.process` to asynchronously perform the replication. Specifically, the call to `Replica.ChangeReplicas` returns before the reservation is fulfilled. The intention is that `Replica.ChangeReplicas` blocks until the preemptive snapshot has been processed remotely. Without that feedback, we quickly iterate over the replicas creating reservations until we hit `defaultMaxReservations` at which point processing fails and we have to wait until the next replica scanner iteration to replicate the range.

When reenabling preemptive snapshots, the sending of the snapshot in `Replica.ChangeReplicas` should be made synchronous. Currently we send the preemptive snapshot via the normal raft transport mechanism. But this only means the snapshot is queued up at the raft transport. The code then proceeds to issue the `ChangeReplicas` operation through Raft. Depending on timing, Raft might then request another snapshot. Regardless of this waste, the feedback loop for replication is being violated by sending the preemptive snapshot asynchronously.

See also #6144

### PR DESCRIPTION
**Pull request by bdarnell**
Introduce a synchronous mode for RaftTransport.

Abort the ChangeReplicas operation if the snapshot cannot be sent. This
required relaxing some of the sanity checks introduced in #7833 in order
to get all the tests passing reliably. Notably, a replica with an active
raft group can now accept preemptive snapshots.

Fixes #7819
Closes #8604

May address #8007, #8056, and #8594

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8613)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[storage/raft_transport.go, line 134 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8613#-KPP7m0vq2nN0XfGWy-5:-KPP7m0vq2nN0XfGWy-6:b-folw2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/2090a12fa7952461c8ef4c15c836caad8db4dc39/storage/raft_transport.go#L134)):*
> ```Go
> 
> // handleRaftRequest proxies a request to the listening server interface.
> func (t *RaftTransport) handleRaftRequest(ctx context.Context, req *RaftMessageRequest,
> ```

can you wrap this in accordance with the style guide?
```
handlRaftRequest(
...
) *roachpb.Error {
```

---

*[storage/raft_transport.go, line 428 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8613#-KPP8SWjkkedWn2eeoPf:-KPP8SWjkkedWn2eeoPg:b-g1gfhw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2090a12fa7952461c8ef4c15c836caad8db4dc39/storage/raft_transport.go#L428)):*
> ```Go
> 		return val.GoError()
> 	default:
> 		log.Infof(ctx, "unexpected response value %T %s", val, val)
> ```

wouldn't it be better to return an error?

---

*[storage/replica.go, line 496 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8613#-KPP8bNKoZADTT9tPsBH:-KPP8bNKoZADTT9tPsBI:bp6ezl5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2090a12fa7952461c8ef4c15c836caad8db4dc39/storage/replica.go#L496)):*
> ```Go
> func (r *Replica) setReplicaIDLocked(replicaID roachpb.ReplicaID) error {
> 	if replicaID == 0 {
> 		// If the incoming message didn't give us a new replica ID,
> ```

this seems like a hack to neutralize bad behaviour from preemptive snapshots. if that's the case, could this code move to the caller?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8613)*

**Comment by tamird** [comment]
:lgtm:

Is testing this prohibitively difficult?

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8613#-:-KPP91PNGTfixZWnfC0S:bokuvmw)*

**Comment by petermattis** [comment]
:lgtm:

`TestStoreRangeRebalance` tests preemptive snapshots but currently has a section disabled because they weren't synchronous. See the `if false`. Can that code now be enabled?

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[storage/raft_transport.go, line 420 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8613#-KPP8xT5hGKb6WjIglQ6:-KPP8xT6hPbnPnQqBI9j:bj1mlml) ([raw file](https://github.com/cockroachdb/cockroach/blob/2090a12fa7952461c8ef4c15c836caad8db4dc39/storage/raft_transport.go#L420)):*
> ```Go
> 	}
> 	client := NewMultiRaftClient(conn)
> 	resp, err := client.RaftMessageSync(ctx, req)
> ```

You could have opened a stream here and sent a single request on it, right? Wondering if that would be better than introducing a new RPC. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8613#-:-KPP9IcHtX_i-klVh-rI:bdnhh0)*

**Comment by bdarnell** [comment]
Yes, looks like the disabled code in TestStoreRangeRebalance can be reenabled. 

Added a test for the most important consequence of this change, which is that ChangeReplicas no longer ignores preemptive snapshot failures. 

---

Review status: 5 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[storage/raft_transport.go, line 134 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8613#-KPP7m0vq2nN0XfGWy-5:-KPPGi60qCSZ8CL38Ct4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2090a12fa7952461c8ef4c15c836caad8db4dc39/storage/raft_transport.go#L134)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can you wrap this in accordance with the style guide?
> ```
> handlRaftRequest(
> ...
> ) *roachpb.Error {
> ```
</details>
Done.

---

*[storage/raft_transport.go, line 420 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8613#-KPP8xT5hGKb6WjIglQ6:-KPPGkCuv5I_WZrciFTR:b-x7jjh2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2090a12fa7952461c8ef4c15c836caad8db4dc39/storage/raft_transport.go#L420)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> You could have opened a stream here and sent a single request on it, right? Wondering if that would be better than introducing a new RPC. 
</details>
No, because there's no ack for a message that has been received on the other side. It would be a little better than before because we could block on stream.Send, but we'd still miss the applySnapshot time on the other side. We could introduce an ack but I think that would be more complicated than 

---

*[storage/raft_transport.go, line 428 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8613#-KPP8SWjkkedWn2eeoPf:-KPPHuIJnQ32Nk1bfEJo:b-mgpugu) ([raw file](https://github.com/cockroachdb/cockroach/blob/2090a12fa7952461c8ef4c15c836caad8db4dc39/storage/raft_transport.go#L428)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> wouldn't it be better to return an error?
</details>
Failing on things we don't understand makes upgrades difficult; I think it's more future-proof to be lenient. 

---

*[storage/replica.go, line 496 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8613#-KPP8bNKoZADTT9tPsBH:-KPPI_SYsb7x1EmJ_K92:b3t3hfn) ([raw file](https://github.com/cockroachdb/cockroach/blob/2090a12fa7952461c8ef4c15c836caad8db4dc39/storage/replica.go#L496)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this seems like a hack to neutralize bad behaviour from preemptive snapshots. if that's the case, could this code move to the caller?
</details>
Not easily; the caller is several steps removed from the code that knows whether we're dealing with a preemptive snapshot.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8613#-:-KPPJhpx_NGIgQNRgKWX:b-8aw76w)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/raft_transport.go, line 428 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8613#-KPP8SWjkkedWn2eeoPf:-KPPQ3RIPHl5a-_XdtAw:b-nebkb0) ([raw file](https://github.com/cockroachdb/cockroach/blob/2090a12fa7952461c8ef4c15c836caad8db4dc39/storage/raft_transport.go#L428)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Failing on things we don't understand makes upgrades difficult; I think it's more future-proof to be lenient. 
</details>
In this particular case, something we don't understand would correspond to new generated code in the protos which we forgot to propagate to this site. In this case, it may be better to be strict.

---

*[storage/replica.go, line 496 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8613#-KPP8bNKoZADTT9tPsBH:-KPPQOPklh5ryGo1ELbH:bizb483) ([raw file](https://github.com/cockroachdb/cockroach/blob/2090a12fa7952461c8ef4c15c836caad8db4dc39/storage/replica.go#L496)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Not easily; the caller is several steps removed from the code that knows whether we're dealing with a preemptive snapshot.
</details>
I see. Could you update comment so that it doesn't read as if this is expected behaviour under "normal" circumstances?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8613)*

File: storage/raft_transport.go [hunk 1]
```diff
@@ -386,3 +410,23 @@ func (t *RaftTransport) SendAsync(req *RaftMessageRequest) bool {
 		return false
 	}
 }
+
+// SendSync sends a raft message and waits for an acknowledgement.
+func (t *RaftTransport) SendSync(ctx context.Context, req *RaftMessageRequest) error {
```
Comment (spencerkimball) [inline storage/raft_transport.go]: I'll have to refactor a bit in order to merge this with my pending transport change. Is there any reason we shouldn't use the same breaker we use for the async send?

File: storage/replica.go [hunk 2]
```diff
@@ -492,6 +492,11 @@ func (r *Replica) setReplicaID(replicaID roachpb.ReplicaID) error {
 
 // setReplicaIDLocked requires that the replica lock is held.
 func (r *Replica) setReplicaIDLocked(replicaID roachpb.ReplicaID) error {
+	if replicaID == 0 {
```
Comment (spencerkimball) [inline storage/replica.go]: This changes behavior. Take the following example:
- replicate to three nodes
- take a node down
- down replicate that same node; downed node won't get the memo
- bring down node back up
- up-replicate again to formerly down node
- pre-emptive snapshot will be sent with `replicaID=0`; previously, this would yield an error here "cannot move backwards from X to 0". Since now we don't return an error, it means we'll be applying the snapshot.

Not necessarily a bad thing, though it's different behavior and I'm not familiar enough with the code to know whether overwriting will potentially cause issues.

**Comment by spencerkimball** [comment]
LGTM

**Comment by bdarnell** [comment]
Review status: 5 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[storage/raft_transport.go, line 428 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8613#-KPP8SWjkkedWn2eeoPf:-KPQIjBTV4CGGTrFlCgG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2090a12fa7952461c8ef4c15c836caad8db4dc39/storage/raft_transport.go#L428)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> In this particular case, something we don't understand would correspond to new generated code in the protos which we forgot to propagate to this site. In this case, it may be better to be strict.
</details>
Done.

---

*[storage/raft_transport.go, line 415 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8613#-KPP6xnHXrb5C8qX8TEy-r3-415:-KPQISZ_EdeN-x7KAsah:b-fm37su) ([raw file](https://github.com/cockroachdb/cockroach/blob/b70e11ca497227aec042562ddd056e3e658dcb82/storage/raft_transport.go#L415)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary>
> I'll have to refactor a bit in order to merge this with my pending transport change. Is there any reason we shouldn't use the same breaker we use for the async send?
</details>
Yeah, same breaker should be fine.

---

*[storage/replica.go, line 496 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8613#-KPP8bNKoZADTT9tPsBH:-KPQIiSGdbOqABsXyXq1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2090a12fa7952461c8ef4c15c836caad8db4dc39/storage/replica.go#L496)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I see. Could you update comment so that it doesn't read as if this is expected behaviour under "normal" circumstances?
</details>
Done.

---

*[storage/replica.go, line 495 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8613#-KPP6xnHXrb5C8qX8TEz-r3-495:-KPQIUb1SfQuZt0DW3Ra:bv2t08e) ([raw file](https://github.com/cockroachdb/cockroach/blob/b70e11ca497227aec042562ddd056e3e658dcb82/storage/replica.go#L495)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary>
> This changes behavior. Take the following example:
> 
> - replicate to three nodes
> 
> - take a node down
> 
> - down replicate that same node; downed node won't get the memo
> 
> - bring down node back up
> 
> - up-replicate again to formerly down node
> 
> - pre-emptive snapshot will be sent with `replicaID=0`; previously, this would yield an error here "cannot move backwards from X to 0". Since now we don't return an error, it means we'll be applying the snapshot.
> 
> 
> 
> Not necessarily a bad thing, though it's different behavior and I'm not familiar enough with the code to know whether overwriting will potentially cause issues.
</details>
Yeah. This should be OK: raft has internal checks to prevent regression in the applied index; the replica id check is mainly there to prevent backtracking past a tombstone when there is nothing else to go by.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8613)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3.
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8613)*
