### PR TITLE
duration: fix negative duration math

### LINKED ISSUE #52135: sql: Interval does not return correct year
When running the interval function, the wrong year is return.  See example below where a 1 year interval returns 2 years.

root@:26257/defaultdb> select current_date, current_date() - INTERVAL ‘1-0 0 0:0:0’ YEAR as “1YrAgo”, current_date() - INTERVAL ‘1’ YEAR as “1YrAgo2";
        current_date        |          1YrAgo           |          1YrAgo2
----------------------------+---------------------------+----------------------------
  2020-07-30 00:00:00+00:00 | 2018-07-30 00:00:00+00:00 | 2018-07-30 00:00:00+00:00

This also occurs as well:

root@127.0.0.1:65028/defaultdb> select now() - '.6 years'::interval;
              ?column?
------------------------------------
  2018-12-24 13:36:26.664877+00:00

### PR DESCRIPTION
**Pull request by otan**
In Go, negative numbers mod positive numbers returns negative numbers
(e.g. -5 % 12 is -7), which is the root of the bug.

Resolves #52135.

Release note (bug fix): Previously, subtracting months from a
timestamp/date/duration whose date value is greater than 28
could subtract a further year off. This has now be rectified.

### CODE REVIEW

**Comment by otan** [comment]
i don't know if it's backport worthy, but i can see some serious bugs with this.

File: pkg/util/duration/duration.go [hunk 1]
```diff
@@ -426,6 +426,11 @@ func Add(t time.Time, d Duration) time.Time {
 
 	// Adjustments for 1-based math.
 	expectedMonth := time.Month((int(t.Month())-1+int(d.Months))%12 + 1)
+	// If we have a negative duration, we have a negative modulus.
+	// Round back up to the positive expectedMonth.
```
Comment (RichardJCai) [inline pkg/util/duration/duration.go:430]: Is Round the correct term here?

**Review by RichardJCai — APPROVED** [review]
LGTM besides one comment nit

**Comment by otan** [comment]
tftr!

bors r=RichardJCai

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52138)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rohany)

___
*[pkg/util/duration/duration.go, line 429 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52138#-MDWU0Al6-zDcrk6CgDv:-MDWU0Al6-zDcrk6CgDw:b-1vzgmu) ([raw file](https://github.com/cockroachdb/cockroach/blob/229da3e8f6371afb5343fa716fc2ab6764da5b3d/pkg/util/duration/duration.go#L429)):*
> ```Go
> 	// Adjustments for 1-based math.
> 	expectedMonth := time.Month((int(t.Month())-1+int(d.Months))%MonthsPerYear) + 1
> 	// If we have a negative duration, we have a negative modulus.
> ```

Heh it's because the golang spec will tell you that `%` is remainder and not modulus

`%    remainder              integers`

https://golang.org/ref/spec#Arithmetic_operators

**Comment by awoods187** [comment]
Can we backport this?

**Comment by otan** [comment]
the backport PRs are ready!

**Comment by otan** [comment]
ORMS flake!

bors r=RichardJCai
