### PR TITLE
changefeedccl: fix race advancing frontier in schemafeed

### LINKED ISSUE #148963: ccl/changefeedccl: TestChangefeedSchemaTTL failed
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

```
Error Trace:	pkg/ccl/changefeedccl/changefeed_test.go:6534
            	            				pkg/ccl/changefeedccl/helpers_test.go:1524
            	Error:      	Expect "ERROR: internal error: cannot advance frontier to 1750959678.165615000,0, which is earlier than the current frontier 1750959678.165804000,0 (SQLSTATE XX000)" to match "GC threshold"
```

**To Reproduce**

checkout 65468cffb3993e61b3bcda2fb966b1126e4a9bd0

Force the test feed sink to be enterprise for 
`TestChangefeedSchemaTTL`

What did you do? Describe in your own words.

```
./dev test pkg/ccl/changefeedccl --filter TestChangefeedSchemaTTL --stress --deadlock
```

Jira issue: CRDB-51896

### PR DESCRIPTION
**Pull request by rharding6373**
In the schema feed, when in `updateTableHistory`, we check that the current frontier is less than the current time. However, since we release the mutex protecting frontier while validating table descriptors, it's possible for another routine to advance the frontier before the first routine tries to advance it. For example, another routine may call pauseOrResumePolling and pause polling at the same time it advances the frontier.As a consequence, it's possible for the first routine to assert fail due to the current frontier being greater than the current time when it tries to advance it.

This change fixes this race by checking that the frontier is greater than the current time (endTS) again before trying to advance the frontier. If the frontier is less than or equal to the current time, the frontier does not need to be advanced and it returns. It's worth keeping the original check in, since it avoids the need to validate descriptors, and releasing the mutex also prevents the routine from holding it while validating.

Epic: none
Fixes: #148963

Release note (bug fix): Fixes a race condition when advancing a changefeed aggregator's frontier. When hit, the race condition could result in an internal error that would shut down the kvfeed and cause the changefeed to retry.

### CODE REVIEW

**Comment by rharding6373** [comment]
I added a flag to protect this change, although the change itself seems minor, since we currently intend to backport this change. With @asg0451's patch to the test, I repo'd the original issue in 8 runs without this change, and haven't seen the error in 1200 runs with the change.

File: pkg/ccl/changefeedccl/changefeedbase/settings.go [hunk 1]
```diff
@@ -369,3 +369,13 @@ var RetryBackoffReset = settings.RegisterDurationSettingWithExplicitUnit(
 	10*time.Minute, /* defaultValue */
 	settings.DurationInRange(1*time.Second, 1*time.Hour),
 )
+
+// FrontierAdvanceCheckEnabled controls whether the changefeed will
+// attempt to advance the frontier depending on the relation between the
+// last recorded frontier and the current time.
+var FrontierAdvanceCheckEnabled = settings.RegisterBoolSetting(
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeedbase/settings.go]: nit: this cluster setting should probably be a private var that lives in `pkg/ccl/changefeedccl/schemafeed/schema_feed.go` given it's only used there

File: pkg/ccl/changefeedccl/schemafeed/schema_feed.go [hunk 2]
```diff
@@ -644,10 +644,15 @@ func (tf *schemaFeed) adjustTimestamps(startTS, endTS hlc.Timestamp, validateErr
...
 		return validateErr
 	}
-
-	if frontier := tf.mu.ts.frontier; frontier.Less(startTS) {
+	frontier := tf.mu.ts.frontier
+	if frontier.Less(startTS) {
 		return errors.Errorf(`gap between %s and %s`, frontier, startTS)
 	}
+	// If the current frontier is greater than the endTS,
+	// then we do not need to advance the frontier.
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/schemafeed/schema_feed.go]: Could you expand this comment (and the commit message) to explain why this could happen? From a quick glance it seems to be from the `pauseOrResumePolling` logic when the table is `schema_locked`. Does that match up with your understanding?

**Comment by KeithCh** [comment]
Just as a sanity check I ran the test 2000 times with the changes here and it passed. 

Looks good to me!

**Review by KeithCh — APPROVED** [review]

File: pkg/ccl/changefeedccl/changefeedbase/settings.go (hunk 1 above)
Comment (rharding6373) [reply pkg/ccl/changefeedccl/changefeedbase/settings.go]: Moved, though I'm planning to delete this setting after backporting to 25.3.

File: pkg/ccl/changefeedccl/schemafeed/schema_feed.go (hunk 2 above)
Comment (rharding6373) [reply pkg/ccl/changefeedccl/schemafeed/schema_feed.go]: I purposefully left out how not having this could lead to errors from the comment, in order to keep the function isolated from caller's and callee's behavior. I added a note that not checking could lead to errors in `advanceFrontier`. I added more on the hypothesis about what specific functions are racing in the commit message instead.

**Review by andyyang890 — APPROVED** [review]

**Comment by rharding6373** [comment]
TFTRs!

bors r+
