### PR TITLE
tracing: avoid data races w.r.t noopSpan

### LINKED ISSUE #50032: sql: TestScatterRandomizeLeases failed
[(sql).TestScatterRandomizeLeases failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2001308&tab=buildLog) on [master@1d4e9d9d93eb2b1953ca4df5d8168ca4d58c52b2](https://github.com/cockroachdb/cockroach/commits/1d4e9d9d93eb2b1953ca4df5d8168ca4d58c52b2):

```
  github.com/cockroachdb/cockroach/pkg/server.(*TestServer).Start()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/testserver.go:425 +0x30a
  github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartServerRaw()
      /go/src/github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_server_shim.go:255 +0x15f
  github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartServer()
      /go/src/github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_server_shim.go:223 +0x65
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).doAddServer()
      /go/src/github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:349 +0x196
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.StartTestCluster()
      /go/src/github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:223 +0xc90
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*testClusterFactoryImpl).StartTestCluster()
      /go/src/github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:898 +0xe9
  github.com/cockroachdb/cockroach/pkg/sql_test.TestScatterRandomizeLeases()
      /go/src/github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_cluster_shim.go:141 +0x1d9
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199

Goroutine 175 (running) created at:
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:191 +0xc3
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/scheduler.go:165 +0x149
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processRaft()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/store_raft.go:573 +0xcb
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).Start()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/store.go:1505 +0xc73
  github.com/cockroachdb/cockroach/pkg/server.(*Node).bootstrapStores()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:564 +0x5f7
  github.com/cockroachdb/cockroach/pkg/server.(*Node).start()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:452 +0x1713
  github.com/cockroachdb/cockroach/pkg/server.(*Server).Start()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1365 +0x2fc1
  github.com/cockroachdb/cockroach/pkg/server.(*TestServer).Start()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/testserver.go:425 +0x30a
  github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartServerRaw()
      /go/src/github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_server_shim.go:255 +0x15f
  github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartServer()
      /go/src/github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_server_shim.go:223 +0x65
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).doAddServer()
      /go/src/github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:349 +0x196
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.StartTestCluster()
      /go/src/github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:223 +0xc90
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*testClusterFactoryImpl).StartTestCluster()
      /go/src/github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:898 +0xe9
  github.com/cockroachdb/cockroach/pkg/sql_test.TestScatterRandomizeLeases()
      /go/src/github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_cluster_shim.go:141 +0x1d9
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199
==================
FAIL	github.com/cockroachdb/cockroach/pkg/sql	1109.863s

```

<details><summary>More</summary><p>
Parameters:

- GOFLAGS=-json

```
make stressrace TESTS=TestScatterRandomizeLeases PKG=./pkg/sql TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestScatterRandomizeLeases.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #55911: ccl/backupccl: TestBackupRestoreDataDriven failed
[(ccl/backupccl).TestBackupRestoreDataDriven failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2389870&tab=buildLog) on [master@33e3abc57cccedd86dd1b2e1d58feb075fcb8dd4](https://github.com/cockroachdb/cockroach/commits/33e3abc57cccedd86dd1b2e1d58feb075fcb8dd4):

```
  github.com/cockroachdb/cockroach/pkg/ccl/backupccl.(*restoreDataProcessor).Run()
      <autogenerated>:1 +0x57
  github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:392 +0x432
  github.com/cockroachdb/cockroach/pkg/sql/rowflow.(*rowBasedFlow).Run()
      <autogenerated>:1 +0x7f
  github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:422 +0x94e
  github.com/cockroachdb/cockroach/pkg/ccl/backupccl.distRestore()
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_processor_planning.go:228 +0x19a0
  github.com/cockroachdb/cockroach/pkg/ccl/backupccl.restore()
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_job.go:621 +0xede
  github.com/cockroachdb/cockroach/pkg/ccl/backupccl.(*restoreResumer).Resume()
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_job.go:1187 +0xbcb
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1089 +0x144
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine()
      /go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1090 +0xa8e
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob()
      /go/src/github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:245 +0x46a
  github.com/cockroachdb/cockroach/pkg/jobs.(*StartableJob).Start.func2()
      /go/src/github.com/cockroachdb/cockroach/pkg/jobs/jobs.go:853 +0x2c9
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:347 +0x162

Goroutine 935 (running) created at:
  golang.org/x/sync/errgroup.(*Group).Go()
      /go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x73
  github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:165 +0xda
  github.com/cockroachdb/cockroach/pkg/ccl/backupccl.runSplitAndScatter()
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/backupccl/split_and_scatter_processor.go:252 +0x2ef
  github.com/cockroachdb/cockroach/pkg/ccl/backupccl.(*splitAndScatterProcessor).Run.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/backupccl/split_and_scatter_processor.go:182 +0x107

Goroutine 729 (running) created at:
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:342 +0x14a
  github.com/cockroachdb/cockroach/pkg/jobs.(*StartableJob).Start()
      /go/src/github.com/cockroachdb/cockroach/pkg/jobs/jobs.go:852 +0x49e
  github.com/cockroachdb/cockroach/pkg/jobs.(*StartableJob).Run()
      /go/src/github.com/cockroachdb/cockroach/pkg/jobs/jobs.go:871 +0x16d
  github.com/cockroachdb/cockroach/pkg/ccl/backupccl.doRestorePlan()
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_planning.go:1627 +0x27dd
  github.com/cockroachdb/cockroach/pkg/ccl/backupccl.restorePlanHook.func2()
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_planning.go:1297 +0x8bc
  github.com/cockroachdb/cockroach/pkg/sql.(*hookFnNode).startExec.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/planhook.go:146 +0x10d
==================
FAIL	github.com/cockroachdb/cockroach/pkg/ccl/backupccl	48.900s

```

<details><summary>More</summary><p>
Parameters:

- GOFLAGS=-json

```
make stressrace TESTS=TestBackupRestoreDataDriven PKG=./pkg/ccl/backupccl TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestBackupRestoreDataDriven.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #55912: ccl/importccl: TestImportIntoCSV failed
[(ccl/importccl).TestImportIntoCSV failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2389870&tab=buildLog) on [master@33e3abc57cccedd86dd1b2e1d58feb075fcb8dd4](https://github.com/cockroachdb/cockroach/commits/33e3abc57cccedd86dd1b2e1d58feb075fcb8dd4):

```

Goroutine 33 (running) created at:
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunLimitedAsyncTask()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:400 +0x2a7
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).sendPartialBatchAsync()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1362 +0x371
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).divideAndSendBatchToRanges()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1276 +0x12dd
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).Send()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:772 +0xab3
  github.com/cockroachdb/cockroach/pkg/kv.(*CrossRangeTxnWrapperSender).Send()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:219 +0xfc
  github.com/cockroachdb/cockroach/pkg/kv.(*DB).sendUsingSender()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:744 +0x1ad
  github.com/cockroachdb/cockroach/pkg/kv.(*DB).send-fm()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:726 +0xf6
  github.com/cockroachdb/cockroach/pkg/kv.sendAndFill()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:654 +0x182
  github.com/cockroachdb/cockroach/pkg/kv.(*DB).Run()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:677 +0xd1
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/protectedts/ptverifier.(*verifier).Verify()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/protectedts/ptverifier/verifier.go:51 +0x1c2
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/protectedts/ptprovider.(*provider).Verify()
      <autogenerated>:1 +0x99
  github.com/cockroachdb/cockroach/pkg/ccl/importccl.(*importResumer).Resume()
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/import_stmt.go:1203 +0x2320
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1089 +0x144
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine()
      /go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1090 +0xa8e
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob()
      /go/src/github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:245 +0x46a
  github.com/cockroachdb/cockroach/pkg/jobs.(*StartableJob).Start.func2()
      /go/src/github.com/cockroachdb/cockroach/pkg/jobs/jobs.go:853 +0x2c9
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:347 +0x162

Goroutine 790 (running) created at:
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:342 +0x14a
  github.com/cockroachdb/cockroach/pkg/jobs.(*StartableJob).Start()
      /go/src/github.com/cockroachdb/cockroach/pkg/jobs/jobs.go:852 +0x49e
  github.com/cockroachdb/cockroach/pkg/jobs.(*StartableJob).Run()
      /go/src/github.com/cockroachdb/cockroach/pkg/jobs/jobs.go:871 +0x16d
  github.com/cockroachdb/cockroach/pkg/ccl/importccl.importPlanHook.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/import_stmt.go:879 +0x1be5
  github.com/cockroachdb/cockroach/pkg/sql.(*hookFnNode).startExec.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/planhook.go:146 +0x10d
==================
FAIL	github.com/cockroachdb/cockroach/pkg/ccl/importccl	330.583s

```

<details><summary>More</summary><p>
Parameters:

- GOFLAGS=-json

```
make stressrace TESTS=TestImportIntoCSV PKG=./pkg/ccl/importccl TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestImportIntoCSV.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #55913: kv/kvserver: TestRandomConcurrentAdminChangeReplicasRequests failed
[(kv/kvserver).TestRandomConcurrentAdminChangeReplicasRequests failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2389870&tab=buildLog) on [master@33e3abc57cccedd86dd1b2e1d58feb075fcb8dd4](https://github.com/cockroachdb/cockroach/commits/33e3abc57cccedd86dd1b2e1d58feb075fcb8dd4):

```
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*grpcTransport).sendBatch()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/transport.go:157 +0x1e5
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*grpcTransport).SendNext()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/transport.go:139 +0x273
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.raceTransport.SendNext()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/transport_race.go:78 +0x423
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*raceTransport).SendNext()
      <autogenerated>:1 +0x108
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).sendToReplicas()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1874 +0xa5a
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).sendPartialBatch()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1495 +0x3cd
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).divideAndSendBatchToRanges()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1133 +0x1eca
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).Send()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:772 +0xab3
  github.com/cockroachdb/cockroach/pkg/kv.(*CrossRangeTxnWrapperSender).Send()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:219 +0xfc
  github.com/cockroachdb/cockroach/pkg/kv.(*DB).sendUsingSender()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:744 +0x1ad
  github.com/cockroachdb/cockroach/pkg/kv.(*DB).send-fm()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:726 +0xf6
  github.com/cockroachdb/cockroach/pkg/kv.sendAndFill()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:654 +0x182
  github.com/cockroachdb/cockroach/pkg/kv.(*DB).Run()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:677 +0xd1
  github.com/cockroachdb/cockroach/pkg/kv.(*DB).AdminChangeReplicas()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:592 +0x166
  github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestRandomConcurrentAdminChangeReplicasRequests.func2()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/client_replica_test.go:2230 +0x1e6
  github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestRandomConcurrentAdminChangeReplicasRequests.func3()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/client_replica_test.go:2237 +0x38

Goroutine 207 (running) created at:
  github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestRandomConcurrentAdminChangeReplicasRequests()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/client_replica_test.go:2237 +0x6e2
  github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestRandomConcurrentAdminChangeReplicasRequests()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/client_replica_test.go:2200 +0x190
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199

Goroutine 351 (running) created at:
  github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestRandomConcurrentAdminChangeReplicasRequests()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/client_replica_test.go:2237 +0x6e2
  github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestRandomConcurrentAdminChangeReplicasRequests()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/client_replica_test.go:2200 +0x190
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199
==================
FAIL	github.com/cockroachdb/cockroach/pkg/kv/kvserver	439.207s

```

<details><summary>More</summary><p>
Parameters:

- GOFLAGS=-json

```
make stressrace TESTS=TestRandomConcurrentAdminChangeReplicasRequests PKG=./pkg/kv/kvserver TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestRandomConcurrentAdminChangeReplicasRequests.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #55914: workload/workloadsql: TestSetup failed
[(workload/workloadsql).TestSetup failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2389870&tab=buildLog) on [master@33e3abc57cccedd86dd1b2e1d58feb075fcb8dd4](https://github.com/cockroachdb/cockroach/commits/33e3abc57cccedd86dd1b2e1d58feb075fcb8dd4):

```
  github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:996 +0x288
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1002 +0x5e3
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:873 +0xb73
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:639 +0x11a9
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:114 +0xe79
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1442 +0x48f
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1444 +0x1c20
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1367 +0x3ff
  github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:477 +0x131
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:627 +0x39a

Goroutine 536 (running) created at:
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:555 +0x1e9
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:281 +0x8d6
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveConn()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:155 +0x307
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:589 +0xa79
  github.com/cockroachdb/cockroach/pkg/server.(*sqlServer).startServeSQL.func1.1()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1989 +0x19c
  github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:147 +0x104

Goroutine 555 (running) created at:
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:555 +0x1e9
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:281 +0x8d6
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveConn()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:155 +0x307
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:589 +0xa79
  github.com/cockroachdb/cockroach/pkg/server.(*sqlServer).startServeSQL.func1.1()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1989 +0x19c
  github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:147 +0x104
==================
FAIL	github.com/cockroachdb/cockroach/pkg/workload/workloadsql	6.309s

```

<details><summary>More</summary><p>
Parameters:

- GOFLAGS=-json

```
make stressrace TESTS=TestSetup PKG=./pkg/workload/workloadsql TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestSetup.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #55917: cli: Example_demo failed
[(cli).Example_demo failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2390239&tab=buildLog) on [master@33e3abc57cccedd86dd1b2e1d58feb075fcb8dd4](https://github.com/cockroachdb/cockroach/commits/33e3abc57cccedd86dd1b2e1d58feb075fcb8dd4):

```
  github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:996 +0x288
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1002 +0x5e3
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:873 +0xb73
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:639 +0x11a9
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:114 +0xe79
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1442 +0x48f
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1444 +0x1c20
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1367 +0x3ff
  github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:477 +0x131
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:627 +0x39a

Goroutine 234 (running) created at:
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:555 +0x1e9
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:281 +0x8d6
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveConn()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:155 +0x307
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:589 +0xa79
  github.com/cockroachdb/cockroach/pkg/server.(*sqlServer).startServeSQL.func1.1()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1989 +0x19c
  github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:147 +0x104

Goroutine 813 (running) created at:
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:555 +0x1e9
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:281 +0x8d6
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveConn()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:155 +0x307
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:589 +0xa79
  github.com/cockroachdb/cockroach/pkg/server.(*sqlServer).startServeSQL.func1.1()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1989 +0x19c
  github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:147 +0x104
==================
FAIL	github.com/cockroachdb/cockroach/pkg/cli	1179.627s

```

<details><summary>More</summary><p>
Parameters:

- GOFLAGS=-json

```
make stressrace TESTS=Example_demo PKG=./pkg/cli TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2AExample_demo.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #55918: kv/kvserver: TestStoreRangeMergeAddReplicaRace failed
[(kv/kvserver).TestStoreRangeMergeAddReplicaRace failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2390316&tab=buildLog) on [master@33e3abc57cccedd86dd1b2e1d58feb075fcb8dd4](https://github.com/cockroachdb/cockroach/commits/33e3abc57cccedd86dd1b2e1d58feb075fcb8dd4):

```
  github.com/cockroachdb/cockroach/pkg/rpc.(*internalClientAdapter).Batch()
      /go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:502 +0x8e
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*grpcTransport).sendBatch()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/transport.go:157 +0x1e5
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*grpcTransport).SendNext()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/transport.go:139 +0x273
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.raceTransport.SendNext()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/transport_race.go:78 +0x423
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*raceTransport).SendNext()
      <autogenerated>:1 +0x108
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).sendToReplicas()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1874 +0xa5a
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).sendPartialBatch()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1495 +0x3cd
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).divideAndSendBatchToRanges()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1133 +0x1eca
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).Send()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:772 +0xab3
  github.com/cockroachdb/cockroach/pkg/kv.(*CrossRangeTxnWrapperSender).Send()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:219 +0xfc
  github.com/cockroachdb/cockroach/pkg/kv.(*DB).sendUsingSender()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:744 +0x1ad
  github.com/cockroachdb/cockroach/pkg/kv.(*DB).send-fm()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:726 +0xf6
  github.com/cockroachdb/cockroach/pkg/kv.sendAndFill()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:654 +0x182
  github.com/cockroachdb/cockroach/pkg/kv.(*DB).Run()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:677 +0xd1
  github.com/cockroachdb/cockroach/pkg/kv.(*DB).AdminMerge()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:512 +0xc7
  github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestStoreRangeMergeAddReplicaRace.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/client_merge_test.go:1937 +0xeb

Goroutine 1538 (running) created at:
  github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestStoreRangeMergeAddReplicaRace()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/client_merge_test.go:1939 +0x502
  github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestStoreRangeMergeAddReplicaRace()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/client_merge_test.go:1925 +0x1b0
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199

Goroutine 1934 (running) created at:
  github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestStoreRangeMergeAddReplicaRace()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/client_merge_test.go:1936 +0x44a
  github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestStoreRangeMergeAddReplicaRace()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/client_merge_test.go:1925 +0x1b0
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199
==================
FAIL	github.com/cockroachdb/cockroach/pkg/kv/kvserver	120.100s

```

<details><summary>More</summary><p>
Parameters:

- GOFLAGS=-json

```
make stressrace TESTS=TestStoreRangeMergeAddReplicaRace PKG=./pkg/kv/kvserver TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestStoreRangeMergeAddReplicaRace.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #55919: workload/workloadsql: TestSplits failed
[(workload/workloadsql).TestSplits failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2390323&tab=buildLog) on [master@33e3abc57cccedd86dd1b2e1d58feb075fcb8dd4](https://github.com/cockroachdb/cockroach/commits/33e3abc57cccedd86dd1b2e1d58feb075fcb8dd4):

```
  github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:996 +0x288
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1002 +0x5e3
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:873 +0xb73
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:639 +0x11a9
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:114 +0xe79
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1442 +0x48f
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1444 +0x1c20
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1367 +0x3ff
  github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:477 +0x131
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:627 +0x39a

Goroutine 407 (running) created at:
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:555 +0x1e9
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:281 +0x8d6
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveConn()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:155 +0x307
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:589 +0xa79
  github.com/cockroachdb/cockroach/pkg/server.(*sqlServer).startServeSQL.func1.1()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1989 +0x19c
  github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:147 +0x104

Goroutine 254 (running) created at:
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:555 +0x1e9
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:281 +0x8d6
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveConn()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:155 +0x307
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:589 +0xa79
  github.com/cockroachdb/cockroach/pkg/server.(*sqlServer).startServeSQL.func1.1()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1989 +0x19c
  github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:147 +0x104
==================
FAIL	github.com/cockroachdb/cockroach/pkg/workload/workloadsql	22.498s

```

<details><summary>More</summary><p>
Parameters:

- GOFLAGS=-json

```
make stressrace TESTS=TestSplits PKG=./pkg/workload/workloadsql TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestSplits.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #55936: kv/kvserver: TestSplitTriggerRaftSnapshotRace failed
[(kv/kvserver).TestSplitTriggerRaftSnapshotRace failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2391536&tab=buildLog) on [master@75234294d22cc9a6e12724b043f49e78f0ac92d2](https://github.com/cockroachdb/cockroach/commits/75234294d22cc9a6e12724b043f49e78f0ac92d2):

```
  github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestSplitTriggerRaftSnapshotRace.func2()
      /go/src/github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:490 +0x287
  github.com/cockroachdb/cockroach/pkg/util/ctxgroup.GroupWorkers.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:175 +0x5d
  github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:166 +0x4e
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x71

Goroutine 53 (running) created at:
  golang.org/x/sync/errgroup.(*Group).Go()
      /go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x73
  github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:165 +0xda
  github.com/cockroachdb/cockroach/pkg/util/ctxgroup.GroupWorkers()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:175 +0xaa
  github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestSplitTriggerRaftSnapshotRace()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/client_split_test.go:533 +0x440
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).StartServer()
      /go/src/github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:409 +0x6a
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).Start()
      /go/src/github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:245 +0x348
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.StartTestCluster()
      /go/src/github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:128 +0x100
  github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestSplitTriggerRaftSnapshotRace()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/client_split_test.go:493 +0x1ad
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199

Goroutine 1148 (running) created at:
  golang.org/x/sync/errgroup.(*Group).Go()
      /go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x73
  github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:165 +0xda
  github.com/cockroachdb/cockroach/pkg/util/ctxgroup.GroupWorkers()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:175 +0xaa
  github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestSplitTriggerRaftSnapshotRace()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/client_split_test.go:533 +0x440
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).StartServer()
      /go/src/github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:409 +0x6a
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).Start()
      /go/src/github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:245 +0x348
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.StartTestCluster()
      /go/src/github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:128 +0x100
  github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestSplitTriggerRaftSnapshotRace()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/client_split_test.go:493 +0x1ad
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199
==================
FAIL	github.com/cockroachdb/cockroach/pkg/kv/kvserver	527.033s

```

<details><summary>More</summary><p>
Parameters:

- GOFLAGS=-json

```
make stressrace TESTS=TestSplitTriggerRaftSnapshotRace PKG=./pkg/kv/kvserver TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestSplitTriggerRaftSnapshotRace.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by tbg**
We were not properly turning all operations on noopSpan into noops.
There is still a lot left to clean up here. Ultimately I want noop spans
to be nil pointers, but that means moving the tracer off first, and this
in turn means moving off the opentracing interfaces.

Touches #50032 

Closes #55911,
Closes #55912,
Closes #55913,
Closes #55914, 
Closes #55917, 
Closes #55918, 
Closes #55919, and
Closes #55936.

Release note: None

### CODE REVIEW

File: pkg/util/tracing/tracer.go [hunk 1]
```diff
@@ -401,6 +386,27 @@ func (t *Tracer) startSpanGeneric(
 		}
 	}
 
+	// Set initial tags.
```
Comment (tbg) [inline pkg/util/tracing/tracer.go:389]: This movement was necessary to fix a bug: we were linking the shadow span after adding baggage to the parent, so the shadow span never received them. Erroneously passed before my other fixes here.

**Comment by tbg** [comment]
I got through a few race iterations of #50032 without issues locally. Will leave it running for a bit and merge on green since the bug this fixes is quite destabilizing.

**Comment by tbg** [comment]
There's a test failure that I will look into tonight.

**Comment by rytaft** [comment]
Not sure if this should close #50032, since there was an unrelated failure there before. But I do think it should should close  #55911, #55912, #55913, #55914, #55917, #55918, #55919, and #55936.
