### PR TITLE
storage: de-flake TestNodeIsLiveCallback

### LINKED ISSUE #19344: teamcity: failed tests on master: test/TestNodeIsLiveCallback
The following tests appear to have failed:

[#381431](https://teamcity.cockroachdb.com/viewLog.html?buildId=381431):

```
--- FAIL: test/TestNodeIsLiveCallback (45.170s)
soon.go:44: storage/node_liveness_test.go:190, condition failed to evaluate within 45s: expected IsLive callback for node 1
	goroutine 96875 [running]:
	runtime/debug.Stack(0x2, 0x2925577, 0x1d)
		/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
	github.com/cockroachdb/cockroach/pkg/testutils.SucceedsSoonDepth(0x1, 0x2c192c0, 0xc4230f6000, 0xc423303f78)
		/go/src/github.com/cockroachdb/cockroach/pkg/testutils/soon.go:45 +0xa1
	github.com/cockroachdb/cockroach/pkg/testutils.SucceedsSoon(0x2c192c0, 0xc4230f6000, 0xc423303f78)
		/go/src/github.com/cockroachdb/cockroach/pkg/testutils/soon.go:36 +0x48
	github.com/cockroachdb/cockroach/pkg/storage_test.TestNodeIsLiveCallback(0xc4230f6000)
		/go/src/github.com/cockroachdb/cockroach/pkg/storage/node_liveness_test.go:190 +0x3c2
	testing.tRunner(0xc4230f6000, 0x1e3fe10)
		/usr/local/go/src/testing/testing.go:746 +0xd0
	created by testing.(*T).Run
		/usr/local/go/src/testing/testing.go:789 +0x2de
------- Stdout: -------
I171018 16:26:14.327307 96875 storage/store.go:1212  [s1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I171018 16:26:14.327359 96875 gossip/gossip.go:331  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:32928" > attrs:<> locality:<> ServerVersion:<major_val:0 minor_val:0 patch:0 unstable:0 > 
W171018 16:26:14.330483 96875 gossip/gossip.go:1277  [n2] no incoming or outgoing connections
I171018 16:26:14.330688 97608 gossip/client.go:129  [n2] started gossip client to 127.0.0.1:32928
I171018 16:26:14.331186 96875 gossip/gossip.go:331  [n2] NodeDescriptor set to node_id:2 address:<network_field:"tcp" address_field:"127.0.0.1:42793" > attrs:<> locality:<> ServerVersion:<major_val:0 minor_val:0 patch:0 unstable:0 > 
W171018 16:26:14.334072 96875 gossip/gossip.go:1277  [n3] no incoming or outgoing connections
I171018 16:26:14.334169 96875 storage/store.go:1212  [s3] [n3,s3]: failed initial metrics computation: [n3,s3]: system config not yet available
I171018 16:26:14.334207 96875 gossip/gossip.go:331  [n3] NodeDescriptor set to node_id:3 address:<network_field:"tcp" address_field:"127.0.0.1:37719" > attrs:<> locality:<> ServerVersion:<major_val:0 minor_val:0 patch:0 unstable:0 > 
I171018 16:26:14.338647 97828 gossip/client.go:129  [n3] started gossip client to 127.0.0.1:32928
I171018 16:26:36.923080 97249 gossip/gossip.go:1291  [n2] node has connected to cluster via gossip
I171018 16:26:38.151013 97626 gossip/gossip.go:1291  [n1] node has connected to cluster via gossip
I171018 16:26:42.559997 97850 gossip/gossip.go:1291  [n3] node has connected to cluster via gossip
I171018 16:26:59.497607 97611 vendor/google.golang.org/grpc/grpclog/grpclog.go:75  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:37719->127.0.0.1:56907: use of closed network connection
I171018 16:26:59.497615 97714 vendor/google.golang.org/grpc/grpclog/grpclog.go:75  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:42793->127.0.0.1:59951: use of closed network connection
I171018 16:26:59.497658 97515 vendor/google.golang.org/grpc/grpclog/grpclog.go:75  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:32928->127.0.0.1:40395: use of closed network connection
I171018 16:26:59.497690 97619 vendor/google.golang.org/grpc/grpclog/grpclog.go:60  transport: http2Client.notifyError got notified that the client transport was broken EOF.
W171018 16:26:59.497732 97850 gossip/gossip.go:1277  [n3] no incoming or outgoing connections

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by tbg**
This test exercised that liveness callbacks fired after a node's liveness
changed from false to true. However, the trigger was tied to Gossip updates
only, but the liveness also updated "eagerly" after the heartbeat.

Recent refactorings made it much more likely that the eager update took
precedence, in which case the Gossip handler would avoid updating a
second time, forgetting the callbacks as a consequence.

This was addressed by making callback invocation the duty of the code
that ingests livenesses.

The test was extremely flaky before, and passed several thousand iterations as
of this commit.

Fixes #19344.

### CODE REVIEW

File: pkg/storage/node_liveness.go [hunk 1]
```diff
@@ -692,13 +692,30 @@ func (nl *NodeLiveness) updateLivenessAttempt(
 	return nil
 }
 
+// maybeUpdate replaces the liveness (if it appears newer) and invokes the
+// registered callbacks if the node became live in the process.
 func (nl *NodeLiveness) maybeUpdate(new Liveness) {
 	nl.mu.Lock()
+	// Note that this works fine even if `old` is empty.
 	old := nl.mu.nodes[new.NodeID]
```
Comment (a-robinson) [inline pkg/storage/node_liveness.go]: Not a big deal by any means, but using `new` as the variable name confuses syntax highlighters :)

**Review by a-robinson — APPROVED** [review]

File: pkg/storage/node_liveness.go (hunk 1 above)
Comment (tschottdorf) [reply pkg/storage/node_liveness.go]: Maybe your syntax highlighter... :-)

image

Won't eat another CI, but I'll keep it in mind and rename the next time I touch this code (hopefully a while down the road).

Comment (a-robinson) [reply pkg/storage/node_liveness.go]: The github syntax highlighter is the one I was referring to :)

screen shot 2017-10-18 at 2 35 45 pm
