### PR TITLE
kvserver: deflake acceptance/version-upgrade

### LINKED ISSUE #52627: roachtest: acceptance/version-upgrade failed consistency check
Pulling out this failure out of the already generated issue for acceptance/version-upgrade:
https://github.com/cockroachdb/cockroach/issues/50000#issuecomment-670780938.

```
Wraps: (3) r262 (/Table/38) is inconsistent: RANGE_INCONSISTENT 
  | (n1,s1):1: checksum 647c99c621aa4b132b5e25adbf9afed1c05535727a90f3ccb6675b1b60086a8ca834eecce9f21d1c5d277f10c64462000b51347adee09583c631ce6b4bd124e9 [minority]
  | - stats: contains_estimates:0 last_update_nanos:1596842364031079451 intent_age:0 gc_bytes_age:0 live_bytes:0 live_count:0 key_bytes:0 key_count:0 val_bytes:0 val_count:0 intent_bytes:0 intent_count:0 sys_bytes:723 sys_count:7 abort_span_bytes:1 
  | - stats.Sub(recomputation): last_update_nanos:1596842364031079451 sys_bytes:723 sys_count:7 abort_span_bytes:1 
  | (n2,s2):4: checksum 59da917862af75013106d0f08b0c6501ebeac2201c8233e20537eb5391569186398aa98a38d66ae025567424d44ab5fb0938bb298b8ddc05b1d1627eecb4e1a0
  | - stats: contains_estimates:0 last_update_nanos:1596842364031079451 intent_age:0 gc_bytes_age:0 live_bytes:0 live_count:0 key_bytes:0 key_count:0 val_bytes:0 val_count:0 intent_bytes:0 intent_count:0 sys_bytes:723 sys_count:7 abort_span_bytes:0 
  | - stats.Sub(recomputation): last_update_nanos:1596842364031079451 sys_bytes:723 sys_count:7 
  | (n4,s4):2: checksum 59da917862af75013106d0f08b0c6501ebeac2201c8233e20537eb5391569186398aa98a38d66ae025567424d44ab5fb0938bb298b8ddc05b1d1627eecb4e1a0
  | - stats: contains_estimates:0 last_update_nanos:1596842364031079451 intent_age:0 gc_bytes_age:0 live_bytes:0 live_count:0 key_bytes:0 key_count:0 val_bytes:0 val_count:0 intent_bytes:0 intent_count:0 sys_bytes:723 sys_count:7 abort_span_bytes:0 
  | - stats.Sub(recomputation): last_update_nanos:1596842364031079451 sys_bytes:723 sys_count:7 
```

Looks like the delta is coming from the abort span bytes counter, added recently in #50938. @asubiotto says it's easily reproducible, which we could start with rebasing atop #52624.

### PR DESCRIPTION
**Pull request by irfansharif**
Fixes #52627.

In #50938 we were careful to not transmit non-zero MVCCStats through the
replica proposal codepaths, but there seems to have been another
instance where we end up transmitting MVCCStats across replicas - during
splits. We similarly zero AbortSpanBytes out when VersionAbortSpanBytes
is inactive to avoid replica divergence.

Release note: None

### CODE REVIEW

**Comment by irfansharif** [comment]
I couldn't actually repro the failure observed, but I'm pretty sure this is what's needed. I can try stressing again tomorrow with and without this patch to confirm. I tried mixed version clusters and generating splits manually but still was unable to. I probably wasn't creating abort span bytes in doing so. Was trying:

```
 make buildshort; 
 roachprod destroy local; 
 roachprod create local -n 4; 
 roachprod put local:1-3 (which cockroach20.1) ./cockroach; 
 roachprod put local:4 bin/workload ./workload; 
 roachprod start local:1-3
 roachprod run local:4 './workload run kv --init --splits 10000 --tolerate-errors {pgurl:2}' &
 echo "sleeping..";
 sleep 3;
 roachprod put local:2 ./cockroachshort ./cockroach; 
 roachprod stop local:2;
 roachprod start local:2;
```

File: pkg/kv/kvserver/batcheval/cmd_end_transaction.go [hunk 1]
```diff
@@ -1036,6 +1036,9 @@ func splitTriggerHelper(
 	if !rec.ClusterSettings().Version.IsActive(ctx, clusterversion.VersionContainsEstimatesCounter) {
 		deltaPostSplitLeft.ContainsEstimates = 0
 	}
+	if !rec.ClusterSettings().Version.IsActive(ctx, clusterversion.VersionAbortSpanBytes) {
```
Comment (tbg) [inline pkg/kv/kvserver/batcheval/cmd_end_transaction.go:1039]: Are you sure? If my reading of the callers of this code is correct, `deltaPostSplitLeft` will essentially be `ms`, meaning that the existing zeroing out should override it just fine. Don't you want to massage the `RHSDelta` above? That would make more sense to me as it is used to seed the stats for the RHS, and will not go through the existing check.

**Comment by irfansharif** [comment]
Looking at the snippet @chrisseto posted:
```
I200812 19:15:29.100791 4262 kv/kvserver/replica_command.go:414  [n1,s1,r11/1:/Table/1{5-6}] initiating a split of this range at key /Table/15/3 [r997] (manual)
...
E200812 19:16:07.986964 6820 kv/kvserver/replica_consistency.go:162  [n1,consistencyChecker,s1,r997/1:/Table/1{5/3-6}] (n1,s1):1: checksum a67704dbec62d0c7a063e8528bf2cb2e4dc3ce4f83d0b700b16c271f27afe7e52b7533774d9607c33ce5c8d8d7f3ec91cdf7571a3d7d7b0ed197c7df4a0d4214 [minority]
```

I'm inclined to say this is the patch we're looking for.

**Review by tbg — CHANGES_REQUESTED** [review]
Oh, tricky! Good catch. I think you got the wrong side of the split, but this does seem like a problem. I hope you can reproduce before and after as this is all tricky enough that there could be yet another problem.

**Comment by irfansharif** [comment]
Hm, I think we need both. Something like:
```diff
@@ -1036,6 +1033,10 @@ func splitTriggerHelper(
        var pd result.Result
        pd.Replicated.Split = &kvserverpb.Split{
          SplitTrigger: *split,
          // NB: the RHSDelta is identical to the stats for the newly created right
          // hand side range (i.e. it goes from zero to its stats).
          RHSDelta: *h.AbsPostSplitRight(),
        }

        deltaPostSplitLeft := h.DeltaPostSplitLeft()
        if !rec.ClusterSettings().Version.IsActive(ctx, clusterversion.VersionContainsEstimatesCounter) {
          deltaPostSplitLeft.ContainsEstimates = 0
        }

        if !rec.ClusterSettings().Version.IsActive(ctx, clusterversion.VersionContainsEstimatesCounter) {
                deltaPostSplitLeft.ContainsEstimates = 0
        }
+       if !rec.ClusterSettings().Version.IsActive(ctx, clusterversion.VersionAbortSpanBytes) {
+               deltaPostSplitLeft.AbortSpanBytes = 0
+               pd.Replicated.Split.RHSDelta.AbortSpanBytes = 0
+       }
        return deltaPostSplitLeft, pd, nil
 }
```

But yes, I'll have to repro instead of wildly speculating.

**Review by irfansharif — COMMENTED** [review]
@tbg Added a (contrived) test that confirms the patch. Happy to not check-in the test into our repo, though I did try to generalize it a bit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52750#-:-MEdo3kpCIXyzi458G0u:b-8mogt4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @madelineliao and @tbg)

___
*[pkg/kv/kvserver/batcheval/cmd_end_transaction.go, line 1039 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52750#-ME_TY6-6TCrD5LXtIXB-r1-1039:-MEdo2W1Cu7F3fnr85u_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/db8226123ff657f4c97ebf59a0f1424c93e9c9be/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L1039)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Are you sure? If my reading of the callers of this code is correct, `deltaPostSplitLeft` will essentially be `ms`, meaning that the existing zeroing out should override it just fine. Don't you want to massage the `RHSDelta` above? That would make more sense to me as it is used to seed the stats for the RHS, and will not go through the existing check.
</blockquote></details>

Done.

**Review by tbg — APPROVED** [review]
> Hm, I think we need both.

Interesting, but why? `deltaPostSplitLeft` is `newMS` in this code here:

https://github.com/cockroachdb/cockroach/blob/06cd1cbadee9cbbfb16d56aa1ed3f27568610702/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L596-L599

so we use it as the "main" stats (which makes sense), so its AbortSpanBytes should be zeroed out by the existing check before proposal. Hmm, your code only zeroes the RHS, so you've come around then?

For the test, I wonder if we can "amend" the existing main version-upgrade test instead of adding a new one? I think it's a good idea to have some more generic splitting going on in that one.

Thanks for the fix!

> Reviewed 7 of 7 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52750#-:-MEhPfOT6eCQR_eneUgX:bud85zy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @madelineliao)

___
*[pkg/kv/kvserver/batcheval/cmd_end_transaction.go, line 1034 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52750#-MEhQcht8RxhqigOtuY4:-MEhQcht8RxhqigOtuY5:bh7zehf) ([raw file](https://github.com/cockroachdb/cockroach/blob/95256b3d01fac9ac2f14f446efe434806bd5054e/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L1034)):*
> ```Go
> 	deltaPostSplitLeft := h.DeltaPostSplitLeft()
> 	if !rec.ClusterSettings().Version.IsActive(ctx, clusterversion.VersionContainsEstimatesCounter) {
> 		deltaPostSplitLeft.ContainsEstimates = 0
> ```

Heh, by my same reasoning, this is not necessary but it's necessary on the right. I don't think splits ever come out with ContainsEstimates set, on the RHS, though. Too late now anyway. :-)

**Review by irfansharif — COMMENTED** [review]
> Interesting, but why?

Yea I was mistaken, I walked through the codepaths after and realized what you were saying. I'll try seeing what the amended version of version-upgrade looks like and abandon this other test, but I might also defer to later given it's holding up the release. We could probably run `workload kv` against it in the same way I did here. TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52750#-:-MEhSB7X9PrHqFiMHDU9:bo2tvsw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @madelineliao)
