### PR TITLE
log: fix race condition when reconfiguring logging in tests

### LINKED ISSUE #160154: cli: TestIncludeFiles failed
cli.TestIncludeFiles [failed](https://mesolite.cluster.engflow.com/invocations/default/b3e0a381-4884-46bd-80be-2561537c4b2e?testReportRun=3&testReportShard=8&testReportAttempt=1#targets-Ly9wa2cvY2xpOmNsaV90ZXN0) on release-26.1 @ [809f97228f29955caac944bd38b875c859b2d634](https://github.com/cockroachdb/cockroach/commits/809f97228f29955caac944bd38b875c859b2d634):

Fatal error:

```
panic: logging already active; first use:
	goroutine 1779828 [running]:
	runtime/debug.Stack()
		GOROOT/src/runtime/debug/stack.go:26 +0x5e
	github.com/cockroachdb/cockroach/pkg/util/debugutil.Stack(...)
		pkg/util/debugutil/debugutil.go:63
	github.com/cockroachdb/cockroach/pkg/util/log.setActive()
		pkg/util/log/clog.go:449 +0x8b
	github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(_, {{{0xc015d01b60, 0x24}, {0x719efd9, 0x1}, {0x719efd9, 0x1}, {0x70c0e05, 0x6}, {0x719efd9, ...}}, ...})
		pkg/util/log/clog.go:275 +0x45
	github.com/cockroachdb/cockroach/pkg/util/log.logfDepthInternal({0x8006500, 0xc0084c7310}, 0x2, 0x1, 0xf, 0x0?, {0x7323b87, 0x54}, {0xc00bd01db0, 0x1, ...})
		pkg/util/log/channels.go:104 +0x5a5
	github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(...)
		pkg/util/log/channels.go:34
	github.com/cockroachdb/cockroach/pkg/util/log.loggerKvExec.Infof(...)
		bazel-out/k8-fastbuild/bin/pkg/util/log/log_channels_generated.go:6401
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*unbufferedRegistration).publishCatchUpBuffer.func1()
		pkg/kv/kvserver/rangefeed/unbuffered_registration.go:305 +0x22d
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*unbufferedRegistration).publishCatchUpBuffer(0xc012f26780, {0x8006500, 0xc0084c7310})
		pkg/kv/kvserver/rangefeed/unbuffered_registration.go:332 +0xcb
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*unbufferedRegistration).runOutputLoop(0xc012f26780, {0x8006500, 0xc0084c7310}, 0xc0070f8380?)
		pkg/kv/kvserver/rangefeed/unbuffered_registration.go:238 +0x15c
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*ScheduledProcessor).Register.func1.1({0x8007f08?, 0xc00a250640?})
		pkg/kv/kvserver/rangefeed/scheduled_processor.go:377 +0x37
	github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func1({0x8007f08, 0xc00a250640})
		pkg/util/stop/stopper.go:440 +0x8a
	created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx in goroutine 1589481
		pkg/util/stop/stopper.go:438 +0x125
	 [recovered, repanicked]

```
Stack: 

```
goroutine 1579095 [running]:
testing.tRunner.func1.2({0x6b23520, 0xc004393da0})
	GOROOT/src/testing/testing.go:1872 +0x237
testing.tRunner.func1()
	GOROOT/src/testing/testing.go:1875 +0x35b
panic({0x6b23520?, 0xc004393da0?})
	GOROOT/src/runtime/panic.go:783 +0x132
github.com/cockroachdb/cockroach/pkg/util/leaktest.AfterTest.func2()
	pkg/util/leaktest/leaktest.go:136 +0x3a9
panic({0x6b23520?, 0xc004393da0?})
	GOROOT/src/runtime/panic.go:783 +0x132
github.com/cockroachdb/cockroach/pkg/util/log/logcrash.ReportOrPanic({0x80061d0, 0xcba2640}, 0x0, {0x71aacdb?, 0x0?}, {0xc00c821390?, 0x70c91d2?, 0x70c91d2?})
	pkg/util/log/logcrash/crash_reporting.go:434 +0x1e8
github.com/cockroachdb/cockroach/pkg/util/log.ApplyConfig({{0xc009fca6c0, 0xc0059e45d8, 0xc0059e4610, 0xc0059e4890, 0xc0059e463d, {0x1, 0xc00ea13d80, 0x0, 0xc0059e45d4, 0xc0059e45d5, ...}}, ...}, ...)
	pkg/util/log/flags.go:114 +0x115
github.com/cockroachdb/cockroach/pkg/util/log.(*TestLogScope).SetupSingleFileLogging(0xc00d6aa000)
	pkg/util/log/test_log_scope.go:359 +0x2fc
github.com/cockroachdb/cockroach/pkg/cli.TestIncludeFiles(0xc002c6d180)
	zip_test.go:1451 +0x392
testing.tRunner(0xc002c6d180, 0x7512fa0)
	GOROOT/src/testing/testing.go:1934 +0xea
created by testing.(*T).Run in goroutine 1
	GOROOT/src/testing/testing.go:1997 +0x465
```
<details><summary>Log preceding fatal error</summary>
<p>

```
=== RUN   TestIncludeFiles
    test_log_scope.go:171: test logs captured to: outputs.zip/logTestIncludeFiles176844296
    test_log_scope.go:82: use -show-logs to present logs inline
    test_log_scope.go:171: test logs captured to: outputs.zip/logTestIncludeFiles3640491257
    crash_reporting.go:434: -- test log scope end --

ERROR: a panic has occurred!
Details cannot be printed yet because we are still unwinding.
Hopefully the test harness prints the panic below, otherwise check the test logs.

test logs left over in: outputs.zip/logTestIncludeFiles3640491257
    crash_reporting.go:434: -- test log scope end --

ERROR: a panic has occurred!
Details cannot be printed yet because we are still unwinding.
Hopefully the test harness prints the panic below, otherwise check the test logs.

test logs left over in: outputs.zip/logTestIncludeFiles176844296
    crash_reporting.go:434: panic: logging already active; first use:
        goroutine 1779828 [running]:
        runtime/debug.Stack()
        	GOROOT/src/runtime/debug/stack.go:26 +0x5e
        github.com/cockroachdb/cockroach/pkg/util/debugutil.Stack(...)
        	pkg/util/debugutil/debugutil.go:63
        github.com/cockroachdb/cockroach/pkg/util/log.setActive()
        	pkg/util/log/clog.go:449 +0x8b
        github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(_, {{{0xc015d01b60, 0x24}, {0x719efd9, 0x1}, {0x719efd9, 0x1}, {0x70c0e05, 0x6}, {0x719efd9, ...}}, ...})
        	pkg/util/log/clog.go:275 +0x45
        github.com/cockroachdb/cockroach/pkg/util/log.logfDepthInternal({0x8006500, 0xc0084c7310}, 0x2, 0x1, 0xf, 0x0?, {0x7323b87, 0x54}, {0xc00bd01db0, 0x1, ...})
        	pkg/util/log/channels.go:104 +0x5a5
        github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(...)
        	pkg/util/log/channels.go:34
        github.com/cockroachdb/cockroach/pkg/util/log.loggerKvExec.Infof(...)
        	bazel-out/k8-fastbuild/bin/pkg/util/log/log_channels_generated.go:6401
        github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*unbufferedRegistration).publishCatchUpBuffer.func1()
        	pkg/kv/kvserver/rangefeed/unbuffered_registration.go:305 +0x22d
        github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*unbufferedRegistration).publishCatchUpBuffer(0xc012f26780, {0x8006500, 0xc0084c7310})
        	pkg/kv/kvserver/rangefeed/unbuffered_registration.go:332 +0xcb
        github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*unbufferedRegistration).runOutputLoop(0xc012f26780, {0x8006500, 0xc0084c7310}, 0xc0070f8380?)
        	pkg/kv/kvserver/rangefeed/unbuffered_registration.go:238 +0x15c
        github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*ScheduledProcessor).Register.func1.1({0x8007f08?, 0xc00a250640?})
        	pkg/kv/kvserver/rangefeed/scheduled_processor.go:377 +0x37
        github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func1({0x8007f08, 0xc00a250640})
        	pkg/util/stop/stopper.go:440 +0x8a
        created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx in goroutine 1589481
        	pkg/util/stop/stopper.go:438 +0x125
--- FAIL: TestIncludeFiles (2.31s)
```
</p>
</details>

Parameters:
 - <code>attempt=1</code>
 - <code>deadlock=true</code>
 - <code>run=3</code>
 - <code>shard=8</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/obs-prs @cockroachdb/server @cockroachdb/obs-india-prs
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestIncludeFiles.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-58187

### PR DESCRIPTION
**Pull request by angles-n-daemons**
Previously, test code that needed to reconfigure logging would call TestingResetActive() followed by ApplyConfig(). These were two separate operations with a race window between them where a background goroutine could log a message, calling setActive() and setting the active flag back to true.

This was inadequate because when ApplyConfig() subsequently checked IsActive(), it would find active=true and panic with "logging already active". This caused flaky test failures like #114642 and #160154, particularly when tests created log scopes while servers with background logging goroutines were running.

To address this, this patch introduces ApplyConfigForReconfig() which atomically resets the active flag and applies the new configuration under a single lock acquisition, eliminating the race window. All instances of the TestingResetActive() + ApplyConfig() pattern have been replaced with calls to ApplyConfigForReconfig().

Fixes: #160154
Informs: #110028
Epic: none
Release note: none

### CODE REVIEW

File: pkg/util/log/fluent_client_test.go [hunk 1]
```diff
@@ -89,7 +88,7 @@ func TestFluentClient(t *testing.T) {
 	msg, err := json.Marshal(info)
 	require.NoError(t, err)
 
-	const expected = `{"c":1,"f":"util/log/fluent_client_test.go","g":222,"l":72,"message":"hello world","n":1,"r":1,"s":1,"sev":"I","t":"XXX","tag":"logtest.ops","v":"v999.0.0"}`
+	const expected = `{"c":1,"f":"util/log/fluent_client_test.go","g":222,"l":71,"message":"hello world","n":1,"r":1,"s":1,"sev":"I","t":"XXX","tag":"logtest.ops","v":"v999.0.0"}`
```
Comment (alyshanjahani-crl) [inline pkg/util/log/fluent_client_test.go:91]: why did this change? 72 -> 71 ?

**Review by alyshanjahani-crl — APPROVED** [review]
Overall LGTM, nice find.

Would you be able to show one of the flakey tests failing under `race` or `stress` without this patch, and then succeeding with this patch?

File: pkg/util/log/fluent_client_test.go (hunk 1 above)
Comment (angles-n-daemons) [reply pkg/util/log/fluent_client_test.go:91]: Above, the `Ops.Infof` call moved from line 72 to line 71 because we collapsed down log configuration from two lines to one.

**Review by alyshanjahani-crl — APPROVED** [review]
Nice, thank you!
