### PR TITLE
roachtest: add Mocha test parser for node-postgres tests

### LINKED ISSUE #152728: roachtest: node-postgres failed
roachtest.node-postgres [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20408023?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20408023?buildTab=artifacts#/node-postgres) on release-25.3.1-rc @ [092bace42e2cb3784a76705117251577939bd869](https://github.com/cockroachdb/cockroach/commits/092bace42e2cb3784a76705117251577939bd869):

```
(nodejs_postgres.go:132).func1: COMMAND_PROBLEM: exit status 2
test artifacts and logs in: /artifacts/node-postgres/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>metamorphicLeases=epoch</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20408023/node-postgres/1756461636573/1756461876264)

</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*node-postgres.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-54014

### PR DESCRIPTION
**Pull request by spilchen**
This commit introduces Mocha test output parsing for the node-postgres roachtest. The parser handles hierarchical test suites (suite => subsuite => test) and properly categorizes test results against blocklists and ignorelists.

With this ignorelist in place, this also ignores a test flake as outlined here: https://github.com/cockroachdb/cockroach/issues/152728#issuecomment-3245640238

Fixes #152728

Release note: None
Epic: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/nodejs_postgres_blocklist.go [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+
+// Please keep these lists alphabetized for easy diffing.
+// After a failed run, an updated version of this blocklist should be available
+// in the test log.
+//
+// Note: For Mocha tests organized in suites, test names are reported as
+// "suite => subsuite => ... => testcase" (e.g., "pool => with callbacks => removes client...").
+// Use the full hierarchical path in the blocklist/ignorelist.
+var nodePostgresBlockList = blocklist{
+	"pool size of 1 => can only send 1 query at a time": "152728",
```
Comment (rafiss) [inline pkg/cmd/roachtest/tests/nodejs_postgres_blocklist.go]: i don't think this one was failing consistently -- since it's flaky, should it be in the ignorelist instead?

File: pkg/cmd/roachtest/tests/nodejs_helpers.go [hunk 2]
```diff
@@ -0,0 +1,204 @@
...
+
+// parseMochaOutput parses Mocha test output and extracts test results.
+// Mocha output format:
+//
+//	✓ passing test name
+//	1) failing test name
+//	- skipped test name
+//
+// Returns a slice of test results.
+func parseMochaOutput(output string) []mochaTestResult {
```
Comment (rafiss) [inline pkg/cmd/roachtest/tests/nodejs_helpers.go:40]: very nice! thanks so much for building this

**Review by rafiss — APPROVED** [review]
this should save a lot of toil!

did you get to try a real execution by running `roachtest` manually?

File: pkg/cmd/roachtest/tests/nodejs_postgres_blocklist.go (hunk 1 above)
Comment (spilchen) [reply pkg/cmd/roachtest/tests/nodejs_postgres_blocklist.go]: It failed each time I ran it. But if there is a chance that it could succeed, that would cause the entire test to fail. I'll move it over.

**Review by spilchen — COMMENTED** [review]
It doesn't take long to run, so once I had all of the changes sorted out I ran it in a tight loop. I got about 12 successes in a row before cancelling the loop.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/154520#-:-OaVximu1ueRJfig5y6h:b-dphgxe)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @spilchen)
