### PR TITLE
sql: improve fingerprinting runtime by increasing concurrency

### LINKED ISSUE #124725: roachtest: backup-restore/small-ranges failed [fingerprinting slow]
roachtest.backup-restore/small-ranges [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/15417787?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/15417787?buildTab=artifacts#/backup-restore/small-ranges) on master @ [0ea8b622c5354a891cfb867d8d872a0746ba77b3](https://github.com/cockroachdb/cockroach/commits/0ea8b622c5354a891cfb867d8d872a0746ba77b3):

```
(test_runner.go:1255).runTest: test timed out (4h0m0s)
test artifacts and logs in: /artifacts/backup-restore/small-ranges/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=true</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-15417787/backup-restore-small-ranges/1716789307996/1716803861145)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backup-restore/small-ranges.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-39040

### PR DESCRIPTION
**Pull request by navsetlur**
The previous fingerprint algorithm was tied to 1 worker per node which led to slower performance. The current algorithm spins up as many workers as roach spans leading to quicker runtimes. The change alone leads to a speedup of 28%, but when paired with disabling admission control on CPU time for export requests, can lead to improvements as high as 64%. It's not possible to set cluster settings in code, so for now the admission control is untouched. More details found here: https://docs.google.com/spreadsheets/d/1VNZ_giEQWNagc6laAmYZYSdnR9Tb1vDAaBO-81ksJ8k/edit?usp=sharing

Fixes: #124725
Release note: none

### CODE REVIEW

File: pkg/sql/fingerprint_span.go [hunk 1]
```diff
@@ -163,12 +177,14 @@ func (p *planner) fingerprintSpanFanout(
...
 			}
-			return nil
 		})
 	}
+
+	close(spanChannel)
 	if err := grp.Wait(); err != nil {
 		return 0, nil, err
 	}
+	// TODO: Why lock and unlock if all threads done?
```
Comment (navsetlur) [inline pkg/sql/fingerprint_span.go:187]: @stevendanna can you explain why you lock and unlock before returning?

Comment (stevendanna) [reply pkg/sql/fingerprint_span.go:187]: If I had to guess, we massaged this code a few times during development and ended up with oddity as a result.  If you do remove this, make sure to run the tests under --race just in case. But, I agree we don't need to lock here.

File: pkg/sql/fingerprint_span.go [hunk 2]
```diff
@@ -129,14 +128,26 @@ func (p *planner) fingerprintSpanFanout(
...
+		count += length
+	}
+	// Take as many workers as partitions to efficiently distribute work
+	maxWorkerCount = min(maxWorkerCount, count)
+
+	// Each span partition contains spans that are likely to be served by
+	// the same node. By round robin grabbing a span from each partition
+	// and pushing to the channel, ideally sequential workers won't attempt
+	// to read from the same node at the same time.
+	spanChannel := make(chan roachpb.Span, count)
```
Comment (dt) [inline pkg/sql/fingerprint_span.go:145]: I wonder if we'd benefit from shuffling the partitions too?

File: pkg/sql/fingerprint_span.go [hunk 3]
```diff
@@ -163,14 +177,13 @@ func (p *planner) fingerprintSpanFanout(
 				rv.fingerprint = rv.fingerprint ^ localFingerprint
 				rv.Unlock()
 			}
-			return nil
 		})
 	}
+
+	close(spanChannel)
```
Comment (dt) [inline pkg/sql/fingerprint_span.go:183]: you can close this as soon as you finish putting spans in the ch, before launching the goroutines, just to be sure it closes even if you panic while launching for some reason.

File: pkg/sql/fingerprint_span.go [hunk 4]
```diff
@@ -145,15 +156,18 @@ func (p *planner) fingerprintSpanFanout(
...
 	grp := ctxgroup.WithContext(ctx)
-	for i := range workerPartitions {
-		workerIdx := i
+	for range maxWorkerCount {
 		grp.GoCtx(func(ctx context.Context) error {
-			spans := workerPartitions[workerIdx].Spans
-			for _, sp := range spans {
+			// Run until channel is empty
+			for {
+				sp, ok := <-spanChannel
```
Comment (dt) [inline pkg/sql/fingerprint_span.go:167]: Probably want to `select` on the spanCh and on ctx.Done() in case we cancel while there is still work in the ch

**Review by dt — APPROVED** [review]

File: pkg/sql/fingerprint_span.go (hunk 2 above)
Comment (navsetlur) [reply pkg/sql/fingerprint_span.go:145]: With the round robin setup, what would shuffling improve?

**Comment by navsetlur** [comment]
bors r=dt
