### PR TITLE
pkg/server: fix `/demologin` to properly redirect to home page

### LINKED ISSUE #98253: pkg/server: `/demologin` doesn't redirect, doesn't provide multitenant-encoded cookie
**Describe the problem**

When I use the `/demologin` endpoint, many times I am still returned to the login page. On the occasions that it does work, I noticed that the `session` cookie isn't in the multitenant format (e.g. no encoded tenant name(s), and only a single session).

**To Reproduce**

Run `./cockroach demo --multitenant=true` and use the provided `/demologin` link. Note the above stated behavior.

**Expected behavior**
The user should be logged in with a multitenant session cookie.

Jira issue: CRDB-25153

Epic: CRDB-12100

### PR DESCRIPTION
**Pull request by abarganier**
With the introduction of the server controller, we introduced a layer between the HTTP handler and the HTTP server. When this was introduced, the logic to attempt a login to all tenants forgot to handle a specific case for `/demologin`, where the status code is set to a 302 redirect, instead of a 200 status OK.

This broke the redirect piece of the `/demologin` endpoint.

This patch updates the `attemptLoginToAllTenants` HTTP handler to properly set the 302 response code in the case where the underlying login function does so on the sessionWriter.

Release note: none

Epic: CRDB-12100

Fixes: https://github.com/cockroachdb/cockroach/issues/98253

### CODE REVIEW

File: pkg/server/server_controller_http.go [hunk 1]
```diff
@@ -185,6 +186,12 @@ func (c *serverController) attemptLoginToAllTenants() http.Handler {
 					name:      string(name),
 					setCookie: setCookieHeader,
 				})
+				// In the case of /demologin, we want to redirect to the home page.
+				// If we get back a cookie along with a 302, be sure to transfer that
+				// into the ResponseWriter later.
+				if sw.code == 302 {
```
Comment (knz) [inline pkg/server/server_controller_http.go:192]: `http.StatusTemporaryRedirect`?

File: pkg/server/server_controller_http.go [hunk 2]
```diff
@@ -217,7 +224,12 @@ func (c *serverController) attemptLoginToAllTenants() http.Handler {
 					return
 				}
 			}
-			w.WriteHeader(http.StatusOK)
+			if redirect {
+				w.Header()["Location"] = []string{"/"}
```
Comment (knz) [inline pkg/server/server_controller_http.go:228]: `http.Redirect()`.

Comment (abarganier) [reply pkg/server/server_controller_http.go]: `http.Redirect(w, r, "/", http.StatusTemporaryRedirect)` worked well. Thanks!

File: pkg/server/server_controller_http.go (hunk 1 above)
Comment (abarganier) [reply pkg/server/server_controller_http.go]: `http.StatusTemporaryRedirect` is assigned to code `307`. Seems like that's what we should be using anyway, so I went ahead and switched both places (the `/demologin` handler, and the quoted code above) to use `http.StatusTemporaryRedirect`.

**Review by dhartunian — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98319)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/server/server_controller_http.go` line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98319#-NQ6YHuu3Zr4m2iWybpz-r1-228:-NQap7WJ53_olozSqLll:b-cejpp5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d4d7752c72754e9128a7fe12bbd5df65338f80e/pkg/server/server_controller_http.go#L228)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

`http.Redirect(w, r, "/", http.StatusTemporaryRedirect)` worked well. Thanks!
</blockquote></details>

Should we also grab the Location from the fanout response?

**Review by abarganier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98319)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/server/server_controller_http.go` line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98319#-NQ6YHuu3Zr4m2iWybpz-r1-228:-NQfjHIN7vrLAa33VJwp:b-nuwblj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d4d7752c72754e9128a7fe12bbd5df65338f80e/pkg/server/server_controller_http.go#L228)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Should we also grab the Location from the fanout response?
</blockquote></details>

Good idea! Added this, with a default value of `/`

**Review by dhartunian — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98319#-:-NQkKtfY0HuFdEV8tMKW:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

**Comment by abarganier** [comment]
TFTR!

bors r=dhartunian

**Comment by aadityasondhi** [comment]
CI failure: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BazelUnitTests/9104679?showRootCauses=true&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

Trying to repro on gceworker usiung this branch but have had no luck.
```
1656 runs so far, 0 failures, over 8m30s
```
@dhartunian @abarganier  do you have any ideas on why these goroutine dumps show up in CI but not locally or in gceworker:
```
 output didn't match expected:
        @@ -141,12 +141,14 @@
         [node 1] requesting stacks... received response... writing binary output: debug/nodes/1/stacks.txt... done
         [node 1] requesting stacks with labels... received response... writing binary output: debug/nodes/1/stacks_with_labels.txt... done
         [node 1] requesting heap profile... received response... writing binary output: debug/nodes/1/heap.pprof... done
         [node 1] requesting heap file list... received response... done
         [node ?] ? heap profiles found
        +[node 1] retrieving goroutine_dump.2023-03-16T23_26_21.355.double_since_last_dump.000001066.txt.gz... received response... done
         [node 1] requesting goroutine dump list... received response... done
         [node ?] ? goroutine dumps found
        +[node 1] retrieving goroutine_dump.2023-03-16T23_26_21.355.double_since_last_dump.000001066.txt.gz... received response... done
         [node 1] requesting log file ...
         [node 1] 0 log file ...
         [node 1] requesting ranges... received response...
         [node 1] requesting ranges: last request failed: rpc error: ...
         [node 1] requesting ranges: creating error output: debug/nodes/1/ranges.err.txt... done
```

**Comment by aadityasondhi** [comment]
sorry for the noise, wrong PR

**Comment by abarganier** [comment]
bors retry
