### PR TITLE
builtins: implement to_timestamp for Unix epoch

### LINKED ISSUE #77591: builtins: implement to_timestamp
**Describe the problem**

To use a timestamp value in decimal, in Postgres, I use the `to_timestamp()` function as follows
```sql
select to_timestamp(1646906263.278);
```

Since cockroach doesn't have `to_timestamp()`, I use a cast instead:
```sql
select 1646906263.278::timestamptz;
```
But it results in `SQL Error [42846]: ERROR: invalid cast: decimal -> timestamptz`

Casting an integer to timestamptz works, thought it loses precision:
```sql
select 1646906263::timestamptz; # removed .278
```

**Environment:**
 - CockroachDB CCL v21.2.6 (x86_64-unknown-linux-gnu, built 2022/02/22 18:30:37, go1.16.6)

----

Instructions for contributors:

Add a built-in in https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/builtins.go
Add a test in https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/timestamp, and run make testbaselogic FILES='timestamp' TESTFLAGS='-rewrite' to test it.
Run make buildshort to regenerate automatically generated files.
Submit a PR.

----

Jira issue: CRDB-13671
Epic CRDB-14049

### PR DESCRIPTION
**Pull request by nnaka2992**
fixes #77591

Previously, CockroachDB did not support to_timestamp(double precision)
In PostgreSQL, the function also handles INT, DECIMAL and text by casting,
so the commit also implements those for compatibility.

Release note (sql change): Add new function to_timestamp which
converts Unix epoch of FLOAT, INT, DECIMAL and text to Timestamp with time zone.

### CODE REVIEW

File: pkg/sql/logictest/testdata/logic_test/timestamp [hunk 1]
```diff
@@ -516,3 +516,83 @@ SELECT date_trunc('day', t), date_trunc('hour', t) FROM (VALUES
...
+
+## Test for to_timestamp with NULL
+query T
+SELECT to_timestamp(NULL)
+----
+NULL
+
+## Test for invalid inputs
+statement error to_timestamp\(\): invalid input for type text
+SELECT to_timestamp('invalid')
```
Comment (otan) [inline pkg/sql/logictest/testdata/logic_test/timestamp:598]: can you add test cases for NaN too

File: pkg/sql/sem/builtins/builtins.go [hunk 2]
```diff
@@ -9629,3 +9736,26 @@ func prettyStatement(p tree.PrettyCfg, stmt string) (string, error) {
...
+	if math.IsNaN(ts) {
+		return nil, pgerror.New(pgcode.DatetimeFieldOverflow, "timestamp cannot be NaN")
+	}
+	if ts == math.Inf(0) {
+		return tree.MakeDTimestampTZ(pgdate.TimeInfinity, time.Microsecond)
+	}
+	if ts == math.Inf(-1) {
+		return tree.MakeDTimestampTZ(pgdate.TimeNegativeInfinity, time.Microsecond)
+	}
+	strts := strings.Split(strconv.FormatFloat(ts, 'f', 6, 64), ".")
```
Comment (otan) [inline pkg/sql/sem/builtins/builtins.go:9750]: we should not be casting to string to do this.
return tree.MakeDTimestampTZ(timeutil.Unix(0, int64(ts * float64(time.Second)), time.Microsecond)` should do the trick!

File: pkg/sql/sem/builtins/builtins.go [hunk 3]
```diff
@@ -9629,3 +9736,26 @@ func prettyStatement(p tree.PrettyCfg, stmt string) (string, error) {
 	}
 	return formattedStmt.String(), nil
 }
+
+func floatToTimestampTZ(ts float64) (tree.Datum, error) {
+	if math.IsNaN(ts) {
+		return nil, pgerror.New(pgcode.DatetimeFieldOverflow, "timestamp cannot be NaN")
+	}
+	if ts == math.Inf(0) {
```
Comment (otan) [inline pkg/sql/sem/builtins/builtins.go:9744]: this should be Inf(1) - please add a test for pos/neg inf.

**Review by otan — COMMENTED** [review]
thanks! just some small tweaks.

File: pkg/sql/logictest/testdata/logic_test/timestamp (hunk 1 above)
Comment (nnaka2992) [reply pkg/sql/logictest/testdata/logic_test/timestamp:598]: Added test of `to_timestamp()` for testing NaN.

File: pkg/sql/sem/builtins/builtins.go (hunk 3 above)
Comment (nnaka2992) [reply pkg/sql/sem/builtins/builtins.go]: Inf(0) and Inf(1) are the same thing, but just fixed

File: pkg/sql/sem/builtins/builtins.go (hunk 2 above)
Comment (nnaka2992) [reply pkg/sql/sem/builtins/builtins.go]: Using `tree.MakeDTimestampTZ(timeutil.Unix(0, int64(ts * float64(time.Second)), time.Microsecond)` instead of custing to string.

**Review by otan — APPROVED** [review]
bors r+

**Comment by korpa** [comment]
Will this be released in the next 22.1 version or do we have to wait till 22.2?

**Comment by otan** [comment]
22.2 unless there's compelling reason. is there a use case you need it for?

**Comment by korpa** [comment]
Yes, there is a reason: https://github.com/apache/superset/issues/15825

File: pkg/sql/sem/builtins/builtins.go [hunk 4]
```diff
@@ -2595,6 +2595,113 @@ var builtins = map[string]builtinDefinition{
...
+			ReturnType: tree.FixedReturnType(types.TimestampTZ),
+			Fn: func(ctx *eval.Context, args tree.Datums) (tree.Datum, error) {
+				ts, err := strconv.ParseFloat(string(tree.MustBeDString(args[0])), 64)
+				if err != nil {
+					return nil, pgerror.New(pgcode.AmbiguousFunction, "invalid input for type text")
+				}
+				return floatToTimestampTZ(ts)
+			},
+			Info:       "Convert Unix epoch (seconds since 1970-01-01 00:00:00+00) to timestamp with time zone.",
+			Volatility: volatility.Immutable,
```
Comment (mgartner) [inline pkg/sql/sem/builtins/builtins.go:2667]: I believe this should be stable, not immutable. In Postgres:

```
marcus=# select proargtypes, prorettype::regtype, provolatile, proleakproof from pg_proc where proname = 'to_timestamp';
 proargtypes |        prorettype        | provolatile | proleakproof
-------------+--------------------------+-------------+--------------
 701         | timestamp with time zone | i           | f
 25 25       | timestamp with time zone | s           | f
(2 rows)

marcus=# select 701::oid::regtype, 25::oid::regtype;
     regtype      | regtype
------------------+---------
 double precision | text
(1 row)
```

File: pkg/sql/sem/builtins/builtins.go [hunk 5]
```diff
@@ -2595,6 +2595,113 @@ var builtins = map[string]builtinDefinition{
...
+	//
+	//               postgres=# select to_timestamp(1646906263.123456::real);
+	//               to_timestamp
+	//               ------------------------
+	//               2022-03-10 09:57:20+00
+	//
+	//               postgres=# select to_timestamp('1646906263.123456');
+	//               to_timestamp
+	//               -------------------------------
+	//               2022-03-10 09:57:43.123456+00
```
Comment (mgartner) [inline pkg/sql/sem/builtins/builtins.go:2652]: This PR adds overloads that do not exist in Postgres. The only two overloads in PG are `to_timestamp(double_precision)` and `to_timestamp(text, text)`.

All of these other examples work because the argument type can be implicitly cast to a FLOAT8, or they are parsed as numeric types, as in `to_timestamp('1646906263.123456')`.

File: pkg/sql/sem/builtins/builtins.go [hunk 6]
```diff
@@ -2595,6 +2595,113 @@ var builtins = map[string]builtinDefinition{
...
+	//
+	"to_timestamp": makeBuiltin(
+		tree.FunctionProperties{Category: categoryDateAndTime},
+		tree.Overload{
+			Types:      tree.ArgTypes{{"timestamp", types.String}},
```
[the remark this answers is not in the document]
Comment (mgartner) [reply pkg/sql/sem/builtins/builtins.go:2657]: It's similar, but `experimental_strptime` doesn't support the same formatting strings as `to_timestamp`. Here's an example from the Postgres docs:

```
defaultdb> select experimental_strptime('05 Dec 2000', 'DD Mon YYYY');
  experimental_strptime
--------------------------
  0001-01-01 00:00:00+00
```

The result should be `2000-12-05 00:00:00-05` (assuming the timezone is set to `-05`). It looks like `experimental_strptime` returns a default value when parsing fails, rather than erring.

File: pkg/sql/sem/builtins/builtins.go (hunk 5 above)
Comment (nnaka2992) [reply pkg/sql/sem/builtins/builtins.go:2652]: It is better if we can implicitly cast text to numeric on function call. However at least on v22, CockroachDB
does not perform implicit casting, so I added the overload, `to_timestamp(text)` for compatibility.

Is it much suitable to fix overload.go (or any other files) to parse text as numeric?

File: pkg/sql/sem/builtins/builtins.go (hunk 4 above)
Comment (otan) [reply pkg/sql/sem/builtins/builtins.go:2667]: The one arg version is immutable - so this is right right?
