### PR TITLE
ui: `Canary vs Stable` Statement Times and Plan Distribution bar charts

### LINKED ISSUE #150015: sql: "canary release" for SQL table statistics
The optimizer relies heavily on SQL table stats to planning planning decisions. Consequently, plan regressions are more likely to occur when new stats are collected, e.g., when those stats are less representative of the actual data in the table.

To avoid plan regressions, we could follow the [canary release](https://en.wikipedia.org/wiki/Feature_toggle#Canary_release) pattern where new changes are released to a subset of users, and only promoted to the entire user base once deemed acceptable. For example, we could introduce the new stats for a subset of queries, and only promote the stats to be used by all queries once we have determined that there are no major regressions.

Thanks to @tbg for the inspiration here.

Jira issue: CRDB-52469

Epic CRDB-55121

### PR DESCRIPTION
**Pull request by ZhouXing19**
Informs: https://github.com/cockroachdb/cockroach/issues/156817
Fixes: #165850
Fixes: #150015

This PR introduce 2 charts that helps differentiate performance of canary and stable table stats for a statement.  Both charts live under the `Statement Fingerprint` page, which can be accessed via the `SQL Activity` panel.

### 1. Canary vs Stable Statement Times

Similar to the existing `Statement Times`, the new `Canary vs Stable Statement Times` dual-bar chart shows the aggregated planning and execution latency for the statement, but also differentiate the canary and stable exections.

Screenshot 2026-03-16 at 9 33 26 PM

Supports the "hovering to show details" and "click legend to isolate" effect.

### 2. Canary vs Stable Plan Distribution

Similar to the existing `Plan Distribution Over Time`, the `Canary vs Stable Plan Distribution` dual bar chart shows the aggregated plan distribution for the statement, but also differentiate the canary and stable exections. Also, the plan gist are colored according to their average execution time duration, with the longer the durtion, the darker the plan gist. 

Screenshot 2026-03-16 at 9 33 14 PM

Supports the "hovering to show details" and "click legend to isolate" effect.

Release note (sql ops): Introduce "Canary vs Stable Statement Times" and "Canary vs Stable Plan Distribution" dual-bar charts in the dbconsole's statement fingerprint page, which only shows up when the statement is enrolled in canary stats rollout feature. These bar charts can help differentiate the performance brought by the canary and stable table statistics, which facilitate troubleshooting possible regression caused by freshly collected table statistics.

### CODE REVIEW

File: pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/index.tsx [hunk 1]
```diff
@@ -117,6 +117,135 @@ export const BarGraphTimeSeries: React.FC<BarGraphTimeSeriesProps> = ({
...
+      yAxisUnits,
+      colourPalette,
+      timezone,
+    );
+
+    // When groupLabels is set but the caller overrides the legend to be
+    // visible (e.g. for the Statement Times chart), hide group 2's
+    // duplicate legend entries so only one set of layer labels appears.
+    if (groupLabels && opts.legend?.show) {
+      const nn = groupSize ?? Math.floor((alignedData.length - 1) / 2);
```
Comment (jasonlmfong) [inline pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/index.tsx:220]: for this commit this prop is not defined, i think you add it in the next commit but I prefer if each commit compiles correctly

File: pkg/ui/workspaces/cluster-ui/src/statementDetails/timeseriesUtils.ts [hunk 2]
```diff
@@ -198,3 +198,75 @@ export function generatePlanDistributionTimeseries(
...
+  const planGistSet = new Set<string>();
+  let hasCanary = false;
+
+  stats.forEach(stat => {
+    const ts = TimestampToNumber(stat.aggregated_ts) * 1e3;
+    const planGist = stat.plan_gist || "unknown";
+    planGistSet.add(planGist);
+
+    // eslint-disable-next-line @typescript-eslint/no-explicit-any
+    const canaryCount = Number((stat as any).canary_execution_count || 0);
```
Comment (jasonlmfong) [inline pkg/ui/workspaces/cluster-ui/src/statementDetails/timeseriesUtils.ts]: whats the reason for as any here

File: pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/bars.ts [hunk 3]
```diff
@@ -310,6 +535,145 @@ export const getGroupedStackedBarOpts = (
     };
   });
 
+  // Restack both groups based on the current group 1 visibility state.
+  // Group 2 show flags are synced to match group 1 before restacking.
+  function restackGroups(u: uPlot): void {
```
Comment (jasonlmfong) [inline pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/bars.ts]: theres a lot of uplot magic here that might be prone to issues

File: pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/plugins.ts [hunk 4]
```diff
@@ -228,6 +228,157 @@ export function categoricalBarTooltipPlugin(
...
+
+    // Which layer? Compare cursor y (in data coords) against the
+    // cumulative stacked boundaries for the selected group.
+    const yVal = u.posToVal(top, "yAxis");
+    // In stackedData: group 0 occupies indices 1..n,
+    //                 group 1 occupies indices n+1..2n.
+    const groupOffset = groupIdx === 0 ? 1 : 1 + n;
+
+    let hitLayer = -1;
+    for (let i = 0; i < n; i++) {
```
Comment (jasonlmfong) [inline pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/plugins.ts:274]: should `n` be dynamic here? when you click some bar it would change the total number of items available right?

**Review by jasonlmfong — COMMENTED** [review]
overall looks good, some questions

File: pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/index.tsx (hunk 1 above)
Comment (ZhouXing19) [reply pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/index.tsx:220]: Good point, done.

File: pkg/ui/workspaces/cluster-ui/src/statementDetails/timeseriesUtils.ts (hunk 2 above)
Comment (ZhouXing19) [reply pkg/ui/workspaces/cluster-ui/src/statementDetails/timeseriesUtils.ts]: No good reason -- the `canary_execution_count` and `stable_execution_count` fields are already in the proto definition (added in the backend commit), so the generated `IStatementPlanDistribution` interface includes them. Removed the as any casts.

File: pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/bars.ts (hunk 3 above)
Comment (ZhouXing19) [reply pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/bars.ts]: Yeah... I have claude added a high-level comment block explaining why restackGroups exists and documenting its 3 steps (sync group visibility, rebuild cumulative sums, rebuild bands). Open to suggestions if you see a way to simplify.

File: pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/plugins.ts (hunk 4 above)
Comment (ZhouXing19) [reply pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/plugins.ts:274]: `n` is the total number of layers per group in the data array layout, which stays constant even when series are toggled off. Toggling only changes visibility and restacks the data (via `restackGroups` in `bars.ts`) without altering the array structure — hidden layers collapse to zero height, so the hit-test naturally skips them. Added clarifying comment.

File: pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/bars.ts (hunk 3 above)
Comment (jasonlmfong) [reply pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/bars.ts]: fine with the addition if there is no other way around it, but maybe leave a note that it is prone to break if we ever upgrade uplot version and these no longer work

File: pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.ts [hunk 5]
```diff
@@ -162,6 +162,32 @@ export function addExecStats(a: ExecStats, b: ExecStats): ExecStats {
   };
 }
 
+export function addExperimentStatsInfo(
```
Comment (jasonlmfong) [inline pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.ts:165]: simple enough but would be nice to add a test in the appstats.spec.ts
also makes sure we dont get any undefined or NaN outputs

File: pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/index.tsx [hunk 6]
```diff
@@ -117,6 +117,170 @@ export const BarGraphTimeSeries: React.FC<BarGraphTimeSeriesProps> = ({
...
+  preCalcGraphSize = true,
+  title,
+  tooltip,
+  uPlotOptions,
+  yAxisUnits,
+  xScale,
+}) => {
+  const graphRef = useRef<HTMLDivElement>(null);
+  const samplingIntervalMillis =
+    alignedData[0].length > 1 ? alignedData[0][1] - alignedData[0][0] : 1e3;
```
Comment (jasonlmfong) [inline pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/index.tsx]: i think the old code also doesn't check this but good to defensively check if alignedData is not null before accessing

File: pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/index.tsx [hunk 7]
```diff
@@ -117,6 +117,170 @@ export const BarGraphTimeSeries: React.FC<BarGraphTimeSeriesProps> = ({
...
+  const timezone = useContext(TimezoneContext);
+
+  useEffect(() => {
+    if (!alignedData) return;
+
+    const start = xScale.graphTsStartMillis
```
Comment (jasonlmfong) [inline pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/index.tsx]: similarly check if xScale is present

File: pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/bars.ts
Comment (jasonlmfong) [inline pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/bars.ts:1]: since all these additions are isolated and only served this new feature, can you put these into a new file instead?

File: pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/bars.ts (hunk 3 above)
Comment (ZhouXing19) [reply pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/bars.ts]: Moved to `groupedBars.ts` and added warnings at both the file level and on restackGroups.

File: pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.ts (hunk 5 above)
Comment (ZhouXing19) [reply pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.ts:165]: Done -- the test covers null/undefined inputs, single non-null input, two non-null aggregation (verifies weighted means), and zero-count edge case (verifies no NaN).

File: pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/index.tsx (hunk 6 above)
Comment (ZhouXing19) [reply pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/index.tsx]: Good point, done.

File: pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/index.tsx (hunk 7 above)
Comment (ZhouXing19) [reply pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/index.tsx]: Done.

File: pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/bars.ts
Comment (ZhouXing19) [reply pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/bars.ts:1]: Done, please see the first commit with the `groupedBars.ts`.

**Review by jasonlmfong — APPROVED** [review]
looks good to me now
