### PR TITLE
log: fix race in TestLogEntryPropagation

### LINKED ISSUE #122791: util/log: TestLogEntryPropagation failed
util/log.TestLogEntryPropagation [failed](https://tanzanite.cluster.engflow.com/invocations/default/be232a8b-c406-45e5-a00a-fdbe1a5bf38f?testReportRun=1&testReportShard=1&testReportAttempt=1#targets-Ly9wa2cvdXRpbC9sb2c6bG9nX3Rlc3Q=) on master @ [347cdc76d4c5abb2e872f325e944337a46b5883f](https://github.com/cockroachdb/cockroach/commits/347cdc76d4c5abb2e872f325e944337a46b5883f):

```
==================
WARNING: DATA RACE
Write at 0x0000022898f8 by goroutine 311:
  github.com/cockroachdb/cockroach/pkg/util/log.TestLogEntryPropagation()
      github.com/cockroachdb/cockroach/pkg/util/log/clog_test.go:753 +0x3b3
  testing.tRunner()
      GOROOT/src/testing/testing.go:1689 +0x21e
  testing.(*T).Run.gowrap1()
      GOROOT/src/testing/testing.go:1742 +0x44

Previous read at 0x0000022898f8 by goroutine 301:
  github.com/cockroachdb/cockroach/pkg/util/log.(*fileSink).gcOldFiles()
      github.com/cockroachdb/cockroach/pkg/util/log/file_log_gc.go:48 +0xb3
  github.com/cockroachdb/cockroach/pkg/util/log.(*fileSink).gcDaemon()
      github.com/cockroachdb/cockroach/pkg/util/log/file_log_gc.go:36 +0x124
  github.com/cockroachdb/cockroach/pkg/util/log.ApplyConfig.gowrap2()
      github.com/cockroachdb/cockroach/pkg/util/log/flags.go:328 +0x4f

Goroutine 311 (running) created at:
  testing.(*T).Run()
      GOROOT/src/testing/testing.go:1742 +0x825
  testing.runTests.func1()
      GOROOT/src/testing/testing.go:2161 +0x85
  testing.tRunner()
      GOROOT/src/testing/testing.go:1689 +0x21e
  testing.runTests()
      GOROOT/src/testing/testing.go:2159 +0x8be
  testing.(*M).Run()
      GOROOT/src/testing/testing.go:2027 +0xf17
  github.com/cockroachdb/cockroach/pkg/util/log_test.TestMain()
      github.com/cockroachdb/cockroach/pkg/util/log_test/pkg/util/log/main_test.go:29 +0xce
  main.main()
      main/bazel-out/k8-fastbuild/bin/pkg/util/log/log_test_/testmain.go:306 +0x824

Goroutine 301 (finished) created at:
  github.com/cockroachdb/cockroach/pkg/util/log.ApplyConfig()
      github.com/cockroachdb/cockroach/pkg/util/log/flags.go:328 +0x1d79
  github.com/cockroachdb/cockroach/pkg/util/log.newLogScope.func1()
      github.com/cockroachdb/cockroach/pkg/util/log/test_log_scope.go:165 +0x319
  github.com/cockroachdb/cockroach/pkg/util/log.newLogScope()
      github.com/cockroachdb/cockroach/pkg/util/log/test_log_scope.go:172 +0x82e
  github.com/cockroachdb/cockroach/pkg/util/log.ScopeWithoutShowLogs()
      github.com/cockroachdb/cockroach/pkg/util/log/test_log_scope.go:101 +0x45
  github.com/cockroachdb/cockroach/pkg/util/log.TestFileSeverityFilter()
      github.com/cockroachdb/cockroach/pkg/util/log/clog_test.go:647 +0x7b
  testing.tRunner()
      GOROOT/src/testing/testing.go:1689 +0x21e
  testing.(*T).Run.gowrap1()
      GOROOT/src/testing/testing.go:1742 +0x44
==================
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=1</code>
 - <code>shard=1</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #121548 util/log: TestLogEntryPropagation failed [A-observability-inf C-test-failure O-robot P-3 T-observability branch-release-24.1]
</p>
</details>
/cc @cockroachdb/obs-prs
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLogEntryPropagation.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-38069

### PR DESCRIPTION
**Pull request by abarganier**
Fixes: https://github.com/cockroachdb/cockroach/issues/122791

TestLogEntryPropagation was unsafely reassigning `OrigStderr` in the log
package which was tripping the race detector.

This patch makes use of the existing `redirectStderr` function which
allows us to safely reassign stderr.

Release note: none

### CODE REVIEW

File: pkg/util/log/stderr_redirect.go [hunk 1]
```diff
@@ -12,26 +12,86 @@ package log
...
+// SwapFile atomically swaps out the underlying file wrapped by this
+// ThreadSafeStderr
+func (t *ThreadSafeStderr) SwapFile(file *os.File) {
+	t.mu.Lock()
+	defer t.mu.Unlock()
+	t.mu.file = file
+}
+
+// File returns a reference to the underlying file. Generally, this is
+// only useful if you're about to call SwapFile, and you want to hold onto
```
Comment (xinhaoz) [inline pkg/util/log/stderr_redirect.go:70]: Why not make `SwapFile` return the old file? Then we don't need this fn.

**Review by xinhaoz — COMMENTED** [review]
Are we unable to use https://github.com/cockroachdb/cockroach/blob/2f9f3d686e76cf3a106dd4cf5e70c48fc60ef97b/pkg/util/log/stderr_redirect.go#L47 or export this fn, https://github.com/cockroachdb/cockroach/blob/2f9f3d686e76cf3a106dd4cf5e70c48fc60ef97b/pkg/util/log/stderr_redirect.go#L41 in the tests to accomplish this?

Looks like there are thread safe utils in the log pkg for this already, but not sure if we want to export them.

**Review by abarganier — COMMENTED** [review]
> Are we unable to use

I was looking at this mutex and `hijackStderr` as well, but I believe their purpose is to safely reassign `os.Stderr`, whereas the work done here is to ensure proper reassignment of `log.OrigStderr`. LMK if I'm missing something - this `hijackStderr` stuff isn't something I've dealt with prior to this PR. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124219#-:-NyQcSvh58aTM84wGJf6:b-d12rq7)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kyle-a-wong and @xinhaoz)

___
*[`pkg/util/log/stderr_redirect.go` line 70 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124219#gh-1607347379:-NyQcRfN92czqtgOtmh6:b1iebdp) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e510b5f2c6eefdd766843d5e516f6d65bcd0334/pkg/util/log/stderr_redirect.go#L70)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Why not make `SwapFile` return the old file? Then we don't need this fn.
</blockquote></details>

Good idea, done.

**Review by abarganier — COMMENTED** [review]
Hold off on reviewing, I'm going to take another look based on our discussion at standup today.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124219#-:-NyQojbN0rJLFRUD8zQR:b-q2wuk6)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kyle-a-wong and @xinhaoz)

**Review by xinhaoz — APPROVED** [review]
Nice! Thank you for the changes 👍

**Comment by dhartunian** [comment]
bors r=xinhaoz
