### PR TITLE
sql/driver: break dependency on util/log

### LINKED ISSUE #2683: Transitive dependency issue with the log package.
The transitive dependency on github.com/cockroachdb/cockroach/util/log breaks use of the SQL driver in grpc-based application stacks, this is a pretty bad experience. I realise that this is an alpha, however because of thie transitive dependency, you'll get a runtime panic of "logtostderr is already defined" from the flag package.

I can try and whip up a simple example, but any code that happens to also depend on the original glog code will also fail to work.

### PR DESCRIPTION
**Pull request by tamird**
Fixes #2683.

It ain't pretty, but not as bad as it could have been.

### CODE REVIEW

File: sql/driver/flags_test.go [hunk 1]
```diff
@@ -0,0 +1,65 @@
+// Copyright 2015 The Cockroach Authors.
```
Comment (petermattis) [inline sql/driver/flags_test.go]: Why the name `flags_test.go`? Looks to me like this is a test of imports.

Comment (tamird) [inline sql/driver/flags_test.go]: yeah, should be link_test, will rename

File: base/context.go [hunk 2]
```diff
@@ -113,18 +113,14 @@ func (ctx *Context) GetClientTLSConfig() (*tls.Config, error) {
 	}
 
 	if ctx.Certs != "" {
-		if log.V(1) {
-			log.Infof("setting up TLS from certificates directory: %s", ctx.Certs)
-		}
+		log.Printf("setting up TLS from certificates directory: %s\n", ctx.Certs)
```
Comment (petermattis) [inline base/context.go]: Rather than changing the `base` package, I wonder if it would be better to remove the dependency on `base` from `sql/driver`. The only thing `sql/driver` is using from `base` is `base.Context`. And the only method on `base.Context` is `GetHTTPClient`.

Comment (tamird) [inline base/context.go]: Not quite; take a look at sql/driver/sender.go

Comment (petermattis) [inline base/context.go]: Took a look. Didn't see anything of note. Probably just too tired. Can you be more explicit?

Comment (tamird) [inline base/context.go]: we use `Context.User` and `Context.HTTPRequestScheme()` in addition to `GetHTTPClient`

Comment (tamird) [inline base/context.go]: The former is probably removable, though.

Comment (petermattis) [inline base/context.go]: So is the latter:

```
func (ctx *Context) HTTPRequestScheme() string {
	if ctx.Insecure {
		return httpScheme
	}
	return httpsScheme
}
```

File: cli/flags_test.go [hunk 3]
```diff
@@ -56,7 +56,7 @@ func TestNoLinkTesting(t *testing.T) {
 		}
 
 		for _, imp := range pkg.Imports {
-			// https: //github.com/golang/tools/blob/master/refactor/importgraph/graph.go#L115
+			// https://github.com/golang/tools/blob/master/refactor/importgraph/graph.go#L115
```
Comment (bdarnell) [inline cli/flags_test.go]: Ah, I thought this code looked familiar but I grepped for the wrong name. We should put both forbidden-import tests in the same place (`testutil`?)` instead of duplicating this code.

Comment (tamird) [inline cli/flags_test.go]: Let me do that after this or #2688 lands so I don't have to keep updating both PRs

File: base/context.go [hunk 4]
```diff
@@ -113,18 +113,14 @@ func (ctx *Context) GetClientTLSConfig() (*tls.Config, error) {
 	}
 
 	if ctx.Certs != "" {
-		if log.V(1) {
```
Comment (bdarnell) [inline base/context.go]: Upgrading these from `V(1)` to default will be irritating. It might be better to remove them than to promote them.

File: base/context.go (hunk 2 above)
Comment (bdarnell) [inline base/context.go]: Is `base` also our only route to the `security` package? We should definitely try to cut off dependencies when we can instead of modifying them.

File: base/context.go (hunk 4 above)
Comment (tamird) [inline base/context.go]: removed the "everything's cool" logs, kept the others

File: cli/flags_test.go (hunk 3 above)
Comment (tamird) [inline cli/flags_test.go]: brought that refactor this PR

**Comment by tschottdorf** [comment]
LGTM after any open comments.

**Comment by bdarnell** [comment]
LGTM
