### PR TITLE
*: de-flake TestPaginatedBackupTenant and remove data race

### LINKED ISSUE #74932: importccl: TestCSVImportCanBeResumed failed under testrace
Example build: https://teamcity.cockroachdb.com/viewLog.html?buildId=4140135&buildTypeId=Cockroach_UnitTests

DATA RACE:
```
Write at 0x00c00128b340 by goroutine 232:
  github.com/google/btree.(*items).insertAt()
      /go/src/github.com/cockroachdb/cockroach/vendor/github.com/google/btree/btree.go:148 +0x28a
  github.com/google/btree.(*node).insert()
      /go/src/github.com/cockroachdb/cockroach/vendor/github.com/google/btree/btree.go:316 +0x1d8
  github.com/google/btree.(*BTree).ReplaceOrInsert()
      /go/src/github.com/cockroachdb/cockroach/vendor/github.com/google/btree/btree.go:702 +0x5fc
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*storeReplicaBTree).ReplaceOrInsertReplica()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/store_replica_btree.go:182 +0x44
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).addReplicaInternalLocked()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/store_create_replica.go:271 +0x20e
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).SplitRange()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/store_split.go:312 +0x4ea
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.splitPostApply()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/store_split.go:149 +0xd5
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleSplitResult()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_application_result.go:245 +0x917
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaStateMachine).handleNonTrivialReplicatedEvalResult()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_application_state_machine.go:1245 +0x847
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaStateMachine).ApplySideEffects()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_application_state_machine.go:1127 +0x81c
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.StateMachine.ApplySideEffects-fm()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/task.go:55 +0x85
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.mapCheckedCmdIter()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/cmd.go:206 +0x1f0
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.(*Task).applyOneBatch()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/task.go:291 +0x277
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.(*Task).ApplyCommittedEntries()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/task.go:247 +0xd2
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_raft.go:870 +0x1d3d
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReady()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_raft.go:511 +0x14f
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processReady()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/store_raft.go:507 +0x17b
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).worker()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/scheduler.go:305 +0x2e1
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).worker-fm()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/scheduler.go:250 +0x4d
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:488 +0x228

Previous read at 0x00c00128b340 by goroutine 77:
  github.com/google/btree.(*node).iterate()
      /go/src/github.com/cockroachdb/cockroach/vendor/github.com/google/btree/btree.go:510 +0x1e9
  github.com/google/btree.(*BTree).AscendRange()
      /go/src/github.com/cockroachdb/cockroach/vendor/github.com/google/btree/btree.go:750 +0x1a8
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*storeReplicaBTree).ascendRange()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/store_replica_btree.go:225 +0x2e
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*storeReplicaBTree).VisitKeyRange()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/store_replica_btree.go:142 +0x264
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).onSpanConfigUpdate()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/store.go:2339 +0x411
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).Start.func4()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/store.go:1950 +0xe4
  github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigkvsubscriber.(*handler).invoke()
      /go/src/github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigkvsubscriber/kvsubscriber.go:441 +0x12d
  github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigkvsubscriber.(*KVSubscriber).run()
      /go/src/github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigkvsubscriber/kvsubscriber.go:377 +0x170e
  github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigkvsubscriber.(*KVSubscriber).Start.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigkvsubscriber/kvsubscriber.go:185 +0x2a4
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:488 +0x228
```

### PR DESCRIPTION
**Pull request by irfansharif**
See individual commits; this PR squashes a data race in KV among other things.

---

This test readily fails under stress with span configs enabled (#73876).
Now that we split within the tenant keyspace for tenant tables, the
export requests generated for each BACKUP is liable to be retried if
concurrent with range splits. The splits causes KV to error out with
RangeKeyMismatchErrors, at which point the request is internally
retried. The test, which wants to assert on what ExportSpan requests are
intercepted, previously did not need to consider these retries/need to
de-dup -- it now does.

Release note: None

### CODE REVIEW

File: pkg/ccl/backupccl/backup_test.go [hunk 1]
```diff
@@ -6816,10 +6818,12 @@ func TestPaginatedBackupTenant(t *testing.T) {
...
 					!isLeasingExportRequest(exportRequest) {
-					exportRequestSpans = append(
-						exportRequestSpans,
-						requestSpanStr(roachpb.Span{Key: exportRequest.Key, EndKey: exportRequest.EndKey}, exportRequest.ResumeKeyTS),
-					)
+					req := requestSpanStr(roachpb.Span{Key: exportRequest.Key, EndKey: exportRequest.EndKey}, exportRequest.ResumeKeyTS)
+					if _, found := exportRequestSpansSet[req]; found {
+						return nil // nothing to do
+					}
+					exportRequestSpansSet[req] = struct{}{}
```
Comment (tbg) [inline pkg/ccl/backupccl/backup_test.go:6825]: Doesn't this want a mutex? Even if we "know" that there are no concurrent SSTs in this test, it would be better not to put in this assumption.

File: pkg/kv/kvserver/store.go [hunk 2]
```diff
@@ -2336,6 +2336,9 @@ func (s *Store) onSpanConfigUpdate(ctx context.Context, updated roachpb.Span) {
 	}
 
 	now := s.cfg.Clock.NowAsClockTimestamp()
+
+	s.mu.RLock()
```
Comment (tbg) [inline pkg/kv/kvserver/store.go:2340]: Aha!

File: pkg/server/status_test.go [hunk 3]
```diff
@@ -1478,6 +1478,7 @@ func TestStatusAPICombinedTransactions(t *testing.T) {
 	defer log.Scope(t).Close(t)
 
 	params, _ := tests.CreateTestServerParams()
+	params.Knobs.SpanConfig = &spanconfig.TestingKnobs{ManagerDisableJobCreation: true} // TODO(irfansharif): #74919.
```
Comment (tbg) [inline pkg/server/status_test.go:1481]: Not sure if this is supposed to be merged?

File: pkg/ccl/backupccl/backup_test.go (hunk 1 above)
Comment (irfansharif) [reply pkg/ccl/backupccl/backup_test.go]: Done.

File: pkg/server/status_test.go (hunk 3 above)
Comment (irfansharif) [reply pkg/server/status_test.go:1481]: It is, yes. Investigating https://github.com/cockroachdb/cockroach/issues/74919 separately.

**Review by tbg — APPROVED** [review]
The "sqush race" commit needs to be backed out.

**Review by arulajmani — APPROVED** [review]
> Reviewed 3 of 3 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74926)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, @irfansharif, @nvanbenschoten, and @tbg)
