### PR TITLE
cli: fix demo --global latencies

### LINKED ISSUE #62542: demo: global simulated latency does not work with bi-directional streams
I haven't gotten to the root cause of this, but something is wrong with the simulated latency of Raft in `demo --global`. As we can see below, the 130ms for a write is about double what we expect.

```
> ./cockroach demo --nodes=9 --global --empty

demo@127.0.0.1:26257/defaultdb> create table kv (k int primary key, v int);
CREATE TABLE

Time: 5ms total (execution 5ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> show ranges from table kv;
  start_key | end_key | range_id | range_size_mb | lease_holder | lease_holder_locality | replicas |                             replica_localities
------------+---------+----------+---------------+--------------+-----------------------+----------+-----------------------------------------------------------------------------
  NULL      | NULL    |       37 |             0 |            1 | region=us-east1,az=b  | {1,3,8}  | {"region=us-east1,az=b","region=us-west1,az=a","region=europe-west1,az=d"}
(1 row)

Time: 337ms total (execution 337ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> insert into kv values (1, 2);
INSERT 1

Time: 130ms total (execution 130ms / network 0ms)
```

We see from traces that this time is all spent in Raft. My current guess is that Raft's approach to establish a separate gRPC stream in each direction and send requests and responses on the "sender" side of each stream is tripping up the `delayingConn`. Maybe it expects requests and responses to be matched up more closely, as they are in a unary RPC. Or maybe the streams are causing issues because artificial delays aren't being pipelined properly across multiple requests in the same direction. I'm not sure, but something is going wrong here.

I suspect this is also contributing to the issues we've seen with DistSQL flow setup in https://cockroachlabs.slack.com/archives/CJGSARZJR/p1616188441010400.

cc. @ajstorm. Given our desire to use `demo --global` more, do you view this as a GA-blocker?

### PR DESCRIPTION
**Pull request by jordanlewis**
Fixes #62542

Previously, the --global flag to demo had some inconsistent behavior:
some of the time, the actual "global" latencies were double what we
would expect. The reason for this was that we were accidentally only
introducing a delay on one of the sides of the connection, some of the
time.

The fix was to change a method to use a pointer receiver :)

Release note (cli change): fix the artificial latencies introduced by
the --global flag to demo.

### CODE REVIEW

File: pkg/rpc/context.go [hunk 1]
```diff
@@ -901,11 +911,9 @@ func (d delayingConn) Read(b []byte) (n int, err error) {
 		// If we somehow don't get our expected magic, throw an error.
 		if hdr.Magic != magic {
 			panic(errors.New("didn't get expected magic bytes header"))
-			// TODO (rohany): I can't get this to work. I suspect that the problem
```
Comment (otan) [inline pkg/rpc/context.go:904]: i was confused about this TODO. I hit it easily when I do `\demo shutdown <node>`

**Review by otan — APPROVED** [review]

File: pkg/rpc/context.go (hunk 1 above)
Comment (jordanlewis) [reply pkg/rpc/context.go:904]: The TODO was about the thing below. You're right that shutdown is broken... we can fix that separately.
