### PR TITLE
kvserver: estimate AddSStable stats if ComputeStatsDiff assuptions violated

### LINKED ISSUE #151979: roachtest: c2c/initialscan/kv0 failed
roachtest.c2c/initialscan/kv0 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20352447?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20352447?buildTab=artifacts#/c2c/initialscan/kv0) on master @ [8f5ae52a8f9a419efd0c4ab26464ff9b265ad1f3](https://github.com/cockroachdb/cockroach/commits/8f5ae52a8f9a419efd0c4ab26464ff9b265ad1f3):

```
(soon.go:60).SucceedsWithin: condition failed to evaluate within 30m0s: from cluster_to_cluster.go:2039: no replicated time
(monitor.go:267).Wait: monitor failure: monitor user task failed: t.Fatal() was called
test artifacts and logs in: /artifacts/c2c/initialscan/kv0/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=8</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=false</code>
 - <code>metamorphicLeases=expiration</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20352447/c2c-initialscan-kv0/1755332956090/1755335425009)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*c2c/initialscan/kv0.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-53565

### PR DESCRIPTION
**Pull request by msbutler**
Previously the request would fail-- now we internally retry the stats computation with estimates. We should further investigate why the ComputeStatsDiff assumptions are violated in the c2c/kv0 test though.

Fixes #151979
Release note: none

### CODE REVIEW

File: pkg/kv/kvserver/batcheval/cmd_add_sstable.go [hunk 1]
```diff
@@ -474,12 +474,11 @@ func computeSSTStatsDiffWithFallback(
 ) (enginepb.MVCCStats, error) {
 	stats, err := storage.ComputeSSTStatsDiff(
 		ctx, sst, readWriter, nowNanos, start, end)
-	if errors.Is(err, storage.ComputeSSTStatsDiffReaderHasRangeKeys) {
-		// Fall back to stats estimates if there are range keys in the engine.
-		log.VEventf(ctx, 2, "computing SST stats as estimates after detecting range keys in engine")
+	if errors.IsAny(err, storage.ComputeSSTStatsDiffReaderHasRangeKeys, storage.ComputeStatsDiffViolation) {
+		log.Infof(ctx, "computing SST stats as estimates because of ComputeSSTStatsDiff error: %s", err)
```
Comment (jeffswenson) [inline pkg/kv/kvserver/batcheval/cmd_add_sstable.go]: This is probably rare enough we could make it a warning.

**Review by jeffswenson — APPROVED** [review]
LGTM

File: pkg/kv/kvserver/batcheval/cmd_add_sstable.go (hunk 1 above)
Comment (msbutler) [reply pkg/kv/kvserver/batcheval/cmd_add_sstable.go]: Done.

**Comment by msbutler** [comment]
TFTR!

bors r=jeffswenson
