### PR TITLE
importer: support {} format for arrays in CSV

### LINKED ISSUE #84631: CockroachDB Serverless: IMPORT INTO using CSV with array-column fails with syntax error
**Describe the problem**

I'm trying to import CSV Data from a postgres export made using the following command:
```
psql --no-password -c "\COPY $table_name TO STDOUT WITH NULL AS 'SQLNULL' CSV HEADER FORCE QUOTE *" > "$PG_BACKUP_PATH/tables/$table_name.csv"
```

I'm using the following command from a SQL console to import the data to Cockroach Serverless:
```
IMPORT INTO gw2_api_tokens (account_id, gw2_account_id, creation_time, gw2_api_token, gw2_api_permissions, display_name, last_valid_check_time, is_valid)
    CSV DATA ( 's3 presigned url' )
WITH skip = '1' ;
```

The column `gw2_api_permissions` is a `STRING[]`.

When executing the above command, I see the following error:
```
[XXUUU] ERROR: <s3 presigned url>: error parsing row 2: parse "gw2_api_permissions" as STRING[]: at or near "{": syntax error (row: <uuid>,<uuid>,<timestamp>,<token>,{somevalue,anothervalue,anothervalue123},SomeName,<timestamp>,t)
```

The CSV I'm trying to import is fully quoted using `"`. The column `gw2_api_permissions` in the source CSV looks like this:
```
"{somevalue,anothervalue,anothervalue123}"
```

The issue also happens when using `DELIMITED DATA`:
```
IMPORT INTO gw2_api_tokens (account_id, gw2_account_id, creation_time, gw2_api_token, gw2_api_permissions, display_name, last_valid_check_time, is_valid)
    DELIMITED DATA ( s3 presigned url' )
WITH skip = '1', fields_terminated_by = ',', fields_enclosed_by = '"', fields_escaped_by = '\' ;
```

**To Reproduce**

Table creation script:
```sql
CREATE TABLE test (
    id UUID NOT NULL,
    values TEXT[] NOT NULL,
    PRIMARY KEY (id)
) ;
```

Dummy csv:
```csv
"id","values"
"cebd93ac-d9df-4952-ad3f-e1571b67fbb3","{somevalue,anothervalue,anothervalue123}"
```

1. Set up a fresh CockroachDB Serverless Cluster
2. Create the table above in the newly created CockroachDB Serverless Cluster
3. Import the CSV above using `IMPORT INTO test (id, values) CSV DATA ( 'csvurl' ) WITH skip = '1' ;`

**Expected behavior**
The data import should work

**Additional data / screenshots**
N/A

**Environment:**
 - CockroachDB Version: 22.1.1 (Serverless)
 - Client app: IntelliJ Query Console (JDBC)

**Additional context**
For the migration from a self-hosted postgres database to CockroachDB Serverless I'm planning to have a new node of my application running (disconnected from the LB at that time), but connected to CockroachDB Serverless. This application will create the schema on startup, without data.

I was planning to then create a dump of my postgres tables as CSV, import by running a script that creates presigned URLs for the CSVs stored in S3 and then switch the LB to use the new, already running node which is already connected to CockroachDB Serverless.

An alternative approach would be to create a full export (including the schema) using `pg_dump` and import the whole database using `IMPORT PGDUMP`. I decided not to take this approach for the following reasons:
- Without major refactoring of my application, I wouldn't be able to start a node without an existing schema
- The sql produced by `pg_dump` contains expression indexes `md5(column)` which are not yet supported by `IMPORT PGDUMP`

Jira issue: CRDB-17768
Epic CRDB-14049

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/84631

Release note (sql change): Arrays can now be imported in a CSV file
using the {} format, similar to COPY FROM. Importing array expressions
(e.g. ARRAY[1, 2, 3]) is still supported as well.

### CODE REVIEW

File: pkg/sql/importer/read_import_csv.go [hunk 1]
```diff
@@ -221,11 +221,18 @@ func (c *csvRowConsumer) FillDatums(
...
-				col := conv.VisibleCols[i]
-				return newImportRowError(
-					errors.Wrapf(err, "parse %q as %s", col.GetName(), col.GetType().SQLString()),
-					strRecord(record, c.opts.Comma),
-					rowNum)
+				// Fallback to parsing as a string literal. This allows us to support
+				// both array expressions (like `ARRAY[1, 2, 3]`) and literals (like
+				// `{1, 2, 3}`).
+				var err2 error
+				conv.Datums[datumIdx], _, err2 = tree.ParseAndRequireString(conv.VisibleColTypes[i], field.Val, conv.EvalCtx)
```
Comment (ecwall) [inline pkg/sql/importer/read_import_csv.go:228]: It is probably outside the scope of this change, but is there a grammar that a parser can be generated from?

**Review by ecwall — APPROVED** [review]

File: pkg/sql/importer/read_import_csv.go (hunk 1 above)
Comment (rafiss) [reply pkg/sql/importer/read_import_csv.go:228]: you mean to avoid the fallback logic? it won't be that easy -- the difference between these two formats is that one is an expression (e.g. `ARRAY[1, 2, 3 ...]`) but the other is the format that arrays represented as string literals use (e.g. in `{1, 2, 3 ... }::INT[]`). The string literal format isn't (and i think shouldn't) be represented in our sql.y file, but it's handled in pkg/sql/sem/tree/parse_array.go

**Comment by rafiss** [comment]
tftr!

bors r=ecwall
