### PR TITLE
kvfeed: fix writer being closed with wrong error when drain fails

### LINKED ISSUE #139805: ccl/changefeedccl: TestSchemachangeDoesNotBreakSinklessFeed failed
ccl/changefeedccl.TestSchemachangeDoesNotBreakSinklessFeed [failed](https://tanzanite.cluster.engflow.com/invocations/default/bc3a5ff8-2bb0-4df7-8040-56a3ef576797?testReportRun=3&testReportShard=16&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on master @ [49e62ff4c0215218fbfc12c2ab3cf3429f0315a3](https://github.com/cockroachdb/cockroach/commits/49e62ff4c0215218fbfc12c2ab3cf3429f0315a3):

```
test logs left over in: outputs.zip/logTestSchemachangeDoesNotBreakSinklessFeed2617045424
--- FAIL: TestSchemachangeDoesNotBreakSinklessFeed (19.44s)
=== RUN   TestSchemachangeDoesNotBreakSinklessFeed/sinkless
    helpers_test.go:883: making server as secondary tenant
    helpers_test.go:962: making sinkless feed factory
    helpers_test.go:1027: pgURL sinkless SinklessFeedUser
    helpers_test.go:1027: pgURL sinkless root
    testfeed_test.go:271: sinkless feed creating changefeed: CREATE CHANGEFEED FOR TABLE mytable
    changefeed_test.go:9028: 
        	Error Trace:	pkg/ccl/changefeedccl/helpers_test.go:198
        	            				pkg/ccl/changefeedccl/helpers_test.go:273
        	            				pkg/ccl/changefeedccl/changefeed_test.go:9028
        	            				pkg/ccl/changefeedccl/helpers_test.go:1134
        	            				pkg/ccl/changefeedccl/helpers_test.go:1169
        	Error:      	Received unexpected error:
        	            	expected message
        	            	(1) assertion failure
        	            	Wraps: (2) attached stack trace
        	            	  -- stack trace:
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.readNextMessages
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:118
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.assertPayloadsBaseErr
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:209
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.assertPayloadsBase.func1
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:201
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.withTimeout.func1
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:266
        	            	  | github.com/cockroachdb/cockroach/pkg/util/timeutil.RunWithTimeout
        	            	  | 	pkg/util/timeutil/timeout.go:28
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.withTimeout
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:262
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.assertPayloadsBase
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:199
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.assertPayloads
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:273
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.TestSchemachangeDoesNotBreakSinklessFeed.func1
        	            	  | 	pkg/ccl/changefeedccl/changefeed_test.go:9028
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.cdcTestNamed.func1
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:1134
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.cdcTestNamedWithSystem.func1
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:1169
        	            	  | testing.tRunner
        	            	  | 	GOROOT/src/testing/testing.go:1689
        	            	  | runtime.goexit
        	            	  | 	src/runtime/asm_amd64.s:1695
        	            	Wraps: (3) expected message
        	            	Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.leafError
        	Test:       	TestSchemachangeDoesNotBreakSinklessFeed/sinkless
    testfeed_test.go:278: closing sinkless feed
    --- FAIL: TestSchemachangeDoesNotBreakSinklessFeed/sinkless (19.43s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>deadlock=true</code>
 - <code>run=3</code>
 - <code>shard=16</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestSchemachangeDoesNotBreakSinklessFeed.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-46823

### LINKED ISSUE #140669: ccl/changefeedccl: TestChangefeedEachColumnFamilySchemaChanges failed
ccl/changefeedccl.TestChangefeedEachColumnFamilySchemaChanges [failed](https://tanzanite.cluster.engflow.com/invocations/default/07ece540-3062-492e-8a5d-b92ed065cc1f?testReportRun=1&testReportShard=6&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on release-25.1.0-rc @ [839543761f65547a48b78c10af993545590bded5](https://github.com/cockroachdb/cockroach/commits/839543761f65547a48b78c10af993545590bded5):

```
test logs left over in: outputs.zip/logTestChangefeedEachColumnFamilySchemaChanges2336678610
--- FAIL: TestChangefeedEachColumnFamilySchemaChanges (19.44s)
=== RUN   TestChangefeedEachColumnFamilySchemaChanges/sinkless
    helpers_test.go:883: making server as secondary tenant
    helpers_test.go:962: making sinkless feed factory
    helpers_test.go:1027: pgURL sinkless SinklessFeedUser
    helpers_test.go:1027: pgURL sinkless root
    testfeed_test.go:270: sinkless feed creating changefeed: CREATE CHANGEFEED FOR foo WITH split_column_families
    changefeed_test.go:3366: 
        	Error Trace:	pkg/ccl/changefeedccl/helpers_test.go:198
        	            				pkg/ccl/changefeedccl/helpers_test.go:273
        	            				pkg/ccl/changefeedccl/changefeed_test.go:3366
        	            				pkg/ccl/changefeedccl/helpers_test.go:1134
        	            				pkg/ccl/changefeedccl/helpers_test.go:1169
        	Error:      	Received unexpected error:
        	            	expected message
        	            	(1) assertion failure
        	            	Wraps: (2) attached stack trace
        	            	  -- stack trace:
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.readNextMessages
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:118
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.assertPayloadsBaseErr
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:209
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.assertPayloadsBase.func1
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:201
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.withTimeout.func1
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:266
        	            	  | github.com/cockroachdb/cockroach/pkg/util/timeutil.RunWithTimeout
        	            	  | 	pkg/util/timeutil/timeout.go:28
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.withTimeout
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:262
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.assertPayloadsBase
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:199
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.assertPayloads
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:273
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.TestChangefeedEachColumnFamilySchemaChanges.func1
        	            	  | 	pkg/ccl/changefeedccl/changefeed_test.go:3366
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.cdcTestNamed.func1
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:1134
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.cdcTestNamedWithSystem.func1
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:1169
        	            	  | testing.tRunner
        	            	  | 	GOROOT/src/testing/testing.go:1689
        	            	  | runtime.goexit
        	            	  | 	src/runtime/asm_amd64.s:1695
        	            	Wraps: (3) expected message
        	            	Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.leafError
        	Test:       	TestChangefeedEachColumnFamilySchemaChanges/sinkless
    testfeed_test.go:277: closing sinkless feed
    --- FAIL: TestChangefeedEachColumnFamilySchemaChanges/sinkless (19.44s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>deadlock=true</code>
 - <code>run=1</code>
 - <code>shard=6</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestChangefeedEachColumnFamilySchemaChanges.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-47289

### LINKED ISSUE #141453: changefeedccl: potential race in how kv feed schema change errors are handled
When a schema change happens, the kv feed sends a sentinel error in two ways:
* https://github.com/cockroachdb/cockroach/blob/fda253ea2114f59611d8b70666946ae4c9db6c12/pkg/ccl/changefeedccl/kvfeed/kv_feed.go#L179
* https://github.com/cockroachdb/cockroach/blob/fda253ea2114f59611d8b70666946ae4c9db6c12/pkg/ccl/changefeedccl/kvfeed/kv_feed.go#L188

This error is processed slightly differently depending on which if clause in `*changeAggregator.Next` is hit first:
https://github.com/cockroachdb/cockroach/blob/fda253ea2114f59611d8b70666946ae4c9db6c12/pkg/ccl/changefeedccl/changefeed_processors.go#L747-L759

It seems like this race was introduced in https://github.com/cockroachdb/cockroach/commit/9143d8c33137d4c640819c3270744437027aef31.

We think this may explain the test failures we've been seeing like https://github.com/cockroachdb/cockroach/issues/140669.

Jira issue: CRDB-47830

### LINKED ISSUE #142181: ccl/changefeedccl: TestChangefeedSchemaChangeAllowBackfill failed
ccl/changefeedccl.TestChangefeedSchemaChangeAllowBackfill [failed](https://tanzanite.cluster.engflow.com/invocations/default/bf189846-64a3-4d3b-9501-618660efb735?testReportRun=3&testReportShard=14&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on master @ [e527f6b34c009ed7b52777e854687fb5d6ce3378](https://github.com/cockroachdb/cockroach/commits/e527f6b34c009ed7b52777e854687fb5d6ce3378):

```
=== RUN   TestChangefeedSchemaChangeAllowBackfill/sinkless
    helpers_test.go:945: making server as secondary tenant
    helpers_test.go:1024: making sinkless feed factory
    helpers_test.go:1089: pgURL sinkless SinklessFeedUser
    helpers_test.go:1089: pgURL sinkless root
    testfeed_test.go:271: sinkless feed creating changefeed: CREATE CHANGEFEED FOR add_column_def WITH updated
    testfeed_test.go:278: closing sinkless feed
    testfeed_test.go:271: sinkless feed creating changefeed: CREATE CHANGEFEED FOR add_col_comp WITH updated
    testfeed_test.go:278: closing sinkless feed
    testfeed_test.go:271: sinkless feed creating changefeed: CREATE CHANGEFEED FOR drop_column WITH updated
    testfeed_test.go:278: closing sinkless feed
    testfeed_test.go:271: sinkless feed creating changefeed: CREATE CHANGEFEED FOR multiple_alters WITH updated
    testfeed_test.go:278: closing sinkless feed
    --- FAIL: TestChangefeedSchemaChangeAllowBackfill/sinkless (37.64s)
=== RUN   TestChangefeedSchemaChangeAllowBackfill/sinkless/add_column_with_default
    changefeed_test.go:2963: 
        	Error Trace:	pkg/ccl/changefeedccl/helpers_test.go:220
        	            				pkg/ccl/changefeedccl/helpers_test.go:300
        	            				pkg/ccl/changefeedccl/changefeed_test.go:2963
        	Error:      	Received unexpected error:
        	            	expected message
        	            	(1) assertion failure
        	            	Wraps: (2) attached stack trace
        	            	  -- stack trace:
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.readNextMessages
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:119
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.assertPayloadsBaseErr
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:236
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.assertPayloadsBase.func1
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:223
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.withTimeout.func1
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:293
        	            	  | github.com/cockroachdb/cockroach/pkg/util/timeutil.RunWithTimeout
        	            	  | 	pkg/util/timeutil/timeout.go:28
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.withTimeout
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:289
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.assertPayloadsBase
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:221
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.assertPayloads
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:300
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.TestChangefeedSchemaChangeAllowBackfill.func1.1
        	            	  | 	pkg/ccl/changefeedccl/changefeed_test.go:2963
        	            	  | testing.tRunner
        	            	  | 	GOROOT/src/testing/testing.go:1690
        	            	  | runtime.goexit
        	            	  | 	src/runtime/asm_amd64.s:1700
        	            	Wraps: (3) expected message
        	            	Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.leafError
        	Test:       	TestChangefeedSchemaChangeAllowBackfill/sinkless/add_column_with_default
        --- FAIL: TestChangefeedSchemaChangeAllowBackfill/sinkless/add_column_with_default (8.19s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>deadlock=true</code>
 - <code>run=3</code>
 - <code>shard=14</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #141417 ccl/changefeedccl: TestChangefeedSchemaChangeAllowBackfill failed [A-cdc C-test-failure O-robot P-2 T-cdc X-duplicate branch-release-25.1]
- #139825 ccl/changefeedccl: TestChangefeedSchemaChangeAllowBackfill failed [A-cdc C-test-failure O-robot P-2 T-cdc branch-release-24.2.9-rc]
- #137273 ccl/changefeedccl: TestChangefeedSchemaChangeAllowBackfill failed [A-cdc C-test-failure O-robot P-2 T-cdc branch-release-24.3]
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestChangefeedSchemaChangeAllowBackfill.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-48203

### LINKED ISSUE #142326: ccl/changefeedccl: TestChangefeedEachColumnFamilySchemaChanges failed
ccl/changefeedccl.TestChangefeedEachColumnFamilySchemaChanges [failed](https://tanzanite.cluster.engflow.com/invocations/default/d5542db9-894f-48f5-8954-6bb4f7e4bed8?testReportRun=3&testReportShard=5&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on master @ [478d65a28755b45c2952cc755a0cc8ae466514a7](https://github.com/cockroachdb/cockroach/commits/478d65a28755b45c2952cc755a0cc8ae466514a7):

```
=== RUN   TestChangefeedEachColumnFamilySchemaChanges
    test_log_scope.go:165: test logs captured to: outputs.zip/logTestChangefeedEachColumnFamilySchemaChanges4155187007
    test_log_scope.go:76: use -show-logs to present logs inline
    changefeed_test.go:3417: -- test log scope end --
test logs left over in: outputs.zip/logTestChangefeedEachColumnFamilySchemaChanges4155187007
--- FAIL: TestChangefeedEachColumnFamilySchemaChanges (315.69s)
=== RUN   TestChangefeedEachColumnFamilySchemaChanges/kafka
    helpers_test.go:945: making server as secondary tenant
    helpers_test.go:1024: making kafka feed factory
    changefeed_test.go:3402: 
        	Error Trace:	pkg/ccl/changefeedccl/helpers_test.go:220
        	            				pkg/ccl/changefeedccl/helpers_test.go:300
        	            				pkg/ccl/changefeedccl/changefeed_test.go:3402
        	            				pkg/ccl/changefeedccl/helpers_test.go:1196
        	            				pkg/ccl/changefeedccl/helpers_test.go:1231
        	Error:      	Received unexpected error:
        	            	operation "withTimeout-1052208006830424065" timed out after 5m0s (given timeout 5m0s): operation "kafka.Next-1052208006830424065" timed out after 5m0s (given timeout 5m0s): context deadline exceeded
        	            	(1) operation "withTimeout-1052208006830424065" timed out after 5m0s (given timeout 5m0s)
        	            	Wraps: (2) operation "kafka.Next-1052208006830424065" timed out after 5m0s (given timeout 5m0s)
        	            	Wraps: (3) context deadline exceeded
        	            	Error types: (1) *timeutil.TimeoutError (2) *timeutil.TimeoutError (3) context.deadlineExceededError
        	Test:       	TestChangefeedEachColumnFamilySchemaChanges/kafka
    --- FAIL: TestChangefeedEachColumnFamilySchemaChanges/kafka (315.68s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=3</code>
 - <code>shard=5</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #142032 ccl/changefeedccl: TestChangefeedEachColumnFamilySchemaChanges failed [A-cdc C-test-failure O-robot P-2 T-cdc branch-release-24.2]
- #140669 ccl/changefeedccl: TestChangefeedEachColumnFamilySchemaChanges failed [A-cdc C-bug C-test-failure O-robot P-2 T-cdc branch-release-25.1.0-rc target-release-25.2.0]
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestChangefeedEachColumnFamilySchemaChanges.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-48276

### LINKED ISSUE #142719: ccl/changefeedccl: TestChangefeedSingleColumnFamilySchemaChanges failed
ccl/changefeedccl.TestChangefeedSingleColumnFamilySchemaChanges [failed](https://tanzanite.cluster.engflow.com/invocations/default/2526618f-035b-41a4-b36b-6321778c1b6f?testReportRun=3&testReportShard=4&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on master @ [e0e47286b08aadf23058825c7b339f19ce852b71](https://github.com/cockroachdb/cockroach/commits/e0e47286b08aadf23058825c7b339f19ce852b71):

```
=== RUN   TestChangefeedSingleColumnFamilySchemaChanges/sinkless
    helpers_test.go:1021: making server as secondary tenant
    helpers_test.go:1100: making sinkless feed factory
    helpers_test.go:1165: pgURL sinkless SinklessFeedUser
    helpers_test.go:1165: pgURL sinkless root
    testfeed_test.go:272: sinkless feed creating changefeed: CREATE CHANGEFEED FOR foo FAMILY most
    testfeed_test.go:272: sinkless feed creating changefeed: CREATE CHANGEFEED FOR foo FAMILY rest
    changefeed_test.go:3370: 
        	Error Trace:	pkg/ccl/changefeedccl/helpers_test.go:256
        	            				pkg/ccl/changefeedccl/helpers_test.go:344
        	            				pkg/ccl/changefeedccl/changefeed_test.go:3370
        	            				pkg/ccl/changefeedccl/helpers_test.go:1272
        	            				pkg/ccl/changefeedccl/helpers_test.go:1307
        	Error:      	Received unexpected error:
        	            	expected message
        	            	(1) assertion failure
        	            	Wraps: (2) attached stack trace
        	            	  -- stack trace:
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.readNextMessages
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:119
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.assertPayloadsBaseErr
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:273
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.assertPayloadsBase.func1
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:259
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.withTimeout.func1
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:337
        	            	  | github.com/cockroachdb/cockroach/pkg/util/timeutil.RunWithTimeout
        	            	  | 	pkg/util/timeutil/timeout.go:28
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.withTimeout
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:333
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.assertPayloadsBase
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:257
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.assertPayloads
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:344
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.TestChangefeedSingleColumnFamilySchemaChanges.func1
        	            	  | 	pkg/ccl/changefeedccl/changefeed_test.go:3370
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.cdcTestNamed.func1
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:1272
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.cdcTestNamedWithSystem.func1
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:1307
        	            	  | testing.tRunner
        	            	  | 	GOROOT/src/testing/testing.go:1690
        	            	  | runtime.goexit
        	            	  | 	src/runtime/asm_amd64.s:1700
        	            	Wraps: (3) expected message
        	            	Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.leafError
        	Test:       	TestChangefeedSingleColumnFamilySchemaChanges/sinkless
    testfeed_test.go:279: closing sinkless feed
    testfeed_test.go:279: closing sinkless feed
--- FAIL: TestChangefeedSingleColumnFamilySchemaChanges/sinkless (15.82s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>deadlock=true</code>
 - <code>run=3</code>
 - <code>shard=4</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestChangefeedSingleColumnFamilySchemaChanges.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-48483

### LINKED ISSUE #142811: ccl/changefeedccl: TestNoBackfillAfterNonTargetColumnDrop failed
ccl/changefeedccl.TestNoBackfillAfterNonTargetColumnDrop [failed](https://tanzanite.cluster.engflow.com/invocations/default/e6e361e5-57e0-48da-b9d8-3ab11474ea0a?testReportRun=2&testReportShard=6&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on master @ [540a0423c37e471e51012b325ec822c03ccb1067](https://github.com/cockroachdb/cockroach/commits/540a0423c37e471e51012b325ec822c03ccb1067):

```
=== RUN   TestNoBackfillAfterNonTargetColumnDrop
    test_log_scope.go:165: test logs captured to: outputs.zip/logTestNoBackfillAfterNonTargetColumnDrop12559171
    test_log_scope.go:76: use -show-logs to present logs inline
    changefeed_test.go:1933: -- test log scope end --
test logs left over in: outputs.zip/logTestNoBackfillAfterNonTargetColumnDrop12559171
--- FAIL: TestNoBackfillAfterNonTargetColumnDrop (315.60s)
=== RUN   TestNoBackfillAfterNonTargetColumnDrop/pulsar
    helpers_test.go:1030: making server as secondary tenant
    helpers_test.go:1109: making pulsar feed factory
    changefeed_test.go:1920: 
        	Error Trace:	pkg/ccl/changefeedccl/helpers_test.go:258
        	            				pkg/ccl/changefeedccl/helpers_test.go:353
        	            				pkg/ccl/changefeedccl/changefeed_test.go:1920
        	            				pkg/ccl/changefeedccl/helpers_test.go:1281
        	            				pkg/ccl/changefeedccl/helpers_test.go:1316
        	Error:      	Received unexpected error:
        	            	operation "withTimeout-1054459084146671617" timed out after 5m0.001s (given timeout 5m0s): operation "pulsar.Next-1054459084146671617" timed out after 5m0.001s (given timeout 5m0s): context deadline exceeded
        	            	(1) operation "withTimeout-1054459084146671617" timed out after 5m0.001s (given timeout 5m0s)
        	            	Wraps: (2) operation "pulsar.Next-1054459084146671617" timed out after 5m0.001s (given timeout 5m0s)
        	            	Wraps: (3) context deadline exceeded
        	            	Error types: (1) *timeutil.TimeoutError (2) *timeutil.TimeoutError (3) context.deadlineExceededError
        	Test:       	TestNoBackfillAfterNonTargetColumnDrop/pulsar
--- FAIL: TestNoBackfillAfterNonTargetColumnDrop/pulsar (315.59s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=2</code>
 - <code>shard=6</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #142118 ccl/changefeedccl: TestNoBackfillAfterNonTargetColumnDrop failed [A-cdc C-test-failure O-robot P-2 T-cdc branch-release-25.1.0-rc]
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestNoBackfillAfterNonTargetColumnDrop.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-48531

### LINKED ISSUE #143782: ccl/changefeedccl: TestNoStopAfterNonTargetAddColumnWithBackfill failed
ccl/changefeedccl.TestNoStopAfterNonTargetAddColumnWithBackfill [failed](https://tanzanite.cluster.engflow.com/invocations/default/9a4de5b2-fa51-44bc-ac4e-08231010e806?testReportRun=1&testReportShard=10&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on master @ [70cf5807022e3ec424ac25b747f2d68a78afcabc](https://github.com/cockroachdb/cockroach/commits/70cf5807022e3ec424ac25b747f2d68a78afcabc):

```
test logs left over in: outputs.zip/logTestNoStopAfterNonTargetAddColumnWithBackfill1724784341
--- FAIL: TestNoStopAfterNonTargetAddColumnWithBackfill (16.15s)
=== RUN   TestNoStopAfterNonTargetAddColumnWithBackfill/sinkless
    helpers_test.go:1031: making server as secondary tenant
    helpers_test.go:1110: making sinkless feed factory
    helpers_test.go:1175: pgURL sinkless SinklessFeedUser
    helpers_test.go:1175: pgURL sinkless root
    testfeed_test.go:291: sinkless feed creating changefeed: CREATE CHANGEFEED FOR TABLE hasfams FAMILY b_and_c WITH schema_change_policy='stop'
    changefeed_test.go:2091: 
        	Error Trace:	pkg/ccl/changefeedccl/helpers_test.go:259
        	            				pkg/ccl/changefeedccl/helpers_test.go:354
        	            				pkg/ccl/changefeedccl/changefeed_test.go:2091
        	            				pkg/ccl/changefeedccl/helpers_test.go:1282
        	            				pkg/ccl/changefeedccl/helpers_test.go:1317
        	Error:      	Received unexpected error:
        	            	expected message
        	            	(1) assertion failure
        	            	Wraps: (2) attached stack trace
        	            	  -- stack trace:
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.readNextMessages
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:122
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.assertPayloadsBaseErr
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:276
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.assertPayloadsBase.func1
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:262
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.withTimeout.func1
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:347
        	            	  | github.com/cockroachdb/cockroach/pkg/util/timeutil.RunWithTimeout
        	            	  | 	pkg/util/timeutil/timeout.go:28
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.withTimeout
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:343
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.assertPayloadsBase
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:260
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.assertPayloads
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:354
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.TestNoStopAfterNonTargetAddColumnWithBackfill.func1
        	            	  | 	pkg/ccl/changefeedccl/changefeed_test.go:2091
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.cdcTestNamed.func1
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:1282
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.cdcTestNamedWithSystem.func1
        	            	  | 	pkg/ccl/changefeedccl/helpers_test.go:1317
        	            	  | testing.tRunner
        	            	  | 	GOROOT/src/testing/testing.go:1690
        	            	  | runtime.goexit
        	            	  | 	src/runtime/asm_amd64.s:1700
        	            	Wraps: (3) expected message
        	            	Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.leafError
        	Test:       	TestNoStopAfterNonTargetAddColumnWithBackfill/sinkless
    testfeed_test.go:298: closing sinkless feed
--- FAIL: TestNoStopAfterNonTargetAddColumnWithBackfill/sinkless (16.14s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=1</code>
 - <code>shard=10</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #142028 ccl/changefeedccl: TestNoStopAfterNonTargetAddColumnWithBackfill failed [A-cdc C-test-failure O-robot P-2 T-cdc branch-release-25.1]
- #141891 ccl/changefeedccl: TestNoStopAfterNonTargetAddColumnWithBackfill failed [A-cdc C-test-failure O-robot P-2 T-cdc branch-release-24.2]
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestNoStopAfterNonTargetAddColumnWithBackfill.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-49034

### PR DESCRIPTION
**Pull request by andyyang890**
This patch fixes an issue where the kv feed's writer could be closed
with ErrNormalRestartReason even though draining failed, which could
lead to boundary resolved span messages quietly not being delivered.

Fixes #141453

Test failures on master:
Fixes #139805
Fixes #140669
Fixes #142181
Fixes #142326
Fixes #142719
Fixes #142811
Fixes #143782

Test failures on release branches (won't be fixed until PR is backported):
Informs #139825
Informs #140796
Informs #141128
Informs #141412
Informs #141355
Informs #141891
Informs #142028
Informs #142032
Informs #142118

Release note: None

### CODE REVIEW

File: pkg/ccl/changefeedccl/kvfeed/kv_feed.go [hunk 1]
```diff
@@ -172,18 +172,19 @@ func Run(ctx context.Context, cfg Config) error {
...
+	if err := f.writer.CloseWithReason(ctx, kvevent.ErrNormalRestartReason); err != nil {
+		return err
+	}
+
+	// This context is canceled by the change aggregator when it receives
+	// an error reading from the Writer that was closed above.
+	<-ctx.Done()
 
-	return err
+	return nil
```
Comment (asg0451) [inline pkg/ccl/changefeedccl/kvfeed/kv_feed.go:187]: return ctx.Err() ?

**Review by asg0451 — APPROVED** [review]
looks about like what we discussed. can you add a test if it's not too much trouble?

**Comment by andyyang890** [comment]
> can you add a test if it's not too much trouble?

Added some testing knobs to force the precise ordering that I suspect is the cause of all the weird changefeed shut down test flakes we've been seeing. I also ran it against the code without the kv feed code change and confirmed that I get the unexpected "expected message" error.

File: pkg/ccl/changefeedccl/helpers_test.go [hunk 2]
```diff
@@ -1629,3 +1631,68 @@ func checkSchema(actual []cdctest.TestFeedMessage) error {
...
+				if !regression141453 {
+					testFn(t, s, f)
+					return
+				}
+
+				knobs := s.TestingKnobs.
+					DistSQL.(*execinfra.TestingKnobs).
+					Changefeed.(*TestingKnobs)
+
+				// We only want to make drain fail once, otherwise the test will never
```
Comment (asg0451) [inline pkg/ccl/changefeedccl/helpers_test.go:1654]: nit: can you expand this comment to describe exactly what we're doing here? iirc it waits till an event is Added, then makes subsequent Pops block until Drain has finished

**Review by asg0451 — APPROVED** [review]

**Comment by andyyang890** [comment]
TFTR!

bors r=asg0451
