### PR TITLE
roachprod: add sufficient tenant ids when creating v22.2 client certs

### LINKED ISSUE #133282: roachtest: multitenant-upgrade failed
roachtest.multitenant-upgrade [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/17419844?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/17419844?buildTab=artifacts#/multitenant-upgrade) on release-24.3 @ [f4bf28879d49979d438967379b44c2fe3464f968](https://github.com/cockroachdb/cockroach/commits/f4bf28879d49979d438967379b44c2fe3464f968):

```
(mixedversion.go:732).Run: mixed-version test failure while running step 47 (run "run workload on tenants"): full command output in run_184450.815848678_n6_v23213cockroach-work.log: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/multitenant-upgrade/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_runtimeAssertionsBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-17419844/multitenant-upgrade/1729706351356/1729709246238)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*multitenant-upgrade.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-43533

### PR DESCRIPTION
**Pull request by DarrylWong**
In v22.2, tenant ids must be specified when creating client certs. Previously, only a select number tenant ids of were specified. Those ids were chosen to match the hardcoded ids used by the old multitenant roachprod framework.

Now that the new mt framework assigns ids sequentially, we see that creating tenants with ids not specified causes auth issues on clusters bootstrapped on 22.2. Since there should be no drawback to assigning more valid tenant ids than needed, we now add tenants 1 to 100. This should be more than enough for roachprod/roachtest.

Fixes: https://github.com/cockroachdb/cockroach/issues/133282
Epic: none
Relese note: none

### CODE REVIEW

File: pkg/roachprod/install/cluster_synced.go [hunk 1]
```diff
@@ -1712,7 +1712,7 @@ VERSION=$(%[1]s version --build-tag)
 VERSION=${VERSION::5}
 TENANT_SCOPE_OPT=""
 if [[ $VERSION = v22.2 ]]; then
-       TENANT_SCOPE_OPT="--tenant-scope 1,2,3,4,11,12,13,14"
+       TENANT_SCOPE_OPT="--tenant-scope $(echo {1..100} | tr ' ' ,)"
```
Comment (srosenberg) [inline pkg/roachprod/install/cluster_synced.go:1715]: Nit: I'd still enclose the delimiter in quotes for ease of (human) parsing; i.e., `','`

**Review by srosenberg — APPROVED** [review]

**Review by herkolategan — APPROVED** [review]

**Comment by DarrylWong** [comment]
TFTRs

bors r=srosenberg, herkolategan
