### PR TITLE
sqlstats: add close chan to buffer ingester

### LINKED ISSUE #128453: spanconfig/spanconfigkvsubscriber: TestBlockedKVSubscriberDisablesQueues failed
spanconfig/spanconfigkvsubscriber.TestBlockedKVSubscriberDisablesQueues [failed](https://tanzanite.cluster.engflow.com/invocations/default/69e2fb92-3249-4b38-aa13-f0240e4620e1?testReportRun=1&testReportShard=1&testReportAttempt=1#targets-Ly9wa2cvc3BhbmNvbmZpZy9zcGFuY29uZmlna3ZzdWJzY3JpYmVyOnNwYW5jb25maWdrdnN1YnNjcmliZXJfdGVzdA==) on release-24.2.0-rc @ [3d1bcc1df630c10c4065a22fc846daa911b436d6](https://github.com/cockroachdb/cockroach/commits/3d1bcc1df630c10c4065a22fc846daa911b436d6):

Fatal error:

```
panic: test timed out after 41m37s
running tests:
	TestBlockedKVSubscriberDisablesQueues (40m41s)
	TestBlockedKVSubscriberDisablesQueues/queue=replicate (40m24s)

```
Stack: 

```
goroutine 26335 [running]:
testing.(*M).startAlarm.func1()
	GOROOT/src/testing/testing.go:2366 +0x265
created by time.goFunc
	GOROOT/src/time/sleep.go:177 +0x45
```
<details><summary>Log preceding fatal error</summary>
<p>

```
* github.com/cockroachdb/cockroach/pkg/sql/contention/contentionutils.(*ConcurrentBufferGuard).syncLocked(0xc00a3231f0)
* 	github.com/cockroachdb/cockroach/pkg/sql/contention/contentionutils/concurrent_buffer_guard.go:158 +0x52
* github.com/cockroachdb/cockroach/pkg/sql/contention/contentionutils.(*ConcurrentBufferGuard).ForceSync(0xc00a3231f0)
* 	github.com/cockroachdb/cockroach/pkg/sql/contention/contentionutils/concurrent_buffer_guard.go:123 +0x87
* github.com/cockroachdb/cockroach/pkg/sql/sqlstats/insights.(*concurrentBufferIngester).Start.func2({0xc004077c08?, 0x0?})
* 	github.com/cockroachdb/cockroach/pkg/sql/sqlstats/insights/pkg/sql/sqlstats/insights/ingester.go:120 +0x65
* github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
* 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:485 +0x263
* created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx in goroutine 18997
* 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:476 +0x69d
* 
* goroutine 24360 [select, 2 minutes]:
* database/sql.(*DB).connectionOpener(0xc00b67a750, {0xb416ac0, 0xc00b67eeb0})
* 	GOROOT/src/database/sql/sql.go:1246 +0xed
* created by database/sql.OpenDB in goroutine 18997
* 	GOROOT/src/database/sql/sql.go:824 +0x2d4
* 
* goroutine 26217 [sleep]:
* time.Sleep(0x4c4b40)
* 	GOROOT/src/runtime/time.go:195 +0x115
* github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Quiesce(0xc000e2f4a0, {0xb416af8, 0xc00d607230})
* 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:610 +0x176
* github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).stopServers.func1(0x1, 0xc000e2f4a0)
* 	github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:156 +0x17f
* created by github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).stopServers in goroutine 18997
* 	github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:152 +0x1cf
* 
* goroutine 26104 [select, 2 minutes]:
* github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker.func1()
* 	github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/disk_health.go:253 +0x19b
* created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker in goroutine 26031
* 	github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/disk_health.go:248 +0xad
* 
* goroutine 26105 [sync.Cond.Wait, 2 minutes]:
* sync.runtime_notifyListWait(0xc00e2f40a8, 0x1)
* 	GOROOT/src/runtime/sema.go:569 +0x159
* sync.(*Cond).Wait(0xc00e2f4098)
* 	GOROOT/src/sync/cond.go:70 +0x75
* github.com/cockroachdb/pebble/record.(*flusherCond).Wait(...)
* 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:369
* github.com/cockroachdb/pebble/record.(*LogWriter).flushLoop(0xc00e2f4000, {0xc006b84140?, 0x7cef3a0?})
* 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:643 +0xb79
* runtime/pprof.Do({0xb416998, 0xfffae00}, {{0xc000cecfc0?, 0x20367a0?, 0xc005c4b4b0?}}, 0xc00c3aafc0)
* 	GOROOT/src/runtime/pprof/runtime.go:51 +0x118
* github.com/cockroachdb/pebble/record.NewLogWriter.func2()
* 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:562 +0x92
* created by github.com/cockroachdb/pebble/record.NewLogWriter in goroutine 26031
* 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:561 +0x8e5
* 
*
```
</p>
</details>

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=1</code>
 - <code>shard=1</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestBlockedKVSubscriberDisablesQueues.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-41025

### PR DESCRIPTION
**Pull request by dhartunian**
The buffer ingester could get stuck during closing because it would independently evaluate a `running` bool and then try to write to a channel with a buffer of 1. This channel could have accumulated a payload prior to the ingester shutting down and would then block forever.

Instead of using the boolean, the flush operation now selects on a channel that we close on shutdown. This ensure that no matter how many extra flushes we have blocked, they will all get cancelled.

Resolves: #128453
Epic: None

Release note: None

### CODE REVIEW

File: pkg/sql/sqlstats/insights/ingester.go [hunk 1]
```diff
@@ -40,6 +40,8 @@ type ConcurrentBufferIngester struct {
 	registry      *lockingRegistry
 	running       uint64
```
Comment (xinhaoz) [inline pkg/sql/sqlstats/insights/ingester.go:41]: Can we get rid of this field now?

**Review by xinhaoz — APPROVED** [review]
LGTM!

File: pkg/sql/sqlstats/insights/ingester_test.go [hunk 2]
```diff
@@ -246,3 +248,44 @@ func (s testEvent) TransactionID() uuid.UUID {
...
+
+	// We queue up a bunch of sync operations because it's unclear how
+	// many will proceed between the `Start()` and `Stop()` calls below.
+	ingester.guard.ForceSync()
+	extraSyncsFinished := false
+	go func() {
+		ingester.guard.ForceSync()
+		ingester.guard.ForceSync()
+		ingester.guard.ForceSync()
+		extraSyncsFinished = true
```
Comment (xinhaoz) [inline pkg/sql/sqlstats/insights/ingester_test.go:278]: I think this may need to be an atomic value.

File: pkg/sql/sqlstats/insights/ingester.go (hunk 1 above)
Comment (dhartunian) [reply pkg/sql/sqlstats/insights/ingester.go]: Thanks for the nudge. I avoided it earlier because I didn't take time to understand the one test that was using it, it wasn't obvious that I could remove the check. I ended up simplifying that test a lot and getting rid of the async stuff!

File: pkg/sql/sqlstats/insights/ingester_test.go (hunk 2 above)
Comment (dhartunian) [reply pkg/sql/sqlstats/insights/ingester_test.go]: thx. done.

Comment (dhartunian) [reply pkg/sql/sqlstats/insights/ingester_test.go]: I realized this was more idiomatic as a waitgroup so I got rid of the atomic bool.

**Comment by dhartunian** [comment]
bors r=xinhaoz
