### PR TITLE
sql: include partial index predicates in pg_catalog and pg builtins 

### LINKED ISSUE #53843: sql: activerecord PostgreSQLAdapterTest#test_partial_index fails because pg_get_indexdef is not accurate
The test `PostgreSQLAdapterTest#test_partial_index` fails.

The test code is here: https://github.com/rails/rails/blob/9055156668faa84821097e8fe324aaa1529abdfe/activerecord/test/cases/adapters/postgresql/postgresql_adapter_test.rb#L289

To run it:
- clone the [activerecord-cockroachdb-adapter](https://github.com/cockroachdb/activerecord-cockroachdb-adapter) 
- remove/comment [this line](https://github.com/cockroachdb/activerecord-cockroachdb-adapter/blob/0bb8a93adcf7aee6258100b317d851d7ca35f21f/test/excludes/ActiveRecord/ConnectionAdapters/PostgreSQLAdapterTest.rb#L5)
- follow instructions in CONTRIBUTING.md
- run `RUBYOPT="-W0" TESTOPTS="-v" TEST_FILES_AR=test/cases/adapters/postgresql/postgresql_adapter_test.rb bundle exec rake test`

failure:
```
Failure:
ActiveRecord::ConnectionAdapters::PostgreSQLAdapterTest#test_partial_index [/usr/local/lib/ruby/gems/2.7.0/bundler/gems/rails-c8e3aa01c3c9/activerecord/test/cases/adapters/postgresql/postgresql_adapter_test.rb:237]:
Expected: "(number > 100)"
  Actual: nil
```

It seems that the failure is when trying to introspect on the WHERE clause of the partial index.

This is the introspection query that ActiveRecord uses: https://github.com/rails/rails/blob/9055156668faa84821097e8fe324aaa1529abdfe/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb#L86

It looks like the issue is that `pg_get_indexdef(d.indexrelid)` does not include the WHERE clause in the result.

## Repro with SQL only

```
root@:26257/defaultdb> create table a(a int primary key, b int);
CREATE TABLE

root@:26257/defaultdb> create index partial on a(b) where b > 100;
CREATE INDEX

root@:26257/defaultdb> SELECT distinct i.relname, d.indisunique, d.indkey, pg_get_indexdef(d.indexrelid), t.oid,
                            pg_catalog.obj_description(i.oid, 'pg_class') AS comment
            FROM pg_class t
            INNER JOIN pg_index d ON t.oid = d.indrelid
            INNER JOIN pg_class i ON d.indexrelid = i.oid
            LEFT JOIN pg_namespace n ON n.oid = i.relnamespace
            WHERE i.relkind IN ('i', 'I')
              AND d.indisprimary = 'f'
              AND t.relname = 'a'
              AND n.nspname = 'public'
            ORDER BY i.relname;
  relname | indisunique | indkey |                        pg_get_indexdef                         | oid  | comment
----------+-------------+--------+----------------------------------------------------------------+------+----------
  partial |    false    |      2 | CREATE INDEX partial ON defaultdb.public.a USING btree (b ASC) | 2349 | NULL
(1 row)
```

### LINKED ISSUE #53908: sql: SHOW CONSTRAINTS does not show WHERE clause of unique partial index
Unique partial indexes guarantee uniqueness on a subset of rows. This is indicated by a `WHERE` clause. CRDB currently shows this `WHERE` clause in `SHOW CREATE TABLE`, but it is not present in `SHOW CONSTRAINTS`. This is confusing because it appears as a full-table unique constraint.

```
root@127.0.0.1:49802/movr> create unique index on users(id,name) where city = 'seattle';
CREATE INDEX

root@127.0.0.1:49802/movr> show constraints from users;
  table_name |  constraint_name  | constraint_type |            details             | validated
-------------+-------------------+-----------------+--------------------------------+------------
  users      | primary           | PRIMARY KEY     | PRIMARY KEY (city ASC, id ASC) |   true
  users      | users_id_name_key | UNIQUE          | UNIQUE (id ASC, name ASC)      |   true

root@127.0.0.1:49802/movr> show create table users;
  table_name |                                    create_statement
-------------+-----------------------------------------------------------------------------------------
  users      | CREATE TABLE public.users (
             |     id UUID NOT NULL,
             |     city VARCHAR NOT NULL,
             |     name VARCHAR NULL,
             |     address VARCHAR NULL,
             |     credit_card VARCHAR NULL,
             |     CONSTRAINT "primary" PRIMARY KEY (city ASC, id ASC),
             |     UNIQUE INDEX users_id_name_key (id ASC, name ASC) WHERE city = 'seattle':::STRING,
             |     FAMILY "primary" (id, city, name, address, credit_card)
             | )
```

### PR DESCRIPTION
**Pull request by mgartner**
#### logictest: make pg_catalog 46799 regression test more robust

This commit updates the `regression_46799` subtest in `pg_catalog` logic
tests so that hard-coded relids are not used. Previously, every time a
new relation was added in the test file, this test would have to be
rewritten with new relids. Determining the new relid was a nuisance.
Now, this test should not require changes when other relations are added
or removed elsewhere in the file.

Release justification: This is a test-only, non-production code change.

Release note: None

#### sql: include partial index predicate in pg_catalog.pg_indexes

This commit adds the partial index predicate expression to the formatted
`indexdef` column of `pg_catalog.pg_indexes`. Also, the predicate is now
included in the output of the `pg_get_indexdef` builtin function.
Including the predicate is critical for compatibility with Postgres
ORMs.

Fixes #53843

Release justification: This is a low-risk change to new functionality,
partial indexes.

Release note: None

#### pkg: include partial index predicate expressions in SHOW CONSTRAINTS

This commit updates `pg_catalog.pg_constraint.condef` to include the
predicate of unique partial index constraints. Also, the predicate is
now included in the output of `SHOW CONSTRAINTS` and
`pg_get_constraintdef()`.

Fixes #53908

Release justification: This is a low-risk change to new functionality,
partial indexes.

Release note: None

### CODE REVIEW

File: pkg/sql/logictest/testdata/logic_test/builtin_function [hunk 1]
```diff
@@ -2064,13 +2064,38 @@ SELECT pg_catalog.pg_get_indexdef(0)
...
 SELECT pg_catalog.pg_get_indexdef((SELECT oid from pg_class WHERE relname='pg_indexdef_idx'))
 ----
 CREATE UNIQUE INDEX pg_indexdef_idx ON test.public.pg_indexdef_test USING btree (a ASC)
 
+query T
+SELECT pg_catalog.pg_get_indexdef((SELECT oid from pg_class WHERE relname='pg_indexdef_partial_idx'))
+----
+CREATE INDEX pg_indexdef_partial_idx ON test.public.pg_indexdef_test USING btree (a ASC) WHERE a > 0
+
+# TODO(mgartner): To match Postgres, "::" casts should be appended to constants
```
Comment (rafiss) [inline pkg/sql/logictest/testdata/logic_test/builtin_function:2089]: i noticed this too, for other pg_catalog columns. i have a change here (https://github.com/cockroachdb/cockroach/pull/53965) that does it, and it should be easy to do here too

File: pkg/sql/pg_catalog.go [hunk 2]
```diff
@@ -1835,7 +1843,21 @@ func indexDefFromDescriptor(
...
 		indexDef.Interleave = intlDef
 	}
-	fmtCtx := tree.NewFmtCtx(tree.FmtPGIndexDef)
+	if index.IsPartial() {
+		// Format the raw predicate for display in order to resolve user-defined
+		// types to a human readable form.
+		//
+		// TODO(mgartner): Avoid the parsing he predicate expression twice. It
+		// is parsed in schemaexpr.FormatExprForDisplay and again here.
+		formattedPred, err := schemaexpr.FormatExprForDisplayWithoutTypeAnnotations(ctx, table, index.Predicate, p.SemaCtx())
```
Comment (rafiss) [inline pkg/sql/pg_catalog.go:1852]: just a bit confused -- why can't `formattedPred` be used directly as the return value?

**Review by rafiss — APPROVED** [review]
LGTM, just had a small question. also depending on if this PR or #53965 is merged first, one of us will have to accommodate the others changes. which order of merging would you prefer? also, can i rope you into reviewing mine? 😄

File: pkg/sql/pg_catalog.go (hunk 2 above)
Comment (mgartner) [reply pkg/sql/pg_catalog.go:1852]: This is confusing because this function converts an `IndexDescriptor` to a `tree.CreateIndex`. The `tree.CreateIndex.Predicate` field is a `tree.Expr` not a string. So we have to parse it again.

This is definitely not an ideal solution, but I think it's the most minimal one for now. In the long-term, I think it would be prudent to consider whether this conversion back into a `tree.CreateIndex` AST node is the right way to go about this. At the very least, the many code paths for formatting indexes should converge as much as possible.

**Comment by mgartner** [comment]
Let's get yours in first. I can rebase afterwards. I'll review it now.

**Comment by rafiss** [comment]
https://github.com/cockroachdb/cockroach/pull/53965 is merged, so if you rebase now, you should be able to address some of the TODOs you made by using `schemaexpr.FormatExprForDisplay(..., tree.FmtPGCatalog)`. i think you can also get rid of `tree.FmtPGIndexDef` potentially, but i'll leave it to you to verify that.

**Comment by mgartner** [comment]
@rafiss I've updated this so that casts are now included for string types, and I've removed `tree.FmtPGIndexDef`. Ready for another look.

**Review by rafiss — APPROVED** [review]
excellent, lgtm!

> Reviewed 2 of 5 files at r5, 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53967#-:-MGitxo854p9ltjaLqne:b-r1h4e0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rafiss)

**Comment by mgartner** [comment]
TFTR!

I've added to the 20.2 backport metaissue to get approval for backporting. https://github.com/cockroachdb/cockroach/issues/53662

**Comment by mgartner** [comment]
bors r=rafiss
