### PR TITLE
pgwire: use OS default for tcp_user_timeout

### LINKED ISSUE #164452: roachtest: schemachange/during/tpcc failed
roachtest.schemachange/during/tpcc [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21161643?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21161643?buildTab=artifacts#/schemachange/during/tpcc) on master @ [e842395e827c7ed19ca7e1d7b973557bf561cfe1](https://github.com/cockroachdb/cockroach/commits/e842395e827c7ed19ca7e1d7b973557bf561cfe1):

Failed with:

```
(cluster.go:2529).Run: full command output in run_201304.096043542_n5_cockroach-workload-c.log: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/schemachange/during/tpcc/run_1
```
Cluster Node to Ip Mapping:
| Node | Public IP | Private IP |
| --- | --- | --- |
| teamcity-21161643-1772090583-197-n5cpu16-0001 | 34.138.213.140 | 10.142.1.96 |
| teamcity-21161643-1772090583-197-n5cpu16-0002 | 35.231.203.238 | 10.142.1.97 |
| teamcity-21161643-1772090583-197-n5cpu16-0003 | 35.237.249.255 | 10.142.1.98 |
| teamcity-21161643-1772090583-197-n5cpu16-0004 | 35.231.14.75 | 10.142.1.100 |
| teamcity-21161643-1772090583-197-n5cpu16-0005 | 34.73.243.215 | 10.142.0.227 |

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=16</code>
 - <code>diskCount=0</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>metamorphicLeases=default</code>
 - <code>runtimeAssertionsBuild=false</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-21161643/schemachange-during-tpcc/1772124973865/1772137030518)

</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*schemachange/during/tpcc.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-60808

### PR DESCRIPTION
**Pull request by fqazi**
Previously, we would set a tcp_user_timeout of 30 seconds by default on connections. This lead to test flakes, so this patch reverts the setting back to the operating system default.

Fixes: #164452

Release note: None

### CODE REVIEW

File: pkg/server/tcpkeepalive/tcp_keepalive.go [hunk 1]
```diff
@@ -61,7 +61,7 @@ var UserTimeout = settings.RegisterDurationSetting(
 	"specifies the maximum amount of time that transmitted data "+
```
Comment (rafiss) [inline pkg/server/tcpkeepalive/tcp_keepalive.go:63]: could this descripton mention that a value of 0 results in using the OS default?

same for server.sql_tcp_keep_alive.count and server.sql_tcp_keep_alive.interval

**Review by rafiss — APPROVED** [review]
