### PR TITLE
cli/flags: recognize fractional values for --cache and --max-sql-memory

### LINKED ISSUE #19393: cli: `--cache` and `--max-sql-memory` are tricky to use with percentages
Encountered this on gitter: cockroach was configured through systemd with `--cache=25%` and `--max-sql-memory=25%` which are reasonable values.
However, systemd uses `%` inside configs, so the proper way to escape it is to use `%%`.

The cluster started properly, but any attempt at a sql connection failed with
```
Error: unable to connect or connection lost.
Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).
EOF
Failed running "sql"`
```

We dug around thinking it was certificates or `--host`, but no. We finally saw:
```
E171019 22:30:22.461609 51001 server/server.go:753 [n1,client=[::1]:54828] unable to pre-allocate 21504 bytes for this connection: root: memory budget exceeded: 112640 bytes requested, 25 bytes in budget
```

A few things we could/should do here:
1. document that `%` may need to be escaped (CC: @jseldess)
1. warn/error on `start` for really really small values (me I guess?)
1. return a better error message on connection failure due to memory budgets (CC: @knz)

### PR DESCRIPTION
**Pull request by knz**
Fixes #19393.
 
CockroachDB enables users to specify a fraction of total memory with
`--cache` and `--max-sql-memory`. Prior to this patch, only the
notation `NN%` was recognized.

Unfortunately, many system administration tools (incl. systemd,
supervisord) also support string interpolation in configuration
strings, and users get confused about why they need to write `NN%%`
with these tools.

In order to simplify the configuration story, this patch extends the
configuration syntax to also support fractional values, so that users
can use e.g. `--cache=.25` as an alias for `--cache=25%`.

Release note (cli change): the `--cache` and `--max-sql-memory` now
also support decimal notation to support a fraction of total available
RAM size, e.g. `--cache=.25` is equivalent to `--cache=25%`. This
simplifies integration with system management tools.

### CODE REVIEW

**Comment by knz** [comment]
I notice we don't currently have tests for the percentage values. Where do you suggest to put them?

**Comment by mberhault** [comment]
I think a `flags_util_test.go` would be ok to start. The more complex flags (eg: `--store`) tend to be tested in the parsing functions.

File: pkg/cli/cliflags/flags.go [hunk 1]
```diff
@@ -160,7 +160,7 @@ accept requests.`,
 Maximum memory capacity available to store temporary data for SQL clients,
 including prepared queries and intermediate data rows during query execution.
 Accepts numbers interpreted as bytes, size suffixes (e.g. 1GB and 1GiB) or a
-percentage of physical memory (e.g. 25%).
+percentage of physical memory (e.g. 25% or .25).
```
Comment (bdarnell) [inline pkg/cli/cliflags/flags.go]: There's no need to give two examples; I would just use the decimal form here (and s/percentage/fraction/). We can give both forms in the full documentation but other than backwards compatibility there's no reason for someone to use the percentage form instead of the decimal.

**Review by bdarnell — APPROVED** [review]

File: pkg/cli/cliflags/flags.go (hunk 1 above)
Comment (knz) [reply pkg/cli/cliflags/flags.go]: Done.

**Comment by knz** [comment]
Also added the missing test.
