### PR TITLE
changefeedccl: Flush prior to emitting trailing metadata

### LINKED ISSUE #116388: cdc: Incorrect checkpoint logic during shutdown
When changefeed shuts down (either due to node drain or due to changefeed
restart), the change aggregator emits an up to date checkpoint information
which is used to minimize the number of duplicates emitted during changefeed
restarts.

This logic is faulty in that we should never emit checkpoint information before
ensuring that any in-memory data is flushed.  Doing so may result in changefeed
failing to emit events.

Jira issue: CRDB-34603

### PR DESCRIPTION
**Pull request by miretskiy**
Change aggregator emits trailing metadata during aggregator shutdown (which can happen during node drain, or if the changefeed is shutting down or restarting).  Before we can emit the metadata containing change aggregator checkpoint, we must ensure that the events that may be buffered in memory are flushed.

Fixes #116388

Release note: None

### CODE REVIEW

**Comment by miretskiy** [comment]
> It looks like your PR touches production code but doesn't add or edit any test code. Did you consider adding tests to your PR?
> 
> 🦉 Hoot! I am a [Blathers](https://github.com/apps/blathers-crl), a bot for [CockroachDB](https://github.com/cockroachdb). My owner is [dev-inf](https://github.com/orgs/cockroachdb/teams/dev-inf).

@nicktrav  -- fyi: this code is tested in https://github.com/cockroachdb/cockroach/pull/105764
That PR has a test that reliably failed w/out this fix.

File: pkg/ccl/changefeedccl/changefeed_processors.go [hunk 1]
```diff
@@ -683,17 +665,44 @@ func (ca *changeAggregator) Next() (rowenc.EncDatumRow, *execinfrapb.ProducerMet
...
+		// to MoveToDraining again).
+		_ = ca.emitShutdownCheckpoint(false /* not a node drain */)
 	}
 
 	return nil, ca.DrainHelper()
 }
 
+func (ca *changeAggregator) emitShutdownCheckpoint(isDrain bool) error {
+	// Before emitting shutdown checkpoint, we must flush any buffered events.
+	if err := ca.flushBufferedEvents(); err != nil {
```
Comment (jayshrivastava) [inline pkg/ccl/changefeedccl/changefeed_processors.go:681]: It would be good to know how fast this happens realistically. The node drain mechanism waits for 10 seconds before cancelling the context. A concern here is that flushing events may take more than 10 seconds, in which case we would get an error here and return it.

It is still better to have this code than not to have it though.

**Review by jayshrivastava — APPROVED** [review]

File: pkg/ccl/changefeedccl/changefeed_processors.go (hunk 1 above)
Comment (miretskiy) [reply pkg/ccl/changefeedccl/changefeed_processors.go:681]: It's all best effort; if this is not fast enough -- one can change the flags to increase the timeout.
