### PR TITLE
sql: alter primary key hangs if index references exist

### LINKED ISSUE #123017: schemachanger: unexpected behavior of ALTER PRIMARY KEY with hard-coded index in a UDF
```sql
CREATE TABLE t (
    col0_1 STRING NOT NULL,
    col0_2 INT2,
    UNIQUE (col0_2 ASC)
);
CREATE FUNCTION f() RETURNS RECORD LANGUAGE SQL AS $$
  SELECT NULL FROM t@t_col0_2_key
$$;

SET statement_timeout = '0.1s';
ALTER TABLE t ALTER PRIMARY KEY USING COLUMNS (col0_1);
```
on `demo` hangs indefinitely (it gets 'query canceled error' against single node local cluster, so this reproduction is racy).

Here is what I have in `SHOW JOBS`:
```
  963139126921854977 | NEW SCHEMA CHANGE | ALTER TABLE defaultdb.public.t ALTER PRIMARY KEY USING COLU … col0_1) | root      | reverting | NULL           | 2024-04-24 22:18:55+00 | 2024-04-24 22:18:55+00 | NULL                   | 2024-04-24 22:18:55+00 |                  1 | executing declarative schema change PostCommitNonRevertiblePhase stage 3 of 4 with 7 MutationType ops (rollback=false) for ALTER TABLE: error executing PostCommitNonRevertiblePhase stage 3 of 4 with 7 MutationType ops: relation "t" (104): index ID 2 found in depended-on-by references, no such index in this relation |           NULL
```

Jira issue: CRDB-38166

Epic CRDB-37763

### PR DESCRIPTION
**Pull request by fqazi**
Previously, ALTER PRIMARY KEY could hang if an index reference existed from either a view or function using the index selection syntax. This was becasue neither the declarative schema changer or legacy schema changer support updating these references. To address this, this patch will prevent ALTER PRIMARY KEY if such references exist to any indexes that will be recreated.

Fixes: #123017
Release note (bug fix): ALTER PRIMARY KEY could hang if the table had any indexes which were referred to by views or functions using the force index syntax.

### CODE REVIEW

**Review by annrpom — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124132)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/logictest/testdata/logic_test/alter_table` line 3514 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124132#-Ny0sYI67wARZ7bl7SVC:-Ny0sYI67wARZ7bl7SVD:bcwvw6z) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6a3f9d0d97f25a1aff0da20a4a5194ffa9b62be/pkg/sql/logictest/testdata/logic_test/alter_table#L3514)):*
> ```
> DROP INDEX t_108974_f@t_108974_f_i_j_idx;
> 
> skipif config local-legacy-schema-changer
> ```

nit: shouid we have to distinguish the error messages between the legacy vs declarative schema changer (i'm assuming that the order of error prop. is the diff between the two ? the dsc looks like it does it in `disallowDroppingPrimaryIndexReferencedInUDFOrView`)

File: pkg/sql/alter_primary_key.go [hunk 1]
```diff
@@ -453,6 +453,22 @@ func (p *planner) AlterPrimaryKey(
...
+		// If this index is referenced by any other objects, then we wil
+		// block the primary key swap, since we don't have a mechanism to
+		// fix these references yet.
+		for _, tableRef := range tableDesc.GetDependedOnBy() {
+			if tableRef.IndexID == idx.GetID() {
+				refDesc, err := p.Descriptors().ByIDWithLeased(p.txn).Get().Desc(ctx, tableRef.ID)
+				if err != nil {
+					return err
+				}
+				return pgerror.Newf(pgcode.ObjectNotInPrerequisiteState,
```
Comment (rafiss) [inline pkg/sql/alter_primary_key.go:465]: should we use the `unimplemented.NewWithIssue` helper and point at the issue you filed?

File: pkg/sql/logictest/testdata/logic_test/alter_table [hunk 2]
```diff
@@ -3511,7 +3511,12 @@ SET sql_safe_updates = false;
 statement error pgcode 2BP01 pq: cannot drop index "t_108974_f_i_j_idx" because function "f_108974" depends on it
 DROP INDEX t_108974_f@t_108974_f_i_j_idx;
 
-statement error pgcode 2BP01 pq: cannot drop index "t_108974_f_pkey" because function "f_108974" depends on it
+skipif config local-legacy-schema-changer
+statement error pgcode 55000 pq: table \"t_108974_f\" has an index \(t_108974_f_i_j_idx\) that is still referenced by \"f_108974\"
+ALTER TABLE t_108974_f ALTER PRIMARY KEY USING COLUMNS (j);
+
+onlyif config local-legacy-schema-changer
```
Comment (rafiss) [inline pkg/sql/logictest/testdata/logic_test/alter_table:3518]: does this mean the legacy schema changer isn't actually affected? (since it disallows the alter PK for a different reason already?)

File: pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_primary_key.go [hunk 3]
```diff
@@ -684,6 +687,37 @@ func recreateAllSecondaryIndexes(
...
+		// block the primary key swap, since we don't have a mechanism to
+		// fix these references yet.
+		// TODO(fqazi): As a part of #124131 we should add logic to fix
+		// these references.
+		backrefs := b.BackReferences(idx.TableID)
+		functions := backrefs.FilterFunctionBody().Elements()
+		for _, function := range functions {
+			for _, tableRef := range function.UsesTables {
+				if tableRef.TableID == idx.TableID && tableRef.IndexID == idx.IndexID {
+					panic(pgerror.Newf(pgcode.ObjectNotInPrerequisiteState,
```
Comment (rafiss) [inline pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_primary_key.go:700]: should we use the `unimplemented.NewWithIssue` helper and point at the issue you filed?

**Review by rafiss — APPROVED** [review]
nice! does it need to be backported to 23.2 also?

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124132)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom and @rafiss)

___
*[`pkg/sql/logictest/testdata/logic_test/alter_table` line 3518 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124132#gh-1603582427:-Ny1-ZG41QcgY8RC6cMh:b3x5cpd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6a3f9d0d97f25a1aff0da20a4a5194ffa9b62be/pkg/sql/logictest/testdata/logic_test/alter_table#L3518)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

does this mean the legacy schema changer isn't actually affected? (since it disallows the alter PK for a different reason already?)
</blockquote></details>

Only in the case of functions and only if there are PK references, not secondary indexes, but views are still broken.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124132)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom and @rafiss)

___
*[`pkg/sql/alter_primary_key.go` line 465 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124132#gh-1603580097:-Ny3ObNB0KKUyyIkk6uQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6a3f9d0d97f25a1aff0da20a4a5194ffa9b62be/pkg/sql/alter_primary_key.go#L465)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should we use the `unimplemented.NewWithIssue` helper and point at the issue you filed?
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_primary_key.go` line 700 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124132#gh-1603582948:-Ny3ObsbEF3MKatcu1tF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6a3f9d0d97f25a1aff0da20a4a5194ffa9b62be/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_primary_key.go#L700)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should we use the `unimplemented.NewWithIssue` helper and point at the issue you filed?
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/alter_table` line 3514 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124132#-Ny0sYI67wARZ7bl7SVC:-Ny3T5lD0iRhRTTs9oSF:bm7g64t) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6a3f9d0d97f25a1aff0da20a4a5194ffa9b62be/pkg/sql/logictest/testdata/logic_test/alter_table#L3514)):*
<details><summary><i>Previously, annrpom (annie pompa) wrote…</i></summary><blockquote>

nit: shouid we have to distinguish the error messages between the legacy vs declarative schema changer (i'm assuming that the order of error prop. is the diff between the two ? the dsc looks like it does it in `disallowDroppingPrimaryIndexReferencedInUDFOrView`)
</blockquote></details>

Good point, I moved the check to later in the legacy schema changer. The declarative one can't be modified because we do it once for the comma syntax.

**Comment by fqazi** [comment]
@annrpom @rafiss bors r+

**Comment by yuzefovich** [comment]
@fqazi friendly reminder to backport this to 23.2 branch - we just saw a roachtest failure due to this #124549.

**Comment by fqazi** [comment]
@yuzefovich Thanks for the reminder, let me get one open now.
