### PR TITLE
roachtest: update blacklists

### LINKED ISSUE #42475: roachtest: lib/pq failed
SHA: https://github.com/cockroachdb/cockroach/commits/8622fad01478fb4a4f05b5579eb0b8561c02e491

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=lib/pq PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1591079&tab=artifacts#/lib/pq

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/20191114-1591079/lib/pq/run_1
	orm_helpers.go:174,orm_helpers.go:111,java_helpers.go:204,libpq.go:99,test_runner.go:697: 
		Tests run on Cockroach v20.1.0-alpha.00000000-888-g8622fad
		Tests run against lib/pq v1.2.0
		167 Total Tests Run
		124 tests passed
		43 tests failed
		0 tests skipped
		3 tests ignored
		1 test passed unexpectedly
		0 tests failed unexpectedly
		0 tests expected failed but skipped
		0 tests expected failed but not run
		For a full summary look at the lib/pq artifacts 
		
		An updated blacklist (libPQBlacklist20_1) is available in the artifacts' lib/pq log

```

### LINKED ISSUE #42477: roachtest: pgjdbc failed
SHA: https://github.com/cockroachdb/cockroach/commits/8622fad01478fb4a4f05b5579eb0b8561c02e491

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=pgjdbc PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1591079&tab=artifacts#/pgjdbc

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/20191114-1591079/pgjdbc/run_1
	orm_helpers.go:174,orm_helpers.go:111,java_helpers.go:204,pgjdbc.go:172,pgjdbc.go:183,test_runner.go:697: 
		Tests run on Cockroach v20.1.0-alpha.00000000-888-g8622fad
		Tests run against pgjdbc REL42.2.8
		5782 Total Tests Run
		4385 tests passed
		1397 tests failed
		0 tests skipped
		1 test ignored
		2 tests passed unexpectedly
		0 tests failed unexpectedly
		0 tests expected failed but skipped
		0 tests expected failed but not run
		For a full summary look at the pgjdbc artifacts 
		
		An updated blacklist (pgjdbcBlackList20_1) is available in the artifacts' pgjdbc log

```

### LINKED ISSUE #42587: roachtest: psycopg failed
SHA: https://github.com/cockroachdb/cockroach/commits/1c3fce73cd25fa69e5a8c05ce8e215d66b4f49e4

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=psycopg PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1599833&tab=artifacts#/psycopg

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/20191120-1599833/psycopg/run_1
	orm_helpers.go:181,orm_helpers.go:111,psycopg.go:121,psycopg.go:133,test_runner.go:697: 
		Tests run on Cockroach v20.1.0-alpha.20191118-183-g1c3fce7
		Tests run against psycopg 2_8_4
		672 Total Tests Run
		387 tests passed
		285 tests failed
		96 tests skipped
		2 tests ignored
		2 tests passed unexpectedly
		0 tests failed unexpectedly
		0 tests expected failed but skipped
		0 tests expected failed but not run
		---
		--- PASS: tests.test_dates.DatetimeTests.test_type_roundtrip_timetz - https://github.com/cockroachdb/cockroach/issues/26097 (unexpected)
		--- PASS: tests.test_dates.DatetimeTests.test_time_24 - https://github.com/cockroachdb/cockroach/issues/36118 (unexpected)
		For a full summary look at the psycopg artifacts 
		
		An updated blacklist (psycopgBlackList20_1) is available in the artifacts' psycopg log

```

### PR DESCRIPTION
**Pull request by rafiss**
Compatibility work has been done recently that caused more tests to
pass.

closes #42475
closes #42477
closes #42587

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/hibernate_blacklist.go [hunk 1]
```diff
@@ -23,8 +23,8 @@ var hibernateBlacklists = blacklistsForVersion{
 // After a failed run, an updated version of this blacklist should be available
 // in the test log.
 var hibernateBlackList20_1 = blacklist{
-	"org.hibernate.id.QuotedIdentifierTest.testDirectIdPropertyAccess":                                                                                                               "26925",
-	"org.hibernate.id.hhh12973.PostgreSQLSequenceGeneratorWithSerialTest.test":                                                                                                       "unknown",
+	"org.hibernate.id.QuotedIdentifierTest.testDirectIdPropertyAccess":                                                                                                               "24062",
+	"org.hibernate.id.hhh12973.PostgreSQLSequenceGeneratorWithSerialTest.test":                                                                                                       "24062",
```
Comment (jordanlewis) [inline pkg/cmd/roachtest/hibernate_blacklist.go]: This issue is closed - shoudl we open a new and more appropriate one?

**Review by jordanlewis — APPROVED** [review]

File: pkg/cmd/roachtest/hibernate_blacklist.go (hunk 1 above)
Comment (rafiss) [reply pkg/cmd/roachtest/hibernate_blacklist.go]: yeah, I created this but forgot to use it here: https://github.com/cockroachdb/cockroach/issues/42662
