### PR TITLE
roachtest: fix flakey follower read roachtest

### LINKED ISSUE #34701: roachtest: follower-reads/nodes=3 failed
SHA: https://github.com/cockroachdb/cockroach/commits/a46a7e275b4406fee6cc919fd935487add0874f0

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=follower-reads/nodes=3 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1128052&tab=buildLog

```
The test failed on release-2.1:
	test.go:748,follower_reads.go:191: error verifying node values: pq: unknown function: experimental_follower_read_timestamp()

```

### PR DESCRIPTION
**Pull request by ajwerner**
The follower read roachtest sustains reads against followers and verifies that
the 90th %-ile latency never exceeds 20ms. During certain situations like lease
transfer, the latency may jump up. This change now runs the sustained reads for
longer (3 minutes instead of 1) and verifies that the latency is low at least
80% of the time. This should be much less fragile.

Fixes #34701.

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/follower_reads.go [hunk 1]
```diff
@@ -208,7 +208,7 @@ func runFollowerReadsTest(ctx context.Context, t *test, c *cluster) {
 	// Run reads for 60s which given the metrics window of 10s should guarantee
```
Comment (nvanbenschoten) [inline pkg/cmd/roachtest/follower_reads.go]: > Run reads for 60s

**Review by nvb — APPROVED** [review]
