### PR TITLE
workload: fix divide by zero in `csvServerPaths`

### LINKED ISSUE #152092: Sentry: fixture.go:170: runtime error: integer divide by zero
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/ccl/workloadccl.csvServerPaths
  | 	pkg/ccl/workloadcc...
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/6820049254/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/6820049254/?referrer=webhooks_plugin)

Panic Message:

```
fixture.go:170: runtime error: integer divide by zero
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/ccl/workloadccl.csvServerPaths
  | 	pkg/ccl/workloadccl/fixture.go:170
  | github.com/cockroachdb/cockroach/pkg/ccl/workloadccl.ImportFixture
  | 	pkg/ccl/workloadccl/fixture.go:418
  | github.com/cockroachdb/cockroach/pkg/ccl/workloadccl.ImportDataLoader.InitialDataLoad
  | 	pkg/ccl/workloadccl/fixture.go:316
  | github.com/cockroachdb/cockroach/pkg/workload/workloadsql.Setup
  | 	pkg/workload/workloadsql/workloadsql.go:47
  | github.com/cockroachdb/cockroach/pkg/workload/cli.runInitImpl
  | 	pkg/workload/cli/run.go:361
  | github.com/cockroachdb/cockroach/pkg/workload/cli.runInit
  | 	pkg/workload/cli/run.go:321
  | github.com/cockroachdb/cockroach/pkg/workload/cli.init.3.func1.CmdHelper.7
  | 	pkg/workload/cli/run.go:239
  | github.com/cockroachdb/cockroach/pkg/workload/cli.init.3.func1.CmdHelper.HandleErrs.8
  | 	pkg/workload/cli/cli.go:82
  | github.com/spf13/cobra.(*Command).execute
  | 	external/com_github_spf13_cobra/command.go:920
  | github.com/spf13/cobra.(*Command).ExecuteC
  | 	external/com_github_spf13_cobra/command.go:1044
  | github.com/spf13/cobra.(*Command).Execute
  | 	external/com_github_spf13_cobra/command.go:968
  | github.com/cockroachdb/cockroach/pkg/cli.Run
  | 	cli.go:301
  | github.com/cockroachdb/cockroach/pkg/cli.doMain
  | 	cli.go:139
  | github.com/cockroachdb/cockroach/pkg/cli.Main
  | 	cli.go:64
  | main.main
  | 	pkg/cmd/cockroach/main.go:21
  | runtime.main
  | 	GOROOT/src/runtime/proc.go:272
  | runtime.goexit
  | 	src/runtime/asm_arm64.s:1223
Wraps: (2) runtime error: integer divide by zero
Error types: (1) *withstack.withStack (2) runtime.errorString
-- report composition:
runtime.errorString
fixture.go:170: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_arm64.s#L1222-L1224](src/runtime/asm_arm64.s#L1222-L1224)
[GOROOT/src/runtime/proc.go#L271-L273](GOROOT/src/runtime/proc.go#L271-L273)
[pkg/cmd/cockroach/main.go#L20-L22](pkg/cmd/cockroach/main.go#L20-L22)
[cli.go#L63-L65](cli.go#L63-L65)
[cli.go#L138-L140](cli.go#L138-L140)
[cli.go#L300-L302](cli.go#L300-L302)
[external/com_github_spf13_cobra/command.go#L967-L969](external/com_github_spf13_cobra/command.go#L967-L969)
[external/com_github_spf13_cobra/command.go#L1043-L1045](external/com_github_spf13_cobra/command.go#L1043-L1045)
[external/com_github_spf13_cobra/command.go#L919-L921](external/com_github_spf13_cobra/command.go#L919-L921)
[pkg/workload/cli/cli.go#L81-L83](pkg/workload/cli/cli.go#L81-L83)
[pkg/workload/cli/run.go#L238-L240](pkg/workload/cli/run.go#L238-L240)
[pkg/workload/cli/run.go#L320-L322](pkg/workload/cli/run.go#L320-L322)
[pkg/workload/cli/run.go#L360-L362](pkg/workload/cli/run.go#L360-L362)
[pkg/workload/workloadsql/workloadsql.go#L46-L48](pkg/workload/workloadsql/workloadsql.go#L46-L48)
[pkg/ccl/workloadccl/fixture.go#L315-L317](pkg/ccl/workloadccl/fixture.go#L315-L317)
[pkg/ccl/workloadccl/fixture.go#L417-L419](pkg/ccl/workloadccl/fixture.go#L417-L419)
[pkg/ccl/workloadccl/fixture.go#L169-L171](pkg/ccl/workloadccl/fixture.go#L169-L171)
</details>

```
src/runtime/asm_arm64.s in runtime.goexit at line 1223
GOROOT/src/runtime/proc.go in runtime.main at line 272
pkg/cmd/cockroach/main.go in main.main at line 21
cli.go in pkg/cli.Main at line 64
cli.go in pkg/cli.doMain at line 139
cli.go in pkg/cli.Run at line 301
external/com_github_spf13_cobra/command.go in github.com/spf13/cobra.(*Command).Execute at line 968
external/com_github_spf13_cobra/command.go in github.com/spf13/cobra.(*Command).ExecuteC at line 1044
external/com_github_spf13_cobra/command.go in github.com/spf13/cobra.(*Command).execute at line 920
pkg/workload/cli/cli.go in pkg/workload/cli.init.3.func1.CmdHelper.HandleErrs.8 at line 82
pkg/workload/cli/run.go in pkg/workload/cli.init.3.func1.CmdHelper.7 at line 239
pkg/workload/cli/run.go in pkg/workload/cli.runInit at line 321
pkg/workload/cli/run.go in pkg/workload/cli.runInitImpl at line 361
pkg/workload/workloadsql/workloadsql.go in pkg/workload/workloadsql.Setup at line 47
pkg/ccl/workloadccl/fixture.go in pkg/ccl/workloadccl.ImportDataLoader.InitialDataLoad at line 316
pkg/ccl/workloadccl/fixture.go in pkg/ccl/workloadccl.ImportFixture at line 418
pkg/ccl/workloadccl/fixture.go in pkg/ccl/workloadccl.csvServerPaths at line 170
```

### Tags

| Tag | Value |
| --- | --- |
| Command | workload init movr |
| Environment | v25.2.4 |
| Go Version | go1.23.7 X:nocoverageredesign |
| Platform | darwin arm64 |
| Distribution | CCL |
| Cockroach Release | v25.2.4 |
| Cockroach SHA | db39678e142ec9f40d40b7139c3f821a94fcb80f |
| # of CPUs | 14 |
| # of Goroutines | 11 |

Jira issue: CRDB-53641

### PR DESCRIPTION
**Pull request by srosenberg**
Previously, `getNodeCount` could return zero without an error. This internal helper is used in `csvServerPaths` to determine `rowStep`. Not having any SQL nodes "available" is plausibly a valid system state. However, in the context of loading data, that indicates an error.

This PR ensures `getNodeCount` returns a non-zero result or an error. As a precaution, we also clamp down the divisor.

Epic: none
Fixes: #152092
Release note: None

### CODE REVIEW

File: pkg/ccl/workloadccl/fixture.go [hunk 1]
```diff
@@ -167,7 +167,7 @@ func csvServerPaths(
 	// so our "integer multiple" is picked to be 1 to minimize this effect. Too
 	// bad about the progress tracking granularity.
 	numFiles := numNodes
-	rowStep := table.InitialRows.NumBatches / numFiles
+	rowStep := table.InitialRows.NumBatches / min(numFiles, 1)
```
Comment (stevendanna) [inline pkg/ccl/workloadccl/fixture.go]: Should this be: 

```suggestion
	rowStep := table.InitialRows.NumBatches / max(numFiles, 1)
```

Comment (srosenberg) [reply pkg/ccl/workloadccl/fixture.go]: 🤦

**Review by stevendanna — APPROVED** [review]
Thanks!

**Review by williamchoe3 — APPROVED** [review]
lgtm

**Comment by srosenberg** [comment]
TFTR!

bors r=stevendanna,williamchoe3
