### PR TITLE
sql: do not distribute queries with subqueries returning OIDs

### LINKED ISSUE #86075: roachtest/sqlsmith: ResolveFunctionByOID unimplemented
roachtest.sqlsmith/setup=rand-tables/setting=no-ddl [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6079423?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6079423?buildTab=artifacts#/sqlsmith/setup=rand-tables/setting=no-ddl) on master @ [0dd438d3dc0b42543890455945a7a6b42811def1](https://github.com/cockroachdb/cockroach/commits/0dd438d3dc0b42543890455945a7a6b42811def1):

```
test artifacts and logs in: /artifacts/sqlsmith/setup=rand-tables/setting=no-ddl/run_1
	sqlsmith.go:265,sqlsmith.go:325,test_runner.go:896: error: pq: internal error: ResolveFunctionByOID unimplemented
		stmt:
		SELECT
			NULL AS col_84195,
			tab_42278.col1_4 AS col_84196,
			(-0.2449352525117256):::FLOAT8 AS col_84197,
			(SELECT tab_42279.col5_3 AS col_84198 FROM defaultdb.public.table5@[0] AS tab_42279 LIMIT 1:::INT8) AS col_84199
		FROM
			defaultdb.public.table1@[0] AS tab_42278
		ORDER BY
			tab_42278.col1_8 DESC, tab_42278.col1_15 DESC, tab_42278.col1_13;
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=rand-tables/setting=no-ddl.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-18555

### PR DESCRIPTION
**Pull request by yuzefovich**
If a subquery results in a DOid datum, the datum will get a type
annotation (because DOids are ambiguous) when serializing the
render expression involving the result of the subquery. As a
result, we might need to perform a cast on a remote node which
might fail, thus we prohibit the distribution of the main query.

Fixes: #86075.

Release justification: bug fix.

Release note: None

### CODE REVIEW

File: pkg/sql/distsql_physical_planner.go [hunk 1]
```diff
@@ -273,6 +273,16 @@ func (v *distSQLExprCheckVisitor) VisitPre(expr tree.Expr) (recurse bool, newExp
 	case *tree.DOid:
 		v.err = newQueryNotSupportedError("OID expressions are not supported by distsql")
 		return false, expr
+	case *tree.Subquery:
+		if t.ResolvedType().Family() == types.OidFamily {
```
Comment (cucaroach) [inline pkg/sql/distsql_physical_planner.go:277]: What if t is an array or tuple containing an OID?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86186)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @mgartner)

___
*[`pkg/sql/distsql_physical_planner.go` line 277 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86186#-N9YhNW1z8TA3nU5Zedb-r1-277:-N9hUitv5raFgSe0-tkr:bv6v0g6) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a48adb406f28496f07aac52f6533f7c64c2b758/pkg/sql/distsql_physical_planner.go#L277)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

What if t is an array or tuple containing an OID?
</blockquote></details>

Good point - it would still be a problem. Fixed.

**Review by mgartner — APPROVED** [review]
Thanks!
:lgtm: 

> Reviewed 1 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86186#-:-NA5CV878AhCC7AzexL5:bbk4xod)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach)

**Comment by yuzefovich** [comment]
TFTRs!

bors r+
