### PR TITLE
exec: fix NaN comparison logic

### LINKED ISSUE #38751: exec: float 'NaN' comparisons are incorrect
A few of the `float` logic test fail for `local-vec`:
```
--- FAIL: TestLogic (0.61s)
    test_log_scope.go:77: test logs captured to: /var/folders/9q/5bgz_tb55tdfxrfz_bnp6p6r0000gn/T/logTestLogic230065997
    test_log_scope.go:58: use -show-logs to present logs inline
    --- FAIL: TestLogic/local-vec (0.00s)
        --- FAIL: TestLogic/local-vec/float (0.58s)
            logic.go:2338:

                testdata/logic_test/float:43: select f, f > 'NaN' from p@{FORCE_INDEX=primary} where f > 'NaN' ORDER BY f
                expected:
                    -Inf  true
                    -1    true
                    0     true
                    1     true
                    +Inf  true

                but found (query options: "") :


            logic.go:2338:

                testdata/logic_test/float:52: select f, f > 'NaN' from p@{FORCE_INDEX=p_f_key} where f > 'NaN' ORDER BY f
                expected:
                    -Inf  true
                    -1    true
                    0     true
                    1     true
                    +Inf  true

                but found (query options: "") :
                    -Inf  false
                    -1    false
                    0     false
                    1     false
                    +Inf  false
```

### PR DESCRIPTION
**Pull request by solongordon**
I added special NaN handling for float comparisons. In SQL, NaNs are
treated as less than any other float value.

Thankfully I'm not seeing a performance hit when I run our sort
benchmarks with float64 values.

Fixes #38751

Release note: None

### CODE REVIEW

**Review by asubiotto — APPROVED** [review]
:lgtm: it's great how clean of a change this is

**Comment by jordanlewis** [comment]
Mind blown that this doesn't affect benchmarks too much. Does it affect selection benchmarks?

**Comment by solongordon** [comment]
Yeah, good point, I should have run that one too. Noticeable drop-off in performance there unfortunately.
```
name                                                      old time/op    new time/op    delta
SelLTFloat64Float64ConstOp/useSel=true,hasNulls=true-4      1.28µs ± 1%    2.68µs ± 2%  +109.95%  (p=0.016 n=4+5)
SelLTFloat64Float64ConstOp/useSel=true,hasNulls=false-4      816ns ± 9%    1601ns ± 1%   +96.10%  (p=0.008 n=5+5)
SelLTFloat64Float64ConstOp/useSel=false,hasNulls=true-4     1.19µs ± 2%    1.82µs ± 3%   +52.50%  (p=0.008 n=5+5)
SelLTFloat64Float64ConstOp/useSel=false,hasNulls=false-4     645ns ± 3%    1877ns ± 1%  +191.04%  (p=0.008 n=5+5)
SelLTFloat64Float64Op/useSel=true,hasNulls=true-4           1.80µs ± 4%    2.41µs ± 2%   +33.47%  (p=0.008 n=5+5)
SelLTFloat64Float64Op/useSel=true,hasNulls=false-4           807ns ± 4%    1303ns ± 2%   +61.52%  (p=0.008 n=5+5)
SelLTFloat64Float64Op/useSel=false,hasNulls=true-4          1.38µs ±11%    2.76µs ± 2%   +99.86%  (p=0.008 n=5+5)
SelLTFloat64Float64Op/useSel=false,hasNulls=false-4          641ns ± 8%    1171ns ± 2%   +82.77%  (p=0.008 n=5+5)

name                                                      old speed      new speed      delta
SelLTFloat64Float64ConstOp/useSel=true,hasNulls=true-4    6.40GB/s ± 1%  3.05GB/s ± 2%   -52.35%  (p=0.016 n=4+5)
SelLTFloat64Float64ConstOp/useSel=true,hasNulls=false-4   10.1GB/s ± 9%   5.1GB/s ± 1%   -49.09%  (p=0.008 n=5+5)
SelLTFloat64Float64ConstOp/useSel=false,hasNulls=true-4   6.86GB/s ± 2%  4.50GB/s ± 3%   -34.41%  (p=0.008 n=5+5)
SelLTFloat64Float64ConstOp/useSel=false,hasNulls=false-4  12.7GB/s ± 2%   4.4GB/s ± 1%   -65.62%  (p=0.008 n=5+5)
SelLTFloat64Float64Op/useSel=true,hasNulls=true-4         9.08GB/s ± 4%  6.80GB/s ± 2%   -25.12%  (p=0.008 n=5+5)
SelLTFloat64Float64Op/useSel=true,hasNulls=false-4        20.3GB/s ± 4%  12.6GB/s ± 2%   -38.12%  (p=0.008 n=5+5)
SelLTFloat64Float64Op/useSel=false,hasNulls=true-4        11.9GB/s ±10%   5.9GB/s ± 2%   -50.14%  (p=0.008 n=5+5)
SelLTFloat64Float64Op/useSel=false,hasNulls=false-4       25.6GB/s ± 8%  14.0GB/s ± 2%   -45.34%  (p=0.008 n=5+5)
```

**Comment by jordanlewis** [comment]
I figured. I bet if we changed things around to do another pass over the vectors searching for NaNs, things would be different... but I think the effort there is probably too high to justify. You could also imagine doing something similar to nulls/sel array for NaNs, and fast path when you know there's no NaNs at all, but again I don't think it's worth it here.

**Comment by yuzefovich** [comment]
Hm, it appears that bors just ignored "r+" from several hours ago :)

File: pkg/sql/exec/float.go [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+		return -1
+	}
+	if a == b {
+		return 0
+	}
+	if a > b {
+		return 1
+	}
+	if math.IsNaN(a) {
+		if math.IsNaN(b) {
```
Comment (jordanlewis) [inline pkg/sql/exec/float.go]: I wonder if we could avoid this second check by changing `a == b` to be `int64(a) == int64(b)` or whatever - aren't the bits of NaN the same?

Comment (solongordon) [reply pkg/sql/exec/float.go]: Good thought. I think we would use `math.Float64bits`.

Comment (solongordon) [reply pkg/sql/exec/float.go]: BTW, I was worried this might be slower than the normal float equality check, but it's actually faster! Presumably because the normal one has to do NaN checks.
