### PR TITLE
diagnostics: honor stopper quiescence when reporting diagnostics

### LINKED ISSUE #136739: acceptance: TestDockerCLI_test_demo_partitioning failed [slow quiesce in `rpc.(*peer).launch`]
acceptance.TestDockerCLI_test_demo_partitioning [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_Acceptance/18036192?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_Acceptance/18036192?buildTab=artifacts#/) on master @ [74e821f1d1ce358f49354f8581b8663aa4c2fb15](https://github.com/cockroachdb/cockroach/commits/74e821f1d1ce358f49354f8581b8663aa4c2fb15):

```
=== RUN   TestDockerCLI_test_demo_partitioning
    test_log_scope.go:165: test logs captured to: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/_tmp/b38fdc3e3d87d99024418e1ae9af5f4c/logTestDockerCLI_test_demo_partitioning1199483594
    test_log_scope.go:76: use -show-logs to present logs inline
    generated_cli_test.go:147: -- test log scope end --
test logs left over in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/_tmp/b38fdc3e3d87d99024418e1ae9af5f4c/logTestDockerCLI_test_demo_partitioning1199483594
--- FAIL: TestDockerCLI_test_demo_partitioning (368.22s)
=== RUN   TestDockerCLI_test_demo_partitioning/test_demo_partitioning.tcl
    util_docker.go:255: non-zero exit code: 1
    --- FAIL: TestDockerCLI_test_demo_partitioning/test_demo_partitioning.tcl (361.86s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestDockerCLI_test_demo_partitioning.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-45224

### PR DESCRIPTION
**Pull request by dhartunian**
Previously, we would block on the HTTP diagnostics request until the preset timeout regardless of stopper quiescence. This change ensures that the `ctx` passed to the diagnostics reporter and the HTTP client is cancelled if the stopper is quiescing.

Resolves: #136739

Release note: None

### CODE REVIEW

**Review by xinhaoz — APPROVED** [review]

File: pkg/server/diagnostics/reporter.go [hunk 1]
```diff
@@ -192,7 +192,11 @@ func (r *Reporter) PeriodicallyReportDiagnostics(ctx context.Context, stopper *s
 			// Consider something like rand.Float() > resetFreq/reportFreq here to sample
 			// stat reset periods for reporting.
 			if shouldReportDiagnostics(ctx, r.Settings) {
-				r.ReportDiagnostics(ctx)
+				func() {
```
[the remark this answers is not in the document]
Comment (dhartunian) [reply pkg/server/diagnostics/reporter.go:195]: Because I want the defer to execute unconditionally in case `reportDiagnostics` panics

**Comment by dhartunian** [comment]
TFTR!

bors r=xinhaoz

File: pkg/ccl/serverccl/diagnosticsccl/reporter_test.go [hunk 2]
```diff
@@ -366,6 +374,29 @@ func TestTelemetry_SuccessfulTelemetryPing(t *testing.T) {
...
+	ctx := context.Background()
+	setupCluster(t, rt.serverDB)
+
+	defer rt.diagServer.SetWaitSeconds(200)()
+	dr := rt.server.DiagnosticsReporter().(*diagnostics.Reporter)
+	stopper := rt.server.Stopper()
+
+	dr.PeriodicallyReportDiagnostics(ctx, stopper)
+	stopper.Stop(ctx)
+	<-stopper.IsStopped()
```
Comment (angles-n-daemons) [inline pkg/ccl/serverccl/diagnosticsccl/reporter_test.go:397]: Not sure if bors is going to merge this, but might be worth checking some upper bound:

```go
	dr.PeriodicallyReportDiagnostics(ctx, stopper)
	stopper.Stop(ctx)
	select {
	   case <-time.After(time.Second):
	     t.Fatal("expected stopper to signal")
	   case <-stopper.IsStopped9):
	     t.Log("stopped in time")
   }
```

**Review by angles-n-daemons — APPROVED** [review]

File: pkg/ccl/serverccl/diagnosticsccl/reporter_test.go (hunk 2 above)
Comment (dhartunian) [reply pkg/ccl/serverccl/diagnosticsccl/reporter_test.go:397]: That should get captured by the standard test timeouts which trigger in case of slow quiescence or arbitrary blocking. I'll just bump the wait times to 5 minutes to make sure that happens.

Comment (angles-n-daemons) [reply pkg/ccl/serverccl/diagnosticsccl/reporter_test.go:397]: makes sense, that sounds reasonable to me

File: pkg/server/diagnostics/reporter.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (dhartunian) [reply pkg/server/diagnostics/reporter.go:195]: I checked before making my comment 😄 
https://go.dev/play/p/7giP9JjzJtw

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137845)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained

___
*[`pkg/server/diagnostics/reporter.go` line 196 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137845#-OEa7ZCK2W5tmOBTAcQT:-OEa7ZCK2W5tmOBTAcQU:b-lhkxtg) ([raw file](https://github.com/cockroachdb/cockroach/blob/127b8b086460f0d3669c5523d8906b767fb0a094/pkg/server/diagnostics/reporter.go#L196)):*
> ```Go
> 			if shouldReportDiagnostics(ctx, r.Settings) {
> 				func() {
> 					ctx, cancel := stopper.WithCancelOnQuiesce(ctx)
> ```

this will create a new CancelCtx once for each diagnostics report.

could we only create one before calling RunAsyncTask?
```
ctx, cancel := stopper.WithCancelOnQuiesce(ctx)
defer cancel()
_ = stopper.RunAsyncTaskEx(...)
```
