### PR TITLE
restore: fix online restore of MR backups

### LINKED ISSUE #122478: restore: online restore panics with MR backups
When running online restore on the drt-large cluster using an MR backup, the cluster panics with:

```
while ingesting ‹data/957367886513733638.sst›: unsupported storage scheme: ‹""› - refer to docs to find supported storage scheme
```
More info can be found in the internal Slack thread [here](https://cockroachlabs.slack.com/archives/C059C05GM98/p1713300969908859).

Jira issue: CRDB-37903

### PR DESCRIPTION
**Pull request by dt**
Release note: none.
Epic: none.

### CODE REVIEW

**Review by msbutler — APPROVED** [review]

File: pkg/ccl/backupccl/restore_job.go [hunk 1]
```diff
@@ -247,6 +247,7 @@ func makeBackupLocalityMap(
 					return nil, errors.Wrap(err,
 						"creating locality external storage configuration")
 				}
+				conf.URI = uri
```
Comment (stevendanna) [inline pkg/ccl/backupccl/restore_job.go:250]: As a follow-up, do we want to put some validation somewhere either in LinkExternalSSTable or in the online restore code that we are dealing with a valid external file?

**Review by stevendanna — APPROVED** [review]
