### PR TITLE
tree: correctly handle NULLs annotated as a tuple type

### LINKED ISSUE #74729: sql: internal error: unable to vectorize execution plan: ... expected NULL:::RECORD to be of type tuple, found type unknown
roachtest.sqlsmith/setup=seed/setting=no-mutations [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4099953&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4099953&tab=artifacts#/sqlsmith/setup=seed/setting=no-mutations) on master @ [bbd8658d09681135c30e07650798768ca0063f09](https://github.com/cockroachdb/cockroach/commits/bbd8658d09681135c30e07650798768ca0063f09):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/sqlsmith/setup=seed/setting=no-mutations/run_1
	sqlsmith.go:259,sqlsmith.go:298,test_runner.go:780: error: pq: internal error: unable to vectorize execution plan: CASE WHEN "$9" THEN (B'0000000000', ARRAY[18078, 29977, -28375], ('4 mons 716 days 17:39:04.590025':::INTERVAL, (-32768):::INT8)) ELSE (B'1100011111', ARRAY[], NULL:::RECORD) END: incompatible value type: tuples [(B'0000000000', ARRAY[18078, 29977, -28375], ('4 mons 716 days 17:39:04.590025':::INTERVAL, (-32768):::INT8)) (B'1100011111', ARRAY[], NULL:::RECORD)] are not the same type: expected NULL:::RECORD to be of type tuple, found type unknown
		stmt:
		WITH
			with_67032 (col_400597)
				AS (
					SELECT
						CASE
						WHEN tab_163440._bool
						THEN (B'0000000000', ARRAY[18078:::INT8,29977:::INT8,(-28375):::INT8], ('4 mons 716 days 17:39:04.590025':::INTERVAL, (-32768):::INT8))
						ELSE (B'1100011111', ARRAY[]:::INT2[], NULL)
						END
							AS col_400597
					FROM
						defaultdb.public.seed@[0] AS tab_163440
				)
		SELECT
			cte_ref_19680.col_400597 AS col_400598
		FROM
			with_67032 AS cte_ref_19680
		WHERE
			true
		LIMIT
			15:::INT8;
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=seed/setting=no-mutations.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-12233

### PR DESCRIPTION
**Pull request by mgartner**
Fixes #74729

Release note (bug fix): A bug has been fixed that caused errors when
trying to evaluate queries with NULL values annotated as a tuple type,
such as `NULL:::RECORD`. This bug was present since version 19.1.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78287)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @rafiss, and @rharding6373)

___
*[pkg/sql/sem/tree/type_check.go, line 2614 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78287#-MynC8DT3XSlNW9fNZZP:-MynC8DT3XSlNW9fNZZQ:b-d3ny9y) ([raw file](https://github.com/cockroachdb/cockroach/blob/44adf92165ec7942b0a74b4cb4a8e1c56b53e31d/pkg/sql/sem/tree/type_check.go#L2614)):*
> ```Go
> 
> // isNullOrAnnotatedNullTuple returns true if the given expression is a DNull or
> // a DNull that is wrapped by an AnnotateTypeExpr with a tuple type.
> ```

Do we need to care about `CastExpr` too?

**Review by rharding6373 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78287#-:-MynKOvi7XGDwhSxtLQG:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rafiss)

**Comment by mgartner** [comment]
___
*[pkg/sql/sem/tree/type_check.go, line 2614 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78287#-MynC8DT3XSlNW9fNZZP:-MynKS4f35Lcs5pyiihR:bmprvhi) ([raw file](https://github.com/cockroachdb/cockroach/blob/44adf92165ec7942b0a74b4cb4a8e1c56b53e31d/pkg/sql/sem/tree/type_check.go#L2614)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Do we need to care about `CastExpr` too?
</blockquote></details>

Yes, good point. However, only the AnnotateTypedExpr will cause internal errors like in #74729 because those are added by the system in some cases. I guess we do synthesize casts in some cases too, so maybe they could case internal errors.

File: pkg/sql/sem/tree/type_check.go [hunk 1]
```diff
@@ -2607,6 +2610,24 @@ func checkTupleHasLength(t *Tuple, expectedLen int) error {
 	return nil
 }
 
+// isNullOrAnnotatedNullTuple returns true if the given expression is a DNull or
+// a DNull that is wrapped by an AnnotateTypeExpr with a tuple type.
+func isNullOrAnnotatedNullTuple(
```
Comment (rafiss) [inline pkg/sql/sem/tree/type_check.go:2615]: do you know nulls annotated as other types don't cause a problem? if so, maybe explain here or in the commit message.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78287)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss and @yuzefovich)

___
*[pkg/sql/sem/tree/type_check.go, line 2614 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78287#-MynC8DT3XSlNW9fNZZP:-MyrONZO4ZYbHreo0m7H:b-h5l78g) ([raw file](https://github.com/cockroachdb/cockroach/blob/44adf92165ec7942b0a74b4cb4a8e1c56b53e31d/pkg/sql/sem/tree/type_check.go#L2614)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Yes, good point. However, only the AnnotateTypedExpr will cause internal errors like in #74729 because those are added by the system in some cases. I guess we do synthesize casts in some cases too, so maybe they could case internal errors.
</blockquote></details>

I looked into solving for the `CastExpr` too, but it's quite a bit more invovled. I've created an issue to track, #78331, which is part of a larger, longer-term initiative, #75101.
___
*[pkg/sql/sem/tree/type_check.go, line 2615 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78287#-MynBW2K9jEpGL5r00rp-r1-2615:-MyrRZAb66GBQaMGX4K9:b-srcu3b) ([raw file](https://github.com/cockroachdb/cockroach/blob/44adf92165ec7942b0a74b4cb4a8e1c56b53e31d/pkg/sql/sem/tree/type_check.go#L2615)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

do you know nulls annotated as other types don't cause a problem? if so, maybe explain here or in the commit message.
</blockquote></details>

They aren't a problem because if the user supplies them, they would fail type-checking, and the system should never synthesize them (this would cause an internal error during execution). I've updated the comment.

Also, I noticed that the error message when an annotated `NULL` fails type-checking is confusing, so I've created an issue to track: #78335.

**Comment by mgartner** [comment]
@rafiss did you want to take another look before I merge?

**Comment by rafiss** [comment]
lgtm!

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Comment by mgartner** [comment]
Looks like a flake.

bors r+
