### PR TITLE
testserver: disable tenant randomization under race in multi-node clusters

### LINKED ISSUE #115619: pkg/sql/physicalplan: TestFakeSpanResolver fails under remote execution
I suspect this is an OOM.

Example invocation: https://tanzanite.cluster.engflow.com/invocations/default/664ea78e-40a4-4e00-bc76-05ed574dcd8a?testReportShard=44&testReportRun=3&testReportAttempt=0#highlights

Epic: CRDB-8308

Jira issue: CRDB-34130

### PR DESCRIPTION
**Pull request by yuzefovich**
We now run `race` builds in the EngFlow environment which has either 1 CPU or 2 CPU executors. If we have a multi-node cluster and then start a default test tenant, then it's very likely for that environment to be overloaded and lead to unactionable test failures. This commit prevents this from happening by disabling the tenant randomization under race in multi-node clusters. As a result, it optimistically unskips a few tests that we skipped due to those unactionable failures.

Fixes: #115619.

Release note: None

### CODE REVIEW

File: pkg/testutils/serverutils/test_server_shim.go [hunk 1]
```diff
@@ -108,6 +108,14 @@ func ShouldStartDefaultTestTenant(
 		return baseArg
 	}
 
+	if multiNodeCluster && util.RaceEnabled {
```
Comment (stevendanna) [inline pkg/testutils/serverutils/test_server_shim.go:111]: Should include `syncutil.DeadlockEnabled` in this conditional?

File: pkg/testutils/serverutils/test_server_shim.go [hunk 2]
```diff
@@ -108,6 +108,14 @@ func ShouldStartDefaultTestTenant(
...
+		// Race builds now run in the EngFlow environment which seems to be
+		// often overloaded if we have multi-node clusters and start default
+		// test tenant, so we disable the tenant randomization in such a
```
Comment (stevendanna) [inline pkg/testutils/serverutils/test_server_shim.go:114]: start -> start [a|the]

File: pkg/testutils/serverutils/test_server_shim.go [hunk 3]
```diff
@@ -108,6 +108,14 @@ func ShouldStartDefaultTestTenant(
...
+		// scenario.
+		return base.InternalNonDefaultDecision(baseArg, false /* enable */, false /* shared */)
+	}
```
Comment (stevendanna) [inline pkg/testutils/serverutils/test_server_shim.go:117]: Could we put this under the `testTenantDecisionFromEnvironment` block so it is possible to run a test under race with tenants enabled locally still?

**Review by stevendanna — APPROVED** [review]
Thanks for following up on this discussion. I like this overall strategy.

Comments are non-blocking and left to your judgement.

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116910#-:-NmCkPEg092uo0GJSqBH:b-oduykh)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @stevendanna)

___
*[`pkg/testutils/serverutils/test_server_shim.go` line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116910#gh-1433869905:-NmCj6uJ4-ARlMZGGkBE:b-j5uaxy) ([raw file](https://github.com/cockroachdb/cockroach/blob/12555e772554a28f8ac12d395ac5712e32ac5ad7/pkg/testutils/serverutils/test_server_shim.go#L111)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Should include `syncutil.DeadlockEnabled` in this conditional?
</blockquote></details>

I don't think I've seen evidence of problems under deadlock yet, so I'll lean on the side of caution and not include it for now.
___
*[`pkg/testutils/serverutils/test_server_shim.go` line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116910#gh-1433870435:-NmCisqm8M_0f3KNXZ_u:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/12555e772554a28f8ac12d395ac5712e32ac5ad7/pkg/testutils/serverutils/test_server_shim.go#L114)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

start -> start [a|the]
</blockquote></details>

Done.
___
*[`pkg/testutils/serverutils/test_server_shim.go` line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116910#gh-1433873166:-NmCj5UTBpiDVIo1RoNA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/12555e772554a28f8ac12d395ac5712e32ac5ad7/pkg/testutils/serverutils/test_server_shim.go#L117)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Could we put this under the `testTenantDecisionFromEnvironment` block so it is possible to run a test under race with tenants enabled locally still?
</blockquote></details>

Done.
