### PR TITLE
engine: just ignore 'lost+found' dir

### LINKED ISSUE #20564: storage: consider ux of root-owned lost+found directory
On Linux, and probably other Unixes, a `lost+found` directory is automatically created by fsck at the root of some filesystems and is typically only accessible by root. If `lost+found` exists within a Cockroach store directory, Cockroach will be unable to compute the store capacity and refuse to boot.

This is an obvious and easy-to-fix error if the `lost+found` directory exists when the sysadmin chooses a filesystem root as the store dir; the sysadmin will (hopefully) see the error and choose a store dir that is _not_ the filesystem root.

The UX surprise occurs when the `lost+found` directory does not exist when the store dir is chosen. The node will run fine, potentially surviving normal reboots, but if the node ever crashes or if the OS schedules an fsck for some other reason, a `lost+found` directory will be automatically created in Cockroach's store dir and prevent node reboot.

Potential solutions:

  * Special-case lost+found and ignore it when computing store capacity.
  * Ignore all files in the store directory that we don't have permission to see.
  * Detect if we're running at the root of a filesystem and refuse to start.
  * Just document that you shouldn't run at the root of a filesystem.

/cc @dt @a-robinson

### PR DESCRIPTION
**Pull request by dt**
Release note: ignore filesytem-generated "lost+found" directory if it appears in store-dir

Fixes #20564.

### CODE REVIEW

**Review by a-robinson — APPROVED** [review]
LGTM. I wonder if we should just go back to ignoring all errors here -- I think the worst thing that could happen is that you'd get back an incorrect capacity estimate if we ignored a more meaningful error. This is fine though.

File: pkg/storage/engine/rocksdb.go [hunk 1]
```diff
@@ -672,6 +672,12 @@ func (r *RocksDB) Capacity() (roachpb.StoreCapacity, error) {
 			if os.IsNotExist(err) {
 				return nil
 			}
+			// Special-case: if the store-dir is configured using the root of some fs,
+			// e.g. "/mnt/db", we might have special fs-created files like lost+found
+			// that we can't read, so just ignore them rather than crashing.
+			if os.IsPermission(err) && strings.HasSuffix(path, "lost+found") {
```
Comment (benesch) [inline pkg/storage/engine/rocksdb.go]: nit: `filepath.Base`?

**Review by benesch — APPROVED** [review]

**Comment by bdarnell** [comment]
:lgtm:

I'd also be OK with ignoring errors here and only counting accessible files. 

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20565#-:-L00Ry9oZ63f5zJK7th6:bten5ag)*
