### PR TITLE
ui: fix when search contains *

### LINKED ISSUE #81695: ui: searching for `*` in stmts/txns pages crashes page
In the statements and transactions fingerprints pages in SQL Activity, searching for a string containing `*` will crash the page.

This is due to the creation of a regex expression from the search string in the `getHighlightedText` function used in the stmts/txns tables to highlight words in the search string. We should escape the `*` char to avoid creating a malformed regex expr.

https://github.com/cockroachdb/cockroach/blob/1d09af89020b13f1afe56df46d91f641bb8e56a9/pkg/ui/workspaces/cluster-ui/src/highlightedText/highlightedText.tsx#L70

### PR DESCRIPTION
**Pull request by maryliag**
Previously, when searching for * on statement
and transaction pages, the pages would crash.
This commit fixes this issue by using the literal
value * during the regex for highlighting the text.

Fixes #81695

Release note (bug fix): Statement and Transaction pages no longer
crash when search term includes '*'.

### CODE REVIEW

**Review by THardy98 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81988#-:-N3K7U_CB7OzdjIcJXUb:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

File: pkg/ui/workspaces/cluster-ui/src/highlightedText/highlightedText.tsx [hunk 1]
```diff
@@ -83,6 +86,12 @@ export function getHighlightedText(
   const search = highlight
     .split(" ")
     .map(val => {
+      // When it's only a character we want to make sure to use the literal value (by adding []),
+      // this is added to handle cases where the highlighted term is a character used normally
+      // in regex, such as '*', '+', '?'
+      if (val.length == 1) {
```
Comment (knz) [inline pkg/ui/workspaces/cluster-ui/src/highlightedText/highlightedText.tsx:92]: This is likely to produce a strange result if the character is `\` or `^`.
Are you sure about this?

Comment (knz) [reply pkg/ui/workspaces/cluster-ui/src/highlightedText/highlightedText.tsx:92]: A regular expression with the syntax `[\]` is incorrect: it's malformed. The proper syntax should be `[\\]` if you want to match `\`.

A regular expression with the syntax `[^]` matches "everything except the characters after `^`", in this case there is o character so `[^]` is equivalent to `.` (i.e. match anything). The proper syntax to match `^` is ... just `^` or `[\^]`.

**Comment by knz** [comment]
Also the search would also be invalid if the user enters the single character `-` which would result into `[-]` which, for some regexp engines, means "every chacter" too.

**Comment by knz** [comment]
Maybe one solution to move forward is to change the code to do `"\\" + charToSearch` instead of `"[" + charToSearch + "]"` - I think it would cover more grounds.

**Comment by maryliag** [comment]
@knz thanks for the suggestion, it was really helpful, because when I created tests I noticed that we don't highlight special characters, we have a list to ignore them, but for some reason `*` and `ˆ` were not on that list, which was causing the bug I was trying to fix here. I created a new PR to simply update the ignore list and also added the tests for that function https://github.com/cockroachdb/cockroach/pull/82081
