### PR TITLE
release-22.1: kvserver: amortize limiter.WaitN in range scan

### LINKED ISSUE #89695: kvserver: make more coarse, or remove consistency checking rate limit
**Describe the problem**
In a profile, I see us spending as long waiting for quota as we do hashing data. That's wrong. The problem, as far as I can tell, is that we're synchronizing on every single row. That's silly. We should allocate batches of capacity, perhaps a few hundred kilobytes at a time, and wait for that. 
Screen Shot 2022-10-10 at 4 52 55 PM

Jira issue: CRDB-20380

### PR DESCRIPTION
**Pull request by pav-kv**
Backport 1/1 commits from #91389.

/cc @cockroachdb/release

---

This commit reduces the relative cost of quota acquisitions in consistency checker's range scan, by requesting it in chunks of at least 256 KiB at a time.

Fixes #89695

Release note: None
Release justification: performance improvement

### CODE REVIEW

File: pkg/kv/kvserver/replica_consistency.go [hunk 1]
```diff
@@ -55,11 +55,11 @@ const replicaChecksumGCInterval = time.Hour
 
 // fatalOnStatsMismatch, if true, turns stats mismatches into fatal errors. A
 // stats mismatch is the event in which
-// - the consistency checker finds that all replicas are consistent
-//   (i.e. byte-by-byte identical)
-// - the (identical) stats tracked in them do not correspond to a recomputation
-//   via the data, i.e. the stats were incorrect
-// - ContainsEstimates==false, i.e. the stats claimed they were correct.
+//   - the consistency checker finds that all replicas are consistent
```
Comment (pavelkalinnikov) [inline pkg/kv/kvserver/replica_consistency.go:58]: My IDE reformatted this comment, will revert manually.

File: pkg/kv/kvserver/replica_consistency.go [hunk 2]
```diff
@@ -659,6 +672,11 @@ func (*Replica) sha512(
 				iter, span.Start, span.End, 0 /* nowNanos */, visitor,
 			)
 			iter.Close()
+			// Consume the remaining quota borrowed in the visitor. Do it even on
+			// iteration error, but prioritize returning the latter if it occurs.
+			if wErr := limiter.WaitN(ctx, batchSize); wErr != nil && err == nil {
```
Comment (pavelkalinnikov) [inline pkg/kv/kvserver/replica_consistency.go:677]: This is called multiple times (but only a few, as many as spans `MakeReplicatedKeyRangesExceptLockTable` returns), but I figured that it's ok to do a simple copy of this code block instead of trying to call it once.

Comment (erikgrinaker) [reply pkg/kv/kvserver/replica_consistency.go:677]: That's fine, it's only about four spans or so.

**Review by erikgrinaker — APPROVED** [review]

**Comment by pavelkalinnikov** [comment]
Can't get CI to build, it consistently fails on `TestComposeGSS` which seems unrelated.

**Comment by erikgrinaker** [comment]
That test is broken, and was recently skipped. Rebase onto latest release-22.2 to pick it up.
