### PR TITLE
tablemetadatacache: write span stats failures to last_update_error

### LINKED ISSUE #130040: sql/tablemetadatacache: add batch failure handling logic to update table metadata job
Follow up to https://github.com/cockroachdb/cockroach/issues/128993 which updates system.table_metadata in batches. We should add logic to handle cases where a batched metadata collection fails. If a batch fails, we can try in smaller batches or splitting the system.descriptor collection from the span stats RPCs for partial success.

Edit: We'll likely opt for a simpler retry behaviour for the first iteration of this job, which will simply be to retry the query for the failed batch with exponential backoff.

Edit 2: I think retry will be too slow, e.g. if a node is unavailable and there are a lot of batches the job will take a long time to fully complete since it'll retry and fail on every batch. Instead, let's just write the last_error and leave it at that. The entire job can be retried at a later time.

Epic CRDB-37558

Jira issue: CRDB-41848

### PR DESCRIPTION
**Pull request by xinhaoz**
Only the latest commit is for review in this PR.

----------------------------------------

The span stats rpc fan out can contain errors in the
response. Some examples include node dial errors,
or error responses from different nodes. In those cases
we should write the error for the batch to the
last_update_error column and go on to the next batch.

To support reading the errors from the span stats response
we have now split the span stats request off from the query
fetching descriptor information for the batch. Span stats
are now fetched per batch by issuing an rpc request directly
on the span stats server.

Epic: CRDB-37558
Fixes: https://github.com/cockroachdb/cockroach/issues/130040

Release note: None

Release note: None

### CODE REVIEW

File: pkg/sql/tablemetadatacache/table_metadata_batch_iterator.go [hunk 1]
```diff
@@ -184,52 +197,81 @@ func (batchIter *tableMetadataBatchIterator) fetchNextBatch(
...
 	}
 
+	// Collect the span stats for the tables in the batch.
+	res, err := batchIter.spanStatsFetcher.SpanStats(ctx, &roachpb.SpanStatsRequest{
+		Spans:  spans,
+		NodeID: "0", // Fan out.
+	})
+
+	if err != nil {
+		return false, err
```
Comment (kyle-a-wong) [inline pkg/sql/tablemetadatacache/table_metadata_batch_iterator.go:207]: Should we also return `len(batchIter.batchRows) > 0` instead of false here, or do we want to abort the run if there is an error from the SpanStats call? It may be worth continuing to try and update as many rows as possible, instead failing the whole job

File: pkg/sql/tablemetadatacache/table_metadata_updater.go [hunk 2]
```diff
@@ -82,30 +92,31 @@ func (u *tableMetadataUpdater) updateCache(ctx context.Context) (updated int, er
...
 	estimatedRowsToUpdate, err := u.getRowsToUpdateCount(ctx)
 	if err != nil {
 		log.Errorf(ctx, "failed to get estimated row count. err=%s", err.Error())
 	}
 	estimatedBatches := int(math.Ceil(float64(estimatedRowsToUpdate) / float64(tableBatchSize)))
 	batchNum := 0
 	for {
-		more, err := it.fetchNextBatch(ctx, tableBatchSize)
+		more, batchErr := it.fetchNextBatch(ctx, tableBatchSize)
 		if err != nil {
```
Comment (kyle-a-wong) [inline pkg/sql/tablemetadatacache/table_metadata_updater.go:104]: Should this change to:
```suggestion
		if batchErr != nil {
```

File: pkg/sql/tablemetadatacache/table_metadata_updater.go [hunk 3]
```diff
@@ -304,13 +329,44 @@ func (q *tableMetadataBatchUpsertQuery) addRow(
...
+table_name = EXCLUDED.table_name,
+last_update_error = EXCLUDED.last_update_error;
+`)
+	} else {
+		q.stmt.WriteString(`
+ON CONFLICT (db_id, table_id)
+DO UPDATE
+SET
+	db_name = EXCLUDED.db_name,
+  schema_name = EXCLUDED.schema_name,
```
Comment (kyle-a-wong) [inline pkg/sql/tablemetadatacache/table_metadata_updater.go:355]: nit: indentation

File: pkg/sql/tablemetadatacache/testdata/update_table_metadata_errors [hunk 4]
```diff
@@ -0,0 +1,309 @@
...
+query
+SELECT
+  db_id,
+  table_id
+  db_name,
+  table_name,
+  store_ids,
+  total_ranges,
+  last_updated,
+  last_update_error
```
Comment (kyle-a-wong) [inline pkg/sql/tablemetadatacache/testdata/update_table_metadata_errors:89]: nit: should we include all the deterministic columns here, like we do in the non-failure case query to ensure that everything is updated correctly after an error

**Review by kyle-a-wong — COMMENTED** [review]
Mostly looks good. Just have a couple comments / questions

File: pkg/sql/tablemetadatacache/testdata/update_table_metadata_errors (hunk 4 above)
Comment (xinhaoz) [reply pkg/sql/tablemetadatacache/testdata/update_table_metadata_errors]: Done.

File: pkg/sql/tablemetadatacache/table_metadata_updater.go (hunk 3 above)
Comment (xinhaoz) [reply pkg/sql/tablemetadatacache/table_metadata_updater.go:355]: Done.

File: pkg/sql/tablemetadatacache/table_metadata_updater.go (hunk 2 above)
Comment (xinhaoz) [reply pkg/sql/tablemetadatacache/table_metadata_updater.go]: Ah yes, good catch. Done. Also added test coverage for this conditional section.

File: pkg/sql/tablemetadatacache/table_metadata_batch_iterator.go (hunk 1 above)
Comment (xinhaoz) [reply pkg/sql/tablemetadatacache/table_metadata_batch_iterator.go]: Yeah that sounds good to me. Done.

**Review by kyle-a-wong — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132255)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @angles-n-daemons and @xinhaoz)

___
*[`pkg/sql/tablemetadatacache/testdata/update_table_metadata_errors` line 100 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132255#-O8wAYa6DBjL0PXVuQI6:-O8wAYa6DBjL0PXVuQI7:byw25j2) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc9f93d2ef470ca6d98dfc17e7ba4cfb15e3067f/pkg/sql/tablemetadatacache/testdata/update_table_metadata_errors#L100)):*
> ```
> ORDER BY (db_name, table_name)
> ----
> unknown command
> ```

Looks like theres a bug in the data driven test

**Review by kyle-a-wong — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132255)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @angles-n-daemons and @xinhaoz)

___
*[`pkg/sql/tablemetadatacache/testdata/update_table_metadata_errors` line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132255#-O8wB2Vk3clwUi9tcBlP:-O8wB2Vk3clwUi9tcBlQ:b1kl8a4) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc9f93d2ef470ca6d98dfc17e7ba4cfb15e3067f/pkg/sql/tablemetadatacache/testdata/update_table_metadata_errors#L81)):*
> ```
> 
> # Now the last_update_error column should be nil and data
> // should be updated.
> ```

I think this needs to be changed to `# should be updated`

**Comment by xinhaoz** [comment]
*[`pkg/sql/tablemetadatacache/testdata/update_table_metadata_errors` line 100 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132255#-O8wAYa6DBjL0PXVuQI6:-O8wCXHU3UUWEm_D3x1C:b-jqxixg) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc9f93d2ef470ca6d98dfc17e7ba4cfb15e3067f/pkg/sql/tablemetadatacache/testdata/update_table_metadata_errors#L100)):*
<details><summary><i>Previously, kyle-a-wong (Kyle Wong) wrote…</i></summary><blockquote>

Looks like theres a bug in the data driven test
</blockquote></details>

That was due to the comment typo.

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132255)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @angles-n-daemons and @kyle-a-wong)

___
*[`pkg/sql/tablemetadatacache/testdata/update_table_metadata_errors` line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132255#-O8wB2Vk3clwUi9tcBlP:-O8wCRHCC2Bv-eq1qFna:bw10jn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc9f93d2ef470ca6d98dfc17e7ba4cfb15e3067f/pkg/sql/tablemetadatacache/testdata/update_table_metadata_errors#L81)):*
<details><summary><i>Previously, kyle-a-wong (Kyle Wong) wrote…</i></summary><blockquote>

I think this needs to be changed to `# should be updated`
</blockquote></details>

Oops, done.

**Review by kyle-a-wong — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132255#-:-O8wCnbx-edZ4-3eiMN7:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @angles-n-daemons)

**Comment by xinhaoz** [comment]
TFTR!
bors r+
