### PR TITLE
remove uses of golang.org/x/exp/rand

### LINKED ISSUE #143614: remove uses of deprecated golang.org/x/exp/rand
For now I am adding an exception to this warning generated by staticcheck.

Jira issue: CRDB-48946

### PR DESCRIPTION
**Pull request by RaduBerinde**
This package is deprecated in favor of `math/rand/v2`.

Fixes #143614
Release note: None

### CODE REVIEW

File: pkg/workload/ycsb/zipfgenerator_test.go [hunk 1]
```diff
@@ -30,7 +29,7 @@ var gens = []params{
 func TestCreateZipfGenerator(t *testing.T) {
 	defer leaktest.AfterTest(t)()
 	for _, gen := range gens {
-		rng := rand.New(rand.NewSource(uint64(timeutil.Now().UnixNano())))
+		rng := rand.New(rand.NewPCG(rand.Uint64(), rand.Uint64()))
```
Comment (srosenberg) [inline pkg/workload/ycsb/zipfgenerator_test.go:32]: Interesting. The global source is seeded with AT_RANDOM [1].

[1] https://github.com/golang/go/blob/391dde29a37f3fd450f7d61e3f220930e0164b89/src/runtime/os_linux.go#L300-L314

**Review by srosenberg — APPROVED** [review]
Thanks!

**Review by herkolategan — APPROVED** [review]

**Comment by RaduBerinde** [comment]
TFTRs!

bors r+
