### PR TITLE
sql/parser: implement better type checking for variadic functions

### LINKED ISSUE #2964: sql: type system doesn't handle variadic functions
The builtin function `CONCAT` is defined (in CockroachDB, not elsewhere) as accepting variadic arguments, each of which must be a `DString` or `DNull`. Thus, it should be possible to fail the following case at type-checking time:
```sql
CREATE TABLE kv2 (k CHAR PRIMARY KEY, v INT NOT NULL);
-- OR
CREATE TABLE kv2 (k CHAR PRIMARY KEY, v INT);
SELECT CONCAT(k, v) FROM kv;
```
However, we currently do not pass around nullability in type information, which prevents this case from failing until run time.

### PR DESCRIPTION
**Pull request by tamird**
Fixes #2964.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3532)

### CODE REVIEW

File: sql/parser/builtins.go [hunk 1]
```diff
@@ -48,9 +48,15 @@ var errRoundNumberDigits = errors.New("number of digits must be greater than 0")
 type typeList []reflect.Type
 
 type builtin struct {
-	// Set to typeList{} for nullary functions and to nil for varidic
-	// functions.
+	// Variadic functions have a tricky representation:
+	// - If all arguments must be of a specific type, `types` must be
+	// `typeList{<theType>}`, and `variadic` must be true. This will
+	// generate the correct type-checking error.
+	// - If all arguments must be of the same (variable) type, `types`
```
Comment (petermattis) [inline sql/parser/builtins.go]: This comment seems to be out-of-sync with the code. I'm not seeing where you support a `nil` types field.

**Comment by petermattis** [comment]
LGTM

File: sql/parser/builtins.go (hunk 1 above)
Comment (tamird) [inline sql/parser/builtins.go]: L71

Comment (petermattis) [inline sql/parser/builtins.go]: Ah, this was existing code. You don't seem to use this with `variadic == true` which made this comment slightly confusing as it is now written.

Comment (tamird) [inline sql/parser/builtins.go]: Yeah, I'm open to rewording suggestions; that `variadic == true` is not used is what I mean when I say `This representation is not quite "normal", sorry about that.` in the comment

Comment (petermattis) [inline sql/parser/builtins.go]: Oh, that's what that comment meant. It might be worth regularizing (normalizing) the code more. For example, instead of a `variadic` field, we could make `typeList` an interface:

```
type argTypes []reflect.Type

type typeList interface {
  match(types argTypes) bool
}

func (a argTypes) match(types argTypes) bool {
  // Match `a` and `types`.
}

type anyType struct{}

func (anyType) match(types argTypes) bool {
  return true
}

type variadicType reflect.Type

func (v variadicType) match(types argTypes) bool {
  // Match `v` against `types`.
}
```

Comment (tamird) [inline sql/parser/builtins.go]: Yeah, that's much better. Done.

File: sql/parser/builtins.go [hunk 2]
```diff
@@ -45,11 +45,44 @@ var errEmptyInputString = errors.New("the input string must not be empty")
...
+	return true
+}
+
+type variadicType struct {
+	typ reflect.Type
+}
+
+func (v variadicType) match(types argTypes) bool {
+	for _, typ := range types {
+		if !(typ == nullType || typ == v.typ) {
```
Comment (petermattis) [inline sql/parser/builtins.go]: Should comment above `variadicType` the behavior for `NULL` arguments.

**Comment by petermattis** [comment]
LGTM

File: sql/parser/builtins.go (hunk 2 above)
Comment (tamird) [inline sql/parser/builtins.go]: done
