### PR TITLE
changefeedccl: make TestChangefeedJobUpdateFailsIfNotClaimed less flaky

### LINKED ISSUE #144912: ccl/changefeedccl: TestChangefeedJobUpdateFailsIfNotClaimed failed
ccl/changefeedccl.TestChangefeedJobUpdateFailsIfNotClaimed [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/19506672?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/19506672?buildTab=artifacts#/) on master @ [18b42de2ab0bd242c0fa9334d1ba1e90566d7683](https://github.com/cockroachdb/cockroach/commits/18b42de2ab0bd242c0fa9334d1ba1e90566d7683):

```
=== RUN   TestChangefeedJobUpdateFailsIfNotClaimed
    test_log_scope.go:165: test logs captured to: /artifacts/tmp/_tmp/8db35d09d3aa97ee0974c3c6b3b5529d/logTestChangefeedJobUpdateFailsIfNotClaimed326187133
    test_log_scope.go:76: use -show-logs to present logs inline
    changefeed_test.go:6195: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/8db35d09d3aa97ee0974c3c6b3b5529d/logTestChangefeedJobUpdateFailsIfNotClaimed326187133
--- FAIL: TestChangefeedJobUpdateFailsIfNotClaimed (5.74s)
=== RUN   TestChangefeedJobUpdateFailsIfNotClaimed/kafka
    helpers_test.go:1043: making server as system tenant
    helpers_test.go:1119: making kafka feed factory
    changefeed_test.go:6189: expected distflow to fail
--- FAIL: TestChangefeedJobUpdateFailsIfNotClaimed/kafka (5.72s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestChangefeedJobUpdateFailsIfNotClaimed.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-49604

### PR DESCRIPTION
**Pull request by rharding6373**
Recent changes to make changefeed.resolved_timestamp.granularity metamorphic has made tests more flaky due to causing more timeouts. TestChangefeedJobUpdateFailsIfNotClaimed was especially flaky, but its timeout is improved by accounting for
changefeed.resolved_timestamp.granularity.

Epic: none
Fixes: #144912

Release note: none

### CODE REVIEW

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 1]
```diff
@@ -6175,7 +6173,8 @@ func TestChangefeedJobUpdateFailsIfNotClaimed(t *testing.T) {
 		// another node.
 		sqlDB.Exec(t, `UPDATE system.jobs SET claim_session_id = NULL WHERE id = $1`, jobID)
 
-		timeout := 5 * time.Second
+		timeout := (5 * time.Second) + changefeedbase.Quantize.Get(&s.Server.ClusterSettings().SV)
+
 		if util.RaceEnabled {
 			timeout = 30 * time.Second
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_test.go:6179]: Do we need to add the quantization factor here too?

**Review by andyyang890 — APPROVED** [review]

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 2]
```diff
@@ -6175,7 +6173,8 @@ func TestChangefeedJobUpdateFailsIfNotClaimed(t *testing.T) {
 		// another node.
 		sqlDB.Exec(t, `UPDATE system.jobs SET claim_session_id = NULL WHERE id = $1`, jobID)
 
-		timeout := 5 * time.Second
+		timeout := (5 * time.Second) + changefeedbase.Quantize.Get(&s.Server.ClusterSettings().SV)
```
Comment (aerfrei) [inline pkg/ccl/changefeedccl/changefeed_test.go:6176]: I'm seeing from this PR https://github.com/cockroachdb/cockroach/pull/144668 that the quantization is set to up to 20 or 30 seconds. Could lowering that amount help with general flakiness from this?

Comment (rharding6373) [reply pkg/ccl/changefeedccl/changefeed_test.go:6176]: I reset the unit test metamorphic value max to 10s yesterday to reduce flakiness in other tests, but haven't rerun this test with that change yet since it's skipped on master. I doubt it will help in all cases, since the timeout in this test is lower than the max quantization.

File: pkg/ccl/changefeedccl/changefeed_test.go (hunk 1 above)
Comment (rharding6373) [reply pkg/ccl/changefeedccl/changefeed_test.go]: Done.

**Comment by rharding6373** [comment]
TFTR!

bors r=andyyang890
