### PR TITLE
storage: update descriptor after batch commits.

### LINKED ISSUE #7851: storage: Replica.changeReplicasTrigger sets descriptor inappropriately
`Replica.changeReplicasTrigger` sets the updated range descriptor (via a call to `Replica.setDesc`) before the corresponding batch is committed. If the batch fails to commit for some reason the Replica will be in an inconsistent state. This also differs from the behavior of `Replica.splitTrigger` which updates the range descriptors in a `batch.Defer`. We should modify `changeReplicasTrigger` to use a `batch.Defer` as well.

### PR DESCRIPTION
**Pull request by jordanlewis**
Fixes #7851.

Defer update of a replica's range descriptor during a change replicas operation until after its batch completes. Previously, if the batch containing a change replicas operation failed, the range  descriptor would be updated regardless, leading to an inconsistent state for the relevant Replica.

The error handling in this patch seems anemic, but I'm not sure what I can do better. If we finish committing the batch but fail to update the range descriptor for some reason, what should happen?

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7883)

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM. I don't think there's much to do in that case - if the Store let a Replica perform a change that conflicts with the Store in the end, we have a serious bug, and at least that Store is corrupted (obviously it would be pretty fatal if all stores failed in that way in unison, but there will always be some code paths like that and this is one of them).
BTW, I'm hacking on some stuff right now that would perhaps allow the Store itself to carry out most of the things in the `defer`, making the effect somewhat more local (which could open some error handling venue at least for some possible failures).

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7883#-:-KMylgTIYfm6-EfwSaiv:1873323215)*

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7883)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/replica_command.go, line 2835 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7883#-KMym5cga4cN47to8WYR:-KMym5cga4cN47to8WYS:1307491779) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a63c07d12af55e3633212a606667f404731d9c0/storage/replica_command.go#L2835)):*
> ```Go
> 		if err := r.setDesc(&cpy); err != nil {
> 			// Log the error. There's not much we can do because the commit may have already occurred at this point.
> 			log.Fatalf("failed to update Store after change replica: %s", err)
> ```

Add more information about which one failed. For example, log `cpy`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7883)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[storage/replica_command.go, line 2835 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7883#-KMym5cga4cN47to8WYR:-KMyy_hWBb7GRoYYcw0I:1118713925) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a63c07d12af55e3633212a606667f404731d9c0/storage/replica_command.go#L2835)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Add more information about which one failed. For example, log `cpy`.
</details>
Let's put the identifier (the store/range) as the first part of the log message to match up with Arjun's inflight change. I think this can be something like:

```
log.Fatalf("%s: failed to update range descriptor to %+v: %s", r, cpy, err)
```

`batch.Defers` are run in LIFO order, like Go defers. I think we want this defer to be moved to the end of this method so that it occurs before the `replicaGCQueue` defer.

Do we have a test that a removed replica is added to the replica GC queue? Let's file an issue if not.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7883)*

**Comment by jordanlewis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/replica_command.go, line 2835 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7883#-KMym5cga4cN47to8WYR:-KMzQfwEb2Akb83s5U61:723746886) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a63c07d12af55e3633212a606667f404731d9c0/storage/replica_command.go#L2835)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Let's put the identifier (the store/range) as the first part of the log message to match up with Arjun's inflight change. I think this can be something like:
> 
> ```
> log.Fatalf("%s: failed to update range descriptor to %+v: %s", r, cpy, err)
> ```
> 
> `batch.Defers` are run in LIFO order, like Go defers. I think we want this defer to be moved to the end of this method so that it occurs before the `replicaGCQueue` defer.
> 
> Do we have a test that a removed replica is added to the replica GC queue? Let's file an issue if not.
</details>
It seems that there is just one test relating to ChangeReplicas in replica_test.go that  ensures that we can't duplicate replicas. There are other tests for ChangeReplicas elsewhere, but it doesn't look like anything verifies that removed replicas get added to the GC queue, at least in the ChangeReplicas code path.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7883)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/replica_command.go, line 2835 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7883#-KMym5cga4cN47to8WYR:-KMzZ6mzOeevjyBAsdmi:432560900) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a63c07d12af55e3633212a606667f404731d9c0/storage/replica_command.go#L2835)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary>
> It seems that there is just one test relating to ChangeReplicas in replica_test.go that  ensures that we can't duplicate replicas. There are other tests for ChangeReplicas elsewhere, but it doesn't look like anything verifies that removed replicas get added to the GC queue, at least in the ChangeReplicas code path.
</details>
I filed #7893.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7883)*

File: storage/replica_command.go [hunk 1]
```diff
@@ -2858,7 +2850,15 @@ func (r *Replica) changeReplicasTrigger(ctx context.Context, batch engine.Batch,
 			r.store.splitQueue.MaybeAdd(r, r.store.Clock().Now())
 		})
 	}
-	return nil
+	batch.Defer(func() {
+		cpy := *r.Desc()
+		cpy.Replicas = change.UpdatedReplicas
+		cpy.NextReplicaID = change.NextReplicaID
+		if err := r.setDesc(&cpy); err != nil {
+			// Log the error. There's not much we can do because the commit may have already occurred at this point.
```
Comment (tamird) [inline storage/replica_command.go]: This comment is misleading at best; log.Fatalf is about to end the process.
