### PR TITLE
backupccl: fix progress updating test

### LINKED ISSUE #57831: ccl/backupccl: TestBackupRestoreSystemJobsProgress failed
[(ccl/backupccl).TestBackupRestoreSystemJobsProgress failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2513569&tab=buildLog) on [master@3cd932db33c133bff6a298f25d2516ecce1a2f54](https://github.com/cockroachdb/cockroach/commits/3cd932db33c133bff6a298f25d2516ecce1a2f54):

```
=== RUN   TestBackupRestoreSystemJobsProgress
    test_log_scope.go:72: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestBackupRestoreSystemJobsProgress204890354
    test_log_scope.go:73: use -show-logs to present logs inline
    backup_test.go:1366: expected progress to be in range [0.25, 0.75] but got 0.200000
E201211 16:29:28.693480 102662 kv/kvclient/kvcoord/txn_interceptor_committer.go:449  making txn commit explicit failed for "unnamed" meta={id=68ff1924 pri=0.06312649 epo=0 ts=1607704168.593859468,0 min=1607704168.593859468,0 seq=6} lock=true stat=STAGING rts=1607704168.593859468,0 wto=false max=1607704168.593859468,0 int=1 ifw=5: result is ambiguous (server shutdown)
E201211 16:29:28.730435 94231 jobs/registry.go:662  error processing claimed jobs: could query for claimed jobs: select-running/get-claimed-jobs: context canceled
    panic.go:636: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestBackupRestoreSystemJobsProgress204890354
--- FAIL: TestBackupRestoreSystemJobsProgress (62.37s)

```

<details><summary>More</summary><p>
Parameters:

- GOFLAGS=-json

```
make stressrace TESTS=TestBackupRestoreSystemJobsProgress PKG=./pkg/ccl/backupccl TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestBackupRestoreSystemJobsProgress.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by pbardea**
This test was previously flaky since it was assuming that backup would
issue the same number of requests as spans issued. This assumption was
incorrect, and fixing the progress accounting for backup revealed that
this test was faulty.

While planning the work distribution for backup worker nodes,
PartitionSpans automatically merges spans that are co-located on the
same node, therefore reducing the number of ExportRequests issued.
Before this commit, we used to block on the ExportRequest responses.
The blocking was triggered on a per-range-request level. However,
progress is only updated when the processor-level batch request is
returned. This meant that the test might block a batch request and
therefore the progress of the job would be less than what the test
expected.

This is now fixed by adjusting the blocking mechanism and range counting
to all be at the level of the merged ranges with which the backup
processor operates.

Fixes #57831.

This test would fail under stress pretty quickly (~40) -- I was able to get
over 600 runs without failure with this patch.

Release note: none

### CODE REVIEW

File: pkg/ccl/backupccl/backup_test.go [hunk 1]
```diff
@@ -1303,34 +1303,75 @@ func checkInProgressBackupRestore(
...
-				for _, ru := range br.Responses {
-					switch ru.GetInner().(type) {
-					case *roachpb.ExportResponse:
-						<-allowResponse
-					}
-				}
-				return nil
-			},
-		}}
+		DistSQL: &execinfra.TestingKnobs{
```
Comment (adityamaru) [inline pkg/ccl/backupccl/backup_test.go:1306]: Can we delete or edit the comment above, now that we do not install a store response filter.

**Review by adityamaru — APPROVED** [review]

File: pkg/ccl/backupccl/backup_test.go [hunk 2]
```diff
@@ -1303,34 +1303,75 @@ func checkInProgressBackupRestore(
...
 	defer cleanup()
 
 	sqlDB.Exec(t, `CREATE DATABASE restoredb`)
 
+	var totalExpectedBackupRequests int
+	// mergedRangeQuery calculates the number of spans we expect PartitionSpans to
+	// produce. It merges contiguous ranges on the same node.
+	// It sorts ranges by start_key and counts the number of times the
+	// lease_holder changes by comparing against the previous row's lease_holder.
+	mergedRangeQuery := `
```
Comment (adityamaru) [inline pkg/ccl/backupccl/backup_test.go:1331]: nice query, didn't even know you could do this kind of thing in SQL.

**Comment by pbardea** [comment]
TFTR!
bors r+
