### PR TITLE
changefeedccl: improve create changefeed error message

### LINKED ISSUE #137317: cdc: better error message if cursor is older than gc threshold
If a changefeed is created with a cursor that is older than the current GC threshold, the changefeed fails with the error `batch timestamp ... must be after replica GC threshold`. The reason for the failure could be made more clear to the user, e.g., "Could not create changefeed: cursor older than GC threshold X", and a hint could be added to advise the user on how far back a cursor could be set.

Repro:
```
create table t (i int, s string);
alter table t configure zone using gc.ttlseconds=10;
insert into t (i,s) values (1,'a'),(2,'b');
select extract(epoch from current_timestamp)::int;
// note result 
delete from t where i = 1;
// Wait at least 10s.
create changefeed for table t into <uri> with cursor='<result from above in ns>';
show changefeed jobs;
```

Jira issue: CRDB-45517

### PR DESCRIPTION
**Pull request by KeithCh**
Prevously if a user creates a changefeed with a cursor before the GC threshold they'd see

ERROR: failed to resolve targets in the CHANGEFEED stmt: batch timestamp 1541199412.324189000,0 must be after replica GC threshold 1740696773.366361000,0 (r9: /Table/{5-6})
HINT: do the targets exist at the specified cursor time 1541199412.324189000,0?

Now they'd see
ERROR: could not create changefeed: cursor 1741759425000000000 is older than the GC threshold 1741966895145639000: batch timestamp 1741759425.000000000,0 must be after replica GC threshold 1741966895.145639000,0 (r165: /Table/10{6-7})
HINT: use a more recent cursor

Resolves https://github.com/cockroachdb/cockroach/issues/137317

Release note (general): Improve the wording of error message when creating a changefeed with a cursor older than GC threshold.

### CODE REVIEW

File: pkg/ccl/changefeedccl/changefeed_stmt.go [hunk 1]
```diff
@@ -838,15 +841,22 @@ func getTableDescriptors(
...
 		}
 		err = errors.Wrap(err, "failed to resolve targets in the CHANGEFEED stmt")
 		if !initialHighWater.IsEmpty() {
 			// We specified cursor -- it is possible the targets do not exist at that time.
 			// Give a bit more context in the error message.
-			err = errors.WithHintf(err,
-				"do the targets exist at the specified cursor time %s?", initialHighWater)
+			if userSuppliedCursor && errors.As(err, &e) {
+				gcThreshold := e.Threshold.WallTime
+				err = errors.Newf("Could not create changefeed: cursor is older than the GC threshold %d", gcThreshold)
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_stmt.go:854]: nit: do not capitalize error messages

File: pkg/ccl/changefeedccl/changefeed_stmt.go [hunk 2]
```diff
@@ -838,15 +841,22 @@ func getTableDescriptors(
...
+				err = errors.WithHint(err, "Use a more recent cursor")
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_stmt.go:855]: nit: ditto about capitalization

File: pkg/ccl/changefeedccl/changefeed_stmt.go (hunk 1 above)
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_stmt.go:854]: might be useful if the error message contained the cursor too?

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 3]
```diff
@@ -5625,6 +5625,25 @@ func TestChangefeedDataTTL(t *testing.T) {
 	cdcTestWithSystem(t, testFn, feedTestForceSink("sinkless"), feedTestNoTenants)
 }
 
+// TestChangefeedOutdatedCursor ensures that create changefeeds fail with an error in the case
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_test.go:5628]: nit: s/create/creating

also, wrap comments at 80 characters and code at 100 characters unless doing so makes it less legible https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/181371303/Go+Golang+coding+guidelines#Code-comments

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 4]
```diff
@@ -5625,6 +5625,25 @@ func TestChangefeedDataTTL(t *testing.T) {
...
+// where the cursor is older than the GC TTL of the table.
+func TestChangefeedOutdatedCursor(t *testing.T) {
+	defer leaktest.AfterTest(t)()
+	defer log.Scope(t).Close(t)
+
+	testFn := func(t *testing.T, s TestServerWithSystem, f cdctest.TestFeedFactory) { // Create the data table; it will only contain a single row with multiple
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_test.go:5634]: nit: comment should go on its own line

File: pkg/ccl/changefeedccl/changefeed_stmt.go [hunk 5]
```diff
@@ -325,10 +326,16 @@ func changefeedPlanHook(
 		}
 	}
 
+	var e *kvpb.BatchTimestampBeforeGCError
 	rowFnLogErrors := func(ctx context.Context, resultsCh chan<- tree.Datums) error {
 		err := rowFn(ctx, resultsCh)
 		if err != nil {
 			logChangefeedFailedTelemetryDuringStartup(ctx, description, failureTypeForStartupError(err))
+			if errors.As(err, &e) && opts.HasStartCursor() {
+				err = errors.Newf("could not create changefeed: cursor %s is older than the GC threshold %d", opts.GetCursor(), e.Threshold.WallTime)
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_stmt.go:335]: My preference would be to wrap the original error (with `errors.Wrapf`) instead of replacing it

File: pkg/ccl/changefeedccl/changefeed_stmt.go [hunk 6]
```diff
@@ -325,10 +326,16 @@ func changefeedPlanHook(
 		}
 	}
 
+	var e *kvpb.BatchTimestampBeforeGCError
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_stmt.go:329]: Move the var declaration to right before the if statement (reduce scope whenever possible + keep declarations as close as reasonably possible to their usages)

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 7]
```diff
@@ -5625,6 +5625,25 @@ func TestChangefeedDataTTL(t *testing.T) {
 	cdcTestWithSystem(t, testFn, feedTestForceSink("sinkless"), feedTestNoTenants)
 }
 
+// TestChangefeedOutdatedCursor ensures that create changefeeds fail with an error in the case
+// where the cursor is older than the GC TTL of the table.
+func TestChangefeedOutdatedCursor(t *testing.T) {
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_test.go:5630]: This test appears to time out under stress on Bazel Essential CI and also in my local testing

File: pkg/ccl/changefeedccl/changefeed_test.go (hunk 3 above)
Comment (KeithCh) [reply pkg/ccl/changefeedccl/changefeed_test.go:5628]: hmm crlfmt does not change anything about my file at all

Comment (andyyang890) [reply pkg/ccl/changefeedccl/changefeed_test.go:5628]: It's not enforced by `crlfmt` but you should still do it when possible

File: pkg/ccl/changefeedccl/changefeed_test.go (hunk 7 above)
Comment (KeithCh) [reply pkg/ccl/changefeedccl/changefeed_test.go:5630]: Retested with options --stress --race

File: pkg/ccl/changefeedccl/helpers_test.go [hunk 8]
```diff
@@ -912,7 +912,7 @@ func expectErrCreatingFeed(
 	if err == nil {
 		t.Errorf("No error from %s", create)
 	} else {
-		require.Contains(t, err.Error(), errSubstring)
+		require.Regexp(t, errPattern, err.Error())
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/helpers_test.go:915]: You actually don't need to do a regex, it should be sufficient that the full error contains your error as a substring, i.e. `require.Contains` is fine

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 9]
```diff
@@ -5625,6 +5625,28 @@ func TestChangefeedDataTTL(t *testing.T) {
...
+		sqlDB := sqlutils.MakeSQLRunner(s.DB)
+
+		sqlDB.Exec(t, `CREATE TABLE f (a INT PRIMARY KEY)`)
+		outdatedTS := s.Server.Clock().Now().AsOfSystemTime()
+		sqlDB.Exec(t, `INSERT INTO f VALUES (1)`)
+		forceTableGC(t, s.SystemServer, sqlDB, "system", "descriptor")
+		createChangefeed := `CREATE CHANGEFEED FOR TABLE f with cursor = '` + outdatedTS + `'`
+		expectedErrorPattern := ".*could not create changefeed: cursor " + outdatedTS +
+			" is older than the GC threshold .*"
+		expectErrCreatingFeed(t, f, createChangefeed, expectedErrorPattern)
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_test.go:5644]: nit: prefer `fmt.Sprintf` over concatenation

**Review by andyyang890 — APPROVED** [review]
Nice work!

**Comment by KeithCh** [comment]
bors r=andyyang890

**Comment by KeithCh** [comment]
bors r=andyyang890

**Comment by KeithCh** [comment]
bors r=andyyang890
