### PR TITLE
kvserver: fix flaky TestStoreRangeMergeWatcher test

### LINKED ISSUE #67171: kv/kvserver: TestStoreRangeMergeWatcher failed
kv/kvserver.TestStoreRangeMergeWatcher [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3144194&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3144194&tab=artifacts#/) on master @ [9a115359eefeb56acfb0ed57e88f87c0e698bd42](https://github.com/cockroachdb/cockroach/commits/9a115359eefeb56acfb0ed57e88f87c0e698bd42):

```
=== RUN   TestStoreRangeMergeWatcher
    test_log_scope.go:73: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestStoreRangeMergeWatcher413595631
    test_log_scope.go:74: use -show-logs to present logs inline
=== CONT  TestStoreRangeMergeWatcher
    client_merge_test.go:3388: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestStoreRangeMergeWatcher413595631
W210702 02:25:19.871358 213708 kv/range_lookup.go:243  [n1,rangefeed=table-stats-cache,range-lookup=/Meta2/Table/20/NULL] 13  range lookup of key /Meta2/Table/20/NULL found only non-matching ranges []; retrying
W210702 02:25:19.873354 213707 kv/range_lookup.go:243  [n1,rangefeed=table-stats-cache,range-lookup=/Table/20] 14  range lookup of key /Table/20 found only non-matching ranges []; retrying
--- FAIL: TestStoreRangeMergeWatcher (1.83s)
=== RUN   TestStoreRangeMergeWatcher/inject-failures=true
    testcluster.go:307: ensuring SQL migrations: failed to get list of completed migrations: kv/kvserver/client_merge_test.go:3410: injected failure
    --- FAIL: TestStoreRangeMergeWatcher/inject-failures=true (0.45s)
```
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
make stressrace TESTS=TestStoreRangeMergeWatcher PKG=./pkg/kv/kvserver TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```
</p>
<p>Parameters in this failure:

- GOFLAGS=-json
</p>
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #62973 kv/kvserver: TestStoreRangeMergeWatcher failed [C-test-failure O-robot branch-release-21.1]
- #57925 kv/kvserver: TestStoreRangeMergeWatcher failed [C-test-failure O-robot branch-release-20.1]
</p>
</details>
<details><summary>Internal log</summary>
<p>

```
benesch marked as alumn{us/a}; resolving to nvanbenschoten instead
```
</p>
</details>

/cc @cockroachdb/kv nvanbenschoten
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestStoreRangeMergeWatcher.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by aliher1911**
Test is inserting failures into store which are very broad and
prevent initial test setup from performing upreplication.
This change makes request filter more specific so that failure
happens at the right time to verify that rhs merge correctly
rejects incoming requests after merge.

Fixes #67171

Release note: None

### CODE REVIEW

**Comment by aliher1911** [comment]
I also tried delaying failures up to the point the merge is initiated. It also works, but I think this approach is cleaner.

File: pkg/kv/kvserver/client_merge_test.go [hunk 1]
```diff
@@ -3407,7 +3407,9 @@ func testMergeWatcher(t *testing.T, injectFailures bool) {
 						roachpb.NewTransactionRetryError(roachpb.RETRY_SERIALIZABLE, "filter err"))
 				}
 			}
-			if pt := req.GetPushTxn(); pt != nil {
+			// We can detect PushTxn requests generated by the watcher goroutine
+			// because they use the minimum transaction priority.
+			if pt := req.GetPushTxn(); pt != nil && pt.PusherTxn.Priority == enginepb.MinTxnPriority {
```
Comment (tbg) [inline pkg/kv/kvserver/client_merge_test.go:3412]: Thanks for looking into this! Is there a way to sharpen this further by checking the `pt.PusheeTxn.Key` matches that start key of the range at which the txn is anchored (I think that's the LHS)?

Comment (aliher1911) [reply pkg/kv/kvserver/client_merge_test.go:3412]: So there's this thing, we need a key '/Local/Range/System/"tse"/RangeDescriptor' we can probably generate that upfront, but that would rely on range for test key "a" not changing. Alternatively, we can look on range descriptor, but it is not available until the server is started and we have range. That would require pushing this value to filter closure.

Comment (tbg) [reply pkg/kv/kvserver/client_merge_test.go:3412]: I just looked at this test and this is all a bit outdated. The test uses keys "a", "b", "c" but it should really use something closer to what's provided by `append(append([]byte(nil), tc.ScratchRange()...), "a")` etc. to use less ad-hoc keys. ScratchRange is static: https://github.com/cockroachdb/cockroach/blob/9cc036d4e3013e4bbdfdf620410339843eb6ce85/pkg/server/testserver.go#L1225-L1228
and I've had multiple situations in which I really just wanted to hard-code it in the test (which I think is completely reasonable). So perhaps we can add (in package `keys`) `var ScratchRangeKey = TableDataMax` and adjust the snippet above to use that.
With all that done, you should be able to target the particular key the transaction is anchored at as `RangeDescriptorKey(keys.ScratchRangeKey and "a")` or some version thereof, without having to inject some shared memory in the filter.

If you'd rather not go down that rabbit hole, that's ok and the current fix LGTM, though the above is what I'd suggest if you have the stomach for it.

Comment (aliher1911) [reply pkg/kv/kvserver/client_merge_test.go:3412]: I really like that because I think relying on priority is sketchy and is fragile. I might also change the other test from which I took the priority approach.

Comment (aliher1911) [reply pkg/kv/kvserver/client_merge_test.go:3412]: So it doesn't work with filtering on range descriptor key because split transactions use the same keys. I changed tests to use scratch ranges anyways as it seems as a better approach. But to make transaction more selective we can just use name, because those names are used consistently by watcher. They are even declared as private constants, maybe it is worth exporting them for the sake of tests?

Comment (tbg) [reply pkg/kv/kvserver/client_merge_test.go]: Sounds good! I am also okay (maybe slightly prefer) leaving the name unexported and adding a comment that tests rely on it (i.e. do a string search before you change it). We're unlikely to ever want to change it.

**Review by aliher1911 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67563)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/kv/kvserver/client_merge_test.go, line 3412 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67563#-MeW9pqQ2Y_kzsWtZB0Q-r1-3412:-MeiK5vh7vQxgmlm-Qli:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c8c9eb96f77390cbce488d736ac299f9256f24e/pkg/kv/kvserver/client_merge_test.go#L3412)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Sounds good! I am also okay (maybe slightly prefer) leaving the name unexported and adding a comment that tests rely on it (i.e. do a string search before you change it). We're unlikely to ever want to change it.
</blockquote></details>

Done.

**Review by tbg — APPROVED** [review]

**Comment by aliher1911** [comment]
bors r=tbg
