### PR TITLE
fix TestMultiRangeScanReverseScanInconsistent

### LINKED ISSUE #3122: kv: TestMultiRangeScanReverseScanInconsistent is flaky
https://circleci.com/gh/cockroachdb/cockroach/9327
```
--- FAIL: TestMultiRangeScanReverseScanInconsistent (0.06s)
	dist_sender_server_test.go:256: expected 1 row; got 0
```

### PR DESCRIPTION
**Pull request by tbg**
closes #3122

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3133)

### CODE REVIEW

File: kv/dist_sender_server_test.go [hunk 1]
```diff
@@ -217,22 +217,28 @@ func TestMultiRangeScanReverseScanDeleteResolve(t *testing.T) {
...
-		b.Put(key, "value")
-		if err := db.Run(b); err != nil {
-			t.Fatal(err)
+	ts := [2]time.Time{}
+	// This outer loop may seem awkward, but we've actually had issue #3122
+	// since the two timestamps ended up equal. This can happen (very rarely)
+	// since both timestamps are HLC internally and then have their logical
+	// component dropped. Lease changes can push the HLC ahead of the wall
+	// time for short amounts of time, so that losing the logical tick matters.
+	for ts[1].Sub(ts[0]) <= 0 {
```
Comment (tamird) [inline kv/dist_sender_server_test.go]: Use `After/Before` here

**Comment by tamird** [comment]
LGTM

File: kv/dist_sender_server_test.go (hunk 1 above)
Comment (tschottdorf) [inline kv/dist_sender_server_test.go]: done.
