### PR TITLE
storage: Fix CommandQueue command dependency leak on error

### LINKED ISSUE #4810: misc: on unreachable nodes: OOM due to too many goroutines
After some time running a real cluster (approx 12h), some nodes have a problem talking to others (still trying to figure out exactly why).
Once this happens, a lot of goroutines get created and never terminate.
eg: panic-parse output of (some of) the logs:
```
443472: semacquire [0~1 minutes] [Created by storage.(*Store).enqueueRaftUpdateCheck @ store.go:1736]
    sync    sema.go:47            runtime_Semacquire(#3)
    sync    mutex.go:83           (*Mutex).Lock(#2)
    storage store.go:1729         (*Store).enqueueRaftUpdateCheck.func1(#1, 0x33)
538973: semacquire [0~1 minutes] [Created by storage.(*Store).enqueueRaftUpdateCheck @ store.go:1736]
    sync    sema.go:47            runtime_Semacquire(#3)
    sync    mutex.go:83           (*Mutex).Lock(#2)
    storage store.go:1729         (*Store).enqueueRaftUpdateCheck.func1(#1, 0x17)
54160: semacquire [0~1 minutes] [Created by storage.(*Store).enqueueRaftUpdateCheck @ store.go:1736]
    sync    sema.go:47            runtime_Semacquire(#3)
    sync    mutex.go:83           (*Mutex).Lock(#2)
    storage store.go:1729         (*Store).enqueueRaftUpdateCheck.func1(#1, 0x18)
```

### PR DESCRIPTION
**Pull request by nvb**
Fixes #4810.

The bug reported was seeing OOM crashes after running for long periods
of time due to an apparent goroutine leak. Looking into this under
a blocking or goroutine profiler pointed out that these leaked
goroutines were primarily in `Replica.beginCmds`. This method's
purpose is to determine a command's dependencies and wait for them
to clear up before returning the command queue insertion keys.
It made sense that the `WaitGroup`s used in this method to gate a
command from proceeding would see a good amount of blocking, but
they seemed to get stuck, indicating `WaitGroup.Done` was never
being called on them. The commands' WaitGroups were supposed to be
freed up when dependee commands were evicted/removed from the
`CommandQueue`, but clearly this wasn't working everywhere. When looking
at `Replica.addWriteCmd`, it became clear what the issue was.

When the [`Context.Done`](https://github.com/cockroachdb/cockroach/commit/8f1d15f5949d370d3be3613911eab0b314ff0bd7#diff-a7f2d9c7dc147a31309311a50721ed2bR966) handling was added to the method, it did not
remove the commands from the queue. This meant that if a deadline for
a request was ever reached (which eventually would happen under
contentious load), we would leave all of it's dependent commands waiting. 
The fix was to defer the `CommandQueue` removal to guarantee that we 
remove the commands from the queue on success or error.

block

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4847)

### CODE REVIEW

**Comment by tamird** [comment]
Busted :(

LGTM

**Comment by nvanbenschoten** [comment]
Since I'm here, I just made a similar change in `addReadOnlyCmd` to make sure an issue like this doesnt sneak in over there.

File: storage/replica.go [hunk 1]
```diff
@@ -833,20 +833,33 @@ func (r *Replica) addReadOnlyCmd(ctx context.Context, ba roachpb.BatchRequest) (
...
+			r.readOnlyCmdMu.RUnlock()
+		}
+	}()
+
 	// If there are command keys (there might not be if reads are
 	// inconsistent), the read requires the leader lease.
 	if len(cmdKeys) > 0 {
-		if pErr := r.redirectOnOrAcquireLeaderLease(sp); pErr != nil {
-			r.endCmds(cmdKeys, ba, pErr)
+		if pErr = r.redirectOnOrAcquireLeaderLease(sp); pErr != nil {
```
Comment (tschottdorf) [inline storage/replica.go]: I think you might be able to move the lease acquisition above `beginCmds` so that this awkward construct can go.

Comment (nvanbenschoten) [inline storage/replica.go]: Don't we want to avoid acquiring the leader lease if there are no command keys (just reading the comment)? I'm guessing you wrote it though, so I'll defer to your judgement.

File: storage/replica.go [hunk 2]
```diff
@@ -964,11 +969,9 @@ func (r *Replica) addWriteCmd(ctx context.Context, ba roachpb.BatchRequest, wg *
 		case <-ctx.Done():
 			return br, roachpb.NewError(ctx.Err())
```
Comment (tamird) [inline storage/replica.go]: while you're here, can you either make this not a `return` or make the line above a `return`?

Comment (tamird) [inline storage/replica.go]: the whole structure here is weird.

File: storage/replica.go (hunk 1 above)
Comment (tschottdorf) [inline storage/replica.go]: You can check `ba.ReadConsistency != roachpb.INCONSISTENT` instead.

**Comment by petermattis** [comment]
Nice job tracking this down, Nathan.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4847#-:-KBzLYz_jhpOahZFW9JV:-1412981654)*

File: storage/replica.go (hunk 1 above)
Comment (nvanbenschoten) [inline storage/replica.go]: Done.

File: storage/replica.go (hunk 2 above)
Comment (nvanbenschoten) [inline storage/replica.go]: Done.

And yeah the structure was weird because of the mutex. Moving the lease acquisition up allowed it to be a lot cleaner.

**Comment by tamird** [comment]
On looking at this again, I think I'm against using defer here. In `addReadOnlyCmd`, the addition of the defer doesn't provide any protection and just clutters the code - I think I would prefer that `beginCmds` returned a cleanup callback - that would make the contract clearer. Otherwise, going down this route presents a bottomless pit - where does it end? We'd have to defer everything.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4847#-:-KBzMnMJDdb_HLOaOTtw:1964151393)*

**Comment by tamird** [comment]
Nice. LGTM.

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[storage/replica.go, line 850 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4847#-KBzRaH9OEjWlKRdei8Z:-KBzRaH9OEjWlKRdei8_:279788185) ([raw file](https://github.com/cockroachdb/cockroach/blob/eaaef49f861832738f66447b4a742cbebfda6e4e/storage/replica.go#L850)):*
synchronized

---

*[storage/replica.go, line 851 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4847#-KBzRcHrWa83MdKsOC40:-KBzRcHrWa83MdKsOC41:482268808) ([raw file](https://github.com/cockroachdb/cockroach/blob/eaaef49f861832738f66447b4a742cbebfda6e4e/storage/replica.go#L851)):*
add a comment explaining why this is wrapped

---

*[storage/replica.go, line 902 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4847#-KBzRlDn_cPAl7N8iw4W:-KBzRlDn_cPAl7N8iw4X:2018001514) ([raw file](https://github.com/cockroachdb/cockroach/blob/eaaef49f861832738f66447b4a742cbebfda6e4e/storage/replica.go#L902)):*
ditto comment about why this is wrapped

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4847#-:-KBzRstcHvEUazXqqQhy:1466876614)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[storage/replica.go, line 850 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4847#-KBzRaH9OEjWlKRdei8Z:-KBzSFHgLlN4RAK75zB6:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/eaaef49f861832738f66447b4a742cbebfda6e4e/storage/replica.go#L850)):*
Done.

---

*[storage/replica.go, line 851 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4847#-KBzRcHrWa83MdKsOC40:-KBzSOYts-e_CCQbPFz2:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/eaaef49f861832738f66447b4a742cbebfda6e4e/storage/replica.go#L851)):*
Done.

---

*[storage/replica.go, line 902 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4847#-KBzRlDn_cPAl7N8iw4W:-KBzSXBgc02T-hiKLwvn:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/eaaef49f861832738f66447b4a742cbebfda6e4e/storage/replica.go#L902)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4847)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4847)*

**Comment by tschottdorf** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4847#-:-KBzT84Tb8qBABwnAmRh:980077423)*

**Comment by spencerkimball** [comment]
@nvanbenschoten great work on this one.
