### PR TITLE
sql/pgwire: fix statement buffer memory leak when using suspended portals

### LINKED ISSUE #66849: Memory leak in long running query crashes node
**Describe the problem**

Executing a long running query, such as a core changefeed, results in a memory leak which crashes the node it is running on.

##### Notes
The leak appears to be caused by the connection [statement buffer](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/conn_executor.go#L1042) accumulating statements that are not cleared out after being processed, see flamegraph screenshot. A similar bug was fixed by this [commit](https://github.com/cockroachdb/cockroach/commit/cb7b4f360fd70d68c57aa5bbbea198aecf1c0e33#diff-30926eec6a83d84431b319a14fc9081df5096743cff7914a77f3bdbfa5a251c7R1539) by clearing out the statement buffer. This appears to not work for long running queries, maybe related to the use of the [limitedCommandResult](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/pgwire/command_result.go#L394) side state machine which handles the extended Postgres protocol. Each `FETCH` command of the core changefeed query is likely accumulating in the statement buffer.

**To Reproduce**
1. Set up a CockroachDB cluster running in AWS on 6 c5d.xlarge nodes running v21.1.3
2. Run the kv workload, from another machine, against the cluster:
```
cockroach workload init kv $COCKROACH_URL 
cockroach workload run kv $COCKROACH_URL --read-percent 25 --concurrency 512 --max-rate 600 --min-block-bytes 100 --max-block-bytes 150
```
3. Create a core changefeed, setting the JDBC fetch size to 1.
```
EXPERIMENTAL CHANGEFEED FOR TABLE kv.kv WITH updated, diff, format = 'json', cursor='1617245756000000000'
```
4. After a few hours, check the memory usage of the node which is serving the core changefeed query in the admin UI metrics. Note the memory usage continues to grow.
5. Eventually the node will crash when it runs out of memory. 

**Expected behavior**
Executing a long running query will not leak memory and can continue indefinitely.

**Additional data / screenshots**
Cluster memory usage. The core changefeed query is running on node 3 (red line)
Screen Shot 2021-06-24 at 7 51 26 AM
Node 3 memory usage breakdown
Screen Shot 2021-06-24 at 8 01 03 AM
Flame graph showing statement buffer growing
memory_flame_graph

**Environment:**
 - CockroachDB version: v21.1.3
 - Client app: `cockroach sql` /`JDBC`

**Additional context**
* The JDBC fetch size has a direct impact on the speed of the leak. Setting the fetch size to 2 doubles the amount of time it takes to crash the node.

### PR DESCRIPTION
**Pull request by joesankey**
The connection statement buffer grows indefinitely when the client uses the
execute portal with limit feature of the Postgres protocol, eventually causing
the node to crash out of memory. Any long running query that uses the limit
feature will cause this memory leak such as the `EXPERIMENTAL CHANGEFEED FOR`
statement. The execute portal with limit feature of the Postgres protocol is
used by the JDBC Postgres driver to fetch a limited number of rows at a time.

The leak is caused by commands accumulating in the buffer and never getting
cleared out. The client sends 2 commands every time it wants to receive more
rows:

- `Execute {"Portal": "C_1", "MaxRows": 1}`
- `Sync`

The server processes the commands and leaves them in the buffer, every
iteration causes 2 more commands to leak.

A similar memory leak was fixed by #48859, however the execute with limit
feature is implemented by a side state machine in limitedCommandResult. The
cleanup routine added by #48859 is never executed for suspended portals as
they never return to the main conn_executor loop.

After this change the statement buffer gets trimmed to reclaim memory after
each client command is processed in the limitedCommandResult side state
machine. The StmtBuf.Ltrim function was changed to be public visibility to
enable this. While this is not ideal, it does scope the fix to the
limitedCommandResult side state machine and could be addressed when the
limitedCommandResult functionality is refactored into the conn_executor.

Added a unit test which causes the leak, used the PGWire client in the test as
neither the pg or pgx clients use execute with limit, so cant be used to
demonstrate the leak. Also tested the fix in a cluster by following the steps
outlined in #66849.

Resolves: #66849

See also: #48859

Release note (bug fix): fix statement buffer memory leak when using suspended
portals.

@asubiotto @andreimatei

### CODE REVIEW

**Comment by rafiss** [comment]
Thanks for this PR!

The fix seems reasonable to me, but it looks like `TestMonotonicInserts_distsql=off` is failing because it's retrying a txn infinitely. I can't see why that would be related to your change, but I'll poke around a bit.

File: pkg/sql/conn_io.go [hunk 1]
```diff
@@ -457,16 +457,17 @@ func (buf *StmtBuf) translatePosLocked(pos CmdPos) (int, error) {
...
-func (buf *StmtBuf) ltrim(ctx context.Context, pos CmdPos) {
+// It's illegal to Ltrim to a position higher than the current cursor.
+func (buf *StmtBuf) Ltrim(ctx context.Context, pos CmdPos) {
 	buf.mu.Lock()
 	defer buf.mu.Unlock()
 	if pos < buf.mu.startPos {
-		log.Fatalf(ctx, "invalid ltrim position: %d. buf starting at: %d",
-			pos, buf.mu.startPos)
+		// already trimmed, this can happen when the StmtBuf is trimmed from the limitedCommandResult
+		// side state machine and then again in the conn_executor.
```
Comment (rafiss) [inline pkg/sql/conn_io.go:469]: at what point after using a MaxRows portal does conn_executor again try to Ltrim the buffer? i'm wondering if it's possible to teach conn_executor not to do that, so we can keep this error and maybe be a little safer.

**Review by rafiss — CHANGES_REQUESTED** [review]
I'm pretty sure you just had an unlucky flake. I re-ran the CI and it passed, and I also ran the test under stress with `make stress PKG=./pkg/sql/tests TESTS=TestMonotonicInserts` and it never failed after 284 runs.

I left a question, but this looks quite good. i like the test you added!

and also a request for the commit message. can you change the title to:
```
sql/pgwire: fix statement buffer memory leak when using suspended portals
```

File: pkg/sql/conn_io.go (hunk 1 above)
Comment (joesankey) [reply pkg/sql/conn_io.go:469]: After the portal is exhausted in `limitedCommandResult` the flow returns to [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/conn_executor.go#L1671). `Ltrim` is then called again at the bottom of the function [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/conn_executor.go#L1813). At this point conn_executor  uses `pos` to `Ltrim` but that index has already been trimmed. I considered updating `pos` after `execPortal` returns with something like `cmd, pos, err := ex.stmtBuf.CurCmd()`, which would give the cleanup routine in conn_executor a valid index to `LTrim`, but wasn't sure if I was missing some unwanted side effects in the rewind determination code. Let me know if you think that is a better approach.

Comment (joesankey) [reply pkg/sql/conn_io.go]: Made the change to update the state in conn_executor when execPortal returns.

**Comment by joesankey** [comment]
> I'm pretty sure you just had an unlucky flake. I re-ran the CI and it passed, and I also ran the test under stress with `make stress PKG=./pkg/sql/tests TESTS=TestMonotonicInserts` and it never failed after 284 runs.
> 
> I left a question, but this looks quite good. i like the test you added!
> 
> and also a request for the commit message. can you change the title to:
> 
> ```
> sql/pgwire: fix statement buffer memory leak when using suspended portals
> ```

Updated the title

**Review by rafiss — APPROVED** [review]
thanks! this looks good. i'll trigger the merge:

bors r+

> Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67135#-:-Me1IJwO62-Qc8aVFcjr:b-wgdzb4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, @joesankey, and @miretskiy)

___
*[pkg/sql/conn_io.go, line 469 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67135#-MdYqhKPnaP7RFyBNtOL-r1-469:-Me1GhuK3TzMvjDZNN54:bi7e3cp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e12b31e6183fffd2c2888b31c3bc170908a01a92/pkg/sql/conn_io.go#L469)):*
<details><summary><i>Previously, joesankey (Joe Sankey) wrote…</i></summary><blockquote>

Made the change to update the state in conn_executor when execPortal returns.
</blockquote></details>

Sorry I missed your questtion earlier. I think this way is better
