### PR TITLE
backupccl: remove ldr job id references on restoring tables

### LINKED ISSUE #134424: dr/ldr: enabling schema changes on backups taken during the LDR job
currently, schema changes do not work on restored backups that were taken during LDR. we should investigate this behavior and a fix

### PR DESCRIPTION
**Pull request by msbutler**
This patch ensures that the user can run schema changes on a restored a table that was previously apart of an LDR stream.

Fixes #134424

Release note(bug fix): this patch allows a user to run schema changes on a restored table that was previously apart of an LDR stream.

### CODE REVIEW

File: pkg/ccl/backupccl/restore_job.go [hunk 1]
```diff
@@ -1161,6 +1161,10 @@ func createImportingDescriptors(
 	// Set the new descriptors' states to offline.
 	for _, desc := range mutableTables {
 		desc.SetOffline("restoring")
+
+		// Remove any LDR Jobs from the table descriptor, ensuring schema changes
+		// can be run on the table descriptor.
+		desc.LDRJobIDs = desc.LDRJobIDs[:0]
```
Comment (dt) [inline pkg/ccl/backupccl/restore_job.go:1167]: nit: I think `= nil` is a clearer signal of intention to blank it; `= [:0]` is typically associated with an expectation of reuse of the allocated capacity.

**Review by dt — APPROVED** [review]

File: pkg/ccl/backupccl/restore_job.go (hunk 1 above)
Comment (msbutler) [reply pkg/ccl/backupccl/restore_job.go]: Done.

**Comment by msbutler** [comment]
TFTR!

bors r=dt
