### PR TITLE
kv: consider ErrReplicaNotFound and ErrReplicaCannotHoldLease to be retryable

### LINKED ISSUE #96746: backupccl: restore fails when issuing an AdminSplit
When running a large restore we occasionally see the call to `AdminSplit` - https://github.com/cockroachdb/cockroach/blob/2f811420a1492ca547659003f193233341b7fd87/pkg/ccl/backupccl/split_and_scatter_processor.go#L99 failing with:

```
ERROR: importing 228177 ranges: splitting key /Table/134/1/200039096531068: unable to find store 83 in range r17080:/Table/134/1/2000390{55231406-60112830} [(n87,s87):6, (n46,s46):7, (n85,s85):8, next=9, gen=460, sticky=1675807501.216768519,0]
```

This error comes from the code that processes an `AdminTransferLease` - https://github.com/cockroachdb/cockroach/blob/3359d4631e5572d7431ec05d0bb5b806854fcb4c/pkg/kv/kvserver/replica_range_lease.go#L881 when the target replica is not a replica of the range. The stack points to https://github.com/cockroachdb/cockroach/blob/7de12736ece9240707a66dc4d50ea1224005203d/pkg/kv/kvserver/replica_send.go#L952 being where we invoke the transfer from, but it is still unclear where the `AdminSplit` logic sends an `AdminTransferLease`. It is worth noting that there were changes made to how we split and scatter chunks in https://github.com/cockroachdb/cockroach/pull/94805 but it is not yet clear why we are seeing more of this error than before.

Jira issue: CRDB-24307

### LINKED ISSUE #100379: roachtest: restore/tpce/32TB/aws/nodes=15/cpus=16 failed
roachtest.restore/tpce/32TB/aws/nodes=15/cpus=16 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyAwsBazel/9373165?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyAwsBazel/9373165?buildTab=artifacts#/restore/tpce/32TB/aws/nodes=15/cpus=16) on master @ [99102ddf4b7602788b422366f1acc14b81c64d24](https://github.com/cockroachdb/cockroach/commits/99102ddf4b7602788b422366f1acc14b81c64d24):

```
test artifacts and logs in: /artifacts/restore/tpce/32TB/aws/nodes=15/cpus=16/run_1
(monitor.go:127).Wait: monitor failure: monitor task failed: output in run_052239.378670427_n1_cockroach-sql-insecu: ./cockroach sql --insecure -e "RESTORE  FROM LATEST IN 's3://cockroach-fixtures/backups/tpc-e/customers=2000000/v22.2.1/inc-count=48?AUTH=implicit' AS OF SYSTEM TIME '2023-01-11T23:45:00Z' " returned: COMMAND_PROBLEM: ssh verbose log retained in ssh_052239.382670106_n1_cockroach-sql-insecu.log: exit status 1
```
<p>Parameters: <code>ROACHTEST_cloud=aws</code>
, <code>ROACHTEST_cpu=16</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*restore/tpce/32TB/aws/nodes=15/cpus=16.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-26395

### PR DESCRIPTION
**Pull request by nvb**
Fixes #96746.
Fixes #100379.

This commit considers ErrReplicaNotFound and ErrReplicaCannotHoldLease to be retryable replication change errors when thrown by lease transfer requests. In doing so, these errors will be retried by the retry loop in `Replica.executeAdminCommandWithDescriptor`.

This avoids spurious errors when a split gets blocked behind a lateral replica move like we see in the following situation:
1. issue AdminSplit
2. range in joint config, first needs to leave (maybeLeaveAtomicChangeReplicas)
3. to leave, needs to transfer lease from voter_outgoing to voter_incoming 4(a). lease transfer request sent to replica that has not yet applied the
      replication change that added the voter_incoming to the range
4(b). lease transfer request delayed and delivered after voter_incoming has
      been transferred the lease, added to the range, then removed from the
      range.

In either case, retrying the AdminSplit operation on these errors will ensure that it eventually succeeds.

Release note (bug fix): Fixed a rare race that could allow large RESTOREs to fail with a `unable to find store` error.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
I think this is a good improvement regardless, but I would still like to see a demonstration that this resolves the referenced issue. I have that running now, and we should know in about 24h. If that succeeds, I'll mark this PR as "ready for review".

**Comment by nvanbenschoten** [comment]
I killed the test after about 18 hours because it was OOMing due to manifest size issues. I believe DR is aware of this issue. See https://cockroachlabs.slack.com/archives/C2C5FKPPB/p1678239941563699?thread_ts=1678148317.150499&cid=C2C5FKPPB.

I'll open this for review @shralex, as there's evidence that it resolved the issue.

File: pkg/kv/kvserver/markers.go [hunk 1]
```diff
@@ -106,3 +107,14 @@ var errMarkLeaseTransferRejectedBecauseTargetMayNeedSnapshot = errors.New(
 func IsLeaseTransferRejectedBecauseTargetMayNeedSnapshotError(err error) bool {
 	return errors.Is(err, errMarkLeaseTransferRejectedBecauseTargetMayNeedSnapshot)
 }
+
+// IsLeaseTransferRejectedBecauseTargetCannotReceiveLease detects whether an
```
Comment (shralex) [inline pkg/kv/kvserver/markers.go:111]: Can we make it a bit more concise, e.g., 

IsLeaseTransferRejectedBecauseTargetCannotReceiveLease returns true if err (assumed to have been emitted by the current leaseholder when processing a lease transfer request) indicates that the target replica is not qualified to receive the lease. This could be because the current leaseholder has an outdated view of the target replica's state.

File: pkg/kv/kvserver/markers.go [hunk 2]
```diff
@@ -106,3 +107,14 @@ var errMarkLeaseTransferRejectedBecauseTargetMayNeedSnapshot = errors.New(
...
+// error (assumed to have been emitted by a lease transfer request) indicates
+// that the lease transfer failed because the current leaseholder determined
+// that the lease transfer target cannot is not qualified to receive the lease.
+// This can be an indication that the current leaseholder has an outdated view
+// of the lease transfer target's state.
```
Comment (shralex) [inline pkg/kv/kvserver/markers.go:116]: > This can be an indication that the current leaseholder has an outdated view

What could be the other reasons for this error ? In particular, is there a situation where the error indicates a problem that isn't transient, so we shouldn't be retrying ? for example, could it be that the state of the current leaseholder is up-to-date and the target replica was already removed ? or that ErrReplicaCannotHoldLease legitimately represents an error ?

File: pkg/kv/kvserver/markers.go (hunk 1 above)
Comment (nvanbenschoten) [reply pkg/kv/kvserver/markers.go:111]: Done.

File: pkg/kv/kvserver/markers.go (hunk 2 above)
Comment (nvanbenschoten) [reply pkg/kv/kvserver/markers.go:116]: I can't think of any case where the error should not lead to the replication change being retried. Note that this doesn't necessarily mean that the lease transfer should be retried, but that `maybeLeaveAtomicChangeReplicas` should be called again and the caller should recompute whether a lease transfer is needed. If the caller again finds a VOTER_INCOMING in the descriptor, it should try the lease transfer again.

**Review by shralex — APPROVED** [review]
> Reviewed 2 of 9 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98116)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by nvanbenschoten** [comment]
bors r=shralex
