### PR TITLE
release-23.1: jobs: add DeleteTerminalJobByID function

### LINKED ISSUE #118582: sql,jobs: AUTO CREATE STATS jobs cleanup can abandon job_info rows
**Describe the problem**

The AUTO CREATE STATS jobs has code to detect concurrent creation of a status job for a given table and exit with an error to avoid having duplicate stats jobs. Unfortunately, that code then deletes the job from the system.jobs table in an effort to avoid confusing error messages going to the user:

https://github.com/cockroachdb/cockroach/blob/cc4fdffa8532d16544c48ef036689763f737dc6b/pkg/sql/create_stats.go#L160-L170

This code fails to clean up the related system.job_info rows.  Those rows will never be cleaned up because our job-gc maintenance routine only cleans up jobs that are listed in the jobs table.

In a large cluster with many tables, this can result in a very large job_info table, slowing down jobs related queries substantially.

Jira issue: CRDB-35798

gz#20135

### PR DESCRIPTION
**Pull request by stevendanna**
Backport 1/1 commits from #118589.

/cc @cockroachdb/release

Release justification: Bug fix for a bug that leads to job system unavailability. 

---

The CREATE AUTO STATS code was manually modifying the system.jobs table in a way that left the job_info table with abandoned rows.

Fixes #118582

Release note (bug fix): AUTO CREATE STATS jobs could previously lead to growth in an internal system table resulting in slower job-system related queries.

### CODE REVIEW

File: pkg/jobs/registry.go [hunk 1]
```diff
@@ -1319,6 +1319,38 @@ func (r *Registry) cleanupOldJobsPage(
 	return !morePages, maxID, nil
 }
 
+// DeleteTerminalJobByID deletes the given job ID if it is in a
+// terminal state. If it is is in a non-terminal state, an error is
+// returned.
+func (r *Registry) DeleteTerminalJobByID(ctx context.Context, id jobspb.JobID) error {
+	return r.db.Txn(ctx, func(ctx context.Context, txn isql.Txn) error {
+		row, err := txn.QueryRow(ctx, "get-job-status", txn.KV(),
+			"SELECT status FROM system.jobs WHERE id = $1", id)
```
Comment (mgartner) [inline pkg/jobs/registry.go:1328]: You could eliminate this SELECT query by changing the first delete to something like:

```go
rowsAffected, err := txn.Exec(
    ctx, "delete-job", txn.KV(),
    "DELETE FROM system.jobs WHERE id = $1 AND status IN ($2, $3, $4)",
    id, StatusSucceeded, StatusCanceled, StatusFailed,
)
if err != nil { /* ... */ }
if rowsAffected == 0 {
  return errors.Newf("job %d has non-terminal status: %q", id, status)
}
```

**Review by mgartner — APPROVED** [review]
LGTM. I left one optional suggestion you might consider in a future PR—no need to change this PR though.
