### PR TITLE
raft: fix flaky leader index in waitLeader function

### LINKED ISSUE #127413: raft/rafttest: TestRestart failed
raft/rafttest.TestRestart [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/16125659?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/16125659?buildTab=artifacts#/) on master @ [46854026bc11b3870c8bbefc976f5550b18dd82c](https://github.com/cockroachdb/cockroach/commits/46854026bc11b3870c8bbefc976f5550b18dd82c):

```
raft2024/07/18 04:23:33 INFO: 2 not forwarding to itself at term 2; dropping proposal
raft2024/07/18 04:23:33 INFO: 2 not forwarding to itself at term 2; dropping proposal
raft2024/07/18 04:23:33 INFO: 2 not forwarding to itself at term 2; dropping proposal
raft2024/07/18 04:23:33 INFO: 2 not forwarding to itself at term 2; dropping proposal
raft2024/07/18 04:23:33 INFO: 2 not forwarding to itself at term 2; dropping proposal
raft2024/07/18 04:23:33 INFO: 2 not forwarding to itself at term 2; dropping proposal
raft2024/07/18 04:23:33 INFO: 2 not forwarding to itself at term 2; dropping proposal
raft2024/07/18 04:23:33 INFO: 2 not forwarding to itself at term 2; dropping proposal
raft2024/07/18 04:23:33 INFO: 5 is starting a new election at term 2
raft2024/07/18 04:23:33 INFO: 5 became candidate at term 3
raft2024/07/18 04:23:33 INFO: 5 [logterm: 2, index: 6] sent MsgVote request to 1 at term 3
raft2024/07/18 04:23:33 INFO: 5 [logterm: 2, index: 6] sent MsgVote request to 2 at term 3
raft2024/07/18 04:23:33 INFO: 5 [logterm: 2, index: 6] sent MsgVote request to 3 at term 3
raft2024/07/18 04:23:33 INFO: 5 [logterm: 2, index: 6] sent MsgVote request to 4 at term 3
raft2024/07/18 04:23:33 INFO: raft.node: 5 lost leader 2 at term 3
raft2024/07/18 04:23:33 INFO: 5 received MsgVoteResp from 5 at term 3
raft2024/07/18 04:23:33 INFO: 5 has received 1 MsgVoteResp votes and 0 vote rejections
raft2024/07/18 04:23:33 INFO: 1 [term: 2] received a MsgVote message with higher term from 5 [term: 3]
raft2024/07/18 04:23:33 INFO: 1 became follower at term 3
raft2024/07/18 04:23:33 INFO: 1 [logterm: 2, index: 6, vote: 0] cast MsgVote for 5 [logterm: 2, index: 6] at term 3
raft2024/07/18 04:23:33 INFO: raft.node: 1 lost leader 2 at term 3
raft2024/07/18 04:23:33 INFO: 4 [term: 2] received a MsgVote message with higher term from 5 [term: 3]
raft2024/07/18 04:23:33 INFO: 4 became follower at term 3
raft2024/07/18 04:23:33 INFO: 4 [logterm: 2, index: 6, vote: 0] cast MsgVote for 5 [logterm: 2, index: 6] at term 3
raft2024/07/18 04:23:33 INFO: raft.node: 4 lost leader 2 at term 3
raft2024/07/18 04:23:33 INFO: 5 received MsgVoteResp from 1 at term 3
raft2024/07/18 04:23:33 INFO: 5 has received 2 MsgVoteResp votes and 0 vote rejections
raft2024/07/18 04:23:33 INFO: 3 [term: 2] received a MsgVote message with higher term from 5 [term: 3]
raft2024/07/18 04:23:33 INFO: 3 became follower at term 3
raft2024/07/18 04:23:33 INFO: 3 [logterm: 2, index: 6, vote: 0] cast MsgVote for 5 [logterm: 2, index: 6] at term 3
raft2024/07/18 04:23:33 INFO: raft.node: 3 lost leader 2 at term 3
raft2024/07/18 04:23:33 INFO: 2 [term: 2] received a MsgVote message with higher term from 5 [term: 3]
raft2024/07/18 04:23:33 INFO: 2 became follower at term 3
raft2024/07/18 04:23:33 INFO: 2 [logterm: 2, index: 6, vote: 0] cast MsgVote for 5 [logterm: 2, index: 6] at term 3
raft2024/07/18 04:23:33 INFO: raft.node: 2 lost leader 2 at term 3
raft2024/07/18 04:23:33 INFO: 5 received MsgVoteResp from 3 at term 3
raft2024/07/18 04:23:33 INFO: 5 has received 3 MsgVoteResp votes and 0 vote rejections
raft2024/07/18 04:23:33 INFO: 5 became leader at term 3
raft2024/07/18 04:23:33 INFO: raft.node: 5 elected leader 5 at term 3
raft2024/07/18 04:23:33 INFO: raft.node: 2 elected leader 5 at term 3
raft2024/07/18 04:23:33 INFO: raft.node: 1 elected leader 5 at term 3
raft2024/07/18 04:23:33 INFO: raft.node: 3 elected leader 5 at term 3
raft2024/07/18 04:23:33 INFO: raft.node: 4 elected leader 5 at term 3
    node_test.go:91: commits failed to converge!
I240718 04:23:38.520629 388 (gostd) node.go:100  [-] 8  raft.1: stop
I240718 04:23:38.520684 616 (gostd) node.go:100  [-] 9  raft.2: stop
I240718 04:23:38.520698 614 (gostd) node.go:100  [-] 10  raft.3: stop
I240718 04:23:38.520708 394 (gostd) node.go:100  [-] 11  raft.4: stop
I240718 04:23:38.521851 396 (gostd) node.go:100  [-] 12  raft.5: stop
--- FAIL: TestRestart (5.20s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRestart.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-40428

### PR DESCRIPTION
**Pull request by nvb**
Fixes #127413.

This commit bypasses the larger rebase in #122133 to pick up the test flake fix in https://github.com/etcd-io/raft/pull/188. There was some discussion in https://github.com/etcd-io/raft/issues/181 about alternatives for fixing this test. For now, we stick with a direct cherry-pick.

Release note: None

### CODE REVIEW

**Review by pav-kv — APPROVED** [review]
Thanks for picking this up.

**Comment by pav-kv** [comment]
Could you remove the TODO in the beginning of `TestRestart`?

NB: Back then I thought that this fix was inherently flaky and the fix was incomplete. There was some analysis in https://github.com/etcd-io/raft/pull/195#discussion_r1560119462 and other comments there. We can revisit of this comes up again after your PR.

File: pkg/raft/rafttest/node_test.go [hunk 1]
```diff
@@ -137,7 +137,7 @@ func TestPause(t *testing.T) {
 
 func waitLeader(ns []*node) int {
 	var l map[pb.PeerID]struct{}
-	var lindex int
+	var lindex = -1
```
Comment (pav-kv) [inline pkg/raft/rafttest/node_test.go:140]: Should this be reset to `-1` on each iteration? Might be better to move the definition inside the loop then.

**Comment by pav-kv** [comment]
> NB: Back then I thought that this test was inherently flaky and the fix was incomplete.

I stressed this now locally 20k times with the fix applied (one with the `lindex := -1` moved inside the loop, as commented), and it did not flake. Before the fix it flakes pretty eagerly. So this flake will be much less / not at all as noisy now.

File: pkg/raft/rafttest/node_test.go (hunk 1 above)
Comment (nvanbenschoten) [reply pkg/raft/rafttest/node_test.go:140]: Done. I also moved to clearing the map on each iteration, instead of re-allocating it.

**Comment by nvanbenschoten** [comment]
> Could you remove the TODO / skip in the beginning of TestRestart?

Done.

**Comment by nvanbenschoten** [comment]
> I stressed this now locally 20k times with the fix applied (one with the lindex := -1 moved inside the loop, as commented), and it did not flake. Before the fix it flakes pretty eagerly. So this flake will be much less / not at all as noisy now.

I stressed again for 20k iterations and still see that it is stable.

bors r=pav-kv
