### PR TITLE
storage: add gc benchmarks with multiple range tombstones

### LINKED ISSUE #87417: storage: add gc benchmark with multiple range tombstones
Currently we only have a bench which adds a single range tombstone to minimally measure regression in performance.
We need a better coverage if we want to enable mvcc range keys for everyone.

Benchmark should add N range tombstones and make only some of them cover measured GC requests. For example N keys should be spread across the full range of versions, not only bottom N point keys as that would be non-representative.

Jira issue: CRDB-19336

Epic CRDB-2624

### PR DESCRIPTION
**Pull request by aliher1911**
Previously we only had tests that verify GC performance with no range tombstones or with a single range tombstone under all the data. This commit extends the benchmark to have many tombstones interleaving data at different keys.

Release note: None

Fixes #87417

### CODE REVIEW

**Comment by aliher1911** [comment]
I didn't realize that adding multiple range tombstones will be so disruptive. With 1024 range keys bench will time out preparing the data because insertions become too slow.
I think it needs to have handful at most with an option to cover all data or not.

File: pkg/storage/bench_test.go [hunk 1]
```diff
@@ -1588,35 +1597,96 @@ func runMVCCGarbageCollect(
...
-		if opts.numRangeKeys == 1 {
-			if err := MVCCDeleteRangeUsingTombstone(ctx, batch, nil, keys.LocalMax, keys.MaxKey,
-				ts, hlc.ClockTimestamp{}, nil, nil, true, 0, nil); err != nil {
+		// When keys are deleted using range tombstones MVCC operations perform
+		// smart checks to drop them altogether if there's no underlying data.
+		// We want to prevent that for testing purposes and we add a key at lower
+		// timestamp prior to putting first tombstone and subsequently remove it
+		// from the batch at the end of setup.
+		if opts.numRangeKeys > 0 {
+			if err := MVCCPut(ctx, batch, nil, keys.LocalMax, ts, hlc.ClockTimestamp{}, val, nil); err != nil {
```
Comment (erikgrinaker) [inline pkg/storage/bench_test.go:1639]: Why not simply set the `idempotent` parameter for `MVCCDeleteRangeUsingTombstone` to `false` instead? I don't think we want the idempotent behavior here at all, because we want to control the exact number of (defragmented) range keys written.

File: pkg/storage/bench_test.go [hunk 2]
```diff
@@ -57,20 +57,29 @@ func BenchmarkMVCCGarbageCollect(b *testing.B) {
...
-		{2, []int{1}},
-		{1024, []int{1, 16, 32, 512, 1015, 1023}},
+		{
+			total:              2,
+			rangeTombstoneKeys: []int{0, 1, 2},
+			toDelete:           []int{1},
+		},
+		{
+			total:              1024,
+			rangeTombstoneKeys: []int{0, 1, 16, 32},
```
Comment (erikgrinaker) [inline pkg/storage/bench_test.go:73]: Maybe do 0,1,100 instead. We use that a standard number of range keys in all other benchmarks, so it might be nice to standardize on that to better compare the slowdown across multiple benchmarks -- for example, we can know what the best-case slowdown would be from a very simple iterator benchmark, or compare against `MVCCScan`.

File: pkg/storage/bench_test.go (hunk 1 above)
Comment (aliher1911) [reply pkg/storage/bench_test.go]: TIL what idempotent for range tombstones is.

Comment (erikgrinaker) [reply pkg/storage/bench_test.go]: Yeah, "idempotent" is really a bit of a misnomer here.

**Review by erikgrinaker — APPROVED** [review]
LGTM

**Comment by aliher1911** [comment]
bors r=erikgrinaker

**Comment by aliher1911** [comment]
bors r=erikgrinaker
