### PR TITLE
changefeedccl: ensure that spans planned from cdc queries have end keys

### LINKED ISSUE #143101: changefeedccl: changefeeds with cdc queries fail when the query results in a single key scan
repro:
```
CREATE TABLE orders3 (
  order_id INT PRIMARY KEY
);
CREATE CHANGEFEED AS SELECT * FROM orders3 WHERE order_id = 1;
```

in the logs: `changefeed retrying due to transient error: inverted span ‹/Table/106/1/1/0›: interval: inverted range`

Jira issue: CRDB-48654

### PR DESCRIPTION
**Pull request by asg0451**
When a cdc query results in a plan that scans a
single key, the end key of the span is unset. This
causes the feed to fail on startup. We now set
span.EndKey = span.Key.Next().

Fixes: #143101

Release note (bug fix): Fixed a bug that caused feeds to fail on startup when
scanning a single key.

### CODE REVIEW

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 1]
```diff
@@ -10794,6 +10794,49 @@ func TestChangefeedProtectedTimestampUpdate(t *testing.T) {
 	cdcTest(t, testFn, feedTestForceSink("kafka"), withTxnRetries)
 }
 
+func TestCDCQuerySelectSingleRow(t *testing.T) {
+	defer leaktest.AfterTest(t)()
+	defer log.Scope(t).Close(t)
+
+	errCh := make(chan error, 1)
+	knobsFn := func(knobs *base.TestingKnobs) {
+		// TODO: this error should probably be terminal too.
```
Comment (rharding6373) [inline pkg/ccl/changefeedccl/changefeed_test.go:10803]: Which error?

**Review by rharding6373 — COMMENTED** [review]
Nice find!

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 2]
```diff
@@ -10794,6 +10794,52 @@ func TestChangefeedProtectedTimestampUpdate(t *testing.T) {
...
+			foo := feed(t, f, `CREATE CHANGEFEED WITH initial_scan='only' AS SELECT * FROM foo WHERE key = 1`)
+			// db.Exec(t, "CREATE CHANGEFEED WITH initial_scan='only' AS SELECT * FROM foo WHERE key = 1")
+			defer closeFeed(t, foo)
+			assertPayloads(t, foo, []string{`foo: [1]->{"key": 1}`})
+		}()
+
+		select {
+		case err := <-errCh:
+			t.Fatalf("unexpected error: %v", err)
+		case <-time.After(10 * time.Second):
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_test.go:10834]: Should we pick a longer timeout threshold?

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 3]
```diff
@@ -10794,6 +10794,52 @@ func TestChangefeedProtectedTimestampUpdate(t *testing.T) {
...
+			return err
+		}
+	}
+
+	testFn := func(t *testing.T, s TestServer, f cdctest.TestFeedFactory) {
+		db := sqlutils.MakeSQLRunner(s.DB)
+		db.Exec(t, `CREATE TABLE foo (key INT PRIMARY KEY);`)
+		db.Exec(t, `INSERT INTO foo VALUES (1), (2), (3);`)
+
+		execed := make(chan struct{})
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_test.go:10821]: nit: s/execed/done

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 4]
```diff
@@ -10794,6 +10794,52 @@ func TestChangefeedProtectedTimestampUpdate(t *testing.T) {
...
+		go func() {
+			defer close(execed)
+			// initial_scan='only' is not required, but it makes testing this easier.
+			foo := feed(t, f, `CREATE CHANGEFEED WITH initial_scan='only' AS SELECT * FROM foo WHERE key = 1`)
+			// db.Exec(t, "CREATE CHANGEFEED WITH initial_scan='only' AS SELECT * FROM foo WHERE key = 1")
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_test.go:10826]: nit: extra line?

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 5]
```diff
@@ -10794,6 +10794,52 @@ func TestChangefeedProtectedTimestampUpdate(t *testing.T) {
...
+
+		select {
+		case err := <-errCh:
+			t.Fatalf("unexpected error: %v", err)
+		case <-time.After(10 * time.Second):
+			t.Fatal("timed out")
+		case <-execed:
+		}
+	}
+	// This fails with all sinks, but it's easier to detect failures with a sinkless feed.
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_test.go:10839]: What's stopping this test from working with sinkful feeds?

**Review by andyyang890 — APPROVED** [review]
Very nice

**Comment by asg0451** [comment]
bors r=rharding6373,andyyang890

**Comment by asg0451** [comment]
bors cancel

**Comment by asg0451** [comment]
bors r=rharding6373,andyyang890

**Comment by asg0451** [comment]
bors r=rharding6373,andyyang890

**Comment by asg0451** [comment]
bors cancel
