### PR TITLE
changefeedccl: eliminate race in test validation

### LINKED ISSUE #133660: ccl/changefeedccl: TestChangefeedIdleness failed
ccl/changefeedccl.TestChangefeedIdleness [failed](https://tanzanite.cluster.engflow.com/invocations/default/d44c68cc-946c-456d-b2c2-cf5ac1b064a8?testReportRun=3&testReportShard=12&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on release-24.1.7-rc @ [62d13cef08f5a5b487216dc9c996f01a866f1341](https://github.com/cockroachdb/cockroach/commits/62d13cef08f5a5b487216dc9c996f01a866f1341):

```
=== RUN   TestChangefeedIdleness
    test_log_scope.go:165: test logs captured to: outputs.zip/logTestChangefeedIdleness3570400521
    test_log_scope.go:76: use -show-logs to present logs inline
    changefeed_test.go:511: -- test log scope end --
test logs left over in: outputs.zip/logTestChangefeedIdleness3570400521
--- FAIL: TestChangefeedIdleness (236.07s)
=== RUN   TestChangefeedIdleness/webhook
    helpers_test.go:872: making server as system tenant
    helpers_test.go:948: making webhook feed factory
    changefeed_test.go:473: condition failed to evaluate within 3m45s: expected (0) idle changefeeds, found (2)
    --- FAIL: TestChangefeedIdleness/webhook (236.07s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=3</code>
 - <code>shard=12</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestChangefeedIdleness.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-43721

### LINKED ISSUE #134304: ccl/changefeedccl: TestChangefeedIdleness failed
ccl/changefeedccl.TestChangefeedIdleness [failed](https://tanzanite.cluster.engflow.com/invocations/default/46d43d27-2b1b-4f59-9b36-476bbde2d942?testReportRun=1&testReportShard=13&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on release-24.3 @ [6d792725ebcbb766255fc5561a465b997bfc390e](https://github.com/cockroachdb/cockroach/commits/6d792725ebcbb766255fc5561a465b997bfc390e):

```
=== RUN   TestChangefeedIdleness
    test_log_scope.go:165: test logs captured to: outputs.zip/logTestChangefeedIdleness278750903
    test_log_scope.go:76: use -show-logs to present logs inline
    changefeed_test.go:513: -- test log scope end --
test logs left over in: outputs.zip/logTestChangefeedIdleness278750903
--- FAIL: TestChangefeedIdleness (243.19s)
=== RUN   TestChangefeedIdleness/cloudstorage
    helpers_test.go:883: making server as secondary tenant
    helpers_test.go:962: making cloudstorage feed factory
    testfeed_test.go:301: creating external connection
    testfeed_test.go:304: ran create external connection
    testfeed_test.go:301: creating external connection
    testfeed_test.go:304: ran create external connection
    changefeed_test.go:475: condition failed to evaluate within 3m45s: expected (0) idle changefeeds, found (2)
    --- FAIL: TestChangefeedIdleness/cloudstorage (243.18s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=1</code>
 - <code>shard=13</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #133660 ccl/changefeedccl: TestChangefeedIdleness failed [A-cdc C-test-failure O-robot T-cdc branch-release-24.1.7-rc]
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestChangefeedIdleness.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-44015

### PR DESCRIPTION
**Pull request by rharding6373**
TestChangefeedIdleness checks that the changefeed job state correctly moves in and out of the idle state. This change fixes a race condition when validating that jobs move out of idle state after an insert, since it's possible that the job becomes active and then idle again before the test is able to validate that the state was not idle.

Epic: none

Fixes: #134304
Fixes: #133660

Release note: None

### CODE REVIEW

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 1]
```diff
@@ -486,9 +492,13 @@ func TestChangefeedIdleness(t *testing.T) {
 		cf2 := feed(t, f, "CREATE CHANGEFEED FOR TABLE bar WITH resolved='10ms'")
 		defer closeFeed(t, cf1)
 
+		// Changefeed should run after the insert, but start the check before it
+		// because the changefeed may become idle again before the next
+		// opportunity to check occurs.
```
Comment (wenyihu6) [inline pkg/ccl/changefeedccl/changefeed_test.go:497]: Is it possible that the test may still flake if changefeed becomes non-idle for just one instant, and SucceedsSoon misses that during its time.Sleep? https://github.com/cockroachdb/cockroach/blob/049c30ac6956fa8f307ba2adae8b4388f5907859/pkg/util/retry/retry.go#L220

Aside, this explanation makes sense, but I'm confused why this wasn't flaking before. Longer test latency doesn't seem to check out the flakiness here since it feels like what happened here was the changefeed became non-idle and idle again in a shorter duration? How does it feel to you?

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134331)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @wenyihu6)

___
*[`pkg/ccl/changefeedccl/changefeed_test.go` line 497 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134331#gh-1829789591:-OAxmothAVVVQtiaQ2qN:b-gk25cy) ([raw file](https://github.com/cockroachdb/cockroach/blob/395dd50164b6271c270b9491aee3cd2bee3ccc45/pkg/ccl/changefeedccl/changefeed_test.go#L497)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

Is it possible that the test may still flake if changefeed becomes non-idle for just one instant, and SucceedsSoon misses that during its time.Sleep? https://github.com/cockroachdb/cockroach/blob/049c30ac6956fa8f307ba2adae8b4388f5907859/pkg/util/retry/retry.go#L220

Aside, this explanation makes sense, but I'm confused why this wasn't flaking before. Longer test latency doesn't seem to check out the flakiness here since it feels like what happened here was the changefeed became non-idle and idle again in a shorter duration? How does it feel to you? 
</blockquote></details>

Ah, good point, this can't catch all possible job state changes.

The test logs for these failures appear that the # of idle feeds goes from 1 to 2 when checking for the first `waitForIdleCount(0)`, so timing seems like the most likely cause. Depends on how the test routine gets scheduled in relationship to the database. Not sure why it would have only started flaking recently.

Going to spend a bit more time thinking about if there's a better way to check this.

**Review by wenyihu6 — APPROVED** [review]
Discussed over slack - we don't want to hold off merging given this is for test deflaking. We will discuss more as follow-ups if this test continues to flake.

**Comment by rharding6373** [comment]
Neglected to follow up merging this after all. Rebased and ready to try merging again. TFTRs @wenyihu6!

bors r=wenyihu6
