### PR TITLE
sql: add crdb_internal.reset_sql_stats() builtin

### LINKED ISSUE #62587: roachtest: sqlsmith: crdb_internal.reset_sql_stats(): sql stats resetter not set
[(roachtest).sqlsmith/setup=seed/setting=no-mutations failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2812257&tab=buildLog) on [master@cbebc6e05491c6951216993ed5e12e22504624f2](https://github.com/cockroachdb/cockroach/commits/cbebc6e05491c6951216993ed5e12e22504624f2):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/sqlsmith/setup=seed/setting=no-mutations/run_1
	sqlsmith.go:226,sqlsmith.go:262,test_runner.go:768: error: pq: internal error: crdb_internal.reset_sql_stats(): sql stats resetter not set
		stmt:
		WITH
			with_642 (col_3897)
				AS (
					SELECT
						e'{"foo": [], "iqx;qV4": [0.475864628985448, null, [[false, "n<&\\"(p2M", []]], [null, []]]}':::JSONB
							AS col_3897
					FROM
						defaultdb.public.seed@[0] AS tab_1612
					WHERE
						true
				),
			with_648 (col_3909, col_3910)
				AS (
					SELECT
						*
					FROM
						(
							VALUES
								((), e']=c=;\x0e%':::STRING:::NAME),
								(
									(),
									CASE
									WHEN (false AND EXISTS (WITH with_643 (col_3898, col_3899, col_3900, col_3901, col_3902) AS (SELECT * FROM (VALUES ('M':::STRING, '0105000020E6100000070000000102000000070000001445AD92CCE657C0CD3D50F0495E53C0286036004C973240C0BA603ADD7853C0287FF36CDDF23940B6A5AF4AA1A14FC0A8DD7908CD814440EC1EE8DCCBFF51C0F2B2B8BFD9C16240E84B206501524040CAE83703FF245240A047CCC239423940986D807E21C25B40B46BF68F14E854400102000000030000005450A0E4F9CE60404F71B1D16EC450C03661EED88EE46240E00C48CB6AB729C030A888A0B26D5040F0C9DA828BDD4940010200000004000000C0C006825301364057AE6BC8BE1450C0F83A2DF8D7FD6540B68F9ACE005E3DC03CFB33234F554840805A3DF4A8C6F0BF741BD93DEB894AC0526F941ECE39514001020000000300000060C03BE4B55945405B7CD93B6D2A44C09C73F3F4892D5E40B0C0BDEF264312C02265CFC22C5762C0A8AA66A4F95749400102000000020000000E3AA152859B624043C9C4896B3942C0FA275EE96CE560407CA2CBBF169941C0010200000002000000E807A7C63B194540081F70F63E2650C0F8F906538CA33B405630D312B8BF3FC0010200000004000000E83F6E8065C36040DEC02F7D460A50C07EEE8963DD5F6340A0100D88471E0AC000AFF9B6CFE0554050566D92C7461E4000141A4ECF4943C0CC7EFB7646173740':::GEOGRAPHY, '{"DTh": null, "a": ["c", {}], "bar": {"foo": 0.021000040016623533}, "k#q}64z?JqwJ": {"$Ar": {"c": [{"a": []}]}, "ia|$]%MK_": {}}}':::JSONB, '5311d8dc-f3fc-4052-9297-ebc920ce93bd':::UUID, '2006-02-25 05:15:42.000523+00:00':::TIMESTAMPTZ), ('X':::STRING, '0101000020E61000008CA91246215B5940920E3ABF76985240':::GEOGRAPHY, '{"E`ssqK~": [["a", [], {}], [[null]], [null], {}], "bar": "bar", "foo": {}}':::JSONB, '1e5a0a57-fd63-4faf-8ad7-72d7028aa6b4':::UUID, '2008-03-07 19:08:22.000483+00:00':::TIMESTAMPTZ), (e'\x1e':::STRING, '01010000A0E61000003A6462E6E2DE6540E0CD53ACA04C05C0FE6C7110168CFBC1':::GEOGRAPHY, '[[], [false, "a"], {":/uo9:": {"c": ["foobar", [], {}]}, "foo": true}, [], [{"foo": {}}], {"6XH": true}]':::JSONB, '3d7e3645-d204-410d-8814-df01903bcbd2':::UUID, NULL), ('f':::STRING, '0107000020E6100000030000000105000020E610000004000000010200000009000000BC8055CA581A40C02713909A15E852C090F65E2648193FC0DBC9DF063BAC53C01AE3F33459426040399C2135E78A46C02880E67B33735940609AFEEB04A337C0F04D23EFED7E5D40A8CC9FB4195E3340ECDB9599857F5540AA43183229D55240C181D2A9712358C09C8B98DA2E414A405A7DF7675CC060C0B42322EBE47D414038765A21590661C0F445E6F3DA8E41400102000000020000001EDC7598ADAB634038C63A6E2C285640ACF5CA83EB674340C643D562904156400102000000020000000B1870ADEAE563C0208787FDEF8144409AA36163F97852C0880E5FA1DA0F2F40010200000004000000D824A57A47294940DCD0E1A3FE0F4FC06071D00168A356405C7E56602A0652C0ACDDF7B024295840FEF2917BC2F546C04C1E0A8A5E246440B83BECE44C494D400105000020E61000000800000001020000000300000018EA1F7ADC244EC020CB45B2ABB02B4038AD7A77E64D5F409095E384D8A1354080F49A10F9855640AC46222552424D40010200000004000000D4A69461C587634062A7288A77EA54C0984C886374A76540E0943852747548C0B8D061190DFE634068365D025A4049405C9B9AFD11045E40FC7400178DD7384001020000000300000078F3484FDEDA53400F2B1B5201164AC0B8BCFE5909DB5040EECF219A1E335140E07BB08991D832C0A4ED7DCB9B1C5540010200000002000000E8881DE9BC6E63409E71D89D7135424021F31DA1D7B165C0E0FD4EBDD6722D40010200000002000000D0C40730DDAC4F4088AA660F48A037C0931EBF60C0A863C04BF36C56822544C0010200000004000000847C96765FE458403EE304DE88AD42C07E9101D29C7265407C67C8A3CC7544C0920B21DB6A0B6440080E99CC4AA02340E0E062B07D194B402E3F877FB05F4140010200000003000000EE6E25D6AF616240F8CC45AA5B9152C0CCF3349F63C25A40009BA3FCB72FF83F9EFF60E05E536240B8CC693A20733E4001020000000300000008C9A47FFB0152C096F423DF0DE652401285F341714454C0F48B8E63FB8D3940D205834B3F7B54C00097A08B07AF2C400105000020E610000004000000010200000003000000E6D37E365FA155C03AAFC8FDD13151409A24DB7F7FD858C000CEE3F2863BEC3FDBCD82CAD2455BC040621CE0EB151BC0010200000004000000108BED5F04A63640109CC6D613584CC04C95F26BEA85484076E11561F85247C0DA68E00E5FC16440E0DF29C88CFB084050431FC7C2B748408C85E70450C43240010200000002000000FC3090AA16A849C0EC42A3471D6C40408126EB2612C364C09C51368799C84C40010200000002000000C509F6FA538963C0F173994BCBA855C000C0B08F6D2A0440C0DC87C8ED020640':::GEOGRAPHY, (e'[{"6i\\\\K": null, "t{w7CZlp-E": []}, [{"bar": {}, "oAmbPxUc": []}], {}, [], {"a": {}, "bar": []}]':::JSONB::JSONB - e'5\tdZ9':::STRING::STRING)::JSONB, '76641f60-c11b-48be-800b-c93115842548':::UUID, '1991-06-20 11:06:47.000276+00:00':::TIMESTAMPTZ)) AS tab_1613 (col_3898, col_3899, col_3900, col_3901, col_3902)), with_646 (col_3906) AS (SELECT * FROM (VALUES (B'10010000010101001110000110011001111001001100'), ((WITH with_644 (col_3903) AS (SELECT * FROM (VALUES ('05:34:53.155677':::TIME)) AS tab_1614 (col_3903)), with_645 (col_3904) AS (SELECT * FROM (VALUES (5895:::INT8), (21793:::INT8), (NULL), (12373:::INT8), (24859:::INT8), (0:::INT8)) AS tab_1615 (col_3904)) SELECT NULL AS col_3905 FROM defaultdb.public.seed@[0] AS tab_1616 WHERE tab_1616._bool ORDER BY tab_1616._uuid, tab_1616._int4 DESC, tab_1616._date DESC LIMIT 1:::INT8)), (B'00000000000000000000000000000000000000000000')) AS tab_1617 (col_3906)), with_647 (col_3907) AS (SELECT * FROM (VALUES (false), (true), (false)) AS tab_1618 (col_3907)) SELECT tab_1619._interval AS col_3908 FROM defaultdb.public.seed@[0] AS tab_1619 WHERE false))
									THEN e'c&\f\x0b9WX':::STRING:::NAME
									ELSE '{9v)!':::STRING:::NAME
									END
								),
								((), e'?_yeRns\x14A':::STRING:::NAME)
						)
							AS tab_1620 (col_3909, col_3910)
				)
		SELECT
			json_build_object(NULL)::JSONB AS col_3911
		FROM
			with_642 AS cte_ref_213
		GROUP BY
			cte_ref_213.col_3897
		HAVING
			crdb_internal.reset_sql_stats()::BOOL;

```

<details><summary>More</summary><p>

Artifacts: [/sqlsmith/setup=seed/setting=no-mutations](https://teamcity.cockroachdb.com/viewLog.html?buildId=2812257&tab=artifacts#/sqlsmith/setup=seed/setting=no-mutations)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Asqlsmith%2Fsetup%3Dseed%2Fsetting%3Dno-mutations.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by Azhng**
Previously, there was no mechanism to immediately clear SQL statistics. Users
would have to wait until the reset interval expires. This commit creates a
builtin to immediately clears SQL stats.

Release note (sql change): SQL stats can now be cleared using
crdb_internal.reset_sql_stats()

Addresses #33315

### CODE REVIEW

**Comment by Azhng** [comment]
Couldn't recreate the CI failures both locally and on GCE worker. Will take another look tomorrow.

**Comment by Azhng** [comment]
Fixed the test. CI is green. Ready for review

**Review by asubiotto — CHANGES_REQUESTED** [review]
Nice! @maryliag would be great if you could review as well even if it's just to ask questions.

> Reviewed 10 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-:-MWAiJJK4MyP-3m657yn:b-ys4w2u)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[docs/generated/http/full.md, line 2839 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MWAax2LAo3G49Dh48bO:-MWAax2LAo3G49Dh48bP:b28v37v) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/docs/generated/http/full.md#L2839)):*
> ```Markdown
> ## SQLStatisticsReset
> 
> `POST /_status/sqlstatisticsreset`
> ```

I would change the name here to be more in line with the builtin. It also sounds more "active", i.e. "resetsqlstats" instead of "sqlstatisticsreset". I also think it's worth it to shorten statistics to stats here and elsewhere.
___
*[docs/generated/http/full.md, line 2873 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MWAbFBs5Ou_RsjcGJbs:-MWAbFBs5Ou_RsjcGJbt:b-btlgdc) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/docs/generated/http/full.md#L2873)):*
> ```Markdown
> | Field | Type | Label | Description | Support status |
> | ----- | ---- | ----- | ----------- | -------------- |
> | num_of_nodes_resetted | [int32](#cockroach.server.serverpb.SQLStatisticsResetResponse-int32) |  | Number of nodes that have resetted their SQL stats. | [reserved](#support-status) |
> ```

nit: here and elsewhere `s/resetted/reset`.

Also, why return the number of nodes reset? Is it used anywhere?
___
*[docs/generated/sql/functions.md, line 2717 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MWAcREx3qtzI4wB3QjV:-MWAcREx3qtzI4wB3QjW:bnxhf18) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/docs/generated/sql/functions.md#L2717)):*
> ```Markdown
> <tr><td><a name="crdb_internal.range_stats"></a><code>crdb_internal.range_stats(key: <a href="bytes.html">bytes</a>) &rarr; jsonb</code></td><td><span class="funcdesc"><p>This function is used to retrieve range statistics information as a JSON object.</p>
> </span></td></tr>
> <tr><td><a name="crdb_internal.reset_sql_statistics"></a><code>crdb_internal.reset_sql_statistics() &rarr; <a href="bool.html">bool</a></code></td><td><span class="funcdesc"><p>This function can be used to clear the collected SQL-related statistics.</p>
> ```

nit: `s/can be used/is used` and `s/SQL-related/SQL`
___
*[pkg/server/sql_stats.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MWAdV6LA2eNj5sSYtDL:-MWAdV6LA2eNj5sSYtDM:b-dpnbiz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/pkg/server/sql_stats.go#L23)):*
> ```Go
> )
> 
> func (s *statusServer) SQLStatisticsReset(
> ```

cc @yuzefovich when you added the contention API you mentioned a v2 status server, should this method be implemented there?

As mentioned before, I think it'd be nicer to `s/SQLStatisticsReset/ResetSQLStats`
___
*[pkg/server/sql_stats.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MWAdqxWEmAOtmbBohVC:-MWAdqxWEmAOtmbBohVD:b-4vi3c1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/pkg/server/sql_stats.go#L72)):*
> ```Go
> 			response.NumOfNodesResetted++
> 		},
> 		func(nodeID roachpb.NodeID, err error) {
> ```

Empty fn?
___
*[pkg/server/stats_test.go, line 264 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MWAdM9L4ev4wlR3juzi:-MWAdM9L4ev4wlR3juzj:b-rr2q3a) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/pkg/server/stats_test.go#L264)):*
> ```Go
> 
> func resetClusterStats(ctx context.Context, cluster serverutils.TestClusterInterface) {
> 	// Flush stats at the beginning of the test.
> ```

nit: remove comment, I think this belongs outside the function (as you've done)
___
*[pkg/server/stats_test.go, line 287 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MWAf1EMDaQGwLSLZrn6:-MWAf1EMDaQGwLSLZrn7:b-fr1pde) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/pkg/server/stats_test.go#L287)):*
> ```Go
> 
> 	// Flush stats at the beginning of the test.
> 	resetClusterStats(ctx, testCluster)
> ```

Why do the stats need to be reset at the start?
___
*[pkg/server/stats_test.go, line 300 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MWAeDeh2iGSoeReVgNn:-MWAeDeh2iGSoeReVgNo:btsya0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/pkg/server/stats_test.go#L300)):*
> ```Go
> 	statsPreReset, err := status.Statements(ctx, &serverpb.StatementsRequest{})
> 	if err != nil {
> 		t.Fatal(err)
> ```

Consider using `require` (e.g. `require.NoError` in this case) to help with vebosity in this test.
___
*[pkg/server/tenant_status.go, line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MWAei6J8TEyYVnhLIin:-MWAei6J8TEyYVnhLIio:b98w6yg) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/pkg/server/tenant_status.go#L119)):*
> ```Go
> ) (*serverpb.SQLStatisticsResetResponse, error) {
> 	// TODO(azhng): Currently a tenant status server only reset its local SQL stats,
> 	// 	this needs to be updated once the pod-to-pod communication is implemented.
> ```

I think it'd be nice to add a top-level comment about this rather than just have it in this function.
___
*[pkg/server/testserver.go, line 763 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MWAfhIr9SDY-FTbRez7:-MWAfhIr9SDY-FTbRez8:b-2w047g) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/pkg/server/testserver.go#L763)):*
> ```Go
> 
> 	// Since SQLStatusServer requires a pointer to SQLServer, it is constructed after SQLServer is
> 	// constructed and retrospectively added to SQLServer's execCfg.
> ```

nit: I would just delete this comment.
___
*[pkg/server/serverpb/status.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MWAfp0W3_EJ0uH7EXXC:-MWAfp0W3_EJ0uH7EXXD:bynz6yh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/pkg/server/serverpb/status.go#L28)):*
> ```Go
> 	ListContentionEvents(context.Context, *ListContentionEventsRequest) (*ListContentionEventsResponse, error)
> 	ListLocalContentionEvents(context.Context, *ListContentionEventsRequest) (*ListContentionEventsResponse, error)
> 	SQLStatisticsReset(ctx context.Context, request *SQLStatisticsResetRequest) (*SQLStatisticsResetResponse, error)
> ```

cc @azhng in a follow up PR, could you add the actual stats endpoints? This should support us displaying stats in a tenant's DB Console. If it doesn't work it'd be nice to know this sooner rather than later cc @jordanlewis 
___
*[pkg/sql/sem/tree/eval.go, line 3271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MWAiCa46XJaEKvFeVAQ:-MWAiCa46XJaEKvFeVAR:bkb52cv) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/pkg/sql/sem/tree/eval.go#L3271)):*
> ```Go
> // SQLStatisticsResetter is an interface embedded in EvalCtx which can be used by
> // the builtins to reset SQL stats.
> type SQLStatisticsResetter interface {
> ```

nit: `s/SQLStatisticsResetter/SQLStatsResetter`
___
*[pkg/sql/sem/tree/eval.go, line 3272 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MWAi5Cv5fVp6rywWRK5:-MWAi5Cw5o9-YL49jsUx:b39o330) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/pkg/sql/sem/tree/eval.go#L3272)):*
> ```Go
> // the builtins to reset SQL stats.
> type SQLStatisticsResetter interface {
> 	SQLStatsReset(ctx context.Context) error
> ```

Nice.

`s/SQLStatsReset/ResetSQLStats` and comment that the interface exists to avoid a dependency

File: pkg/server/tenant_status.go [hunk 1]
```diff
@@ -109,3 +111,14 @@ func (t *tenantStatusServer) ListLocalContentionEvents(
...
 }
+
+func (t *tenantStatusServer) SQLStatisticsReset(
+	ctx context.Context, _ *serverpb.SQLStatisticsResetRequest,
+) (*serverpb.SQLStatisticsResetResponse, error) {
+	// TODO(azhng): Currently a tenant status server only reset its local SQL stats,
+	// 	this needs to be updated once the pod-to-pod communication is implemented.
+	t.sqlServer.pgServer.SQLServer.ResetSQLStats(ctx)
+	return &serverpb.SQLStatisticsResetResponse{
+		NumOfNodesResetted: 1,
```
Comment (maryliag) [inline pkg/server/tenant_status.go:122]: `NumOfNodesReset`

**Review by maryliag — COMMENTED** [review]
Just a few nit picking

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62175)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @Azhng)

___
*[docs/generated/http/full.md, line 2873 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MWAbFBs5Ou_RsjcGJbs:-MWBcHFL4k6RSNWIu8Ym:bf7yhqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/docs/generated/http/full.md#L2873)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: here and elsewhere `s/resetted/reset`.

Also, why return the number of nodes reset? Is it used anywhere?
</blockquote></details>

My thoughts here is that since resetting the stats requiring fan-out RPCs to all nodes in the cluster, it is possible for number of  RPCs to fail for various reasons. 
If the reset operation only partially failed, it is difficult to communicate the partial failure using a simple boolean. Hence I opted for a numeric value here. 
But yes I should probably change the return value of the builtin from boolean to an int value.  
___
*[pkg/server/sql_stats.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MWAdqxWEmAOtmbBohVC:-MWBexRL8X0lavkjIlnM:bdoi0d7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/pkg/server/sql_stats.go#L72)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Empty fn?
</blockquote></details>

It is empty because I think `iterateNodes` does not check for `nil` before calling `errorFn`. I was using [`statement.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/server/statements.go#L80) as a reference, and seems like it simply ignored the error if the RPC fails. Since the result of RPC is communicate through number of nodes where reset operations were successful, I don't think additional error handling logic is required here.

Though I think the alternative is to modify the `iterateNodes` to check for `nil` before calling `errorFn`. I don't have particular preference for either, what's your thoughts on this?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62175)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @Azhng)

___
*[pkg/server/sql_stats.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MWAdV6LA2eNj5sSYtDL:-MWQBqGz3zPqWRnRn4gj:b-nglo5u) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/pkg/server/sql_stats.go#L23)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

cc @yuzefovich when you added the contention API you mentioned a v2 status server, should this method be implemented there?

As mentioned before, I think it'd be nicer to `s/SQLStatisticsReset/ResetSQLStats`
</blockquote></details>

My thinking is that for now it is ok to implement things as v1 only, but soon (in 21.2 release) we'll need to implement everything as v2, so it's up to Archer to decide when to do it.

**Review by Azhng — COMMENTED** [review]
@asubiotto  can you PTAL ? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-:-MWQbe7h7u-q-YNaZOrl:b4onrci)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @maryliag)

___
*[docs/generated/http/full.md, line 2839 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MWAax2LAo3G49Dh48bO:-MWPfftg0EvxDP6t2ocn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/docs/generated/http/full.md#L2839)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I would change the name here to be more in line with the builtin. It also sounds more "active", i.e. "resetsqlstats" instead of "sqlstatisticsreset". I also think it's worth it to shorten statistics to stats here and elsewhere.
</blockquote></details>

Done.
___
*[docs/generated/http/full.md, line 2873 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MW1CICzfUXV5ncd9L9X-r1-2873:-MWPfgolDGwkbGmGnkhP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/docs/generated/http/full.md#L2873)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

`reset`, not `resetted`
</blockquote></details>

Done.
___
*[pkg/server/sql_stats.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MWAdV6LA2eNj5sSYtDL:-MWQbSxuCL18fudogHxJ:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/pkg/server/sql_stats.go#L23)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

My thinking is that for now it is ok to implement things as v1 only, but soon (in 21.2 release) we'll need to implement everything as v2, so it's up to Archer to decide when to do it.
</blockquote></details>

Done. 
___
*[pkg/server/stats_test.go, line 287 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MWAf1EMDaQGwLSLZrn6:-MWPiL_h0CND7kTcbddT:b-umv7zs) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/pkg/server/stats_test.go#L287)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why do the stats need to be reset at the start?
</blockquote></details>

Hmm seems like it's not needed. Removed
___
*[pkg/server/stats_test.go, line 300 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MWAeDeh2iGSoeReVgNn:-MWPiQlKEkwDnqVvqzIs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/pkg/server/stats_test.go#L300)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Consider using `require` (e.g. `require.NoError` in this case) to help with vebosity in this test.
</blockquote></details>

Done.
___
*[pkg/server/stats_test.go, line 313 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MW1CICzfUXV5ncd9L9e-r1-313:-MWPeVTsAQ1fW-uaO4wb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/pkg/server/stats_test.go#L313)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

the previous test had `but found:` and this one doesn't have the `:`. Change one of them so they're the same
</blockquote></details>

Done.
___
*[pkg/server/tenant_status.go, line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MWAei6J8TEyYVnhLIin:-MWPe_NHAN6wYOAfvAsA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/pkg/server/tenant_status.go#L119)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think it'd be nice to add a top-level comment about this rather than just have it in this function.
</blockquote></details>

Done.
___
*[pkg/server/tenant_status.go, line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MW1CICzfUXV5ncd9L9g-r1-122:-MWPea8-97yA2J9TzvVe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/pkg/server/tenant_status.go#L122)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

`NumOfNodesReset`
</blockquote></details>

Done.
___
*[pkg/server/testserver.go, line 763 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MWAfhIr9SDY-FTbRez7:-MWPiklG21Dx2cBUmKhx:b-v6s1o3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/pkg/server/testserver.go#L763)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: I would just delete this comment.
</blockquote></details>

Removed. 
___
*[pkg/server/serverpb/status.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MWAfp0W3_EJ0uH7EXXC:-MWPiZi12R0dVy5ml7I7:bntmwa3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/pkg/server/serverpb/status.go#L28)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

cc @azhng in a follow up PR, could you add the actual stats endpoints? This should support us displaying stats in a tenant's DB Console. If it doesn't work it'd be nice to know this sooner rather than later cc @jordanlewis 
</blockquote></details>

Sounds good, will send a follow up PR after this. 
___
*[pkg/server/serverpb/status.proto, line 1020 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MW1CICzfUXV5ncd9L9c-r1-1020:-MWPepzP8AVSvia42Bqd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/pkg/server/serverpb/status.proto#L1020)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

comment and variable name (make sure to fix all places this variable is called): `reset` and not `resetted`
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/eval.go, line 3272 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MWAi5Cv5fVp6rywWRK5:-MWPfUl4E5uJEqWhE0wu:b-onyfox) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/pkg/sql/sem/tree/eval.go#L3272)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Nice.

`s/SQLStatsReset/ResetSQLStats` and comment that the interface exists to avoid a dependency
</blockquote></details>

`ResetSQLStats` is already a function in `conn_executor.go`. I suppose I can rename this to `ResetClusterSQLStats`.

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 2 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62175)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @Azhng, and @maryliag)

___
*[pkg/server/sql_stats.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MWAdqxWEmAOtmbBohVC:-MWU3h0V4cwSEPhYDQ1G:bmsqlve) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/pkg/server/sql_stats.go#L72)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

It is empty because I think `iterateNodes` does not check for `nil` before calling `errorFn`. I was using [`statement.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/server/statements.go#L80) as a reference, and seems like it simply ignored the error if the RPC fails. Since the result of RPC is communicate through number of nodes where reset operations were successful, I don't think additional error handling logic is required here.

Though I think the alternative is to modify the `iterateNodes` to check for `nil` before calling `errorFn`. I don't have particular preference for either, what's your thoughts on this?
</blockquote></details>

So why not use this mechanism instead of returning the number of nodes in the response? I think it's not good usability to have the `NumNodesReset` field because you're just pushing the error handling logic one layer up. The caller shouldn't have to care or know the details about how this RPC is executed. I think what you should do is remove that field and instead combine errors in this function and return an error as normal.

**Review by asubiotto — COMMENTED** [review]
> Reviewed 1 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62175)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @Azhng, and @maryliag)

___
*[pkg/server/tenant_status.go, line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MWAei6J8TEyYVnhLIin:-MWU5H1Q6XheQQm5AufM:b-8jo5pz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/pkg/server/tenant_status.go#L119)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, I meant a top-level file comment. i.e. all functions need to be updated once we have pod-to-pod communication. Even better, we probably would remove this tenant status server entirely and use the normal status server once we remove any dependencies unavailable to tenants.

**Comment by Azhng** [comment]
Appears to be a flake.

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62175)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @maryliag)

___
*[pkg/server/sql_stats.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MWAdqxWEmAOtmbBohVC:-MWV6if00o5kqV1fyZ1Y:b-4h6jhy) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/pkg/server/sql_stats.go#L72)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

So why not use this mechanism instead of returning the number of nodes in the response? I think it's not good usability to have the `NumNodesReset` field because you're just pushing the error handling logic one layer up. The caller shouldn't have to care or know the details about how this RPC is executed. I think what you should do is remove that field and instead combine errors in this function and return an error as normal.
</blockquote></details>

Changed the response to have an array of Error protobuf objects. 
___
*[pkg/server/tenant_status.go, line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MWAei6J8TEyYVnhLIin:-MWV7jboDMLAObzc8sDg:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/pkg/server/tenant_status.go#L119)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Sorry, I meant a top-level file comment. i.e. all functions need to be updated once we have pod-to-pod communication. Even better, we probably would remove this tenant status server entirely and use the normal status server once we remove any dependencies unavailable to tenants.
</blockquote></details>

Done

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62175)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @Azhng, and @maryliag)

___
*[pkg/server/sql_stats.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MWAdqxWEmAOtmbBohVC:-MWVRLRo9UoznKhC1bck:b2wa9zs) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/pkg/server/sql_stats.go#L72)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Changed the response to have an array of Error protobuf objects. 
</blockquote></details>

What I meant is use `errors.CombineErrors` and return the result as an error here (i.e. `nil, err`) this will return the error as a GRPC error

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62175)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @maryliag)

___
*[pkg/server/sql_stats.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-MWAdqxWEmAOtmbBohVC:-MWVXMz-AMxf-kbyQLqV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b178cdc30e8c2fa9969f7d7d3650a905bb7f735/pkg/server/sql_stats.go#L72)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

What I meant is use `errors.CombineErrors` and return the result as an error here (i.e. `nil, err`) this will return the error as a GRPC error
</blockquote></details>

Done.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 15 files at r1, 1 of 13 files at r2, 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62175#-:-MWZopYP79lNKir5bd_3:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag)

**Comment by Azhng** [comment]
TFTR! 

bors r=asubiotto

**Comment by Azhng** [comment]
bors r=asubiotto

**Comment by rafiss** [comment]
Just passing by and this looks great! Nice work.

I noticed that the PR description says `Addresses #33315` -- just as a heads up, that will not automatically close the issue. If you use `Closes #33315` or `Fixes #33315`, then it would. See https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by Azhng** [comment]
Hi @rafiss , thanks for the heads up. Though this PR only partially addressed the issue by adding a builtin and an RPC endpoint, we are still working on adding the frontend components that will allow uses to reset SQL stats from db console.

**Comment by rafiss** [comment]
Gotcha! I was wondering if it was on purpose but just wanted to point it out in case
