### PR TITLE
testcluster: fix dial check on restart

### LINKED ISSUE #111163: kv/kvserver/loqrecovery: TestRejectBadVersionApplication failed
kv/kvserver/loqrecovery.TestRejectBadVersionApplication [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/11899228?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/11899228?buildTab=artifacts#/) on master @ [b1a641f1d27653a4e93154926be57d0cae864bd6](https://github.com/cockroachdb/cockroach/commits/b1a641f1d27653a4e93154926be57d0cae864bd6):

```
=== RUN   TestRejectBadVersionApplication
    test_log_scope.go:167: test logs captured to: /artifacts/tmp/_tmp/95fc0dff57a5bf3a6a9cc9666d301bb7/logTestRejectBadVersionApplication4218276940
    test_log_scope.go:81: use -show-logs to present logs inline
    server_integration_test.go:664: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/kv/kvserver/loqrecovery_test/pkg/kv/kvserver/loqrecovery/server_integration_test.go:664
        	Error:      	Should be true
        	Test:       	TestRejectBadVersionApplication
        	Messages:   	restarted node not found in verify status
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/95fc0dff57a5bf3a6a9cc9666d301bb7/logTestRejectBadVersionApplication4218276940
--- FAIL: TestRejectBadVersionApplication (8.39s)
```
<p>Parameters: <code>TAGS=bazel,gss</code>
, <code>stress=true</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/replication
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRejectBadVersionApplication.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-31797

### PR DESCRIPTION
**Pull request by aliher1911**
Previously server restart was incorectly dialing loopback instead of other nodes to reset circuit breakers.
This commit fixes it to dial from existing nodes to restarted one.

Epic: none
Fixes: #111163

Release note: None

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]

**Comment by erikgrinaker** [comment]
Is this relevant for backports?

File: pkg/testutils/testcluster/testcluster.go [hunk 1]
```diff
@@ -1787,6 +1787,7 @@ func (tc *TestCluster) RestartServerWithInspect(
 	// node. This is useful to avoid flakes: the newly restarted node is now on a
 	// different port, and a cycle of gossip is necessary to make all other nodes
 	// aware.
+	id := s.StorageLayer().NodeID()
```
Comment (pavelkalinnikov) [inline pkg/testutils/testcluster/testcluster.go:1790]: Why not just `s.NodeID()`? Is there some kind of mandate to type the "layer" explicitly? CC @knz to help with the answer.

**Review by pav-kv — APPROVED** [review]
Nice catch, thanks.

**Comment by aliher1911** [comment]
There's no bug in 23.1, it was using correct servers for source and destination. Looks like refactor to introduce `StorageLayer()` broke this.

File: pkg/testutils/testcluster/testcluster.go (hunk 1 above)
Comment (aliher1911) [reply pkg/testutils/testcluster/testcluster.go:1790]: We want to be explicit about what we are trying to use StorageLayer (i.e. underlying raw KV) or tenant layer. I think it makes little difference here as we manipulate servers themselves, but maybe having intent expressed explicitly is better. Then we can deprecate those methods on the level above where server could have no storage and no nodeid?
