### PR TITLE
changefeedccl: limit bank transfers in TestCatchupScanOrdering

### LINKED ISSUE #148565: ccl/changefeedccl: TestCatchupScanOrdering failed
ccl/changefeedccl.TestCatchupScanOrdering [failed](https://tanzanite.cluster.engflow.com/invocations/default/b2ffac8e-5aa4-47b6-beaf-ce36c8a7d3d8?testReportRun=3&testReportShard=4&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on master @ [603ca2299bf61260492cbe544d5caffc414d8d54](https://github.com/cockroachdb/cockroach/commits/603ca2299bf61260492cbe544d5caffc414d8d54):

```
    validations_test.go:71: time taken to make the 6296-th bank transfer: 35.34089ms
    validations_test.go:71: time taken to make the 6297-th bank transfer: 45.69017ms
    validations_test.go:71: time taken to make the 6298-th bank transfer: 40.859301ms
    validations_test.go:71: time taken to make the 6299-th bank transfer: 52.789581ms
    validations_test.go:71: time taken to make the 6300-th bank transfer: 52.14131ms
    validations_test.go:71: time taken to make the 6301-th bank transfer: 74.527082ms
    validations_test.go:71: time taken to make the 6302-th bank transfer: 84.992971ms
    validations_test.go:71: time taken to make the 6303-th bank transfer: 56.357931ms
    validations_test.go:71: time taken to make the 6304-th bank transfer: 44.38484ms
    validations_test.go:71: time taken to make the 6305-th bank transfer: 38.631491ms
    validations_test.go:71: time taken to make the 6306-th bank transfer: 45.396881ms
    validations_test.go:71: time taken to make the 6307-th bank transfer: 33.37094ms
    validations_test.go:71: time taken to make the 6308-th bank transfer: 35.068221ms
    validations_test.go:71: time taken to make the 6309-th bank transfer: 27.2631ms
    validations_test.go:71: time taken to make the 6310-th bank transfer: 27.48738ms
    validations_test.go:71: time taken to make the 6311-th bank transfer: 22.668671ms
    validations_test.go:71: time taken to make the 6312-th bank transfer: 30.29951ms
    validations_test.go:71: time taken to make the 6313-th bank transfer: 23.162621ms
    validations_test.go:71: time taken to make the 6314-th bank transfer: 33.646081ms
    validations_test.go:71: time taken to make the 6315-th bank transfer: 28.423121ms
    validations_test.go:71: time taken to make the 6316-th bank transfer: 39.744261ms
    validations_test.go:71: time taken to make the 6317-th bank transfer: 44.927711ms
    validations_test.go:71: time taken to make the 6318-th bank transfer: 45.17037ms
    validations_test.go:71: time taken to make the 6319-th bank transfer: 37.367421ms
    validations_test.go:71: time taken to make the 6320-th bank transfer: 40.59008ms
    validations_test.go:71: time taken to make the 6321-th bank transfer: 26.187411ms
    validations_test.go:71: time taken to make the 6322-th bank transfer: 20.68922ms
    validations_test.go:71: time taken to make the 6323-th bank transfer: 19.69265ms
    validations_test.go:71: time taken to make the 6324-th bank transfer: 23.947181ms
    validations_test.go:71: time taken to make the 6325-th bank transfer: 39.77697ms
    validations_test.go:71: time taken to make the 6326-th bank transfer: 30.044561ms
    validations_test.go:71: time taken to make the 6327-th bank transfer: 40.88427ms
    validations_test.go:71: time taken to make the 6328-th bank transfer: 48.92272ms
    validations_test.go:71: time taken to make the 6329-th bank transfer: 33.721371ms
    validations_test.go:71: time taken to make the 6330-th bank transfer: 43.52647ms
    validations_test.go:71: time taken to make the 6331-th bank transfer: 37.876001ms
    validations_test.go:71: time taken to make the 6332-th bank transfer: 40.39085ms
    validations_test.go:71: time taken to make the 6333-th bank transfer: 28.513481ms
    validations_test.go:71: time taken to make the 6334-th bank transfer: 23.59431ms
    validations_test.go:71: time taken to make the 6335-th bank transfer: 32.646491ms
    validations_test.go:71: time taken to make the 6336-th bank transfer: 28.8967ms
    validations_test.go:71: time taken to make the 6337-th bank transfer: 33.427221ms
    validations_test.go:71: time taken to make the 6338-th bank transfer: 34.22127ms
    validations_test.go:71: time taken to make the 6339-th bank transfer: 41.269841ms
    validations_test.go:71: time taken to make the 6340-th bank transfer: 25.16394ms
    validations_test.go:71: time taken to make the 6341-th bank transfer: 34.765421ms
    validations_test.go:71: time taken to make the 6342-th bank transfer: 28.295201ms
    validations_test.go:71: time taken to make the 6343-th bank transfer: 31.671001ms
    validations_test.go:71: time taken to make the 6344-th bank transfer: 33.90339ms
--- FAIL: TestCatchupScanOrdering/cloudstorage/bank (303.50s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=3</code>
 - <code>shard=4</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestCatchupScanOrdering.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-51674

### PR DESCRIPTION
**Pull request by rharding6373**
TestCatchupScanOrdering validates changefeed ordering by having one goroutine that makes bank transfers continuously and another goroutine that validates the order in which events are received downstream. This change limits the number of bank transfers before exiting the first goroutine to 2x the number expected downstream for a successful test run. The goal is to not have a goroutine that is doing busy work that might hog CPU.

Epic: none
Fixes: #148565

Release note: none

### CODE REVIEW

File: pkg/ccl/changefeedccl/validations_test.go [hunk 1]
```diff
@@ -62,7 +61,7 @@ func TestCatchupScanOrdering(t *testing.T) {
 			g.GoCtx(func(ctx context.Context) error {
 				prevTimeTransfer := time.Now()
 				for {
-					if atomic.LoadInt64(&done) > 0 {
+					if atomic.LoadInt64(&done) > 0 || numOfTrans.Load() > 2*checkRows {
```
Comment (aerfrei) [inline pkg/ccl/changefeedccl/validations_test.go:64]: Curiosity question: Why do we set this check to 2*checkRows instead of checkRows? Is there a risk of making too few transfers here if that number is lower?

Some background: I was curious if we would be able to remove this `done int64` variable that we modify atomically completely with this kind of change and instead rely on this check of the number of transactions here to eventually terminate the goroutine. I found that when we removed that check this goroutine made more transactions than it did on master. Seems like the 200th "seen" transaction is potentially the 103rd or so "made" transaction, I'm assuming because of data loaded in the sql workload setup. Even if we set this number in the comparison to checkRows (instead of checkRows*2) it seems like we'd still have buffer.

**Review by aerfrei — APPROVED** [review]
Looks good!

File: pkg/ccl/changefeedccl/validations_test.go (hunk 1 above)
Comment (rharding6373) [reply pkg/ccl/changefeedccl/validations_test.go:64]: The 2x was arbitrary, but I did want to potentially make some extra transactions in the test, so that when validating ordering we check that we don't send any of the newer transactions. We could remove the `done` check, but it allows the test to shut down earlier if the validator is processing quickly.

**Comment by rharding6373** [comment]
TFTR!

bors r+

File: pkg/ccl/changefeedccl/validations_test.go (hunk 1 above)
Comment (rharding6373) [reply pkg/ccl/changefeedccl/validations_test.go:64]: There are probably other improvements or tweaks that could be done with this test to make it more efficient or effective, which I'll leave for future work.
