### PR TITLE
kvserver: wait for raft leadership in TestLeaseExpirationBelowFutureTimeRequest

### LINKED ISSUE #163750: kv/kvserver: TestLeaseExpirationBelowFutureTimeRequest failed
kv/kvserver.TestLeaseExpirationBelowFutureTimeRequest [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/21112736?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/21112736?buildTab=artifacts#/) on master @ [c2323e2129492ed8f065b5d498df9422e7b97e89](https://github.com/cockroachdb/cockroach/commits/c2323e2129492ed8f065b5d498df9422e7b97e89):

```
=== RUN   TestLeaseExpirationBelowFutureTimeRequest
    test_log_scope.go:172: test logs captured to: /artifacts/tmp/_tmp/7334302ae8c22802de8334e77d6901c9/logTestLeaseExpirationBelowFutureTimeRequest663648490
    test_log_scope.go:82: use -show-logs to present logs inline
    client_replica_test.go:2045: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/7334302ae8c22802de8334e77d6901c9/logTestLeaseExpirationBelowFutureTimeRequest663648490
--- FAIL: TestLeaseExpirationBelowFutureTimeRequest (1.80s)
=== RUN   TestLeaseExpirationBelowFutureTimeRequest/tooFarInFuture=false
    test_server_shim.go:679: DRPC is enabled (via override by TestingGlobalDRPCOption)
    client_replica_test.go:2037: 
        	Error Trace:	pkg/kv/kvserver/client_replica_test.go:2037
        	            				pkg/testutils/subtest.go:23
        	Error:      	Expected nil, but got: &kvpb.Error{UnexposedTxn:(*roachpb.Transaction)(nil), OriginNode:0, EncodedError:errorspb.EncodedError{Error:(*errorspb.EncodedError_Leaf)(0x4002c47730)}, Index:(*kvpb.ErrPosition)(nil), Now:hlc.ClockTimestamp{WallTime:1771337743566954651, Logical:9}}
        	Test:       	TestLeaseExpirationBelowFutureTimeRequest/tooFarInFuture=false
--- FAIL: TestLeaseExpirationBelowFutureTimeRequest/tooFarInFuture=false (0.84s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLeaseExpirationBelowFutureTimeRequest.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-60463

### PR DESCRIPTION
**Pull request by stevendanna**
kvserver: wait for raft leadership in TestLeaseExpirationBelowFutureTimeRequest

Wait for raft leadership transfer to complete before issuing the lease
extension request. Without this, the raft group can be transiently
leaderless after AdminTransferLease, causing the lease extension to be
rejected by verifyAcquisition.

Fixes: #163750
Epic: none
Release note: None

### CODE REVIEW

**Review by miraradeva — APPROVED** [review]
LGTM!

Maybe simplify the inside of the `require.Eventually`?
```
if raftStatus := l.replica1.RaftStatus(); raftStatus != nil {
	return raftStatus.RaftState == raftpb.StateLeader
}
return false
```

File: pkg/kv/kvserver/client_replica_test.go [hunk 1]
```diff
@@ -2000,6 +2000,25 @@ func TestLeaseExpirationBelowFutureTimeRequest(t *testing.T) {
 			return lease.Replica.StoreID == l.replica1.StoreID()
 		}, 5*time.Second, 100*time.Millisecond, "timed out waiting for replica 0 to pick up new lease")
 
+		// Wait for raft leadership to transfer to the leaseholder. The lease
+		// extension below goes through verifyLeaseRequestSafetyRLocked which
+		// treats a stasis-period lease as expired (PrevLeaseExpired=true) and
+		// falls through to verifyAcquisition, which rejects if we're not the
+		// raft leader. Without this wait, the raft group can be leaderless
+		// after AdminTransferLease initiates a leadership transfer.
+		require.Eventually(t, func() bool {
```
Comment (pav-kv) [inline pkg/kv/kvserver/client_replica_test.go]: There is some guidance against `require.Eventually`, in favour of `SucceedsSoon`, see if applies. (ack that this test already uses `require`)

#100796

**Comment by stevendanna** [comment]
blathers backport 26.2
