### PR TITLE
sql/schemachanger: suffix columns were not properly handled for indexes

### LINKED ISSUE #97296: sql: Internal Error when altering primary key
**Describe the problem**

The latest alpha version of the CockroachDB (`v23.1.0-alpha.2`) encounters Internal Error when executing the following query. 

```sql
CREATE TABLE v0 (c1 DECIMAL PRIMARY KEY, c2 INTERVAL NOT NULL, c3 TIME NOT NULL, INDEX i4(c3));
INSERT INTO v0 VALUES (0.0, 'P0Y3M20DT7H43M37S'::INTERVAL, '00:00:00.0000'::TIME);
ALTER TABLE v0 ALTER PRIMARY KEY USING COLUMNS (c2, c1);
```

**To Reproduce**

1. In operating system Ubuntu 20.04 LTS, download the CockroachDB source code from the github source.
2. Download the pre-build CockroachDB binaries (v22.2.3 and v23.1.0 alpha) from [link](https://www.cockroachlabs.com/docs/releases/index.html)
3. Run `./cockroach demo`, and then paste the PoC query to the cockroach cli environment.
4. Observe the `Internal Error` and log the stack information. 

**Expected behavior**
The ALTER TABLE statement should be executed successfully. 

**Additional data / screenshots**

Here is the stack trace from `v23.1.0-alpha.2`:

```
ERROR: internal error: executing declarative schema change PostCommitPhase stage 8 of 15 with 19 MutationType ops (rollback=false) for ALTER TABLE: runtime error: index out of range [1] with length 1
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scerrors/errors.go:80: HandlePanicAndLogError()
GOROOT/src/runtime/panic.go:884: gopanic()
GOROOT/src/runtime/panic.go:113: goPanicIndex()
github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc/index.go:302: GetKeyColumnID()
github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scexec/scmutationexec/index.go:406: AddColumnToIndex()
github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/schemachanger/scop/immediate_mutation_visitor_generated.go:506: Visit()
github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scexec/exec_mutation.go:32: executeMutationOps()
github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scexec/executor.go:28: ExecuteStage()
github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun/scrun.go:186: executeStage()
github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun/scrun.go:132: func1()
github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scdeps/run_deps.go:144: func1()
github.com/cockroachdb/cockroach/pkg/sql/internal.go:1395: func1()
github.com/cockroachdb/cockroach/pkg/sql/internal.go:1483: func4()
github.com/cockroachdb/cockroach/pkg/kv/db.go:960: func1()
github.com/cockroachdb/cockroach/pkg/kv/txn.go:927: exec()
github.com/cockroachdb/cockroach/pkg/kv/db.go:959: runTxn()
github.com/cockroachdb/cockroach/pkg/kv/db.go:922: TxnWithAdmissionControl()
github.com/cockroachdb/cockroach/pkg/kv/db.go:897: Txn()
github.com/cockroachdb/cockroach/pkg/sql/internal.go:1471: txn()
github.com/cockroachdb/cockroach/pkg/sql/internal.go:1393: DescsTxn()
github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scdeps/run_deps.go:109: WithTxnInJob()
github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun/scrun.go:128: RunSchemaChangesInJob()
github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scjob/job.go:114: run()
github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scjob/job.go:45: Resume()
github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1508: func2()
github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1509: stepThroughStateMachine()
github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:413: runJob()
github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:333: func1()
github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470: func2()
GOROOT/src/runtime/asm_amd64.s:1594: goexit()

HINT: You have encountered an unexpected error.
```

**Environment:**
 - CockroachDB version: v23.1.0-alpha.2
 - Server OS: Ubuntu 20.04 LTS
 - Client app: CockroachDB demo command. (`./cockroach demo`)
 - Detailed CockroachDB version output:

```
cockroach version details:
Build Tag:        v23.1.0-alpha.2
Build Time:       2023/02/13 18:32:33
Distribution:     CCL
Platform:         linux amd64 (x86_64-pc-linux-gnu)
Go Version:       go1.19.4
C Compiler:       gcc 6.5.0
Build Commit ID:  eb158026c50d8fa856e42f928d844831ea9e6b28
Build Type:       release
```

**Additional context**

The bug can also be reproduced in `v23.1.0-alpha.2` and `v23.1.0-alpha.1`. However, the Internal Error cannot be reproduced in `v22` and theretofore. The Internal Error problem may be introduced fairly recently. 

Jira issue: CRDB-24620

### PR DESCRIPTION
**Pull request by fqazi**
Previously, the logic to determine composite column IDs, iterated over the key column count when dealing with suffix columns. This meant that when creating indexes with composite columns we could hit index out of
of range error, if the number of suffix columns was less than key columns. Additionally, the composite column IDs could be ordered incorrectly, since the ordinal mapping was incomplete. To address this, this patch loops over the correct length of the suffix columns

Fixes: #97296

Release note: None

### CODE REVIEW

File: pkg/sql/schemachanger/scexec/scmutationexec/index.go [hunk 1]
```diff
@@ -397,13 +397,12 @@ func (i *immediateVisitor) AddColumnToIndex(ctx context.Context, op scop.AddColu
 		// We don't need to track the composite column IDs for stored columns.
 		op.Kind != scpb.IndexColumn_STORED {
 
-		index.NumKeyColumns()
 		var colOrdMap catalog.TableColMap
 		for i := 0; i < index.NumKeyColumns(); i++ {
 			colOrdMap.Set(index.GetKeyColumnID(i), i)
 		}
 		for i := 0; i < index.NumKeySuffixColumns(); i++ {
-			colOrdMap.Set(index.GetKeyColumnID(i), i+index.NumKeyColumns())
```
Comment (chengxiong-ruan) [inline pkg/sql/schemachanger/scexec/scmutationexec/index.go:406]: Looks like it was logically wrong :( .... not just a out of index thing.

**Review by chengxiong-ruan — APPROVED** [review]
LGTM

**Comment by fqazi** [comment]
@chengxiong-ruan TFTR!
