### PR TITLE
sql: support indexes in regclass cast and pg_table_is_visible

### LINKED ISSUE #88097: sql: pg_table_is_visible() doesn't work for indexes
Needed for  #88061.

**Describe the problem**

PostgreSQL and CockroachDB differ on the following:
```sql
create table mytable(mycolumn int);
create index myidx on mytable(mycolumn);
select oid, pg_table_is_visible(oid) from pg_class where relname = 'myidx';
```

In PostgreSQL, this returns properly `true` for the visibility.
In CockroachDB, we get NULL.

cc @rafiss for triage.

Jira issue: CRDB-19683

Epic CRDB-17785

### PR DESCRIPTION
**Pull request by rafiss**
Epic: CRDB-23454
fixes https://github.com/cockroachdb/cockroach/issues/88097

### sql: remove deprecated function from DatabaseCatalog

The ParseQualifiedTableName function was deprecated and unused.

### sql: support casts from index name to regclass

Release note (sql change): Casts from index name to regclass are now
supported. Previously, only table names could be cast to regclass.

### sql: add index on pg_namespace(oid)

This will allow us to efficiently join to this table.

### sql: fix pg_table_is_visible to handle indexes

This uses the internal executor now to do the introspection using
pg_class where everything can be looked up all at once.

There's an increase in number of round trips, but it's a constant
factor.

Release note (bug fix): Fixed the pg_table_is_visible builtin function
so it correctly reports visibility of indexes based on the current
search_path.

### CODE REVIEW

**Comment by rafiss** [comment]
@ajwerner i added you here since this is going to intersect a bit with some changes you did in https://github.com/cockroachdb/cockroach/pull/90116

File: pkg/sql/sem/eval/parse_doid.go [hunk 1]
```diff
@@ -178,12 +179,54 @@ func ParseDOid(ctx context.Context, evalCtx *Context, s string, t *types.T) (*tr
 		if err != nil {
 			return nil, err
 		}
-		id, err := evalCtx.Planner.ResolveTableName(ctx, &tn)
+
+		if tn.ExplicitCatalog {
```
Comment (ajwerner) [inline pkg/sql/sem/eval/parse_doid.go:183]: Can you encapsulate this new logic? It's not very simple and we'll want to comment it.

**Review by ajwerner — COMMENTED** [review]
This change may have surprising performance implications. When this cast is executed, it's now no longer going to be able to leverage leases. Before we'd be doing mostly point-lookups in the happy path from in-memory data structures. Now we're going to be fetching a bunch of descriptors from the key-value store and then materializing a virtual table.

I get the motivation, but it just generally scares me a lot.

The answer I keep coming to in my head is that we need a toolkit to cache and version whole hierarchies of descriptors and we need to build data structures over them to make this sort of thing cheap. We're totally not there and I don't know when we'll get the time to be there. 

How do we validate that this change is not going to trash performance of some workload?

File: pkg/sql/sem/eval/parse_doid.go (hunk 1 above)
Comment (rafiss) [reply pkg/sql/sem/eval/parse_doid.go]: done

**Review by rafiss — COMMENTED** [review]
> Before we'd be doing mostly point-lookups in the happy path from in-memory data structures. Now we're going to be fetching a bunch of descriptors from the key-value store and then materializing a virtual table.

I've modified this so the old happy path remains. The more expensive cast logic should only happen for indexes now. I feel like the index cast is useful for debugging, but isn't something that would be as commonly used in a hot path of a workload. Also, with the new internal executor work, it's sharing more of the descriptor leases.

> How do we validate that this change is not going to trash performance of some workload?

I was hoping to see some results in the RTT benchmarks.

**Comment by ajwerner** [comment]
> >How do we validate that this change is not going to trash performance of some workload?
>
> I was hoping to see some results in the RTT benchmarks.

This is a problem with the rttanalysis benchmark. It can show decreases in round-trips if your change leads to scanning all descriptors because we do that in one round-trip. It's often very expensive.

**Comment by rafiss** [comment]
oh no
```
    rtt_analysis_bench.go:175: ORMQueries/django_table_introspection_4_tables: got 100, expected 2
```

File: pkg/sql/sem/eval/parse_doid.go [hunk 2]
```diff
@@ -178,19 +181,75 @@ func ParseDOid(ctx context.Context, evalCtx *Context, s string, t *types.T) (*tr
...
+		query = `WITH
+			  current_schemas AS (
+		      SELECT * FROM unnest(current_schemas(true)) WITH ORDINALITY AS scname
+		    )
+			SELECT c.oid
+			FROM %[1]spg_catalog.pg_class AS c
+		  JOIN %[1]spg_catalog.pg_namespace AS n ON c.relnamespace = n.oid
+		  JOIN current_schemas AS cs ON cs.scname = n.nspname
+			WHERE c.relname = $1
+			AND $2 IS NOT NULL
```
Comment (ajwerner) [inline pkg/sql/sem/eval/parse_doid.go:228]: when is `$2` NULL here? I think this is `tn.Schema()` but I think that always returns a string value. What's the intention here?

**Review by ajwerner — COMMENTED** [review]
This is cool. Thanks for adding it!

File: pkg/sql/sem/eval/parse_doid.go (hunk 2 above)
Comment (rafiss) [reply pkg/sql/sem/eval/parse_doid.go:228]: it's never null and it should get constant-folded away

there's a comment up above:
```
// There is an unused $2 placeholder in the query so that the call to QueryRow can
// be consolidated.
```

Comment (rafiss) [reply pkg/sql/sem/eval/parse_doid.go:228]: i can make it less confusing by making an `args...` slice that is different in the conditional branches, and passing it through

**Comment by rafiss** [comment]
`ORMQueries/django_table_introspection_4_tables: got 100, expected 2` is caused by the join to pg_namespace. The extra lookups theoretically could be avoided if we added a `pg_namespace(oid)` index, but right now that is not possible because schema OIDs are made through the OID hasher. But I don't see why we can't change the OIDs for schemas to be the descriptor IDs.

**Comment by rafiss** [comment]
This PR is currently blocked on https://github.com/cockroachdb/cockroach/issues/91012

**Comment by yuzefovich** [comment]
I opened up #92713 to fix #91012, it'd be nice to double check that it unblocks this PR.

**Comment by rafiss** [comment]
thanks @yuzefovich - your fix has unblocked this

**Review by ajwerner — APPROVED** [review]
:lgtm: but see how you feel about my suggestion regarding temp schemas

> Reviewed 1 of 16 files at r14, 1 of 16 files at r20, 3 of 3 files at r21, 4 of 6 files at r22, 8 of 8 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90649#-:-NIsVopBEAzuCLyk1dsc:b-fzpslw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msbutler and @rafiss)

___
*[`pkg/sql/pg_catalog.go` line 2083 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/90649#-NIsUcW18aMe3k7UIkce:-NIsUcW2-_K9inApL_LC:b-mj9tsi) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b66cdb65efab3589c186a09391d585357939573/pkg/sql/pg_catalog.go#L2083)):*
> ```Go
> 	indexes: []virtualIndex{
> 		{
> 			// incomplete is true because this index does not contain temporary schemas.
> ```

Does this matter? I think, if we can, it'd be better to say this is complete and just say our temp table implementation is somewhat broken. Given nobody ought to use it, that seems like a better tradeoff to me. Also, this will find the local session's temp namespace, right? WDYT?
___
*[`pkg/sql/pg_catalog.go` line 2107 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/90649#-NIsV7YQ5ga6vkeHnXju:-NIsV7YQ5ga6vkeHnXjv:b-7snuc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b66cdb65efab3589c186a09391d585357939573/pkg/sql/pg_catalog.go#L2107)):*
> ```Go
> 						// No schema found, so no rows.
> 						//nolint:returnerrcheck
> 						return false, nil
> ```

nit: assign err to nil here and you can avoid having to defeat the linter



_Code quote:_
```Go
						// No schema found, so no rows.
						//nolint:returnerrcheck
						return false, nil
```
___
*[`pkg/sql/pg_catalog.go` line 2120 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/90649#-NIsVSkJAY7TP4AfKRKw:-NIsVSkJAY7TP4AfKRKx:b83433m) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b66cdb65efab3589c186a09391d585357939573/pkg/sql/pg_catalog.go#L2120)):*
> ```Go
> 				} else if sc.SchemaKind() == catalog.SchemaPublic {
> 					// admin is the owner of the public schema.
> 					ownerOID = h.UserOid(username.MakeSQLUsernameFromPreNormalizedString("admin"))
> ```

nit: can we pull this out to a var rather than re-hashing every time?

**Review by rafiss — COMMENTED** [review]
tftr! added the changes

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90649#-:-NIsaynY6iUWcNOFlXvZ:b-t8076o)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @msbutler)

___
*[`pkg/sql/pg_catalog.go` line 2083 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/90649#-NIsUcW18aMe3k7UIkce:-NIsWJ6d33SyCWcfyyQB:b-v648wf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b66cdb65efab3589c186a09391d585357939573/pkg/sql/pg_catalog.go#L2083)):*
i'm fine with that tradeoff. 

> Also, this will find the local session's temp namespace, right?

you're right, i didn't realize. that makes me feel better about marking it as complete. added a test.
___
*[`pkg/sql/pg_catalog.go` line 2107 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/90649#-NIsV7YQ5ga6vkeHnXju:-NIsX-A99An9CGV_GjEz:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b66cdb65efab3589c186a09391d585357939573/pkg/sql/pg_catalog.go#L2107)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: assign err to nil here and you can avoid having to defeat the linter
</blockquote></details>

done
___
*[`pkg/sql/pg_catalog.go` line 2120 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/90649#-NIsVSkJAY7TP4AfKRKw:-NIsXJtR8KHUTB2VK4ma:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b66cdb65efab3589c186a09391d585357939573/pkg/sql/pg_catalog.go#L2120)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: can we pull this out to a var rather than re-hashing every time?
</blockquote></details>

done

**Review by rafiss — COMMENTED** [review]
bors r=ajwerner

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90649#-:-NIsb3-474lOzdZjDcaX:bclwjo8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @msbutler)

**Comment by rafiss** [comment]
whoops missed a test ...

bors r-

**Comment by rafiss** [comment]
turns out our implementation of the `pg_is_other_temp_schema` builtin directly depends on on the pg_namespace(oid) index containing temp schemas. so i've just added the fallback logic to the `populate` function.

bors r=ajwerner
