### PR TITLE
sql/schemachanger: avoid assertions when columns are missing

### LINKED ISSUE #104546: sql: v23.1.2: building declarative schema change targets for ALTER TABLE: cannot find column with name ×
This issue was autofiled by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry link: https://cockroach-labs.sentry.io/issues/4234802071/?referrer=webhooks_plugin

Panic message:

>helpers.go:367: building declarative schema change targets for ALTER TABLE: cannot find column with name ×
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scerrors.EventLogger.HandlePanicAndLogError
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scerrors/errors.go:81
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | [...repeated from below...]
Wraps: (2) building declarative schema change targets for ALTER TABLE
Wraps: (3) assertion failure
Wraps: (4) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/internal/scbuildstmt.mustGetColumnIDFromColumnName
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go:367
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/internal/scbuildstmt.alterTableAddForeignKey
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_constraint.go:320
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/internal/scbuildstmt.alterTableAddConstraint
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_constraint.go:64
  | reflect.Value.call
  | 	GOROOT/src/reflect/value.go:584
  | reflect.Value.Call
  | 	GOROOT/src/reflect/value.go:368
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/internal/scbuildstmt.AlterTable
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go:170
  | reflect.Value.call
  | 	GOROOT/src/reflect/value.go:584
  | reflect.Value.Call
  | 	GOROOT/src/reflect/value.go:368
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/internal/scbuildstmt.Process
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go:173
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild.Build
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/build.go:85
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).SchemaChange
  | 	github.com/cockroachdb/cockroach/pkg/sql/schema_change_plan_node.go:68
  | github.com/cockroachdb/cockroach/pkg/sql.buildOpaque
  | 	github.com/cockroachdb/cockroach/pkg/sql/opaque.go:56
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).tryBuildOpaque
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/opaque.go:70
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:434
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:272
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:246
  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildExecMemo
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:574
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:238
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).makeExecPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1975
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1483
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:964
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:142
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2989
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:141
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2174
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2179
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2096
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:892
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:767
  | runtime.goexit
  | 	src/runtime/asm_arm64.s:1172
Wraps: (5) cannot find column with name ×
Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *assert.withAssertionFailure (4) *withstack.withStack (5) *errutil.leafError
-- report composition:
*errutil.leafError: cannot find column with name ×
helpers.go:367: *withstack.withStack (top exception)
*assert.withAssertionFailure
*errutil.withPrefix: building declarative schema change targets for ALTER TABLE
errors.go:81: *withstack.withStack (1)
(check the extra data payloads)

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/schemachanger/scerrors/errors.go#L80-L82 in pkg/sql/schemachanger/scerrors.EventLogger.HandlePanicAndLogError
GOROOT/src/runtime/panic.go#L883-L885 in runtime.gopanic
https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go#L366-L368 in pkg/sql/schemachanger/scbuild/internal/scbuildstmt.mustGetColumnIDFromColumnName
https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_constraint.go#L319-L321 in pkg/sql/schemachanger/scbuild/internal/scbuildstmt.alterTableAddForeignKey
https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_constraint.go#L63-L65 in pkg/sql/schemachanger/scbuild/internal/scbuildstmt.alterTableAddConstraint
GOROOT/src/reflect/value.go#L583-L585 in reflect.Value.call
GOROOT/src/reflect/value.go#L367-L369 in reflect.Value.Call
https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go#L169-L171 in pkg/sql/schemachanger/scbuild/internal/scbuildstmt.AlterTable
GOROOT/src/reflect/value.go#L583-L585 in reflect.Value.call
GOROOT/src/reflect/value.go#L367-L369 in reflect.Value.Call
https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go#L172-L174 in pkg/sql/schemachanger/scbuild/internal/scbuildstmt.Process
https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/schemachanger/scbuild/build.go#L84-L86 in pkg/sql/schemachanger/scbuild.Build
https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/schema_change_plan_node.go#L67-L69 in pkg/sql.(*planner).SchemaChange
https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/opaque.go#L55-L57 in pkg/sql.buildOpaque
https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/opt/optbuilder/opaque.go#L69-L71 in pkg/sql/opt/optbuilder.(*Builder).tryBuildOpaque
https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/opt/optbuilder/builder.go#L433-L435 in pkg/sql/opt/optbuilder.(*Builder).buildStmt
https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/opt/optbuilder/builder.go#L271-L273 in pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot
https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/opt/optbuilder/builder.go#L245-L247 in pkg/sql/opt/optbuilder.(*Builder).Build
https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/plan_opt.go#L573-L575 in pkg/sql.(*optPlanningCtx).buildExecMemo
https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/plan_opt.go#L237-L239 in pkg/sql.(*planner).makeOptimizerPlan
https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor_exec.go#L1974-L1976 in pkg/sql.(*connExecutor).makeExecPlan
https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor_exec.go#L1482-L1484 in pkg/sql.(*connExecutor).dispatchToExecutionEngine
https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor_exec.go#L963-L965 in pkg/sql.(*connExecutor).execStmtInOpenState
https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor_exec.go#L141-L143 in pkg/sql.(*connExecutor).execStmt.func1
https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor_exec.go#L2988-L2990 in pkg/sql.(*connExecutor).execWithProfiling
https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor_exec.go#L140-L142 in pkg/sql.(*connExecutor).execStmt
https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L2173-L2175 in pkg/sql.(*connExecutor).execCmd.func1
https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L2178-L2180 in pkg/sql.(*connExecutor).execCmd
https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L2095-L2097 in pkg/sql.(*connExecutor).run
https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L891-L893 in pkg/sql.(*Server).ServeConn
https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/pgwire/conn.go#L766-L768 in pkg/sql/pgwire.(*conn).processCommandsAsync.func1
src/runtime/asm_arm64.s#L1171-L1173 in runtime.goexit
</details>

```
pkg/sql/schemachanger/scerrors/errors.go in pkg/sql/schemachanger/scerrors.EventLogger.HandlePanicAndLogError at line 81
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go in pkg/sql/schemachanger/scbuild/internal/scbuildstmt.mustGetColumnIDFromColumnName at line 367
pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_constraint.go in pkg/sql/schemachanger/scbuild/internal/scbuildstmt.alterTableAddForeignKey at line 320
pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_constraint.go in pkg/sql/schemachanger/scbuild/internal/scbuildstmt.alterTableAddConstraint at line 64
GOROOT/src/reflect/value.go in reflect.Value.call at line 584
GOROOT/src/reflect/value.go in reflect.Value.Call at line 368
pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go in pkg/sql/schemachanger/scbuild/internal/scbuildstmt.AlterTable at line 170
GOROOT/src/reflect/value.go in reflect.Value.call at line 584
GOROOT/src/reflect/value.go in reflect.Value.Call at line 368
pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go in pkg/sql/schemachanger/scbuild/internal/scbuildstmt.Process at line 173
pkg/sql/schemachanger/scbuild/build.go in pkg/sql/schemachanger/scbuild.Build at line 85
pkg/sql/schema_change_plan_node.go in pkg/sql.(*planner).SchemaChange at line 68
pkg/sql/opaque.go in pkg/sql.buildOpaque at line 56
pkg/sql/opt/optbuilder/opaque.go in pkg/sql/opt/optbuilder.(*Builder).tryBuildOpaque at line 70
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmt at line 434
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot at line 272
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).Build at line 246
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).buildExecMemo at line 574
pkg/sql/plan_opt.go in pkg/sql.(*planner).makeOptimizerPlan at line 238
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).makeExecPlan at line 1975
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1483
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 964
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 142
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 2989
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 141
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func1 at line 2174
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2179
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2096
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 892
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 767
src/runtime/asm_arm64.s in runtime.goexit at line 1172
```

| Tag | Value |
|---|---|
| Cockroach Release | `v23.1.2` |
| Cockroach SHA: | 810d4f27a7f02b9cc2750cab654ed1c62ac3e75a |
| Platform | darwin arm64 |
| Distribution | CCL |
| Environment | v23.1.2 |
| Command | start-single-node |
| Go Version | ``|
| # of CPUs ||
| # of Goroutines ||

Jira issue: CRDB-28596

### PR DESCRIPTION
**Pull request by fqazi**
Previously, the declarative schema changer, when resolving columns would assert if a column name was undefined. This is incorrect behaviour and a regression. To address this, this patch will generate the appropriate missing column error.

Fixes: #104546

Release note (bug fix): Adding a foreign key or setting a column to not null with a non-existent column produced an assertion error, instead of the proper pgcode in the declarative schema changer.

### CODE REVIEW

File: pkg/sql/logictest/testdata/logic_test/fk [hunk 1]
```diff
@@ -4164,3 +4164,14 @@ query I
...
+# See #104546 which was a regression when an invalid column name was specified,
+# when adding a FK reference.
+subtest unknown_column_name
+
+statement ok
+create table t104546 (a int primary key);
+create table t104546_fk_src (a int primary key, b int);
+
+statement error column "b" does not exist
+alter table t104546 add constraint con foreign key (b) references t104546_fk_src(b);
```
Comment (postamar) [inline pkg/sql/logictest/testdata/logic_test/fk:4177]: This test case really confused me for a while. Can you please clarify it to 

```

statement ok
create table t104546 ();
create table t104546_fk_src (id int primary key);

statement error column "badcolname" does not exist
alter table t104546 add constraint con foreign key (badcolname) references t104546_fk_src(id);
```

**Review by postamar — APPROVED** [review]
LGTM modulo one straightforward change.

**Review by rafiss — APPROVED** [review]
thanks!

just want to make sure i understand how this works: the `scbuild` (or is it the `schemachanger`) package has a `recover` call that handles panics for any error that is not an AssertionError?

i notice we have 120 usages of `panic(errors.AssertionFailed...` in pkg/sql/schemachanger. i don't think we need to audit them all right now, but i just am curious if either of you (@postamar or @fqazi) has a feeling about how many of those are likely to be correct usages of assertion errors?

File: pkg/sql/logictest/testdata/logic_test/fk [hunk 2]
```diff
@@ -4164,3 +4164,14 @@ query I
...
+
+# See #104546 which was a regression when an invalid column name was specified,
+# when adding a FK reference.
+subtest unknown_column_name
+
+statement ok
+create table t104546 (a int primary key);
+create table t104546_fk_src (a int primary key, b int);
+
+statement error column "b" does not exist
```
Comment (rafiss) [inline pkg/sql/logictest/testdata/logic_test/fk:4176]: actually one more nit. could you make this `statement error pgcode 42703 column "b" does not exist` to verify that the correct PG error code is used too?

**Review by rafiss — CHANGES_REQUESTED** [review]

File: pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go [hunk 3]
```diff
@@ -364,7 +365,7 @@ func mustGetColumnIDFromColumnName(
 ) catid.ColumnID {
 	colID := getColumnIDFromColumnName(b, tableID, columnName)
 	if colID == 0 {
-		panic(errors.AssertionFailedf("cannot find column with name %v", columnName))
+		panic(colinfo.NewUndefinedColumnError(string(columnName)))
```
Comment (rafiss) [inline pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go:368]: since this is a "must get" function, i'm not sure what the contract is. it's unclear to me if the function contract is that it only should be called with a valid column ID, or if it should handle that case.

- if it should only be called with a valid column ID, then assertion error makes sense, and we should use a different function in cases when we are looking up a column ID that may not exist
- if it should handle unknown column IDs, maybe we shouldn't name it `must...`

**Comment by postamar** [comment]
> i just am curious if either of you (@postamar or @fqazi) has a feeling about how many of those are likely to be correct usages of assertion errors?

We've definitely had instances in the past in `schemachanger` where some assertion errors should have been regular errors. I see things this way: most packages in there are fine (except perhaps `scexec`, see https://github.com/cockroachdb/cockroach/issues/73604 ), but `scbuild` needs improving.

in `scbuild` we have way too many because our grammar for reasoning about elements there is not expressive enough and so we end up peppering the code with assertion failures when doing things like searching for a primary index element when processing an ALTER TABLE: we _know_ it's always there but we guard against the remote possibility that it's not. It makes for verbose, inexpressive code and I really don't like it, I just haven't thought of the best way to improve how we query elements there. As I see it there's two ways we could improve things: 
1. The first is to leverage code generation like in `scpb` perhaps to generate better typed methods for `ElementResultSet` like `MustGetOnePrimaryIndex` which would throw assertion errors instead.
2. The other is to use `rel` somehow but that's not so straightforward because it was designed to operate on an `scgraph.Graph` first and foremost.

It's something I've been meaning to explore soon.

File: pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go (hunk 3 above)
Comment (fqazi) [reply pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go]: This wrapper is generally bad since none of these cases should hit assertion failures (the names are from user input). So, I have modified everything to use: getColumnIDFromColumnName, and have a flag that indicates if the resolution is required (leading to a user-friendly error).

**Review by rafiss — APPROVED** [review]
thanks for the improvement!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104841#-:-NYyQSyMDmaUCaXkVgqx:bifbvs3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @postamar)

**Comment by fqazi** [comment]
@rafiss TFTR!

bors r+
