### PR TITLE
kvcoord: wait on server-side goroutine in MuxRangeFeed

### LINKED ISSUE #136407: ccl/changefeedccl: TestChangefeedSchemaChangeAllowBackfill_Legacy failed
ccl/changefeedccl.TestChangefeedSchemaChangeAllowBackfill_Legacy [failed](https://tanzanite.cluster.engflow.com/invocations/default/d28aec5f-4dce-4abc-b21c-f64fd62ebc6c?testReportRun=2&testReportShard=15&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on master @ [7d48198a57f014a8828194b90098699f70f0695a](https://github.com/cockroachdb/cockroach/commits/7d48198a57f014a8828194b90098699f70f0695a):

```
  github.com/cockroachdb/cockroach/pkg/rpc.serverStreamInterceptorsChain.run()
      pkg/rpc/context.go:861 +0x26f
  github.com/cockroachdb/cockroach/pkg/rpc.internalClientAdapter.MuxRangeFeed.func3()
      pkg/rpc/context.go:1026 +0x1ae

Goroutine 21739 (running) created at:
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveImpl()
      pkg/sql/pgwire/server.go:1193 +0xa4f
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn()
      pkg/sql/pgwire/server.go:957 +0xe64
  github.com/cockroachdb/cockroach/pkg/server.(*systemServerWrapper).serveConn()
      pkg/server/server_controller_sql.go:170 +0x1d7
  github.com/cockroachdb/cockroach/pkg/server.(*serverController).sqlMux()
      pkg/server/server_controller_sql.go:90 +0x50b
  github.com/cockroachdb/cockroach/pkg/server.(*serverController).sqlMux-fm()
      <autogenerated>:1 +0xc4
  github.com/cockroachdb/cockroach/pkg/server.startServeSQL.func1.1()
      pkg/server/server_sql.go:1985 +0x39b
  github.com/cockroachdb/cockroach/pkg/util/netutil.(*TCPServer).ServeWith.func1()
      pkg/util/netutil/net.go:186 +0x1c6
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
      pkg/util/stop/stopper.go:498 +0x338
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.gowrap1()
      pkg/util/stop/stopper.go:499 +0x4f

Goroutine 25811 (running) created at:
  github.com/cockroachdb/cockroach/pkg/rpc.internalClientAdapter.MuxRangeFeed()
      pkg/rpc/context.go:1011 +0x46d
  github.com/cockroachdb/cockroach/pkg/rpc.(*internalClientAdapter).MuxRangeFeed()
      <autogenerated>:1 +0x12b
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*rangefeedMuxer).startNodeMuxRangeFeed()
      pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:391 +0x401
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*rangefeedMuxer).establishMuxConnection.func1()
      pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:349 +0x84
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*rangefeedMuxer).establishMuxConnection.Group.GoCtx.func2()
      pkg/util/ctxgroup/ctxgroup.go:189 +0x11a
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      external/org_golang_x_sync/errgroup/errgroup.go:78 +0x91
==================
=== RUN   TestChangefeedSchemaChangeAllowBackfill_Legacy/sinkless
    helpers_test.go:886: making server as system tenant
    helpers_test.go:962: making sinkless feed factory
    helpers_test.go:1027: pgURL sinkless SinklessFeedUser
    helpers_test.go:1027: pgURL sinkless root
    changefeed_test.go:2566: using legacy schema changer
    testfeed_test.go:270: sinkless feed creating changefeed: CREATE CHANGEFEED FOR add_column_def WITH updated
    testfeed_test.go:277: closing sinkless feed
    testfeed_test.go:270: sinkless feed creating changefeed: CREATE CHANGEFEED FOR add_col_comp WITH updated
    testfeed_test.go:277: closing sinkless feed
=== RUN   TestChangefeedSchemaChangeAllowBackfill_Legacy/sinkless/add_column_computed
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=2</code>
 - <code>shard=15</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestChangefeedSchemaChangeAllowBackfill_Legacy.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-45024

### PR DESCRIPTION
**Pull request by stevendanna**
When using an internal client, we launch a goroutine to run the server-side of the range feed request. Previously, nothing was waiting on this goroutine to exit, causing at lease once race condition because of the shared tracing span.

Now, the internal client implements a close method that can be called before the client returns.

Hopefully,

Fixes #136407

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/139211)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @stevendanna and @wenyihu6)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 415 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/139211#-OH81-VK6lVz7YBB765F:-OH81-VK6lVz7YBB765G:btkob4a) ([raw file](https://github.com/cockroachdb/cockroach/blob/75a37638f5842654c407f62fea77afafc48cbd68/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L415)):*
> ```Go
> 		// be able to send new request on this stream anymore, and we'll retry
> 		// against another node.
> 		if closer, ok := mux.(io.Closer); ok {
> ```

Is there a reason you didn't add this to the interface? As is, it seems a tiny bit brittle.
___
*[`pkg/rpc/context.go` line 982 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/139211#-OH8-NT09_hceLycHaU3:-OH8-NT09_hceLycHaU4:b1pc31x) ([raw file](https://github.com/cockroachdb/cockroach/blob/75a37638f5842654c407f62fea77afafc48cbd68/pkg/rpc/context.go#L982)):*
> ```Go
> 	}
> 
> 	serverCtx, serverCancel := context.WithCancel(ctx)
> ```

The code is fine, just offering my preferred alternative:

```
maybeServerCancel := serverCancel() // set to noop when delegating to caller
defer func() { maybeServerCancel() }

// no longer need to call `serverCancel()` on error paths.

// ... before final return:

maybeServerCancel = func() {}
return &{...}
```

Reordering the client interceptors before the server may also avoid this wrinkle altogether.

File: pkg/rpc/context.go [hunk 1]
```diff
@@ -1013,7 +1015,8 @@ func (a internalClientAdapter) MuxRangeFeed(
 		sender:   eventWriter,
 	}
 
-	go func() {
+	wg := ctxgroup.WithContext(serverCtx)
+	wg.Go(func() error {
```
Comment (wenyihu6) [inline pkg/rpc/context.go:1019]: You are probably right. I just want to learn more here. Why don't we need to use `wg.GoCtx` to watch for this context shutdown in https://github.com/cockroachdb/cockroach/blob/beeec160a11848d750c2cc77237781f0137d181e/pkg/util/ctxgroup/ctxgroup.go#L179? Will wg goroutines (server side call) shut down on itself when the wg context is canceled?

File: pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go [hunk 2]
```diff
@@ -412,6 +412,11 @@ func (m *rangefeedMuxer) startNodeMuxRangeFeed(
 		// another goroutine loaded it.  That's fine, since we would not
 		// be able to send new request on this stream anymore, and we'll retry
 		// against another node.
+		if closer, ok := mux.(io.Closer); ok {
```
Comment (wenyihu6) [inline pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:415]: Is the reason why we don't need to explicitly close at https://github.com/cockroachdb/cockroach/blob/75a37638f5842654c407f62fea77afafc48cbd68/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L399 because the `defer cancel()` during the return will help us cancel the server context?

**Review by wenyihu6 — APPROVED** [review]

File: pkg/rpc/context.go (hunk 1 above)
Comment (stevendanna) [reply pkg/rpc/context.go:1019]: Note that nothing inside this goroutine takes a context.  I haven't looked at the full implementation, but that is the main reason I didn't see a point in using GoCtx.  I assume that shutdown happens on cancellation by virtue of the fact that we store `serverCtx` in rawServerStream and that is handling it correctly. But I didn't fully verify this.

File: pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go (hunk 2 above)
Comment (stevendanna) [reply pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:415]: Here I followed what I think is the usual context. If MuxRangeFeed returns an error, it has already cleaned up its own resources (via explicit calls to cancel in that function) so we only need to call this on error paths in the non-err case. However, this points out that I should probably be calling this at line 405 above.

File: pkg/rpc/context.go (hunk 1 above)
Comment (wenyihu6) [reply pkg/rpc/context.go:1019]: `sp.IsNoop()` check  `ss.Context()`, which would originally return client passed ctx but now returns the server context https://github.com/cockroachdb/cockroach/blob/f20164ebb1d5021f2294b8683f1d7dd21e283881/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L149. 

Can the interceptors end up using the already canceled `serverCtx` during the server side shutdown?https://github.com/cockroachdb/cockroach/blob/f20164ebb1d5021f2294b8683f1d7dd21e283881/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L158-L160 

Or are these interceptors entirely bypassed when serverCtx is canceled and the server stream shut down?

File: pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go (hunk 2 above)
Comment (wenyihu6) [reply pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:415]: Right, that makes sense. At line 405, it should trigger `defer cancel()` during return, which cancels the context passed to MuxRangefeed. This in turn cancels the server context, which also seems correct. Does that seem right to you?

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/139211)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 415 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/139211#-OH81-VK6lVz7YBB765F:-OHDiDvF8PrllF3lvP0b:bycq852) ([raw file](https://github.com/cockroachdb/cockroach/blob/75a37638f5842654c407f62fea77afafc48cbd68/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L415)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Is there a reason you didn't add this to the interface? As is, it seems a tiny bit brittle.
</blockquote></details>

The interface in question is a gRPC-generated client interface which is the main reason I didn't dig into modifying it.

File: pkg/rpc/context.go (hunk 1 above)
Comment (wenyihu6) [reply pkg/rpc/context.go:1022]: Discussed this offline - the tracing span is actually from the client side so it is fine to cancel server context early here.

**Comment by stevendanna** [comment]
blathers backport release-25.1
