### PR TITLE
roachprod: implement "Reset" for aws and azure.

### LINKED ISSUE #77628: roachprod: implement "Reset" for aws and azure
Only GCE supports `Reset`--restarting a VM. As a result, some roachtests may be flaky (or incorrect) when executing outside of GCE. E.g., tpcc roachperf uses `Reset` [1] during each iteration of line search to determine an optimal number of warehouses. While the restart after each iteration is technically not required, it reduces noise.

Other examples include failure-injection scenarios, e.g., restarting a VM at random.

[1] https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/tests/tpcc.go#L1111

Epic: CRDB-10428

Jira issue: CRDB-13686

### PR DESCRIPTION
**Pull request by shailendra-patel**
Reset VM operation was not implemented for aws and azure. As a result some roachtests may be flaky when executing outside of GCE e.g. roachperf uses Reset. For AWS implemented `aws ec2 reboot-instances --region <region> --instances-id <id-1> <id-2>`. For Azure implemented `az vm restart -g <resource-group> -n <resource-name>`.

Fixes: #77628
Epic: CRDB-10428

Release note: None

### CODE REVIEW

**Comment by shailendra-patel** [comment]
Tested and verification for aws
aws-cloudtrail-event-history
aws-last-reboot-cli

**Comment by shailendra-patel** [comment]
Test and verification for azure
azure-vm-activity-log
azure-vm-last-reboot-cli

**Review by herkolategan — APPROVED** [review]
:lgtm:
just a small note on commit msg.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126607#-:-O0s0IVL2HUPGWqOCvE8:b-caka40)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @shailendra-patel)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126607#-O0s0BUCBEtAgTcKZDuX):*
small typo: `reboot-instances`

File: pkg/roachprod/vm/aws/aws.go [hunk 1]
```diff
@@ -727,9 +727,26 @@ func (p *Provider) Delete(l *logger.Logger, vms vm.List) error {
...
+	g := errgroup.Group{}
+	for region, list := range byRegion {
+		args := []string{
+			"ec2", "reboot-instances",
+			"--region", region,
+			"--instance-ids",
+		}
+		args = append(args, list.ProviderIDs()...)
+		g.Go(func() error {
+			_, e := p.runCommand(l, args)
```
Comment (DarrylWong) [inline pkg/roachprod/vm/aws/aws.go:745]: _tiny_ nit: `_, err = p.runCommand(l, args)`

**Review by DarrylWong — APPROVED** [review]
Nice work!

File: pkg/roachprod/vm/aws/aws.go (hunk 1 above)
Comment (srosenberg) [reply pkg/roachprod/vm/aws/aws.go:745]: Yep, it's a Go convention, and it makes things easier to spot since our eyes have been trained to parse out `err` :)

File: pkg/roachprod/vm/aws/aws.go [hunk 2]
```diff
@@ -727,9 +727,26 @@ func (p *Provider) Delete(l *logger.Logger, vms vm.List) error {
...
+	}
+	g := errgroup.Group{}
+	for region, list := range byRegion {
+		args := []string{
+			"ec2", "reboot-instances",
+			"--region", region,
+			"--instance-ids",
+		}
+		args = append(args, list.ProviderIDs()...)
+		g.Go(func() error {
```
Comment (srosenberg) [inline pkg/roachprod/vm/aws/aws.go:744]: Something to keep in mind although I don't think it's really relevant in this situation... Each cloud API imposes its own limits. Sometimes we may have to bound the number of concurrent requests. Since we don't really anticipate restarting 100s of nodes at a time, we should in theory be within those limits.

**Review by srosenberg — APPROVED** [review]
