### PR TITLE
Fix deadlock in TestHeartbeatMultipleGroupsJointLeader.

### LINKED ISSUE #1568: TestHeartbeatMultipleGroupsJointLeader failed
[4283](https://circleci.com/gh/cockroachdb/cockroach/4283)
```
error

        panic: test timed out after 5m0s

goroutine 512 [running]:
testing.func·008()
	/usr/src/go/src/testing/testing.go:681 +0x168
created by time.goFunc
	/usr/src/go/src/time/sleep.go:129 +0x59

goroutine 1 [chan receive, 2 minutes]:
testing.RunTests(0xb651c8, 0xd06b60, 0xa, 0xa, 0x1)
	/usr/src/go/src/testing/testing.go:556 +0xdc3
testing.(*M).Run(0xc20800ad70, 0x50)
	/usr/src/go/src/testing/testing.go:485 +0xe1
github.com/cockroachdb/cockroach/util/leaktest.TestMainWithLeakCheck(0xc20800ad70)
	/go/src/github.com/cockroachdb/cockroach/util/leaktest/leaktest.go:34 +0x36
github.com/cockroachdb/cockroach/multiraft_test.TestMain(0xc20800ad70)
	/go/src/github.com/cockroachdb/cockroach/multiraft/main_test.go:29 +0x36
main.main()
	github.com/cockroachdb/cockroach/multiraft/_test/_testmain.go:70 +0x28d

goroutine 6 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0xd0cc00)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1038 +0x83
created by github.com/cockroachdb/cockroach/util/log.init·1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:604 +0x127

goroutine 17 [syscall, 4 minutes, locked to thread]:
runtime.goexit()
	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 504 [select, 2 minutes]:
github.com/cockroachdb/cockroach/multiraft.func·004()
	/go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:489 +0x2366
github.com/cockroachdb/cockroach/util.func·001()
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:75 +0x80
created by github.com/cockroachdb/cockroach/util.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:76 +0x133

goroutine 476 [select, 2 minutes]:
github.com/cockroachdb/cockroach/multiraft.func·011()
	/go/src/github.com/cockroachdb/cockroach/multiraft/events_test.go:49 +0x577
github.com/cockroachdb/cockroach/util.func·001()
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:75 +0x80
created by github.com/cockroachdb/cockroach/util.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:76 +0x133
```

### PR DESCRIPTION
**Pull request by bdarnell**
Introduce testCluster.elect() method to replace the cumbersome and
error-prone triggerElection/waitForElection pattern (similar to the
changes in #1489).

Removed some uses of waitForElection that are no longer needed now that
we have forwarding and re-proposal.

Fixes #1568.

### CODE REVIEW

File: multiraft/multiraft_test.go [hunk 1]
```diff
@@ -150,6 +159,22 @@ func (c *testCluster) waitForElection(i int) *EventLeaderElection {
...
 
+// elect is a simplified wrapper around triggerElection and waitForElection which
+// waits for the election to complete on all members of a group.
+// TODO(bdarnell): make this work when membership has been changed after creation.
+func (c *testCluster) elect(leaderIndex int, groupID proto.RaftID) {
+	c.triggerElection(leaderIndex, groupID)
+	for _, i := range c.groups[groupID] {
+		el := c.waitForElection(i)
+		if el.NodeID != c.nodes[leaderIndex].nodeID {
+			c.t.Fatalf("wrong leader elected; wanted node %d but got event %v", leaderIndex, el)
```
Comment (tamird) [inline multiraft/multiraft_test.go]: the comment on `triggerElection` reads:
> In most situations the given node will win the election.

When does that not happen?

**Comment by tamird** [comment]
LGTM

File: multiraft/multiraft_test.go (hunk 1 above)
Comment (bdarnell) [inline multiraft/multiraft_test.go]: If another node triggers an election concurrently (shouldn't happen in these tests since they use a manual ticker) or if the designated node has fallen behind the other nodes in the group. It doesn't come up in any of the tests we currently have, but I just wanted to make a note that it's not a guaranteed rigged election.

Comment (tamird) [inline multiraft/multiraft_test.go]: Got it. Thanks
