### PR TITLE
server: enable `_status/ranges` API for secondary tenants

### LINKED ISSUE #110019: server: the "ranges" status API endpoint should work with secondary tenants with sufficient capability
Found while investigating #110001.
This is a variant of  #110018.

**Describe the problem**

When `TestRangesResponse` in `server/storage_api` is modified to point to a secondary tenant (e.g. via #110008), the test starts failing when accessing the `/_status/ranges`  (NB: not `range`) endpoint:

```
=== RUN   TestRangesResponse/test_ranges_response
    ranges_test.go:47: status: 501 Not Implemented, content-type: application/json, body: {
          "error": "method Ranges not implemented",
          "code": 12,
          "message": "method Ranges not implemented",
          "details": [
          ]
        }, error: <nil>
```

**How to reproduce**

from #110008 reset `DefaultTestTenant` in `TestRangesResponse`, run the test with a test tenant and observe the failure.

**Expected behavior**

Once the tenant is granted a suitable capability, the endpoint should work properly.

Epic CRDB-38968

Jira issue: CRDB-31225

### PR DESCRIPTION
**Pull request by shubhamdhama**
Previously, the above endpoint was only available for the system tenant. With this change, it now works for secondary tenants and returns the ranges belonging to the currently logged-in tenant.

Note that although we have `TenantRanges`, which is quite similar to `Ranges`, it was developed to meet the needs of the `debug` command and has a different response body. Another difference is that `TenantRanges` returns ranges for all nodes, while `Ranges` returns data for a particular node.

Fixes: #110019

Epic: CRDB-38968

Release note (multi-tenancy): The `ranges` endpoint on the `Advanced Debug` section of the DB Console is now enabled for secondary tenants and will return the ranges only for the currently logged-in tenant. For the system tenant, it will continue to work as before, returning ranges for all tenants on the specified node.

### CODE REVIEW

File: pkg/ccl/serverccl/statusccl/tenant_status_test.go [hunk 1]
```diff
@@ -1381,20 +1385,10 @@ func testTenantRangesRPC(_ context.Context, t *testing.T, helper serverccl.Tenan
 	tenantB := helper.ControlCluster().TenantStatusSrv(0).(serverpb.TenantStatusServer)
 
 	// Wait for range splits to occur so we get more than just a single range during our tests.
```
Comment (shubhamdhama) [inline pkg/ccl/serverccl/statusccl/tenant_status_test.go:1387]: Not sure about this why we need to wait for splits.

File: pkg/server/status.go
Comment (shubhamdhama) [inline pkg/server/status.go:1]: https://github.com/cockroachdb/cockroach/blob/6a5017e813bd65f3a8af24d232e43838e274d4cf/pkg/server/status.go#L2663-L2667

Here we take `next` for local `TenantRanges` but ignoring `next` for remote responses. I think this pagination stuff is not complete for `TenantRanges` endpoint. But more importantly pagination is not used so in a follow-up we can consider removing this. I almost removed it myself but reverted the change as I'm not an expert in this area. Let me know if removing it would make others happy as well.

**Review by shubhamdhama — COMMENTED** [review]
Keeping it draft as there are few TODOs I need to clear.

File: pkg/server/status.go [hunk 2]
```diff
@@ -2349,6 +2349,21 @@ func (h varsHandler) handleVars(w http.ResponseWriter, r *http.Request) {
 	telemetry.Inc(telemetryPrometheusVars)
 }
 
+// Ranges returns current tenant's range info for the specified node.
+func (t *statusServer) Ranges(
```
Comment (shubhamdhama) [inline pkg/server/status.go:2353]: Behavior of this endpoint in external-process mode would be undefined for `local`.

File: pkg/server/storage_api/ranges_test.go [hunk 3]
```diff
@@ -32,14 +34,16 @@ func TestRangesResponse(t *testing.T) {
...
 	defer kvserver.EnableLeaseHistoryForTesting(100)()
-	srv := serverutils.StartServerOnly(t, base.TestServerArgs{
-		DefaultTestTenant: base.TestIsForStuffThatShouldWorkWithSecondaryTenantsButDoesntYet(110019),
-	})
+	srv := serverutils.StartServerOnly(t, base.TestServerArgs{})
 	defer srv.Stopper().Stop(context.Background())
 	ts := srv.ApplicationLayer()
 
-	// TODO(#110019): grant a special capability to the secondary tenant
-	// before the endpoint can be accessed.
```
Comment (shubhamdhama) [inline pkg/server/storage_api/ranges_test.go:42]: I don't think we need to grant special capability as of now since this endpoint return its own tenant's ranges.

File: pkg/server/status.go
Comment (dhartunian) [reply pkg/server/status.go:1]: Feel free to put up a separate PR removing the pagination, I would not combine with this work. I'm not super familiar with the usage of this endpoint but I agree the pagination here is confusing at first glance. What does it mean to send the same limit/offset to all the nodes during fanout? Are their lists guaranteed to be the same size?

The `next` is ignored for remote responses because it comes back already inside the `resp`.

File: pkg/server/status.go (hunk 2 above)
Comment (dhartunian) [reply pkg/server/status.go:2353]: Can you clarify this comment? I'm not sure I understand. Is it invalid to request this with `node: local` in the request? If so, should that be documented in the docstring?

Comment (shubhamdhama) [reply pkg/server/status.go:2354]: I've clarified in the comment.

Comment (shubhamdhama) [reply pkg/server/status.go:2354]: And just out of curiosity, I wanted to see where tenant connector picks the KV node and which one. Here is the code, and it appears it picks randomly.
https://github.com/cockroachdb/cockroach/blob/8a35ea7bcbe09740893b004b137faa2f7b801587/pkg/kv/kvclient/kvtenant/connector.go#L1010-L1031

**Review by dhartunian — APPROVED** [review]
LGTM, thanks!

**Comment by shubhamdhama** [comment]
Thanks for the review!

bros r=dhartunian

**Comment by shubhamdhama** [comment]
OH-kayy, I misspelled!

bors r=dhartunian
