### PR TITLE
roachtest: pass artifacts-literal flag to local roachtests

### LINKED ISSUE #103778: roachtest: artifacts are not published immediately after failure
It was observed recently (internal thread [1]) that the publishing of artifacts immediately after failure doesn't seem to be working:

image

`roachtest` attempts to publish the artifacts immediately after failure so that they are available in the TC UI before the entire build finishes [2]. While the path in the logs above does look right, the publish is still failing for some reason. We need to investigate the reason for the failure and fix it.

[1] https://cockroachlabs.slack.com/archives/CJ0H8Q97C/p1684840081950479
[2] https://github.com/cockroachdb/cockroach/blob/3d1c664dca7ddf8e3ba0ab93eb15417a2f71a18d/pkg/cmd/roachtest/test_runner.go#L933-L941

Jira issue: CRDB-28197

### PR DESCRIPTION
**Pull request by DarrylWong**
Previously, the --artifacts-literal flag was not passed in for local roachtests. In the event of a test failure, roachtest should immediately publish artifacts so they are available to the TeamCity UI before the entire build finishes. Without explicitly passing in the artifacts directory, roachtest is unable to tell TeamCity where to collect a test's artifacts and the immediate publish fails. To address this, an artifacts-literal flag is now passed for local roachtests.

Fixes: #103778

Epic: None

Release note: None

### CODE REVIEW

File: build/teamcity/cockroach/ci/tests/local_roachtest_impl.sh [hunk 1]
```diff
@@ -27,4 +27,5 @@ $BAZEL_BIN/pkg/cmd/roachtest/roachtest_/roachtest run acceptance kv/splits cdc/b
   --cockroach "$BAZEL_BIN/pkg/cmd/cockroach-short/cockroach-short_/cockroach-short" \
   --workload "$BAZEL_BIN/pkg/cmd/workload/workload_/workload" \
   --artifacts /artifacts \
+  --artifacts-literal="${LITERAL_ARTIFACTS_DIR:-}" \
```
Comment (rickystewart) [inline build/teamcity/cockroach/ci/tests/local_roachtest_impl.sh:30]: Probably will fail due to being an undefined variable.

**Review by rickystewart — APPROVED** [review]
Thanks!

**Review by renatolabs — APPROVED** [review]
:lgtm:

Nice fix!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108536#-:-Nbz0KWaAVnPmJUQuFQM:bmmv5q6)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @rachitgsrivastava, and @smg260)
