### PR TITLE
sql/schemachanger: prevent concurrent type desc changes

### LINKED ISSUE #112390: pkg/ccl/testccl/workload/schemachange/schemachange_test: TestWorkload failed
pkg/ccl/testccl/workload/schemachange/schemachange_test.TestWorkload [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/12186676?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/12186676?buildTab=artifacts#/) on release-23.2 @ [87a94f6ac59d4e01c822bb2128db858176600dd6](https://github.com/cockroachdb/cockroach/commits/87a94f6ac59d4e01c822bb2128db858176600dd6):

```
1, 29, rangelog, 13
1, 29, region_liveness, 9
1, 29, replication_constraint_stats, 25
1, 29, replication_critical_localities, 26
1, 29, replication_stats, 27
1, 29, reports_meta, 28
1, 29, role_id_seq, 48
1, 29, role_members, 23
1, 29, role_options, 33
1, 29, scheduled_jobs, 37
1, 29, settings, 6
1, 29, span_configurations, 47
1, 29, span_stats_buckets, 55
1, 29, span_stats_samples, 56
1, 29, span_stats_tenant_boundaries, 57
1, 29, span_stats_unique_keys, 54
1, 29, sql_instances, 46
1, 29, sqlliveness, 39
1, 29, statement_activity, 60
1, 29, statement_bundle_chunks, 34
1, 29, statement_diagnostics, 36
1, 29, statement_diagnostics_requests, 35
1, 29, statement_execution_insights, 65
1, 29, statement_statistics, 42
1, 29, table_statistics, 20
1, 29, task_payloads, 58
1, 29, tenant_id_seq, 62
1, 29, tenant_settings, 50
1, 29, tenant_tasks, 59
1, 29, tenant_usage, 45
1, 29, tenants, 8
1, 29, transaction_activity, 61
1, 29, transaction_execution_insights, 64
1, 29, transaction_statistics, 43
1, 29, ui, 14
1, 29, users, 4
1, 29, web_sessions, 19
1, 29, zones, 5
100, 0, public, 101
102, 0, public, 103
104, 0, public, 105
104, 0, schema93, 123
104, 105, _enum37, 116
104, 105, _enum67, 120
104, 105, enum37, 115
104, 105, enum67, 119
    schema_change_external_test.go:82: backup in /artifacts/tmp/_tmp/fcba020ca7cb44bf8385bd0e13bcbe2d/logTestWorkload469890276
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/fcba020ca7cb44bf8385bd0e13bcbe2d/logTestWorkload469890276
--- FAIL: TestWorkload (51.70s)
```
<p>Parameters: <code>TAGS=bazel,gss,deadlock</code>
, <code>stress=true</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #111540 pkg/ccl/testccl/workload/schemachange/schemachange_test: TestWorkload failed [error dropping enum type] [C-test-failure O-robot O-schema-testing T-sql-foundations branch-master db-cy-23]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestWorkload.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-32392

### PR DESCRIPTION
**Pull request by fqazi**
Previously, the declarative schema changer only waited for legacy schema changer mutations/jobs on relations and did not correctly account for type schema changes.  As a result, it was possible to drop a type concurrently while a schema change was trying to mutate a type, which could lead to type change jobs hanging. To address this, this patch causes declarative schema changes to wait for type modifications.

Fixes: #112390, #111540

Release note (bug fix): ALTER TYPE could get stuck if DROP TYPE
 was executed concurrently.

### CODE REVIEW

File: pkg/sql/schemachanger/schemachanger_test.go [hunk 1]
```diff
@@ -490,6 +490,66 @@ func TestSchemaChangeWaitsForConcurrentSchemaChanges(t *testing.T) {
 			"defaultdb", "t", expectedKeyCount)
 	}
 
+	typeSchemaChangeFunc := func(t *testing.T, modeFor1stStmt, modeFor2ndStmt sessiondatapb.NewSchemaChangerMode) {
+		ctx, cancel := context.WithCancel(context.Background())
+		dropTypeChan := make(chan struct{})
+		addTypeValueChan := make(chan struct{})
+		var closeAlterPKChanOnce sync.Once
```
Comment (chrisseto) [inline pkg/sql/schemachanger/schemachanger_test.go:497]: Why does this name mean? There doesn't seem to be any Alter PK going on?

File: pkg/sql/schemachanger/schemachanger_test.go [hunk 2]
```diff
@@ -490,6 +490,66 @@ func TestSchemaChangeWaitsForConcurrentSchemaChanges(t *testing.T) {
...
+		params.Knobs = base.TestingKnobs{
+			SQLDeclarativeSchemaChanger: &scexec.TestingKnobs{
+				// If the blocked schema changer is from legacy schema changer, we let
+				// it hijack this knob (which is originally design for declarative
+				// schema changer) if `stmt` is nil.
+				WhileWaitingForConcurrentSchemaChanges: func(stmts []string) {
+					if (len(stmts) == 1 && strings.Contains(stmts[0], "DROP TYPE")) ||
+						stmts == nil {
+						closeAlterPKChanOnce.Do(func() {
+							close(addTypeValueChan)
```
Comment (chrisseto) [inline pkg/sql/schemachanger/schemachanger_test.go:510]: nit: These channel names feel backwards? I would expect this one to be the `dropType` channel. Alternatively you could give them past tense names like `typevalueAddedChan`?

File: pkg/sql/schemachanger/schemachanger_test.go [hunk 3]
```diff
@@ -502,6 +562,10 @@ func TestSchemaChangeWaitsForConcurrentSchemaChanges(t *testing.T) {
 		tf(t, sessiondatapb.UseNewSchemaChangerOff, sessiondatapb.UseNewSchemaChangerUnsafeAlways)
 	})
 
+	t.Run("legacy-then-declarative", func(t *testing.T) {
+		typeSchemaChangeFunc(t, sessiondatapb.UseNewSchemaChangerOff, sessiondatapb.UseNewSchemaChangerUnsafeAlways)
```
Comment (chrisseto) [inline pkg/sql/schemachanger/schemachanger_test.go:566]: Any reason to not run this in the other direction as well?

Comment (chrisseto) [reply pkg/sql/schemachanger/schemachanger_test.go:566]: nit: Give this a unique t.Run name

File: pkg/sql/schemachanger/schemachanger_test.go [hunk 4]
```diff
@@ -490,6 +490,66 @@ func TestSchemaChangeWaitsForConcurrentSchemaChanges(t *testing.T) {
...
+			tdb.Exec(t, `SET CLUSTER SETTING jobs.debug.pausepoints=""`)
+			tdb.Exec(t, "RESUME JOB (SELECT job_id FROM crdb_internal.jobs WHERE status='paused' FETCH FIRST 1 ROWS ONLY);\n")
+		}()
+		<-dropTypeChan
+
+		// Execute 2st DDL synchronously. During waiting, it will unblock 1st DDL so
+		// it will eventually be able to proceed after waiting for a while.
+		tdb.Exec(t, `SET use_declarative_schema_changer = $1`, modeFor2ndStmt.String())
+		tdb.Exec(t, `DROP TYPE STATUS;`)
+		require.True(t, schemaChangeWaitDetected, "no schema change wait was observed.")
```
Comment (chrisseto) [inline pkg/sql/schemachanger/schemachanger_test.go:550]: This feels a bit race-y to me. `schemaChangeWaitDetected` might not immediately flipped, right? It might be more straightforward to close another channel and block on that with a timeout?

**Review by chrisseto — APPROVED** [review]
Fix LGTM but the test is a bit mind bending to me in its current state.

**Comment by chrisseto** [comment]
Side note: Is there a reason that type descriptors don't have a `Mutations` field? 🤔

**Review by fqazi — COMMENTED** [review]
> Side note: Is there a reason that type descriptors don't have a `Mutations` field? 🤔

Honestly, they probably should have since it would simplify code and be more consistent. Assuming things are using accessors we probably can improve things with declarative work.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113639#-:-NiCXYH1A__OoCIu2QVz:b-avfnym)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chrisseto)

___
*[`pkg/sql/schemachanger/schemachanger_test.go` line 497 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113639#gh-1379358744:-NiCVBqA3QnVWw_r3DyV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70984282cc9d487deb916a2e0fb1623446ad16a/pkg/sql/schemachanger/schemachanger_test.go#L497)):*
<details><summary><i>Previously, chrisseto (Chris Seto) wrote…</i></summary><blockquote>

Why does this name mean? There doesn't seem to be any Alter PK going on?
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/schemachanger_test.go` line 510 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113639#gh-1379360490:-NiCWScwE3ZziV_LC0sy:bb752jq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70984282cc9d487deb916a2e0fb1623446ad16a/pkg/sql/schemachanger/schemachanger_test.go#L510)):*
<details><summary><i>Previously, chrisseto (Chris Seto) wrote…</i></summary><blockquote>

nit: These channel names feel backwards? I would expect this one to be the `dropType` channel. Alternatively you could give them past tense names like `typevalueAddedChan`?
</blockquote></details>

Good point think these are clearer:

```
addTypeStartedChan := make(chan struct{})  
resumeAddTypeJobChan := make(chan struct{})
```
___
*[`pkg/sql/schemachanger/schemachanger_test.go` line 550 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113639#gh-1379364616:-NiCWkzK9RZxMeUEDMaE:b283d95) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70984282cc9d487deb916a2e0fb1623446ad16a/pkg/sql/schemachanger/schemachanger_test.go#L550)):*
<details><summary><i>Previously, chrisseto (Chris Seto) wrote…</i></summary><blockquote>

This feels a bit race-y to me. `schemaChangeWaitDetected` might not immediately flipped, right? It might be more straightforward to close another channel and block on that with a timeout?
</blockquote></details>

Yeah, I'll be more paranoid and close another channel.
___
*[`pkg/sql/schemachanger/schemachanger_test.go` line 566 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113639#gh-1379361023:-NiCX8d2E17I3HEenHlp:b-5kf660) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70984282cc9d487deb916a2e0fb1623446ad16a/pkg/sql/schemachanger/schemachanger_test.go#L566)):*
> Any reason to not run this in the other direction as well?

We can't until we implement these alters in the declarative world.

> nit: Give this a unique t.Run name

Renamed this to: typedesc legacy-then-declarative

**Comment by fqazi** [comment]
@chrisseto TFTR!

bors r+

**Review by Xiang-Gu — COMMENTED** [review]
It looks like we cannot amend the existing `tf` function to include testing for type descriptor because we don't have `create type`, `alter type` in declarative schema changer yet. Is this the reason you created a new helper function `typeSchemaChangeFunc`?

If so, then I'd suggest we move this new test into a new, top-level test (instead of a subtest here), maybe called `TestTypeSchemaChangesWaitForConcurrentTypeSchemaChanges`, which is cleaner IMO.
