### PR TITLE
backup: capture function descriptor changes in revision history backups

### LINKED ISSUE #156206: roachtest: backup-restore/round-trip failed [revision history backups don't grab function descs]
**Note:** This build has runtime assertions enabled. If the same failure was hit in a run without assertions enabled, there should be a similar failure without this message. If there isn&#39;t one, then this failure is likely due to an assertion violation or (assertion) timeout.

roachtest.backup-restore/round-trip [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20652697?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20652697?buildTab=artifacts#/backup-restore/round-trip) on release-25.3 @ [6776cbad08844ad9fa7cd586a5d00a2fa10b0b85](https://github.com/cockroachdb/cockroach/commits/6776cbad08844ad9fa7cd586a5d00a2fa10b0b85):

```
(monitor.go:241).Wait: monitor failure: error restoring backup: backup 3_round-trip-test-backup_database-schemachange: error in restore statement: pq: internal error: function descriptor rewrite failed: cannot restore function "udf_w2_275" because back referenced relation 282 was not found
test artifacts and logs in: /artifacts/backup-restore/round-trip/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>metamorphicBufferedSender=true</code>
 - <code>runtimeAssertionsBuild=true</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20652697/backup-restore-round-trip/1761459970128/1761460589624)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backup-restore/round-trip.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-55852

### PR DESCRIPTION
**Pull request by msbutler**
Previously, backup would omit grabbing a function descriptor in revision history backups if the function did not exist at the end time or only within the interval. This patch fixes this bug.

Fixes #156206

Release note: none

### CODE REVIEW

File: pkg/backup/targets.go [hunk 1]
```diff
@@ -159,7 +161,9 @@ func getRelevantDescChanges(
 		} else if change.Desc != nil {
 			desc := backupinfo.NewDescriptorForManifest(change.Desc)
 			switch desc := desc.(type) {
-			case catalog.TableDescriptor, catalog.TypeDescriptor, catalog.SchemaDescriptor:
+			case catalog.TableDescriptor, catalog.TypeDescriptor, catalog.SchemaDescriptor, catalog.FunctionDescriptor:
```
Comment (jeffswenson) [inline pkg/backup/targets.go:164]: Are we also missing Database here?

Comment (msbutler) [reply pkg/backup/targets.go:164]: ugh, we are. i will address in a separate patch as the fix there is not as trivial for _reasons_

**Review by jeffswenson — APPROVED** [review]
LGTM

File: pkg/backup/targets.go (hunk 1 above)
Comment (msbutler) [reply pkg/backup/targets.go:164]: er nvm. one bug is hard to solve and one is easy. i will solve the easy bug with a patch to this PR.

Comment (msbutler) [reply pkg/backup/targets.go:164]: turns out would capture dropped and added databases here :)
https://github.com/msbutler/cockroach/blob/butler-database-drop-expanded-db/pkg/backup/targets.go#L91

So we still have a bug with restore targeting dropped db explicitly, but i'll deal with that later
