### PR TITLE
server: do not use MustBeDString on nullable result col

### LINKED ISSUE #140044: Sentry: expected DString, found tree.dNull [in (*adminServer).DataDistribution]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/6256445744/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/6256445744/?referrer=webhooks_plugin)

Panic Message:

```
datum.go:1216: expected *DString, found tree.dNull
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | [...repeated from below...]
Wraps: (2) assertion failure
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.MustBeDString
  | 	pkg/sql/sem/tree/datum.go:1216
  | github.com/cockroachdb/cockroach/pkg/server.(*adminServer).dataDistributionHelper
  | 	pkg/server/admin.go:3057
  | github.com/cockroachdb/cockroach/pkg/server.(*adminServer).DataDistribution
  | 	pkg/server/admin.go:2928
  | github.com/cockroachdb/cockroach/pkg/server/serverpb._Admin_DataDistribution_Handler.func1
  | 	bazel-out/k8-opt/bin/pkg/server/serverpb/serverpb_go_proto_/github.com/cockroachdb/cockroach/pkg/server/serverpb/admin.pb.go:6281
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.ServerInterceptor.func12
  | 	pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:104
  | google.golang.org/grpc.getChainUnaryHandler.func1
  | 	external/org_golang_google_grpc/server.go:1177
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func3
  | 	pkg/rpc/context.go:165
  | google.golang.org/grpc.getChainUnaryHandler.func1
  | 	external/org_golang_google_grpc/server.go:1177
  | github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor
  | 	pkg/rpc/auth.go:90
  | google.golang.org/grpc.getChainUnaryHandler.func1
  | 	external/org_golang_google_grpc/server.go:1177
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func1.1
  | 	pkg/rpc/context.go:132
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr
  | 	pkg/util/stop/stopper.go:349
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func1
  | 	pkg/rpc/context.go:130
  | google.golang.org/grpc.NewServer.chainUnaryServerInterceptors.chainUnaryInterceptors.func1
  | 	external/org_golang_google_grpc/server.go:1168
  | github.com/cockroachdb/cockroach/pkg/server/serverpb._Admin_DataDistribution_Handler
  | 	bazel-out/k8-opt/bin/pkg/server/serverpb/serverpb_go_proto_/github.com/cockroachdb/cockroach/pkg/server/serverpb/admin.pb.go:6283
  | google.golang.org/grpc.(*Server).processUnaryRPC
  | 	external/org_golang_google_grpc/server.go:1358
  | google.golang.org/grpc.(*Server).handleStream
  | 	external/org_golang_google_grpc/server.go:1735
  | google.golang.org/grpc.(*Server).serveStreams.func1.1
  | 	external/org_golang_google_grpc/server.go:970
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1695
Wraps: (4) expected *DString, found tree.dNull
Error types: (1) *withstack.withStack (2) *assert.withAssertionFailure (3) *withstack.withStack (4) *errutil.leafError
-- report composition:
*errutil.leafError: expected *DString, found tree.dNull
datum.go:1216: *withstack.withStack (top exception)
*assert.withAssertionFailure
panic.go:770: *withstack.withStack (1)
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[external/org_golang_google_grpc/server.go#L969-L971](external/org_golang_google_grpc/server.go#L969-L971)
[external/org_golang_google_grpc/server.go#L1734-L1736](external/org_golang_google_grpc/server.go#L1734-L1736)
[external/org_golang_google_grpc/server.go#L1357-L1359](external/org_golang_google_grpc/server.go#L1357-L1359)
[bazel-out/k8-opt/bin/pkg/server/serverpb/serverpb_go_proto_/https://github.com/cockroachdb/cockroach/blob/b13cf51d928597efcb5a57eb7a9dad19c67b109e/pkg/server/serverpb/admin.pb.go#L6282-L6284](bazel-out/k8-opt/bin/pkg/server/serverpb/serverpb_go_proto_/https://github.com/cockroachdb/cockroach/blob/b13cf51d928597efcb5a57eb7a9dad19c67b109e/pkg/server/serverpb/admin.pb.go#L6282-L6284)
[external/org_golang_google_grpc/server.go#L1167-L1169](external/org_golang_google_grpc/server.go#L1167-L1169)
[pkg/rpc/context.go#L129-L131](pkg/rpc/context.go#L129-L131)
[pkg/util/stop/stopper.go#L348-L350](pkg/util/stop/stopper.go#L348-L350)
[pkg/rpc/context.go#L131-L133](pkg/rpc/context.go#L131-L133)
[external/org_golang_google_grpc/server.go#L1176-L1178](external/org_golang_google_grpc/server.go#L1176-L1178)
[pkg/rpc/auth.go#L89-L91](pkg/rpc/auth.go#L89-L91)
[external/org_golang_google_grpc/server.go#L1176-L1178](external/org_golang_google_grpc/server.go#L1176-L1178)
[pkg/rpc/context.go#L164-L166](pkg/rpc/context.go#L164-L166)
[external/org_golang_google_grpc/server.go#L1176-L1178](external/org_golang_google_grpc/server.go#L1176-L1178)
[pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L103-L105](pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L103-L105)
[bazel-out/k8-opt/bin/pkg/server/serverpb/serverpb_go_proto_/https://github.com/cockroachdb/cockroach/blob/b13cf51d928597efcb5a57eb7a9dad19c67b109e/pkg/server/serverpb/admin.pb.go#L6280-L6282](bazel-out/k8-opt/bin/pkg/server/serverpb/serverpb_go_proto_/https://github.com/cockroachdb/cockroach/blob/b13cf51d928597efcb5a57eb7a9dad19c67b109e/pkg/server/serverpb/admin.pb.go#L6280-L6282)
[pkg/server/admin.go#L2927-L2929](pkg/server/admin.go#L2927-L2929)
[pkg/server/admin.go#L3056-L3058](pkg/server/admin.go#L3056-L3058)
[pkg/sql/sem/tree/datum.go#L1215-L1217](pkg/sql/sem/tree/datum.go#L1215-L1217)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[external/org_golang_google_grpc/server.go#L969-L971](external/org_golang_google_grpc/server.go#L969-L971)
[external/org_golang_google_grpc/server.go#L1734-L1736](external/org_golang_google_grpc/server.go#L1734-L1736)
[external/org_golang_google_grpc/server.go#L1357-L1359](external/org_golang_google_grpc/server.go#L1357-L1359)
[bazel-out/k8-opt/bin/pkg/server/serverpb/serverpb_go_proto_/https://github.com/cockroachdb/cockroach/blob/b13cf51d928597efcb5a57eb7a9dad19c67b109e/pkg/server/serverpb/admin.pb.go#L6282-L6284](bazel-out/k8-opt/bin/pkg/server/serverpb/serverpb_go_proto_/https://github.com/cockroachdb/cockroach/blob/b13cf51d928597efcb5a57eb7a9dad19c67b109e/pkg/server/serverpb/admin.pb.go#L6282-L6284)
[external/org_golang_google_grpc/server.go#L1167-L1169](external/org_golang_google_grpc/server.go#L1167-L1169)
[pkg/rpc/context.go#L129-L131](pkg/rpc/context.go#L129-L131)
[pkg/util/stop/stopper.go#L348-L350](pkg/util/stop/stopper.go#L348-L350)
[pkg/rpc/context.go#L131-L133](pkg/rpc/context.go#L131-L133)
[external/org_golang_google_grpc/server.go#L1176-L1178](external/org_golang_google_grpc/server.go#L1176-L1178)
[pkg/rpc/auth.go#L89-L91](pkg/rpc/auth.go#L89-L91)
[external/org_golang_google_grpc/server.go#L1176-L1178](external/org_golang_google_grpc/server.go#L1176-L1178)
[pkg/rpc/context.go#L164-L166](pkg/rpc/context.go#L164-L166)
[external/org_golang_google_grpc/server.go#L1176-L1178](external/org_golang_google_grpc/server.go#L1176-L1178)
[pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L103-L105](pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L103-L105)
[bazel-out/k8-opt/bin/pkg/server/serverpb/serverpb_go_proto_/https://github.com/cockroachdb/cockroach/blob/b13cf51d928597efcb5a57eb7a9dad19c67b109e/pkg/server/serverpb/admin.pb.go#L6280-L6282](bazel-out/k8-opt/bin/pkg/server/serverpb/serverpb_go_proto_/https://github.com/cockroachdb/cockroach/blob/b13cf51d928597efcb5a57eb7a9dad19c67b109e/pkg/server/serverpb/admin.pb.go#L6280-L6282)
[pkg/server/admin.go#L2927-L2929](pkg/server/admin.go#L2927-L2929)
[pkg/server/admin.go#L3056-L3058](pkg/server/admin.go#L3056-L3058)
[pkg/sql/sem/tree/datum.go#L1215-L1217](pkg/sql/sem/tree/datum.go#L1215-L1217)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1695
external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).serveStreams.func1.1 at line 970
external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).handleStream at line 1735
external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).processUnaryRPC at line 1358
bazel-out/k8-opt/bin/pkg/server/serverpb/serverpb_go_proto_/github.com/cockroachdb/cockroach/pkg/server/serverpb/admin.pb.go in pkg/server/serverpb._Admin_DataDistribution_Handler at line 6283
external/org_golang_google_grpc/server.go in google.golang.org/grpc.NewServer.chainUnaryServerInterceptors.chainUnaryInterceptors.func1 at line 1168
pkg/rpc/context.go in pkg/rpc.NewServerEx.func1 at line 130
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunTaskWithErr at line 349
pkg/rpc/context.go in pkg/rpc.NewServerEx.func1.1 at line 132
external/org_golang_google_grpc/server.go in google.golang.org/grpc.getChainUnaryHandler.func1 at line 1177
pkg/rpc/auth.go in pkg/rpc.kvAuth.unaryInterceptor at line 90
external/org_golang_google_grpc/server.go in google.golang.org/grpc.getChainUnaryHandler.func1 at line 1177
pkg/rpc/context.go in pkg/rpc.NewServerEx.func3 at line 165
external/org_golang_google_grpc/server.go in google.golang.org/grpc.getChainUnaryHandler.func1 at line 1177
pkg/util/tracing/grpcinterceptor/grpc_interceptor.go in pkg/rpc.NewServerEx.ServerInterceptor.func12 at line 104
bazel-out/k8-opt/bin/pkg/server/serverpb/serverpb_go_proto_/github.com/cockroachdb/cockroach/pkg/server/serverpb/admin.pb.go in pkg/server/serverpb._Admin_DataDistribution_Handler.func1 at line 6281
pkg/server/admin.go in pkg/server.(*adminServer).DataDistribution at line 2928
pkg/server/admin.go in pkg/server.(*adminServer).dataDistributionHelper at line 3057
pkg/sql/sem/tree/datum.go in pkg/sql/sem/tree.MustBeDString at line 1216
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
src/runtime/asm_amd64.s in runtime.goexit at line 1695
external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).serveStreams.func1.1 at line 970
external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).handleStream at line 1735
external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).processUnaryRPC at line 1358
bazel-out/k8-opt/bin/pkg/server/serverpb/serverpb_go_proto_/github.com/cockroachdb/cockroach/pkg/server/serverpb/admin.pb.go in pkg/server/serverpb._Admin_DataDistribution_Handler at line 6283
external/org_golang_google_grpc/server.go in google.golang.org/grpc.NewServer.chainUnaryServerInterceptors.chainUnaryInterceptors.func1 at line 1168
pkg/rpc/context.go in pkg/rpc.NewServerEx.func1 at line 130
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunTaskWithErr at line 349
pkg/rpc/context.go in pkg/rpc.NewServerEx.func1.1 at line 132
external/org_golang_google_grpc/server.go in google.golang.org/grpc.getChainUnaryHandler.func1 at line 1177
pkg/rpc/auth.go in pkg/rpc.kvAuth.unaryInterceptor at line 90
external/org_golang_google_grpc/server.go in google.golang.org/grpc.getChainUnaryHandler.func1 at line 1177
pkg/rpc/context.go in pkg/rpc.NewServerEx.func3 at line 165
external/org_golang_google_grpc/server.go in google.golang.org/grpc.getChainUnaryHandler.func1 at line 1177
pkg/util/tracing/grpcinterceptor/grpc_interceptor.go in pkg/rpc.NewServerEx.ServerInterceptor.func12 at line 104
bazel-out/k8-opt/bin/pkg/server/serverpb/serverpb_go_proto_/github.com/cockroachdb/cockroach/pkg/server/serverpb/admin.pb.go in pkg/server/serverpb._Admin_DataDistribution_Handler.func1 at line 6281
pkg/server/admin.go in pkg/server.(*adminServer).DataDistribution at line 2928
pkg/server/admin.go in pkg/server.(*adminServer).dataDistributionHelper at line 3057
pkg/sql/sem/tree/datum.go in pkg/sql/sem/tree.MustBeDString at line 1216
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v25.1.0-beta.2 |
| Go Version | go1.22.8 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v25.1.0-beta.2 |
| Cockroach SHA | b13cf51d928597efcb5a57eb7a9dad19c67b109e |
| # of CPUs | 16 |
| # of Goroutines | 19952 |

Jira issue: CRDB-46973

### PR DESCRIPTION
**Pull request by xinhaoz**
In the data distribution handler we were attempting to read a
`raw_sql_config` on `crdb_internal.zones` using `MustBeDString`
which panics if the value is null.  This column is nullable.
We now allow null values to be read and make the response
value an empty string in that case.

Fixes: https://github.com/cockroachdb/cockroach/issues/140044

Release note (bug fix):  Data distribution page in
advanced debug will no longer crash if there are null
values for `raw_sql_config` in `crdb_internal.zones`.

### CODE REVIEW

File: pkg/server/admin.go [hunk 1]
```diff
@@ -3038,7 +3038,7 @@ func (s *adminServer) dataDistributionHelper(
 	zoneConfigsQuery := `
 		SELECT target, raw_config_sql, raw_config_protobuf
 		FROM crdb_internal.zones
-		WHERE target IS NOT NULL
+		WHERE target IS NOT NULL AND raw_config_sql IS NOT NULL
```
Comment (xinhaoz) [inline pkg/server/admin.go:3041]: Alternative is to continue to return all rows and use empty string when the raw string is null - lmk which is preferable!

**Comment by xinhaoz** [comment]
TODO: add tests and investigate why this didn't trigger the panic handler for http handlers.

File: pkg/server/admin.go (hunk 1 above)
Comment (dhartunian) [reply pkg/server/admin.go:3041]: I would prefer to return the rows and say that they're null/empty. Since this is an advanced debug page, my instinct is that we should try and show as much of the internals as possible as opposed to a more customer-facing page that requires more careful curation.

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/140066)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kyle-a-wong and @xinhaoz)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/140066#-OHt50To94JI5SF4fuNA:-OHt50TpANeDbKBeXZtg:bxrsjlz):*
nit: crdb

**Comment by xinhaoz** [comment]
> why this didn't trigger the panic handler for http handlers

This has a pretty simple explanation which is the DataDistribution endpoint is grpc and https://github.com/cockroachdb/cockroach/pull/72395 only handled panics in http handlers. 

From what I can tell if we want to handle panics like this we'd need to do that in the individual grpc methods we want or [defining a server interceptor here](https://github.com/cockroachdb/cockroach/blob/6a2a8132e1ffff295df5b7c0e839d6a96ee3f7bf/pkg/server/grpc_server.go#L30-L37).
@dhartunian any thoughs on this? My inclination is to go with the latter since it'd be more clear which rpcs we've applied recovery logic for - probably this would be most methods on the admin and status servers.

File: pkg/server/admin.go (hunk 1 above)
Comment (xinhaoz) [reply pkg/server/admin.go]: SGTM - updated and I'll leave the grpc panic recovery in a separate PR.

**Review by dhartunian — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/140066#-:-OIGgt0l07xD2kvU0d-T:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kyle-a-wong)

**Comment by xinhaoz** [comment]
blathers backport 25.1

**Comment by kyle-a-wong** [comment]
blathers backport 23.2

**Comment by kyle-a-wong** [comment]
blathers auth-check

**Comment by kyle-a-wong** [comment]
You shall pass

**Comment by kyle-a-wong** [comment]
blathers backport 23.2
