### PR TITLE
sql: attempt to unsplit ranges in GC job for secondary tenants

### LINKED ISSUE #116240: multi-tenant: gcjob unsplit only supports system tenant
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

The GC Job has code to unsplit indexes and tables on drop, but that code does not run outside of the system tenant:

https://github.com/cockroachdb/cockroach/blob/7b66a50edf641514dc9366e53894ec5b6af2dd0f/pkg/sql/gcjob/gc_job.go#L203-L205

As a result, table's that have been manually split with long expirations may leave small empty ranges in the cluster for a long time as they will be unable to be merged.

Jira issue: CRDB-34536

### PR DESCRIPTION
**Pull request by stevendanna**
Previously, we did not attempt an AdminUnsplit for secondary tenants, since secondary tenants were incapable of issuing unsplit requests. With the addition of tenant capabilities, some tenants may be able to issue unsplits.

Now, we opportunistically issue unsplits in secondary tenants.  If the unsplit fails with a permissions error, we give up and move on.

Note that secondary tenants cannot scan the range descriptors directly, so we use the range iterator to find relevant ranges. As a result, we may miss some ranges if the range cache is out of date.

I've opted for a bit of code duplication to make it easier to verify during review that the non-MT code path, remains the same as before.

Fixes #116240

Release note: None

### CODE REVIEW

File: pkg/sql/gcjob/gc_job.go [hunk 1]
```diff
@@ -195,22 +203,84 @@ func unsplitRangesInSpan(ctx context.Context, kvDB *kv.DB, span roachpb.Span) er
...
+			// permission to AdminUnsplit.
+			//
+			// TODO(ssd): We've opted to log a warning and move on,
+			// but this means in some cases the user may be left
+			// with empty, unmergable ranges.
+			if !execCfg.Codec.ForSystemTenant() && grpcutil.IsAuthError(err) {
+				log.Warningf(ctx, "failed to unsplit range at %s: %s", key, err)
+				continue
+			}
+			return err
```
Comment (stevendanna) [inline pkg/sql/gcjob/gc_job.go:242]: I could be convinced that we should never fail on an unsplit error here.

File: pkg/sql/gcjob/gc_job.go [hunk 2]
```diff
@@ -195,22 +203,84 @@ func unsplitRangesInSpan(ctx context.Context, kvDB *kv.DB, span roachpb.Span) er
 	return nil
 }
 
+// unsplitRangesInSpanForSecondaryTenant unsplits any manually splits ranges
+// within a span using an implementation that is appropriate for a secondary
+// tenant.
+//
+// When operating in a secondary tenant, unsplitting is not guaranteed becuase:
+//
+//   - The tenant may no longer be allowed to unsplit.
```
Comment (ajstorm) [inline pkg/sql/gcjob/gc_job.go:212]: Random drive-by nit: I can understand the motivation to have a "split" capability, but I don't follow why we'd want to gate "unsplit" behind a capability.  Is there some way that "unsplit" would do anything but leave the cluster in a better (i.e. more efficient) state?

Comment (stevendanna) [reply pkg/sql/gcjob/gc_job.go:212]: I am having trouble reconstructing the entire conversation. But, I think at least part of the argument was that `split` is more dangerous than `unsplit` so you might want to allow `unsplit` while restricting `split` in response to some run-away tenant.

But, eh, I do kinda wonder if we would be better served by one capability. Especially since requests still can only impact ranges whose start key is inside the tenant's keyspace.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116312#-:-Nl_HJwU0AlgOJ9HP9cy:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @ajstorm, @dt, and @stevendanna)

___
*[`pkg/sql/gcjob/gc_job.go` line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116312#-Nl_EStG8or_6VxaEQku:-Nl_EStG8or_6VxaEQkv:b8ehhkw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddbc1733e1f4ccb14cd2e34bbd3ed544cb456352/pkg/sql/gcjob/gc_job.go#L206)):*
> ```Go
> }
> 
> // unsplitRangesInSpanForSecondaryTenant unsplits any manually splits ranges
> ```

nit: probably `s/splits/split/`.
___
*[`pkg/sql/gcjob/gc_job.go` line 210 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116312#-Nl_EWDW8eb3ElM_Hjlq:-Nl_EWDW8eb3ElM_Hjlr:b-pq9xna) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddbc1733e1f4ccb14cd2e34bbd3ed544cb456352/pkg/sql/gcjob/gc_job.go#L210)):*
> ```Go
> // tenant.
> //
> // When operating in a secondary tenant, unsplitting is not guaranteed becuase:
> ```

nit: `s/becuase/because/`.
___
*[`pkg/sql/gcjob/gc_job.go` line 242 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116312#gh-1425109243:-Nl_FsxbCDv_yi2nfBxl:b9azn5w) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddbc1733e1f4ccb14cd2e34bbd3ed544cb456352/pkg/sql/gcjob/gc_job.go#L242)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I could be convinced that we should never fail on an unsplit error here.
</blockquote></details>

Returning an error here would fail the GC job, and then it would show up on the Jobs page, right? Are there other consequences? It seems reasonable to me to fail a job in case of an unexpected error here.

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116312)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @ajstorm, @dt, and @yuzefovich)

___
*[`pkg/sql/gcjob/gc_job.go` line 242 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116312#gh-1425109243:-Nl_Ivb00i3x2lv1Fszw:b-7qbdvp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddbc1733e1f4ccb14cd2e34bbd3ed544cb456352/pkg/sql/gcjob/gc_job.go#L242)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Returning an error here would fail the GC job, and then it would show up on the Jobs page, right? Are there other consequences? It seems reasonable to me to fail a job in case of an unexpected error here.
</blockquote></details>

Because the GC job is marked as an "uncancellable" job, I believe an error here will result in a job-system-level retry with backoff. You can see the most recent execution error in some views of the job system and not others. I don't think the jobs  page in the DB console will show it, `SHOW JOBS` will.

**Comment by stevendanna** [comment]
bors r=yuzefovich
