### PR TITLE
cli: Deflake TestRemoveDeadReplicas

### LINKED ISSUE #33495: cli: TestRemoveDeadReplicas failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/d6adf24cae788d7cd967feadae8e9c0388ce5273

Parameters:
```
TAGS=
GOFLAGS=
```

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=TestRemoveDeadReplicas PKG=github.com/cockroachdb/cockroach/pkg/cli TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1079976&tab=buildLog

```
E190104 06:13:32.036907 3439 storage/replica.go:1514  [n1,s1,r6/4:/Table/{SystemCon…-11}] lease repl=(n3,s3):2 seq=2 start=1546582411.279150002,0 epo=1 pro=1546582411.279152482,0 owned by replica (n3,s3):2 that no longer exists
W190104 06:13:32.041459 1806 server/status/runtime.go:294  [n?] Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
W190104 06:13:32.049362 1806 gossip/gossip.go:1499  [n?] no incoming or outgoing connections
W190104 06:13:32.078070 1806 server/status/recorder.go:389  [n4] unable to look up descriptor for n2
W190104 06:13:32.078096 1806 server/status/recorder.go:389  [n4] unable to look up descriptor for n3
W190104 06:13:32.078993 3609 server/status/recorder.go:389  [n4,summaries] unable to look up descriptor for n2
W190104 06:13:32.079024 3609 server/status/recorder.go:389  [n4,summaries] unable to look up descriptor for n3
E190104 06:13:32.100186 3397 storage/replica.go:1514  [n1,s1,r6/4:/Table/{SystemCon…-11}] lease repl=(n3,s3):2 seq=2 start=1546582411.279150002,0 epo=1 pro=1546582411.279152482,0 owned by replica (n3,s3):2 that no longer exists
E190104 06:13:32.100547 3439 storage/replica.go:1514  [n1,s1,r6/4:/Table/{SystemCon…-11}] lease repl=(n3,s3):2 seq=2 start=1546582411.279150002,0 epo=1 pro=1546582411.279152482,0 owned by replica (n3,s3):2 that no longer exists
E190104 06:13:32.100744 3416 storage/replica.go:1514  [n1,s1,r6/4:/Table/{SystemCon…-11}] lease repl=(n3,s3):2 seq=2 start=1546582411.279150002,0 epo=1 pro=1546582411.279152482,0 owned by replica (n3,s3):2 that no longer exists
E190104 06:13:32.102650 3504 storage/replica.go:1514  [n1,s1,r6/4:/Table/{SystemCon…-11}] lease repl=(n3,s3):2 seq=2 start=1546582411.279150002,0 epo=1 pro=1546582411.279152482,0 owned by replica (n3,s3):2 that no longer exists
E190104 06:13:32.103090 3408 storage/replica.go:1514  [n1,s1,r6/4:/Table/{SystemCon…-11}] lease repl=(n3,s3):2 seq=2 start=1546582411.279150002,0 epo=1 pro=1546582411.279152482,0 owned by replica (n3,s3):2 that no longer exists
E190104 06:13:32.103286 3669 storage/replica.go:1514  [n1,s1,r6/4:/Table/{SystemCon…-11}] lease repl=(n3,s3):2 seq=2 start=1546582411.279150002,0 epo=1 pro=1546582411.279152482,0 owned by replica (n3,s3):2 that no longer exists
W190104 06:13:32.107810 1806 server/status/runtime.go:294  [n?] Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
W190104 06:13:32.116802 1806 gossip/gossip.go:1499  [n?] no incoming or outgoing connections
E190104 06:13:32.130185 3354 storage/replica.go:1514  [n1,s1,r6/4:/Table/{SystemCon…-11}] lease repl=(n3,s3):2 seq=2 start=1546582411.279150002,0 epo=1 pro=1546582411.279152482,0 owned by replica (n3,s3):2 that no longer exists
W190104 06:13:32.130261 3354 storage/store.go:1466  [n1,s1,r6/4:/Table/{SystemCon…-11}] could not gossip system config: [NotLeaseHolderError] r6: replica (n1,s1):4 not lease holder; lease holder unknown
W190104 06:13:32.141059 1806 server/status/recorder.go:389  [n5] unable to look up descriptor for n3
W190104 06:13:32.141088 1806 server/status/recorder.go:389  [n5] unable to look up descriptor for n2
W190104 06:13:32.141604 3822 server/status/recorder.go:389  [n5,summaries] unable to look up descriptor for n3
W190104 06:13:32.141712 3822 server/status/recorder.go:389  [n5,summaries] unable to look up descriptor for n2
E190104 06:13:32.146255 3678 storage/replica.go:1514  [n1,s1,r6/4:/Table/{SystemCon…-11}] lease repl=(n3,s3):2 seq=2 start=1546582411.279150002,0 epo=1 pro=1546582411.279152482,0 owned by replica (n3,s3):2 that no longer exists
E190104 06:13:32.146874 3677 storage/replica.go:1514  [n1,s1,r6/4:/Table/{SystemCon…-11}] lease repl=(n3,s3):2 seq=2 start=1546582411.279150002,0 epo=1 pro=1546582411.279152482,0 owned by replica (n3,s3):2 that no longer exists
--- FAIL: TestRemoveDeadReplicas (1.96s)
	testcluster.go:172: system config not available in gossip

```

### PR DESCRIPTION
**Pull request by bdarnell**
The move to create all ranges at bootstrap time means it is no longer
the case that n1 has all the leases. This means that we may need to
wait for leases to expire while waiting for full replication.

Fixes #33495

Release note: None

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34169#-:-LWsMwn5B8gti1JjtINY:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

**Review by andreimatei — CHANGES_REQUESTED** [review]
I'm not sure about this fix. I'd rather have `WaitForFullReplication()` return the error than way seconds. The test can retry on its side if there's nothing better to do. no?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34169#-:-LWsbqpwBNa_sd5K8bUw:bj7z7e5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @bdarnell)

___
*[pkg/testutils/testcluster/testcluster.go, line 567 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34169#-LWsa5Qm1ug44vVK_g35:-LWsa5Qm1ug44vVK_g36:b-rdroyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/4746fd3e1b2e1e6d2495bbd4c3c9e7c188dc3d2b/pkg/testutils/testcluster/testcluster.go#L567)):*
> ```Go
> 				if i == 0 {
> 					if err := s.ForceReplicationScanAndProcess(); err == storage.ErrSystemConfigUnavailable {
> 						// If we're restoring from old store directories and a
> ```

This comment is confusing. It talks about leases, but the condition is about gossip. Can you spell out that the system config is gossipped by the leaseholder of the respective range?

File: pkg/testutils/testcluster/testcluster.go [hunk 1]
```diff
@@ -563,7 +563,14 @@ func (tc *TestCluster) WaitForFullReplication() error {
 				// Force the first node to upreplicate everything. Otherwise, if we rely
 				// on the scanner to do it, it'll take a while.
 				if i == 0 {
-					if err := s.ForceReplicationScanAndProcess(); err != nil {
+					if err := s.ForceReplicationScanAndProcess(); err == storage.ErrSystemConfigUnavailable {
```
Comment (tbg) [inline pkg/testutils/testcluster/testcluster.go]: Use `errors.Cause(err) == ...` here.

**Review by bdarnell — COMMENTED** [review]
>  I'd rather have WaitForFullReplication() return the error than way seconds. The test can retry on its side if there's nothing better to do. no?

The test doesn't call WaitForFullReplication; this is buried within the TestCluster stack. And it's a method with "wait" in its name; it's expected that it might take a while. This isn't something that tests should decide on a case-by-case basis how to handle. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34169#-:-LWvzqdE7COXgeZIABer:b-o6cnbz)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @tbg)

___
*[pkg/testutils/testcluster/testcluster.go, line 566 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34169#-LWr8lq0tQxOLFyYFc3S-r1-566:-LWw-6A03pvcOGZZviBx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4746fd3e1b2e1e6d2495bbd4c3c9e7c188dc3d2b/pkg/testutils/testcluster/testcluster.go#L566)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Use `errors.Cause(err) == ...` here.
</blockquote></details>

Done.
___
*[pkg/testutils/testcluster/testcluster.go, line 567 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34169#-LWsa5Qm1ug44vVK_g35:-LWw-5X66O2foJb5PPXn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4746fd3e1b2e1e6d2495bbd4c3c9e7c188dc3d2b/pkg/testutils/testcluster/testcluster.go#L567)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

This comment is confusing. It talks about leases, but the condition is about gossip. Can you spell out that the system config is gossipped by the leaseholder of the respective range?
</blockquote></details>

Done.

**Review by andreimatei — COMMENTED** [review]
Well, there's waiting and there's waiting :). The method could be named something else other than "wait" since it's not just twiddling its thumbs; it's doing stuff.
It not that individual tests should decide; the majority of tests, who simply start a new cluster, shouldn't hit this error. Other tests that restart a cluster I think again shouldn't hit this error. It's just tests that kill nodes, right?

How about making cluster restarts not ever call `WaitForFullReplication()`? The replication is desirable for initial cluster creation; on restart I think it becomes a lot more debatable.

Feel free to also merge. It seems less than ideal to me but I'm not gonna stop anything.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34169#-:-LWw6TSCDoUabXL6vnBW:bs1db7f)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @tbg)

**Comment by petermattis** [comment]
I think https://github.com/cockroachdb/cockroach/pull/34126 will cause `TestRemoveDeadReplicas` to fail. The problem is that the cluster has 5 replicas, thus the adaptive replication count will be 5 and not 3 and so the `WaitForFullReplication` loop will never exit. We probably have to force `TestRemoveDeadReplicas` to have a fixed replication factor of 3.

**Comment by bdarnell** [comment]
> How about making cluster restarts not ever call WaitForFullReplication()? The replication is desirable for initial cluster creation; on restart I think it becomes a lot more debatable.

Maybe, but this test does wait to wait for full re-replication after the restart, so it would just have to do the same error retry itself. And the reason I modified WaitForFullReplication is that in theory the "system config not gossiped" could happen any time - the gossip of the system config is fundamentally an async operation. It's kind of surprising that we don't otherwise see flakiness from this. 

> I think #34126 will cause TestRemoveDeadReplicas to fail.

Yes, it did. Looks like I need to decommission the removed nodes before waiting for replication after the restart.

**Review by andreimatei — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34169#-:-LXQIYxo-_-lVTul1Szg:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @bdarnell, and @tbg)

___
*[pkg/cli/debug_test.go, line 261 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34169#-LXQIM4x9pIb5KdcOQV8:-LXQIM4y8zvR5Mxok3tM:b-dcrvil) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8a72dc444b2a9d9a7a2c2829ec725c61cc5120b/pkg/cli/debug_test.go#L261)):*
> ```Go
> 	adminClient := serverpb.NewAdminClient(grpcConn)
> 
> 	if err := runDecommissionNodeImpl(ctx, adminClient, nodeDecommissionWaitNone, []string{"2", "3"}); err != nil {
> ```

long line

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34169)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @bdarnell, and @tbg)

___
*[pkg/cli/debug_test.go, line 255 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34169#-LXQTVaU4RPFel7YlZSx:-LXQTVaU4RPFel7YlZSy:b-tky86h) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8a72dc444b2a9d9a7a2c2829ec725c61cc5120b/pkg/cli/debug_test.go#L255)):*
> ```Go
> 	defer tc.Stopper().Stop(ctx)
> 
> 	grpcConn, err := tc.Server(0).RPCContext().GRPCDial(tc.Server(0).ServingAddr()).Connect(ctx)
> ```

OMG! Looks like some helper could be used there, but I see this pattern is used elsewhere.
