### PR TITLE
sql: fix panic when virtual tables inspect tables with UDTs

### LINKED ISSUE #49300: sql: `SHOW CREATE` panics when a table contains a user defined type
This is caused by some lower level descriptor access not hydrating descriptors properly.

### PR DESCRIPTION
**Pull request by rohany**
Fixes #49300.

This PR ensures that tables retrieved by virtual tables have hydrated
types. Additionally, it ensures that all resolved user defined types
have qualified names accessible for use. Previously, this was only the
case for types that were resolved by name.

Release note: None

### CODE REVIEW

**Comment by rohany** [comment]
Its becoming more clear that once we have leasing for all descriptors, there needs to be a unified way of also accessing a descriptor by ID while utilizing the cache. Most of our methods that access things by ID just hit KV directly.

File: pkg/sql/descriptor.go [hunk 1]
```diff
@@ -326,13 +331,45 @@ func GetAllDescriptors(
...
+	// scanned might have types that need hydrating.
+	if len(typDescs) > 0 {
+		// Since we just scanned all the descriptors, we already have everything
+		// we need to hydrate our types. Set up an accessor for the type hydration
+		// method to look into the scanned set of descriptors.
+		typeLookup := func(id sqlbase.ID) (*tree.TypeName, *TypeDescriptor, error) {
+			typDesc := typDescs[id]
+			dbDesc := dbDescs[typDesc.ParentID]
+			schemaName, err := schema.ResolveNameByID(ctx, txn, codec, dbDesc.ID, typDesc.ParentSchemaID)
+			if err != nil {
```
Comment (jordanlewis) [inline pkg/sql/descriptor.go:356]: I think that it's worth being more defensive here. If we somehow got a corrupted table descriptor that references an enum that no longer exists, you'd be unable to do anything that required GetAllDescriptors, which is called all over the place. Would it be possible to log an error, but still return a descriptor that's just not hydrated, and add errors when you actually try to use an unhydrated descriptor?

File: pkg/sql/resolver.go [hunk 2]
```diff
@@ -194,45 +207,49 @@ func (p *planner) ResolveTypeByID(id uint32) (*types.T, error) {
...
+// types present in a table descriptor. typeLookup retrieves the fully
+// qualified name and descriptor for a particular ID.
+func hydrateTypesInTableDescriptor(
+	desc *TableDescriptor, typeLookup func(id sqlbase.ID) (*tree.TypeName, *TypeDescriptor, error),
+) error {
+	for i := range desc.Columns {
+		col := &desc.Columns[i]
+		if col.Type.UserDefined() {
+			// Look up its type descriptor.
+			name, typDesc, err := typeLookup(sqlbase.ID(col.Type.StableTypeID()))
```
Comment (jordanlewis) [inline pkg/sql/resolver.go:220]: ditto about defensiveness in this method

File: pkg/sql/descriptor.go (hunk 1 above)
Comment (rohany) [reply pkg/sql/descriptor.go:356]: Hmm, that's a great point. Logging here makes sense. I'll see what can be done about getting errors from usages of the unhydrated descriptor (see #49404), but it is tricky to plumb errors out of some of these methods. The most important thing for these virtual tables is that the type names in the descriptors are resolved so that they display correctly. Without it, they just display with the unqualified name.

File: pkg/sql/resolver.go (hunk 2 above)
Comment (rohany) [reply pkg/sql/resolver.go:220]: I don't think this one needs to worry about it -- whoever calls this method and passes in the type lookup function should know what to do with the error.

**Comment by rohany** [comment]
Refactored this some more -- thanks to #49354, I'm able to push some more stuff out of SQL. The end state I'm imagining here is that all accesses to descriptors through the `desc.Collection` will return types that have installed metadata, and accesses lower than that don't. This should bring us closer to that state.

**Comment by rohany** [comment]
Pinging for a review on this!

**Review by ajwerner — COMMENTED** [review]
:lgtm: 

>  there needs to be a unified way of also accessing a descriptor by ID while utilizing the cache. 

Indeed. All this work is making it pretty clear what's left to do this release. Thanks for fighting the good fight and dealing with the existing mess. There is so much code to be deduplicated and unified, I'm starting to get pretty excited about it.

> Reviewed 2 of 6 files at r1, 3 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49338#-:-M7nVvHqEsitCiEBNsLl:brxmmbj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @jordanlewis, and @lucy-zhang)

**Review by thoszhang — APPROVED** [review]
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49338)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @jordanlewis, @lucy-zhang, and @rohany)

___
*[pkg/sql/planner.go, line 457 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49338#-M8M8uAH70bd6NQtn0PX:-M8M8uAH70bd6NQtn0PY:bhpre5a) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a7a871c42904e4bb4e0e20e5570fdc94e3a427e/pkg/sql/planner.go#L457)):*
> ```Go
> 
> // LookupTableByID looks up a table, by the given descriptor ID. Based on the
> // CommonLookupFlags, it could use or skip the TableCollection cache. See
> ```

nit: Should just be `Collection`
___
*[pkg/sql/planner.go, line 458 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49338#-M8M8zbQCYejatGvqHk1:-M8M8zbR7IgBkieXei86:buo9nmt) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a7a871c42904e4bb4e0e20e5570fdc94e3a427e/pkg/sql/planner.go#L458)):*
> ```Go
> // LookupTableByID looks up a table, by the given descriptor ID. Based on the
> // CommonLookupFlags, it could use or skip the TableCollection cache. See
> // TableCollection.getTableVersionByID for how it's used.
> ```

Same here

**Comment by rohany** [comment]
TFTRs!

bors r+
