### PR TITLE
roachtest: simplify and deflake cleanup in clock jump test

### LINKED ISSUE #156339: roachtest: clock/jump/large_backward_enabled failed
roachtest.clock/jump/large_backward_enabled [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_Roachtests_RoachtestNightlyIbmBazel/20659363?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_Roachtests_RoachtestNightlyIbmBazel/20659363?buildTab=artifacts#/clock/jump/large_backward_enabled) on release-25.3 @ [692054f785c04833771dcbf228d480c2ef9c3bc5](https://github.com/cockroachdb/cockroach/commits/692054f785c04833771dcbf228d480c2ef9c3bc5):

```
(test_runner.go:1538).func1: failed during post test assertions (see test-post-assertions.log): unable to set 'server.consistency_check.max_rate': EOF
test artifacts and logs in: /artifacts/clock/jump/large_backward_enabled/cpu_arch=s390x/run_1
```

Parameters:
 - <code>arch=s390x</code>
 - <code>cloud=ibm</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>metamorphicBufferedSender=true</code>
 - <code>metamorphicLeases=epoch</code>
 - <code>metamorphicWriteBuffering=true</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for ibm clusters_</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*clock/jump/large_backward_enabled.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-55948

### PR DESCRIPTION
**Pull request by tbg**
Closes #156339.

Passing test run: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20660221?hideTestsFromDependencies=false&hideProblemsFromDependencies=false

Epic: none

### CODE REVIEW

File: pkg/cmd/roachtest/tests/clock_jump_crash.go [hunk 1]
```diff
@@ -76,6 +66,13 @@ func runClockJump(ctx context.Context, t test.Test, c cluster.Cluster, tc clockJ
 	if aliveAfterOffset != tc.aliveAfterOffset {
 		t.Fatalf("Expected node health %v, got %v", tc.aliveAfterOffset, aliveAfterOffset)
 	}
+
+	// Resetting the clock is a jump in the opposite direction which can cause a
+	// crash even if the original jump didn't. Since we do not control when
+	// exactly the clock jumps, we simply stop and wipe the node (which also
+	// prevents the post-test assertions from complaining about a down node).
+	c.Wipe(ctx, c.All())
+	offsetInjector.recover(ctx, c.Spec().NodeCount)
```
Comment (stevendanna) [inline pkg/cmd/roachtest/tests/clock_jump_crash.go:75]: Is this here in case the cluster gets re-used by another roachtest?

**Review by stevendanna — APPROVED** [review]
Looks like the test run passed.

File: pkg/cmd/roachtest/tests/clock_jump_crash.go (hunk 1 above)
Comment (tbg) [reply pkg/cmd/roachtest/tests/clock_jump_crash.go:75]: Yeah, I think this is just for good hygiene. I'm actually not sure, maybe the failover tests reuse the clusters between each other, too.
