### PR TITLE
roachtest: lower changefeed memory for select tests

### LINKED ISSUE #166146: roachtest: cdc/multi-region-execution-locality-tpcc failed
roachtest.cdc/multi-region-execution-locality-tpcc [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21273427?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21273427?buildTab=artifacts#/cdc/multi-region-execution-locality-tpcc) on release-26.1.2-rc @ [0b8f541247b366ba244397ab26d1b6aa4d0f200b](https://github.com/cockroachdb/cockroach/commits/0b8f541247b366ba244397ab26d1b6aa4d0f200b):

Failed with:

```
(assertions.go:369).Fail: 
	Error Trace:	pkg/cmd/roachtest/tests/cdc.go:2082
	            				pkg/cmd/roachtest/test_runner.go:1539
	            				src/runtime/asm_amd64.s:1693
	Error:      	Received unexpected error:
	            	pq: root: memory budget exceeded: 102400 bytes requested, 3979962414 currently allocated, 3979963392 bytes in budget
	Test:       	cdc/multi-region-execution-locality-tpcc
(require.go:1357).NoError: FailNow called
(cdc.go:402).Close: error shutting down prometheus/grafana: context canceled
test artifacts and logs in: /artifacts/cdc/multi-region-execution-locality-tpcc/run_1
```
Cluster Node to Ip Mapping:
| Node | Public IP | Private IP |
| --- | --- | --- |
| teamcity-21273427-1773901263-40-n7cpu4-geo-0001 | 34.75.32.156 | 10.142.2.98 |
| teamcity-21273427-1773901263-40-n7cpu4-geo-0002 | 34.24.193.72 | 10.142.2.97 |
| teamcity-21273427-1773901263-40-n7cpu4-geo-0003 | 34.24.141.93 | 10.142.2.99 |
| teamcity-21273427-1773901263-40-n7cpu4-geo-0004 | 34.105.42.93 | 10.138.0.43 |
| teamcity-21273427-1773901263-40-n7cpu4-geo-0005 | 35.247.91.18 | 10.138.0.42 |
| teamcity-21273427-1773901263-40-n7cpu4-geo-0006 | 34.105.47.254 | 10.138.0.41 |
| teamcity-21273427-1773901263-40-n7cpu4-geo-0007 | 35.231.175.210 | 10.142.1.207 |

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>diskCount=0</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>metamorphicWriteBuffering=true</code>
 - <code>runtimeAssertionsBuild=false</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-21273427/cdc-multi-region-execution-locality-tpcc/1773906508880/1773907274403)

</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/multi-region-execution-locality-tpcc.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-61769

### PR DESCRIPTION
**Pull request by KeithCh**
Some tests were giving changefeeds 4GiB, but 4-CPU machines have 
~3.75 GiB SQL memory pool. Lowering this to be below the SQL 
memory pool size prevents the tests from exceeding memory budget.

Fixes: #166146
Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/cdc.go
Comment (aerfrei) [inline pkg/cmd/roachtest/tests/cdc.go]: It's interesting to me that the issue here is that the changefeed.memory.per_changefeed_limit is set to 4GB in this function, but it's default would be fine. (Under 3.75GB) So then we overwrite that to a third value in some cases. I think it might make the defaults harder to reason about. 

I think a lot of this is preexisting. The naming also seems a bit unintuitive, we call this "makeCDCBenchOptions" but they're actually the default options for _all_ CDC roachtests (at least that use cdcTester). 

Maybe we could do something like this: 
- have a new function called makeCDCDefaultTestOptions that does what makeCDCBenchOptions does now, maybe without this setting. 
- Have makeCDCBenchOptions call that and make additional changes on top of that (maybe just this setting)
- Here we call makeCDCDefaultTestOptions and actually all tests using newCDCTester will use the 2gb default. (Not sure if there's potential downside to that)

Maybe this could have unforeseen impact on other tests, but I think the code would be in a better spot re:readability. Not sure how to weigh the pros and cons, what do you think?

Comment (KeithCh) [reply pkg/cmd/roachtest/tests/cdc.go]: I'm for it. I'm also going to try using the default `changefeed.memory.per_changefeed_limit`.

Comment (KeithCh) [reply pkg/cmd/roachtest/tests/cdc.go]: Tested a regular roachtest `multi-region-execution-locality-tpcc` and it passed, and also a benchmark test
`cdc/scan/initial/nodes=5/cpu=16/rows=1G/ranges=100/protocol=mux/format=json/sink=null`

File: pkg/cmd/roachtest/tests/cdc_bench.go [hunk 1]
```diff
@@ -219,21 +219,48 @@ func formatSI(num int64) string {
...
+
+	return opts, settings
+}
+
+// makeCDCBenchOptions creates common cluster options for CDC benchmarks.
+// Builds on makeCDCDefaultTestOptions with benchmark-specific tuning.
+func makeCDCBenchOptions(c cluster.Cluster) (option.StartOpts, install.ClusterSettings) {
+	opts, settings := makeCDCDefaultTestOptions(c)
+
 	// Give changefeed more memory and slow down rangefeed checkpoints.
```
Comment (aerfrei) [inline pkg/cmd/roachtest/tests/cdc_bench.go]: nit: this "Give changefeed more memory and slow down rangefeed checkpoints." comment seems inaccurate. I'm thinking it isn't less accurate than it was before, but it says we slow down rangefeed checkpoints which I'm understanding to be the commented out "settings.ClusterSettings["kv.rangefeed.closed_timestamp_refresh_interval"] = "5s"" so it probably driften. Might be worth fixing if we're already touching the code.

**Review by aerfrei — APPROVED** [review]
Looks good! I left a nit about a pre-existing comment

File: pkg/cmd/roachtest/tests/cdc_bench.go (hunk 1 above)
Comment (KeithCh) [reply pkg/cmd/roachtest/tests/cdc_bench.go]: Made some small changes to it.
