### PR TITLE
sql: fix a crash due to naive logging

### LINKED ISSUE #14560: sql: nil pointer dereference in Executor
node 9 on indigo died with the following panic:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: INSERT INTO blocks (block_id, writer_id, block_num, raw_bytes) VALUES (7359107162809420170, 'c9377e9c-a3e2-4996-bde1-8664f15d2621', 4347280, $1): runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: INSERT INTO blocks (block_id, writer_id, block_num, raw_bytes) VALUES (7359107162809420170, 'c9377e9c-a3e2-4996-bde1-8664f15d2621', 4347280, $1): runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: INSERT INTO blocks (block_id, writer_id, block_num, raw_bytes) VALUES (7359107162809420170, 'c9377e9c-a3e2-4996-bde1-8664f15d2621', 4347280, $1): runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1274be4]

goroutine 1410 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc420250280)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:198 +0x6e
panic(0x1ad3080, 0xc45069bd10)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve.func1(0xc421a7c000, 0x7fe71e37e500, 0xc420b26d20)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:348 +0x74
panic(0x1ad3080, 0xc45069bd10)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements.func1(0xc42198eabb, 0x90)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:497 +0x131
panic(0x1afdde0, 0x28fbee0)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest(0xc4203c7040, 0xc420d42000, 0xc42198eabb, 0x90, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:717 +0x734
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements(0xc4203c7040, 0xc420d42000, 0xc42198eabb, 0x90, 0xc4a588b498, 0x0, 0x0, 0x0, 0xc42198eb00)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:503 +0x180
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).executeStatements(0xc421a7c000, 0xc42198eabb, 0x90, 0xc4a588b498, 0x2da5d70, 0x0, 0x0, 0x1b12600, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:831 +0x94
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleExecute(0xc421a7c000, 0xc421a7c028, 0xc420f8a2a0, 0xc421a7c045)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:818 +0x172
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc421a7c000, 0x7fe71e37e500, 0xc420b26d20, 0xc420846cc0, 0x5400, 0xc4203a8690, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:450 +0xb37
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc4203a8540, 0x7fe71e37e4c0, 0xc420ff9840, 0x2940d80, 0xc420b3aa80, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:415 +0x927
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func9.1(0x2942e20, 0xc420d05900)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:587 +0x153
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc420250280, 0xc42026a020, 0x2942e20, 0xc420d05900, 0xc420a59bc0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:136 +0x95
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
        /go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:138 +0x239
```

This seems to be caused by [this line](https://github.com/cockroachdb/cockroach/blob/4d2c8be8e93e560a3a4dabda87c69c5363056311/pkg/sql/executor.go#L734) in `executor.go`.

### PR DESCRIPTION
**Pull request by andreimatei**
Fixes #14560

Because of #7881, we somehow get an AutoCommitError while txnState.txn
is nil. This shouldn't happen - we shouldn't be attempting to autocommit
if we're no longer in a KV transaction.
A logging statement that was added for #7881 failed to behave properly
for this supposedly-impossible case. This commit fixes the logging
statement.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14577)

### CODE REVIEW

File: pkg/sql/executor.go [hunk 1]
```diff
@@ -729,9 +729,13 @@ func (e *Executor) execRequest(
...
+					var txnProto *roachpb.Transaction
+					if txnState.txn != nil {
+						txnProto = txnState.txn.Proto()
+					}
 					log.Eventf(session.Ctx(), "executor got AutoCommitError: %s\n"+
 						"txn: %+v\nexecOpt.AutoRetry %t, execOpt.AutoCommit:%t, stmts %+v, remaining %+v",
-						aErr, txnState.txn.Proto(), execOpt.AutoRetry, execOpt.AutoCommit, stmts,
+						aErr, txnProto, execOpt.AutoRetry, execOpt.AutoCommit, stmts,
 						remainingStmts)
 					if txnState.txn == nil {
```
Comment (asubiotto) [inline pkg/sql/executor.go]: Maybe merge this with your addition above into one `if {...} else {...}` block

**Comment by asubiotto** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/executor.go, line 740 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14577#-KgpFvXT5RYJZkDUTnsZ-r1-740:-KgpbECCVvtkeuDtqD01:b-uem2ji) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b4ff381a254124b83dc63b8a8e8e6d9b092c43f/pkg/sql/executor.go#L740)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

well the first log message is generally good to have, for tracing. I'd leave it outside...
</blockquote></details>

There's no problem leaving the first log message (`Eventf`) outside, but I mean having something like:
```
if txnState.txn != nil {
    txnProto = txnState.txn.Proto()
} else {
    log.Errorf(...)
    txnState.sp.SetBaggageItem(...)
}
log.Eventf(..., txnProto)
```
to avoid a second if statement

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14577)*

**Comment by andreimatei** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/executor.go, line 740 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14577#-KgpFvXT5RYJZkDUTnsZ-r1-740:-KgpftCsA-oZr9m-28U8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b4ff381a254124b83dc63b8a8e8e6d9b092c43f/pkg/sql/executor.go#L740)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

There's no problem leaving the first log message (`Eventf`) outside, but I mean having something like:
```
if txnState.txn != nil {
    txnProto = txnState.txn.Proto()
} else {
    log.Errorf(...)
    txnState.sp.SetBaggageItem(...)
}
log.Eventf(..., txnProto)
```
to avoid a second if statement
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14577)*

**Review by asubiotto — APPROVED** [review]
