### PR TITLE
cli: Fix demo simluated latencies in --insecure mode

### LINKED ISSUE #77001: Simulated network latencies in cockroach multi-region demo are too subtle
**Issue:**
Cockroach demo in a multi-region mode need more dramatic latency differences, at least by an order of magnitude to illustrate MR benefits. Currently, in a MR demo, EU is <5 ms away from US.

**Repro:**
- `cockroach demo --no-example-database --insecure --nodes 9 --global`
- confirm the cluster is regionalized with `SHOW REGIONS FROM CLUSTER;` and other simple metadata queries
- point a browser to the db console and observe the latencies on the network map page

**Environment:**
 - CockroachDB version v21.2.4
 - Server OS: Windows10
 - Client app: n/a

**Additional context**
This issue has a significant/material impact on customer demos that can be accommodated by a local/portable/laptop setup, which eliminates demo risks factors and allows customers to take ownership/repro the demo in-house.

Jira issue: CRDB-13365

### PR DESCRIPTION
**Pull request by ajstorm**
Previously we were not initializing the simulated latency correctly in all
cases. In the insecure case specifically, we may have had an uninitialized
simulated latency header which we'd then use as the simulated latency for the
given transmission. This commit changes the initialization so that we only
setup a simulated latency header if the supplied simulated latency is not 
set to zero.

The commit also adds a test for both --insecure and secure mode to validate
that the simulated latencies are setup correctly.

Release justification: bug fix
Release note (cli change): Fixes a bug where demo with the --global
flag would not simulate latencies correctly when combined with the --insecure
flag.

Resolves: #77001 and #63098

### CODE REVIEW

File: pkg/rpc/context.go [hunk 1]
```diff
@@ -1111,9 +1111,11 @@ func (d *delayingConn) Read(b []byte) (n int, err error) {
 			return 0, errors.WithStack(errMagicNotFound)
 		}
 
-		// Once we receive our first packet, we set our delay to the expected
-		// delay that was sent on the write side.
-		d.latency = time.Duration(hdr.DelayMS) * time.Millisecond
+		// Once we receive our first packet with a DelayMS field set, we set our
+		// delay to the expected delay that was sent on the write side.
```
Comment (jordanlewis) [inline pkg/rpc/context.go:1115]: I think it would be nice to augment this comment with some more explanation about what this conditional is about, considering how confused we were trying to understand what was going on. I'm thinking about an explanation of when this check actually gets hit, and how the sender is the one responsible for setting the latency, and so on.

**Review by jordanlewis — APPROVED** [review]
Looks great!

File: pkg/rpc/context.go (hunk 1 above)
Comment (ajstorm) [reply pkg/rpc/context.go]: I added something but TBH, I don't fully understand all of the reasons why this was broken just yet.  The comment explains that, as well as the rationale for why it's safe to not overwrite a non-zero value.  Let me know if this is along the lines of what you were hoping to see.

**Comment by ajstorm** [comment]
@jordanlewis please take a look at my latest revision.  There's one more place where we _might_ want to use a pointer receiver for a delayingConn function (Write).  That function updates the structure but wasn't using a pointer receiver up until now.  I was hoping that might have been the issue here, but it doesn't seem to address the root problem of the overwrite to zero (which continues to be solved by the conditional I added).

File: pkg/rpc/context.go [hunk 2]
```diff
@@ -1079,7 +1079,7 @@ type delayingConn struct {
 	readBuf     *bytes.Buffer
 }
 
-func (d delayingConn) Write(b []byte) (n int, err error) {
+func (d *delayingConn) Write(b []byte) (n int, err error) {
 	tNow := timeutil.Now()
 	if d.lastSendEnd.Before(tNow) {
 		d.lastSendEnd = tNow
```
Comment (jordanlewis) [inline pkg/rpc/context.go:1085]: This would have done nothing before your change. Is that a problem? I don't remember what we use `lastSendEnd` for, but this really wouldn't have worked whatsoever unless we only use it down below in this same function to set `ReadTime`.

Comment (ajstorm) [reply pkg/rpc/context.go:1085]: I think it's more than `lastSendEnd` that's an issue though, as here:

https://github.com/cockroachdb/cockroach/blob/397046b4aca08f01bfefaf1856041094ea4f35ff/pkg/rpc/context.go#L1093-L1095

we're writing the header to the `d.Conn`.  Without the pointer receiver, won't that update not get persisted?

Comment (jordanlewis) [reply pkg/rpc/context.go:1085]: No, that'll work fine, because `d.Conn` is an interface and therefore a pointer. So even a copy of `d` will have the same `Conn` as the original `d`. The only issue here is value (non-pointer) fields in `d`, such as `d.lastSendEnd`.

Comment (ajstorm) [reply pkg/rpc/context.go]: Ahh, cool, thanks.  I didn't realize that interfaces were automatically pointers, but that makes sense.

OK, I think we're good leaving this as-is then, as `lastSendEnd` is only used in this function, and then written to the `hdr` which then gets written to the `Conn` interface.  I've reverted the change.  I think we're good to go now.

**Comment by ajstorm** [comment]
TFTR!

bors r=jordanlewis
