### PR TITLE
ui: fix statement activity timepicker for sub-hour ranges

### LINKED ISSUE #145430: ui: statement activity page timepicker doesn't work with ranges less than an hour
Background:
CRDB allows users to configure the aggregation interval of sql stats, which defines the interval length in which sql stats are aggregated for a given fingerprint. As an example, setting the cluster setting `sql.stats.aggregation.interval='10m'` will create a new aggregation every 10 minutes for a given fingerprint. 

Setting this setting allows granular introspection into sql stats by allowing sql stats tables to queried with smaller time slices. 

Issue:
If a user defines a smaller aggregation interval (say 10m as mentioned above) db console will allow a user to specify a 10 minute window in the time picker, but the start and end timestamps used to request sql stats are those for the encapsulating hour. 

Fix:
We should fix this so that the the api call to the backend sends the expected timestamps

initial slack conversation reporting the issue: https://cockroachlabs.slack.com/archives/C063CP41TG9/p1745853166239859

screenshot:

Image

Jira issue: CRDB-49897

### PR DESCRIPTION
**Pull request by angles-n-daemons**
ui: fix statement activity timepicker for sub-hour ranges

This commit fixes a bug where the statement activity time picker wasn't working correctly with time ranges less than an hour when sql.stats.aggregation.interval is set to values smaller than 1h.

The issue was that API calls were using toRoundedDateRange() which rounds timestamps to hour boundaries instead of toDateRange() which uses the exact selected time range. This prevented sub-hour time ranges from working properly even when the aggregation interval supported them.

Changed the following components to use toDateRange():
- StatementsPage
- TransactionsPage
- TransactionDetails
- StatementDetails selectors
- IndexDetails API

Fixes #145430

Epic: None
Release note (bug fix): Fixed statement activity page time picker to work correctly with time ranges less than an hour when sql.stats.aggregation.interval is configured to sub-hour values. Previously, selecting a 10-minute window would query for a full hour of data instead of the precise selected range.

### CODE REVIEW

File: pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts [hunk 1]
```diff
@@ -41,12 +41,10 @@ export const selectStatementDetails = createSelector(
...
-    // Since the aggregation interval is 1h, we want to round the selected timeScale to include
-    // the full hour. If a timeScale is between 14:32 - 15:17 we want to search for values
-    // between 14:00 - 16:00. We don't encourage the aggregation interval to be modified, but
-    // in case that changes in the future we might consider changing this function to use the
-    // cluster settings value for the rounding function.
-    const [start, end] = toRoundedDateRange(timeScale);
+    // Use the exact time range selected by the user, not rounded to hour boundaries.
+    // This allows for more granular time ranges when sql.stats.aggregation.interval
+    // is set to a value smaller than 1 hour.
+    const [start, end] = toDateRange(timeScale);
```
Comment (dhartunian) [inline pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts:47]: I think the default configuration will leave users confused when they zoom in and "see nothing" inside an hour. How can we mitigate this? We should at the very least surface a warning to the user that they're looking at something smaller than their aggregation interval.

I imagine the rounding was added for exactly this reason.

Comment (angles-n-daemons) [reply pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts:47]: That makes sense, we added the warning, let me know what you think!

**Review by dhartunian — APPROVED** [review]
