### PR TITLE
server: enable TestServerControllerLoginLogout for secondary tenants

### LINKED ISSUE #110002: serverccl: TestServerControllerLoginLogout misbehaves when pointed to a secondary tenant
Found while working on #110001.

**Describe the problem**

This test misbehaves when pointed to a secondary tenant; that is, the following sequence fails:
```go
   client, _ ≔ s.GetAuthenticatedHTTPClient(false, serverutils.SingleTenantSession)
   resp, _ ≔ client.Post(s.AdminURL().WithPath("/logout").String(), "", nil)
   require.Equal(t, 200, resp.StatusCode)
```

The error is "expected 200, got 405" . It's strange and unexpected that /logout on a secondary tenant would return 405.

**To Reproduce**

Change the test as follows:
```go
 srv ≔ serverutils.StartServerOnly(t, base.TestServerArgs{})
 s := srv.ApplicationLayer()
```

Epic CRDB-38970

Jira issue: CRDB-31212

### PR DESCRIPTION
**Pull request by shubhamdhama**
Fixes: #110002
Epic: CRDB-38970
Release note: none

### CODE REVIEW

File: pkg/ccl/serverccl/server_controller_test.go [hunk 1]
```diff
@@ -563,16 +563,16 @@ func TestServerControllerLoginLogout(t *testing.T) {
...
 	s := srv.ApplicationLayer()
+	isExternal := srv.DeploymentMode().IsExternal()
 
-	client, err := s.GetAuthenticatedHTTPClient(false, serverutils.SingleTenantSession)
+	sessionType := serverutils.SingleTenantSession
+	client, err := s.GetAuthenticatedHTTPClient(false, sessionType)
 	require.NoError(t, err)
 
-	resp, err := client.Post(s.AdminURL().WithPath("/logout").String(), "", nil)
+	resp, err := client.Get(s.AdminURL().WithPath("/logout").String())
```
[the remark this answers is not in the document]
Comment (shubhamdhama) [reply pkg/ccl/serverccl/server_controller_test.go:575]: I think `Get` is the way to go since browser also uses `Get` for this.

Comment (shubhamdhama) [inline pkg/ccl/serverccl/server_controller_test.go:575]: @dhartunian curious to get your take on this small change—was the use of `.Post` intentional here, or should it be `.Get` like the rest?

Comment (shubhamdhama) [reply pkg/ccl/serverccl/server_controller_test.go:575]: Also, I guess we use `.Get` in DB Console UI

Comment (dhartunian) [reply pkg/ccl/serverccl/server_controller_test.go:575]: I think our endpoint doesn't check the HTTP method in the handler. I generally believe that logout/login should be POST requests since they're not cacheable and modify request state.

I don't care strongly what the test does since our handler doesn't enforce.
DB Console does stuff with redirecting to /logout to force it to happen, so I haven't modified the handler.

**Review by dhartunian — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/143354)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @copilot-pull-request-reviewer[bot], @cthumuluru-crdb, and @shubhamdhama)

___
*[`pkg/ccl/serverccl/server_controller_test.go` line 587 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/143354#-ONMCgtP4AKQ7I6oRj5O:-ONMCgtP4AKQ7I6oRj5P:biwsw0r) ([raw file](https://github.com/cockroachdb/cockroach/blob/68b3608fcb836de1cddf6330ec0171e4350192c8/pkg/ccl/serverccl/server_controller_test.go#L587)):*
> ```Go
> 		// TODO: Not sure why 'Secure' isn't set for logout in external mode,
> 		// even though it's set in other cases. This isn't just a test issue —
> 		// it happens outside of tests too.
> ```

I think this is because there's different code for logging out in single and multi-tenant setups:

multi-tenant logout: https://github.com/cockroachdb/cockroach/blob/master/pkg/server/server_controller_http.go#L334-L336

single-tenant logout: https://github.com/cockroachdb/cockroach/blob/master/pkg/server/authserver/authentication.go#L416-L419

I wrote these changes and if I want to remember why I did this, I think it was likely because when I added the `forHTTPSOnly` flag I didn't want to break existing cookie callsites so I defaulted to `false`. It seemed OK not to force the logout cookie to be secure. Also, it seems like during logout we don't have the context of whether our original cookie was secure, although I'm sure we can retrieve that somehow. My thinking was that forcing logout in more scenarios than not (by not making the cookie secure) was a good tradeoff.

File: pkg/ccl/serverccl/server_controller_test.go (hunk 1 above)
Comment (cthumuluru-crdb) [reply pkg/ccl/serverccl/server_controller_test.go:575]: > I generally believe that logout/login should be POST requests since they're not cacheable and modify request state.

+1. Lets retain `Post()` if possible in the test.

**Review by cthumuluru-crdb — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/143354)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @copilot-pull-request-reviewer[bot], @dhartunian, and @shubhamdhama)

___
*[`pkg/ccl/serverccl/server_controller_test.go` line 587 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/143354#-ONMCgtP4AKQ7I6oRj5O:-ONOHHd9-rcaZIkD3Mg8:b-5il2gp) ([raw file](https://github.com/cockroachdb/cockroach/blob/68b3608fcb836de1cddf6330ec0171e4350192c8/pkg/ccl/serverccl/server_controller_test.go#L587)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

I think this is because there's different code for logging out in single and multi-tenant setups:

multi-tenant logout: https://github.com/cockroachdb/cockroach/blob/master/pkg/server/server_controller_http.go#L334-L336

single-tenant logout: https://github.com/cockroachdb/cockroach/blob/master/pkg/server/authserver/authentication.go#L416-L419

I wrote these changes and if I want to remember why I did this, I think it was likely because when I added the `forHTTPSOnly` flag I didn't want to break existing cookie callsites so I defaulted to `false`. It seemed OK not to force the logout cookie to be secure. Also, it seems like during logout we don't have the context of whether our original cookie was secure, although I'm sure we can retrieve that somehow. My thinking was that forcing logout in more scenarios than not (by not making the cookie secure) was a good tradeoff.
</blockquote></details>

Thanks, @dhartunian. @shubhamdhama, can you please summarize this context and replace the comment.

File: pkg/ccl/serverccl/server_controller_test.go (hunk 1 above)
Comment (shubhamdhama) [reply pkg/ccl/serverccl/server_controller_test.go:575]: `.Post()` doesn't work here for external-process mode.

Comment (cthumuluru-crdb) [reply pkg/ccl/serverccl/server_controller_test.go:575]: @shubhamdhama, in that case, can you please add a comment to indicate `Post` doesn't work and we choose to use `Get` for the test?

Comment (shubhamdhama) [reply pkg/ccl/serverccl/server_controller_test.go:577]: Done
