### PR TITLE
kv: reacquire proscribed leases on drain, then transfer

### LINKED ISSUE #83372: roachtest: transfer-leases/signal failed [presumed same as #83261]
roachtest.transfer-leases/signal [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/5558662?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/5558662?buildTab=artifacts#/transfer-leases/signal) on master @ [fc7ae339c3f85ad2a2b28643e47d7c20768fe237](https://github.com/cockroachdb/cockroach/commits/fc7ae339c3f85ad2a2b28643e47d7c20768fe237):

```
test artifacts and logs in: /artifacts/transfer-leases/signal/run_1
	quit.go:72,quit.go:323,soon.go:69,retry.go:207,soon.go:75,soon.go:48,quit.go:228,quit.go:95,quit.go:154,context.go:91,quit.go:153,quit.go:95,quit.go:54,quit.go:359,test_runner.go:896: (1) ranges with no lease outside of node 1: []string{"11"}
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*transfer-leases/signal.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-17030

### LINKED ISSUE #89962: roachtest: transfer-leases/drain-other-node failed
roachtest.transfer-leases/drain-other-node [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6937707?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6937707?buildTab=artifacts#/transfer-leases/drain-other-node) on release-22.2.0 @ [79756fd7476c970f763661a63824beaedc339bd3](https://github.com/cockroachdb/cockroach/commits/79756fd7476c970f763661a63824beaedc339bd3):

```
test artifacts and logs in: /artifacts/transfer-leases/drain-other-node/run_1
	quit.go:72,quit.go:323,soon.go:69,retry.go:208,soon.go:75,soon.go:48,quit.go:228,quit.go:95,quit.go:154,context.go:91,quit.go:153,quit.go:95,quit.go:54,quit.go:359,test_runner.go:930: (1) ranges with no lease outside of node 3: []string{"43"}
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #89568 roachtest: transfer-leases/drain-other-node failed [C-test-failure O-roachtest O-robot T-kv branch-master]
- #87770 roachtest: transfer-leases/drain-other-node failed [C-test-failure GA-blocker O-roachtest O-robot T-kv branch-release-22.1 no-test-failure-activity]
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*transfer-leases/drain-other-node.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-20518

### LINKED ISSUE #89963: roachtest: transfer-leases/signal failed
roachtest.transfer-leases/signal [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6937707?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6937707?buildTab=artifacts#/transfer-leases/signal) on release-22.2.0 @ [79756fd7476c970f763661a63824beaedc339bd3](https://github.com/cockroachdb/cockroach/commits/79756fd7476c970f763661a63824beaedc339bd3):

```
test artifacts and logs in: /artifacts/transfer-leases/signal/run_1
	quit.go:72,quit.go:323,soon.go:69,retry.go:208,soon.go:75,soon.go:48,quit.go:228,quit.go:95,quit.go:154,context.go:91,quit.go:153,quit.go:95,quit.go:54,quit.go:359,test_runner.go:930: (1) ranges with no lease outside of node 1: []string{"44"}
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #83372 roachtest: transfer-leases/signal failed [presumed same as #83261] [C-test-failure O-roachtest O-robot T-kv branch-master]
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*transfer-leases/signal.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-20519

### LINKED ISSUE #90022: roachtest: transfer-leases/drain failed
roachtest.transfer-leases/drain [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6953767?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6953767?buildTab=artifacts#/transfer-leases/drain) on release-22.2 @ [cffe9bc440988894abe9a598ea6b2f15e1b7df93](https://github.com/cockroachdb/cockroach/commits/cffe9bc440988894abe9a598ea6b2f15e1b7df93):

```
test artifacts and logs in: /artifacts/transfer-leases/drain/run_1
	quit.go:72,quit.go:323,soon.go:69,retry.go:208,soon.go:75,soon.go:48,quit.go:228,quit.go:95,quit.go:154,context.go:91,quit.go:153,quit.go:95,quit.go:54,quit.go:359,test_runner.go:930: (1) ranges with no lease outside of node 1: []string{"43"}
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #89962 roachtest: transfer-leases/drain-other-node failed [C-test-failure O-roachtest O-robot T-kv branch-release-22.2.0 release-blocker]
- #89568 roachtest: transfer-leases/drain-other-node failed [C-test-failure O-roachtest O-robot T-kv branch-master]
- #87770 roachtest: transfer-leases/drain-other-node failed [C-test-failure GA-blocker O-roachtest O-robot T-kv branch-release-22.1 no-test-failure-activity]
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*transfer-leases/drain.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-20550

### PR DESCRIPTION
**Pull request by nvb**
Fixes #83372.
Fixes #90022.
Fixes #89963.
Fixes #89962.

This commit instructs stores to reacquire proscribed leases when draining in order to subsequently transfer them away. This addresses a source of flakiness in `transfer-lease` roachtests where some lease would not be transferred away before the drain completed. This could result in range unavailable for up to 9 seconds while other replicas waited out the lease'S expiration. This is because only the previous leaseholder knows that a proscribed lease is invalid. All other replicas still consider the lease to be valid.

This failure mode was always present if a lease transfer failed during a drain. However, it became more likely with 034611b. With that change, we began rejecting lease transfers that were deemed to be "unsafe" more frequently. 034611b introduced a best-effort, graceful version of this check and an airtight, ungraceful version of the check. The former performs the check before revoking the outgoing leaseholder's lease while the latter performs the check after revoking the outgoing leaseholder's lease. In rare cases, it was possible to hit the airtight, ungraceful check and cause the lease to be proscribed. See https://github.com/cockroachdb/cockroach/issues/83261#issuecomment-1178366134 for more details on how this led to test flakiness in the `transfer-lease` roachtest suite.

Release notes: None.

Release justification: Avoids GA-blocking roachtest failures.

### CODE REVIEW

File: pkg/kv/kvserver/batcheval/cmd_lease_transfer.go [hunk 1]
```diff
@@ -74,7 +74,6 @@ func TransferLease(
 	prevLease, _ := cArgs.EvalCtx.GetLease()
 
 	newLease := args.Lease
-	args.Lease = roachpb.Lease{} // prevent accidental use below
```
Comment (nvanbenschoten) [inline pkg/kv/kvserver/batcheval/cmd_lease_transfer.go:77]: For reviewers: this line was intentionally removed because it was not needed and I found that it once again caused a good deal of confusion when trying to write a test. It's best not to mutate input requests, especially if they may later be exposed to testing hooks.

**Review by shralex — APPROVED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90106)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/cmd/roachtest/tests/quit.go` line 316 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90106#-NEfxcsh8xigRrNJw66K:-NEfxcsh8xigRrNJw66L:bpxcp0j) ([raw file](https://github.com/cockroachdb/cockroach/blob/52087f5123b93a8533b2c205c34d7cd8dec32076/pkg/cmd/roachtest/tests/quit.go#L316)):*
> ```Go
> 		}
> 		// (1): is there a range where no replica thinks the lease is held
> 		// outside of nodeID? If so, the value in knownRanges will be set to 0.
> ```

nit: IMHO would be even clearer if you rephrase to the same text as (2), replacing "any" by "every": "is there a range where every replica thinks the lease is held by nodeID"
___
*[`pkg/kv/kvserver/store.go` line 1579 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90106#-NEg-WcFDmM3FdqfdOQQ:-NEg-WcFDmM3FdqfdOQR:b32azgz) ([raw file](https://github.com/cockroachdb/cockroach/blob/52087f5123b93a8533b2c205c34d7cd8dec32076/pkg/kv/kvserver/store.go#L1579)):*
> ```Go
> 								log.VErrEventf(ctx, 1 /* level */, failFormat, infoArgs...)
> 							}
> 						}
> ```

nit: Should we log anything on success if verbose || log.V(1) ? 
___
*[`pkg/kv/kvserver/store.go` line 1580 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90106#-NEg-jq1CMZoSqGj9KdZ:-NEg-jq1CMZoSqGj9Kd_:b-wf0xvq) ([raw file](https://github.com/cockroachdb/cockroach/blob/52087f5123b93a8533b2c205c34d7cd8dec32076/pkg/kv/kvserver/store.go#L1580)):*
> ```Go
> 							}
> 						}
> 						return
> ```

Will we visit this store again to transfer the lease once the state is out of proscribed and re-aquired ? could we add a comment about this ?

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90106)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @shralex)

___
*[`pkg/cmd/roachtest/tests/quit.go` line 316 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90106#-NEfxcsh8xigRrNJw66K:-NEgE0iT4jaDambTCUOF:b-fznogt) ([raw file](https://github.com/cockroachdb/cockroach/blob/52087f5123b93a8533b2c205c34d7cd8dec32076/pkg/cmd/roachtest/tests/quit.go#L316)):*
<details><summary><i>Previously, shralex wrote…</i></summary><blockquote>

nit: IMHO would be even clearer if you rephrase to the same text as (2), replacing "any" by "every": "is there a range where every replica thinks the lease is held by nodeID"
</blockquote></details>

Good idea, done.
___
*[`pkg/kv/kvserver/store.go` line 1579 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90106#-NEg-WcFDmM3FdqfdOQQ:-NEgE7zB7eJbdTshWkAc:b-th8taq) ([raw file](https://github.com/cockroachdb/cockroach/blob/52087f5123b93a8533b2c205c34d7cd8dec32076/pkg/kv/kvserver/store.go#L1579)):*
<details><summary><i>Previously, shralex wrote…</i></summary><blockquote>

nit: Should we log anything on success if verbose || log.V(1) ? 
</blockquote></details>

We aren't logging on success during the transfer, so I figured I'd keep this symmetrical and only log on error here.
___
*[`pkg/kv/kvserver/store.go` line 1580 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90106#-NEg-jq1CMZoSqGj9KdZ:-NEgFOh7AFhT_BtCXtqS:b5hazy8) ([raw file](https://github.com/cockroachdb/cockroach/blob/52087f5123b93a8533b2c205c34d7cd8dec32076/pkg/kv/kvserver/store.go#L1580)):*
<details><summary><i>Previously, shralex wrote…</i></summary><blockquote>

Will we visit this store again to transfer the lease once the state is out of proscribed and re-aquired ? could we add a comment about this ?
</blockquote></details>

Done. I also reworked this to fall directly through after a successful reacquisition.

**Comment by nvanbenschoten** [comment]
bors r=shralex
