### PR TITLE
changefeedccl: fix ALTER CHANGEFEED max PTS age bug

### LINKED ISSUE #148029: changefeedccl: ALTER CHANGEFEED does not observe max PTS age cluster setting
The ALTER CHANGEFEED code is missing code to use the `changefeed.protect_timestamp.max_age` cluster setting as the altered job's max PTS age when `gc_protect_expires_after` is not specified: 

https://github.com/cockroachdb/cockroach/blob/ac05162842f8353fc8cdff9802060d54a8b94560/pkg/ccl/changefeedccl/alter_changefeed_stmt.go#L245-L249

Here is the CREATE CHANGEFEED code for reference:

https://github.com/cockroachdb/cockroach/blob/ac05162842f8353fc8cdff9802060d54a8b94560/pkg/ccl/changefeedccl/changefeed_stmt.go#L825-L828

One case we may want to consider is in the event `gc_protect_expires_after` was not set both before/after the ALTER, whether we should maintain the value of `changefeed.protect_timestamp.max_age` at the time to the changefeed job was created or replace it with the current value.

### PR DESCRIPTION
**Pull request by andyyang890**
This patch fixes a bug where modifying a changefeed with ALTER CHANGEFEED
that either unset or left the `gc_protect_expires_after` option unset would
cause the changefeed's max PTS age to become unbounded instead of being set to
the default value configured by the `changefeed.protect_timestamp.max_age`
cluster setting.

This bug was occurring because the ALTER CHANGEFEED code was manually querying
the option instead of relying on the CREATE CHANGEFEED code path that also
consulted the cluster setting. This inconsistency has now been corrected.

Fixes #148029

Release note (bug fix): A bug where modifying a changefeed with ALTER CHANGEFEED
that either unset or left the `gc_protect_expires_after` option unset would
cause the changefeed's max PTS age to become unbounded instead of being set to
the default value configured by the `changefeed.protect_timestamp.max_age`
cluster setting.

### CODE REVIEW

File: pkg/ccl/changefeedccl/alter_changefeed_stmt.go [hunk 1]
```diff
@@ -227,11 +227,8 @@ func alterChangefeedPlanHook(
 		newPayload.Details = jobspb.WrapPayloadDetails(newDetails)
 		newPayload.Description = jobRecord.Description
 		newPayload.DescriptorIDs = jobRecord.DescriptorIDs
-		newExpiration, err := newOptions.GetPTSExpiration()
-		if err != nil {
-			return err
-		}
-		newPayload.MaximumPTSAge = newExpiration
+		newPayload.MaximumPTSAge = jobRecord.MaximumPTSAge
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/alter_changefeed_stmt.go:233]: `jobRecord.MaximumPTSAge` will be populated correctly by the `createChangefeedJobRecord` call above

**Review by KeithCh — APPROVED** [review]

File: pkg/ccl/changefeedccl/alter_changefeed_stmt.go (hunk 1 above)
Comment (asg0451) [reply pkg/ccl/changefeedccl/alter_changefeed_stmt.go:233]: can you add this as a code comment?

**Review by asg0451 — APPROVED** [review]

**Comment by asg0451** [comment]
missing description in pr body.

**Comment by asg0451** [comment]
also, i'm not sure if we should backport this per the new policy:

> Fixes for serious issues: As described in the [backport policy](https://cockroachlabs.atlassian.net/wiki/x/_YEuPg), “this includes correctness, stability, or security issues, data corruption/loss, significant performance regressions, breaking working and widely used functionality, and an inability to detect and debug production issues.”

i feel like this doesnt qualify as a serious issue

**Comment by andyyang890** [comment]
TFTR!

bors r=KeithCh,asg0451

**Comment by rharding6373** [comment]
[Team meeting]: Not a critical enough bug, and fix/job migration is risky, so we don't plan to backport the fix.
