### PR TITLE
sql: fix uniqueness errors

### LINKED ISSUE #1891: `client.Batch.Results` doesn't get filled on error
For a batch containing multiple calls, it's impossible to determine which call failed. This happens because the error case short-circuits the execution of `client.DB.Run`:
```
func (db *DB) Run(b *Batch) error {
	if err := b.prepare(); err != nil {
		return err
	}
	if err := db.send(b.calls...); err != nil {
		return err
	}
	return b.fillResults()
}
```

### PR DESCRIPTION
**Pull request by tbg**
fixes #1891. A lot of mechanical changes, so probably best to review commit-by-commit.

### CODE REVIEW

File: client/db.go [hunk 1]
```diff
@@ -423,9 +426,9 @@ func sendAndFill(send func(...proto.Call) error, b *Batch) error {
 // Upon completion, Batch.Results will contain the results for each
 // operation. The order of the results matches the order the operations were
 // added to the batch.
-func (db *DB) Run(b *Batch) error {
+func (db *DB) Run(b *Batch) *proto.Error {
```
Comment (petermattis) [inline client/db.go]: Rather than changing this return type, could `proto.Error` implement the `error` interface and let the caller extract the `proto.Error` type when desired?

Comment (tschottdorf) [inline client/db.go]: That was the case before (see #2579), and (at least I) always found it a source of confusion to have an error wrapping another error (if you get an `error` and interface match it against errors you expect, you're going to miss it when it's wrapped). I feel that much clarity has been won by explicitly returning a `*proto.Error` here (and nothing's lost, since you get the thing you had before by just calling `GoError()`). We're moving a little bit away from idiomatic go to idiomatic use of the `req -> (resp, err)` pattern, but I think even on the `Go` side it's a net win (it's easy to have `*proto.Error` implement `error` again and then it'll be obvious which code paths relied on the wrapped error - the other way around wasn't so obvious at all).

Comment (petermattis) [inline client/db.go]: Hmm, ok. I'd feel more strongly about this if the `client` package was exposed to the user. But it's not anymore. So this is fine by me.

File: proto/errors.proto [hunk 2]
```diff
@@ -204,9 +204,13 @@ message Error {
...
+  optional TransactionRestart transaction_restart = 3 [(gogoproto.nullable) = false];
 
   // If an ErrorDetail is present, it may contain additional structured data
   // about the error.
-  optional ErrorDetail detail = 3;
+  optional ErrorDetail detail = 4;
+
+  // The Index, if given, contains the index of the request (in the batch)
+  // whose execution caused the error.
+  optional int32 index = 5 [default=-1];
```
Comment (tamird) [inline proto/errors.proto]: since this is nullable (and i think that's correct) you might want to make it unsigned.

Comment (bdarnell) [inline proto/errors.proto]: Non-zero defaults in protobufs are considered harmful. Also, proto3 will remove both nullable fields and non-zero defaults, so if we want to be able to move this to proto3 we'll have to use a separate boolean `has_index` field.

File: storage/store.go [hunk 3]
```diff
@@ -1231,9 +1231,7 @@ func (s *Store) ExecuteCmd(ctx context.Context, args proto.Request) (proto.Respo
 			// clients will retry.
 			err = proto.NewRangeNotFoundError(rng.Desc().RangeID)
 		} else if iErr, ok := err.(*errWithIndex); ok {
-			err, index = iErr.err, iErr.index
-			// TODO(tschottdorf): propagate the index up. See #1891.
-			_ = index
+			err, index = iErr.err, &iErr.index
```
Comment (bdarnell) [inline storage/store.go]: Storing a pointer into the `errWithIndex` struct could have surprising results if that struct is later reused, and also prevents GC of the original error. Better to make a copy of `iErr.index` with `index = proto.Int32(iErr.index)`.

**Comment by bdarnell** [comment]
LGTM

File: proto/errors.proto (hunk 2 above)
Comment (tschottdorf) [inline proto/errors.proto]: how do you feel about shifting everything up by one? That is, zero means "no index" and everything else is just a cardinal number.

Comment (bdarnell) [inline proto/errors.proto]: I'd rather have a separate bool than have a non-zero-based "index". Another option would be to wrap the index in an ErrorLocation message (nested messages will remain nullable in proto3; it's just primitives that will become non-nullable).

Comment (tschottdorf) [inline proto/errors.proto]: ok, separate message sounds best to me then.

File: storage/store.go (hunk 3 above)
Comment (tschottdorf) [inline storage/store.go]: done.
