### PR TITLE
multitenant: always disallow disallow batch on stopped tenant

### LINKED ISSUE #138301: server: tenant remains writable even after service mode is stopped
**Describe the problem**

Related discussion in https://cockroachlabs.slack.com/archives/C03JCUUSCD6/p1735407188845879?thread_ts=1734543915.272749&cid=C03JCUUSCD6.

Shared tenants undergo a graceful draining process once we stop a tenant's service. When the tenant's service mode transitions to none, there may still be existing connections to the tenant, and these connections can still write to the tenant. 

**To Reproduce**
```
cockroach start-single-node --insecure

# Create a new tenant via the system tenant.
create tenant "test-tenant";
alter tenant "test-tenant" start service shared;

# Connect to the test tenant.
cockroach sql --url "postgresql://root@localhost:26257/cluster:test-tenant/defaultdb?sslmode=disable"
set cluster setting server.shutdown.drain_wait = '100s'; (or server.shutdown.connection_wait)

# Stop the tenant in the system tenant.
alter tenant "test-tenant" stop service;
show tenants -> wait until service mode is none

# Write/query from the test tenant.
create table foo (a int)
select * from foo
```

**Expected behavior**

We expect that there should be no draining process whenever a tenant transitions from external/shared to stopping, and finally to none. When the service mode is none, we should guarantee that the tenant is no longer accessible and writable.

Jira issue: CRDB-46023

### PR DESCRIPTION
**Pull request by stevendanna**
Requests from secondary tenants should aways be rejected once the tenant is stopping.

Fixes #138301
Release note: None

### CODE REVIEW

**Comment by stevendanna** [comment]
NB: Do not merge without a test! I opened this to see how many existing tests fail if we move this check.

File: pkg/multitenant/mtinfopb/info.go [hunk 1]
```diff
@@ -61,6 +61,7 @@ var TenantServiceModeValues = map[string]TenantServiceMode{
 	"none":     ServiceModeNone,
 	"external": ServiceModeExternal,
 	"shared":   ServiceModeShared,
+	"stopping": ServiceModeStopping,
```
Comment (msbutler) [inline pkg/multitenant/mtinfopb/info.go:64]: why does this require adding a new service mode? why not use `TenantDataState`?

Comment (dt) [reply pkg/multitenant/mtinfopb/info.go:64]: DataState describes the state of their persisted data, not their service. i.e. if you are half-way done restoring or importing or reverting them, the data is inconsistent vs the data is correct, but you can choose if and how to serve it -- but that actual choice is separate, and represented by svc mode.

Comment (dt) [reply pkg/multitenant/mtinfopb/info.go:64]: Also note that this "new service mode" isn't all that new: we started adding it back in back in https://github.com/cockroachdb/cockroach/pull/117677.

Comment (msbutler) [reply pkg/multitenant/mtinfopb/info.go:64]: Ah, thanks for the context.

**Review by dt — APPROVED** [review]
> V222

... 

> January 2025

😭

File: pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go [hunk 2]
```diff
@@ -406,36 +407,34 @@ func (a *Authorizer) getMode(
 
 	// If the mode is "on", we need to check the capabilities. Are they
```
Comment (msbutler) [inline pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go:408]: nit: stale comment

**Review by msbutler — APPROVED** [review]

**Review by shubhamdhama — APPROVED** [review]

**Comment by stevendanna** [comment]
bors r=dt,msbutler,shubhamdhama
