### PR TITLE
roachtest: fix single node sysbench setup

### LINKED ISSUE #139024: roachtest: sysbench/oltp_insert/nodes=1/cpu=32/conc=64 failed
roachtest.sysbench/oltp_insert/nodes=1/cpu=32/conc=64 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/18490544?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/18490544?buildTab=artifacts#/sysbench/oltp_insert/nodes=1/cpu=32/conc=64) on master @ [097438ac38e411b0fde101ebcae5cf97a798d1db](https://github.com/cockroachdb/cockroach/commits/097438ac38e411b0fde101ebcae5cf97a798d1db):

```
(monitor.go:149).Wait: monitor failure: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/sysbench/oltp_insert/nodes=1/cpu=32/conc=64/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=32</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-18490544/sysbench-oltp-insert-nodes-1-cpu-32-conc-64/1736862646143/1736862797855)

</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sysbench/oltp_insert/nodes=1/cpu=32/conc=64.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

### PR DESCRIPTION
**Pull request by DarrylWong**
The single node setup was accidentally using HAProxy for the prepare step, causing it to silently fail and segfault later on. Since segfaults are an ignored error, the single node tests were silently failing.

Fixes: https://github.com/cockroachdb/cockroach/issues/139024
Epic: none
Release note: none

### CODE REVIEW

**Comment by DarrylWong** [comment]
Kicked off a some sysbench runs here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/18496503?hideProblemsFromDependencies=false&hideTestsFromDependencies=false

File: pkg/cmd/roachtest/tests/sysbench.go [hunk 1]
```diff
@@ -185,12 +185,21 @@ func runSysbench(ctx context.Context, t test.Test, c cluster.Cluster, opts sysbe
 	var start time.Time
 	runWorkload := func(ctx context.Context) error {
 		t.Status("preparing workload")
-		c.Run(ctx, option.WithNodes(c.WorkloadNode()), opts.cmd(true /* haproxy */)+" prepare")
+		cmd := opts.cmd(useHAProxy /* haproxy */)
+		result, err := c.RunWithDetailsSingleNode(ctx, t.L(), option.WithNodes(c.WorkloadNode()), cmd+" prepare")
+		if err != nil {
+			return err
+		} else if strings.Contains(result.Stdout, "FATAL") {
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/tests/sysbench.go:192]: Think this should be okay to do, looks like sysbench [doesn't do any retry logic](https://github.com/akopytov/sysbench/blob/de18a036cc65196b1a4966d305f33db3d8fa6f8e/src/lua/oltp_common.lua#L90-L93) so if we get just one FATAL we know setup for sure failed.

**Review by srosenberg — APPROVED** [review]

**Comment by DarrylWong** [comment]
Ah, looks like this is a [brand new regression from yesterday](https://github.com/cockroachdb/cockroach/commit/9a261a669ca969557531061467539b202ffb08df). 😅 Phew, thought that it had been silently failing ever since we turned on secure clusters.

TFTR!

bors r=srosenberg

**Comment by srosenberg** [comment]
> Ah, looks like this is a [brand new regression from yesterday](https://github.com/cockroachdb/cockroach/commit/9a261a669ca969557531061467539b202ffb08df). 😅 Phew, thought that it had been silently failing ever since we turned on secure clusters.
> 

Nice! I was also a bit terrified, but the failure is conditional on sysbench segfaulting, which we know is a rare occurrence.

**Comment by DarrylWong** [comment]
looks like the bors batch crashed

bors retry

**Comment by tbg** [comment]
My bad - thank you for catching this!
