### PR TITLE
sql: Fix mutex leak within TestCheckConstraintDropAndColumn

### LINKED ISSUE #107433: potential mutex leaks
While writing a custom linter for [1], I added a naive check for potential mutex leaks. Despite a high number of false positives, the full set was small enough to perform a manual audit,

```
wc -l ~/leaked_mutex.txt
      40 /Users/srosenberg/leaked_mutex.txt
```

After inspecting the code, the following appear to be true positives,

```
/Users/srosenberg/workspace/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2927:4
lock "ex.mu" may have leaked at /Users/srosenberg/workspace/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:3189:4
lock "jobControlMu" may have leaked at /Users/srosenberg/workspace/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer_test.go:7011:6
lock "jobControlMu" may have leaked at /Users/srosenberg/workspace/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer_test.go:7298:6
lock "ex.mu" may have leaked at 
```

In `conn_executor`, `ex.mu.Lock()` is not released upon error [2]. According to FSM, `eventNonRetriableErr` doesn't change state, which suggests a deadlock is possible?

In `TestDropColumnAfterMutations` (and in `TestCheckConstraintDropAndColumn`), `jobControlMu` is not released upon error [3]. If resume is retried, a deadlock will occur. Note, the test is currently skipped due to being "flaky" [4]. It's not immediately clear if the observed leaked goroutine is related.

[1] https://github.com/cockroachdb/cockroach/issues/105366#issuecomment-1647159766
[2] https://github.com/cockroachdb/cockroach/blob/d293bb3acd9b7f67ac793ddb6a0836e637864629/pkg/sql/conn_executor.go#L2924-L2928
[3] https://github.com/cockroachdb/cockroach/blob/d293bb3acd9b7f67ac793ddb6a0836e637864629/pkg/sql/schema_changer_test.go#L7008-L7011
[4] https://github.com/cockroachdb/cockroach/issues/76843

Jira issue: CRDB-30040

### PR DESCRIPTION
**Pull request by rimadeodhar**
The test does not unlock the jobControlMu mutex in the case of an error. This PR fixes that.

Epic: none
Fixes: https://github.com/cockroachdb/cockroach/issues/107433
Release note: none

### CODE REVIEW

File: pkg/sql/schema_changer_test.go [hunk 1]
```diff
@@ -7006,6 +7006,7 @@ func TestCheckConstraintDropAndColumn(t *testing.T) {
 				jobControlMu.Lock()
 				scJob, err := s.JobRegistry().(*jobs.Registry).LoadJob(ctx, jobID)
 				if err != nil {
+					jobControlMu.Unlock()
```
Comment (chrisseto) [inline pkg/sql/schema_changer_test.go:7009]: nit: consider adding a quick note about the usage of the mutex below? At first glance, I was confused about why this wasn't a `defer jobControlMu.Unlock()`.

**Review by chrisseto — APPROVED** [review]
LGTM!

File: pkg/sql/schema_changer_test.go (hunk 1 above)
Comment (rimadeodhar) [reply pkg/sql/schema_changer_test.go:7014]: Done.

**Comment by rimadeodhar** [comment]
TFTR

bors r+
