### PR TITLE
cli,server: produce JDBC-compatible connection URLs

### LINKED ISSUE #35998: cli: passwords with special characters cannot be passed in URL
**Describe the problem**

@vilterp @mberhault @nstewart

The managed console has a model that shows a `cockroach` command that lets the user connect securely to their cluster. Here is an example command, with a fake password:

> cockroach sql --url 'postgres://josh:password>@aws-us-east-1.laughing-ladybug.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&sslrootcert=/Users/josh/Downloads/laughing-ladybug-ca.crt'

If your password has special characters in it (e.g. ">"), the cmd fails. I used a password manager to generate my password, and so it had five or so different special characters in it. The error message looks like this:

> Error: invalid argument "postgres://josh:password>@aws-us-east-1.laughing-ladybug.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&sslrootcert=/Users/josh/Downloads/laughing-ladybug-ca.crt" for "--url" flag: parse postgres://josh:password>@aws-us-east-1.laughing-ladybug.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&sslrootcert=/Users/josh/Downloads/laughing-ladybug-ca.crt: net/url: invalid userinfo
Failed running "sql"

It works with psql tho:

> psql 'postgres://josh:password>@aws-us-east-1.laughing-ladybug.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&sslrootcert=/Users/josh/Downloads/laughing-ladybug-ca.crt'

`cockroach` works if you don't put the password in the URL; `cockroach` then prompts you for a password and there seems to be no issue even with special characters.

On the managed side, we are gonna work around this issue by not including the password in the `cockroach` command we display to users. Perhaps we should fix the broader issue tho.

Nate found the following issue on stackoverflow:

https://stackoverflow.com/questions/48671938/go-url-parsestring-fails-with-certain-user-names-or-passwords

The issue looks relevant. Could we call url.QueryEscape()?

**To Reproduce**

Connect to cluster with `cockroach` command with special character such as ">" in password part of connection URL. e.g.:

> cockroach sql --url 'postgres://josh:password>@aws-us-east-1.laughing-ladybug.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&sslrootcert=/Users/josh/Downloads/laughing-ladybug-ca.crt'

**Expected behavior**

Ideally this would work without requiring user to escape the password. At the very least the error message could be clearer.

**Environment:**

> $ cockroach version
Build Tag:    v2.1.5
Build Time:   2019/02/19 16:35:28
Distribution: CCL
Platform:     darwin amd64 (x86_64-apple-darwin18.2.0)
Go Version:   go1.11.5
C Compiler:   4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)
Build SHA-1:  1634c6bbf48d82ef8994386f29750c9dc3f6163a
Build Type:   release

### LINKED ISSUE #63962: Add JDBC URL to connection parameters list printed by "cockroach demo"
It would be helpful to have a JDBC URL to paste into a local Java program for testing.

### PR DESCRIPTION
**Pull request by knz**
Fixes #63962. 
Fixes #35998.
cc @cockroachdb/server 

This PR contains a batch of changes related to the production and handling of connection strings (URLs) inside CockroachDB.

Salient changes:

- ensure a database name is always included in the URL (better compatibility with JDBC)
- new sub-command `cockroach convert-url` to convert a connection URL between libpq and JDBC format (example below)
- the libpq-compatible and JDBC URLs are now printed side-by-side by `cockroach start` and `cockroach demo`.

Example output for `cockroach convert-url`:
image

Example output for `cockroach start`:
```
sql:                 postgresql://root@kenax:26257/defaultdb?sslmode=disable
sql (JDBC):          jdbc:postgresql://kenax:26257/defaultdb?sslmode=disable&user=root
```

Example output for `cockroach demo`:

```
#   (sql)      postgresql://demo:demo64277@127.0.0.1:26257/movr?sslmode=require
#   (sql/jdbc) jdbc:postgresql://127.0.0.1:26257/movr?password=demo64277&sslmode=require&user=demo
```

### CODE REVIEW

**Comment by bdarnell** [comment]
Neat - I was just testing this and didn't realize that jdbc supported username/password in query parameters (I assumed the lack of support for the `user:password@` was them taking a stance against putting passwords in urls at all). However, we need to test this to make sure it's supported by other drivers too. From a quick glance at the code I don't think that the javascript pg driver will work with this url. (I have a testbed for this and can confirm later). 

> This increases compatibility with more drivers and handles special
characters properly.

The handling of special characters varies by driver - python/psycopg2 is a stickler for correct url encoding even in query parameters where there is no ambiguity.

**Comment by knz** [comment]
> The handling of special characters varies by driver - python/psycopg2 is a stickler for correct url encoding even in query parameters where there is no ambiguity.

My point is more that Go's `url.Encode` function doesn't properly urlencode characters in the password field before `@`, but does properly urlencode the query arguments.

File: pkg/cli/demo_cluster.go [hunk 1]
```diff
@@ -883,29 +893,26 @@ func generateCerts(certsDir string) (err error) {
...
-	serverIdx int, gen workload.Generator, includeAppName bool,
+	serverIdx int, includeAppName bool,
 ) (string, error) {
 	options := url.Values{}
 	if includeAppName {
 		options.Add("application_name", catconstants.ReportableAppNamePrefix+"cockroach demo")
 	}
 	sqlURL := url.URL{
-		Scheme: "postgres",
+		Scheme: "postgresql",
```
Comment (rafiss) [inline pkg/cli/demo_cluster.go:903]: would it be worth introducing a `const PostgreSQLScheme = "postgresql"` somewhere so that all these url builders can refer to the same thing?

(btw, i hope there aren't any drivers out there that only accept `postgres` and not `postgresql`. i haven't been able to find one yet)

**Review by rafiss — APPROVED** [review]

**Review by rafiss — COMMENTED** [review]
oh,, just saw Ben's comment. confirmed that with the `node-postgres` driver (JS) the connection string `postgresql://localhost:26257/defaultdb?sslmode=disable&user=root`

results in 
```
error: password authentication failed for user rafiss
    at Connection.parseE (/Users/rafiss/scratch/node_modules/pg/lib/connection.js:567:11)
    at Connection.parseMessage (/Users/rafiss/scratch/node_modules/pg/lib/connection.js:391:17)
```
(username is not picked up)

**Comment by knz** [comment]
@rafiss can you try `postgresql://root@localhost:26257/defaultdb?sslmode=disable&user=root` ?

i.e. pass the username both before @ and in the query args

**Comment by knz** [comment]
looking at the node-postgres docs I think it won't work. maybe we need the two urls side-by-side.

**Comment by rafiss** [comment]
confirmed -- `postgresql://root@localhost:26257/defaultdb?sslmode=disable&user=root` works with `node-postgres`

> maybe we need the two urls side-by-side.

I think this might be the best approach for resolving this issue -- show the existing URL and a "JDBC friendly URL." though for both of these URLs, using a scheme of `postgresql` instead of `postgres` seems better

---

this may be an aside, but one more bit of trivia to be aware of: some ORMs use the URL scheme to decide which _ORM_ adapter/dialect to use. for example, sqlalchemy and typeorm need you to use a URL like `cockroachdb://root@localhost:26257/defaultdb?sslmode=disable` in order for them to work properly with CRDB. (ORMs usually also usually let you configure each property one by one and not use a URL at all)

**Comment by emily-horing** [comment]
@knz just making sure I understand correctly, this is adding another option for formatting the url to work better with certain tools, but using `username:password` would still work, correct? So for example if I already had a connection up between my app and CRDB I would not have to make any changes?

**Comment by knz** [comment]
Emily, yes.

**Comment by knz** [comment]
Emily, what this work is revealing though is that some client tools need one URL and some other tools need another. 

So for your work I think it will be useful to present two different URLs in the "connection string" tab in CC. The first one would be the current one, and the one under it would be "for Java/JDBC applications".

**Comment by emily-horing** [comment]
Agreed, I think medium-term we need to iron out how everything we present in the UI can be just copy/pastable for the user with minimal input. For now we will rely a bit more on docs though and direct users to find the exact code snippets there as we figure out designs.

**Comment by knz** [comment]
RFAL: See the updated PR description at the top for a summary.

I have reworked the PR entirely. There is now a new package `pgurl` that handles the various URL formats, consistently across all the parts of CockroachDB that use URLs. Both JDBC and libpq-compatible URLs are now displayed side-by-side.

File: pkg/cli/demo_cluster.go (hunk 1 above)
Comment (knz) [reply pkg/cli/demo_cluster.go]: Done.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65460)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @emily-horing, and @knz)

___
*[pkg/server/pgurl/testdata/url, line 14 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65460#-Mab2HDf7ufUQDHAxiar:-Mab2HDgDje_-8gKf48_:bmtaqq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/18f2fb3a5af285e09aeab2d55d6b7d8e44a9bef2/pkg/server/pgurl/testdata/url#L14)):*
> ```
> # Empty host.
> url
> postgres:///somedb
> ```

do other tools really treat empty fields like this as valid? that's a bit surprising to me. it seems like it would be fine if we were more restrictive, but i suppose it's nice to support as much as we can as long as it's standard

(i had a similar thought for a case below that has a username but empty password)

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65460)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @emily-horing, and @rafiss)

___
*[pkg/server/pgurl/testdata/url, line 14 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65460#-Mab2HDf7ufUQDHAxiar:-MacmFLU5N6u98vo3i0D:b-gad8uh) ([raw file](https://github.com/cockroachdb/cockroach/blob/18f2fb3a5af285e09aeab2d55d6b7d8e44a9bef2/pkg/server/pgurl/testdata/url#L14)):*
> it would be fine if we were more restrictive

that is possibly the case, but I'm coming to this from the other end - the omitted fields syntax was allowed by previous versions of cockroachdb, and I'm generally shy of removing functionality.

> a username but empty password

that, on the other hand, seems like a legitimate use case. Why do you find this surprising?

**Comment by knz** [comment]
I have rebased this and fixed all problems that had been detected by tests (hopefully).

Is this PR still relevant? If so would appreciate another look.

**Review by rafiss — APPROVED** [review]
this looks good to me!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65460#-:-MbOK0Tm9VP6WuRCHu_1:b-2bm22q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @emily-horing, and @knz)

___
*[pkg/server/pgurl/testdata/url, line 14 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65460#-Mab2HDf7ufUQDHAxiar:-MbOJYEM3gSS3ds5r5CZ:be4i4od) ([raw file](https://github.com/cockroachdb/cockroach/blob/18f2fb3a5af285e09aeab2d55d6b7d8e44a9bef2/pkg/server/pgurl/testdata/url#L14)):*
>  the omitted fields syntax was allowed by previous versions of cockroachdb, and I'm generally shy of removing functionality.

makes sense

> username but empty password

i was just surprised that a username followed by a colon followed by nothing worked, but it does make sense as a use case

**Comment by knz** [comment]
TFYR!

bors r=rafiss

**Comment by knz** [comment]
build failed due to fastly outage

**Comment by knz** [comment]
bors r=rafiss

**Comment by knz** [comment]
@rafiss do we need this backported to 21.1?

**Comment by rafiss** [comment]
The new URL info would be helpful. A backport would be nice, though it doesn't seem like these changes satisfy the "Patches should change as little code as possible" condition in our backport policy. So if you feel like the code changes are risky, then I am fine without the backport.

**Comment by knz** [comment]
yes, if we want to backport this we'll need a higher level of scrutiny.

we can de-risk it by creating a smaller PR which only uses the new `pgurl` package to print out the URL but keeps the previous code alongside it (i.e. accept code duplication in 21.1).

Both options would require more work hours than a regular backport, so I'd rather only do it if we have clear demand.

**Comment by rafiss** [comment]
Let's not backport then. Thanks for your work here!
