### PR TITLE
kvserver: skip TestVoterRemovalWithoutDemotion under race

### LINKED ISSUE #142809: kv/kvserver: TestVoterRemovalWithoutDemotion failed
kv/kvserver.TestVoterRemovalWithoutDemotion [failed](https://tanzanite.cluster.engflow.com/invocations/default/77770f2f-8d1e-40d5-b7f7-aff60804a36e?testReportRun=3&testReportShard=32&testReportAttempt=1#targets-Ly9wa2cva3Yva3ZzZXJ2ZXI6a3ZzZXJ2ZXJfdGVzdA==) on release-25.1.2-rc @ [b43906816caeb28624cc40bb0631ce5e6bd62099](https://github.com/cockroachdb/cockroach/commits/b43906816caeb28624cc40bb0631ce5e6bd62099):

```
      pkg/kv/kvclient/kvcoord/dist_sender.go:1746 +0x101e
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).Send()
      pkg/kv/kvclient/kvcoord/dist_sender.go:1265 +0xa99
  github.com/cockroachdb/cockroach/pkg/kv.lookupRangeFwdScan()
      pkg/kv/range_lookup.go:326 +0x841
  github.com/cockroachdb/cockroach/pkg/kv.RangeLookup()
      pkg/kv/range_lookup.go:201 +0x3d3
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).RangeLookup()
      pkg/kv/kvclient/kvcoord/dist_sender.go:987 +0x546
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/rangecache.(*RangeCache).performRangeLookup()
      pkg/kv/kvclient/rangecache/range_cache.go:983 +0x112
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/rangecache.tryLookupImpl.func1()
      pkg/kv/kvclient/rangecache/range_cache.go:877 +0xc4
  github.com/cockroachdb/cockroach/pkg/util/timeutil.RunWithTimeout()
      pkg/util/timeutil/timeout.go:28 +0x12d
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/rangecache.tryLookupImpl()
      pkg/kv/kvclient/rangecache/range_cache.go:874 +0x1e6
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/rangecache.(*RangeCache).tryLookup.func3()
      pkg/kv/kvclient/rangecache/range_cache.go:772 +0xa4
  github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).doCall.func1()
      pkg/util/syncutil/singleflight/singleflight.go:384 +0x4b
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTask()
      pkg/util/stop/stopper.go:316 +0x246
  github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).doCall()
      pkg/util/syncutil/singleflight/singleflight.go:383 +0x292
  github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).DoChan.gowrap1()
      pkg/util/syncutil/singleflight/singleflight.go:353 +0xc6

Goroutine 5416 (running) created at:
  testing.(*T).Run()
      GOROOT/src/testing/testing.go:1742 +0x825
  testing.runTests.func1()
      GOROOT/src/testing/testing.go:2161 +0x85
  testing.tRunner()
      GOROOT/src/testing/testing.go:1689 +0x21e
  testing.runTests()
      GOROOT/src/testing/testing.go:2159 +0x8be
  testing.(*M).Run()
      GOROOT/src/testing/testing.go:2027 +0xf17
  github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestMain()
      pkg/kv/kvserver/main_test.go:37 +0x184
  main.main()
      bazel-out/k8-fastbuild/bin/pkg/kv/kvserver/kvserver_test_/testmain.go:1764 +0x8f3
  runtime.main()
      GOROOT/src/runtime/proc.go:271 +0x29c
  github.com/cockroachdb/cockroach/pkg/util/parquet.box2DDecoder.decode()
      pkg/util/parquet/decoders.go:175 +0x3b
  github.com/cockroachdb/cockroach/pkg/util/parquet.init.0()
      pkg/util/parquet/decoders.go:402 +0x1d0
==================
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=3</code>
 - <code>shard=32</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestVoterRemovalWithoutDemotion.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-48529

### PR DESCRIPTION
**Pull request by arulajmani**
This test modifies the range descriptor in the proposal filter, which is technically not allowed; see the comment in ReplicaState.Desc which talks about the RangeDescriptor needing to be immutable. As such, we're susceptible to bening test-only races, as seen in
https://github.com/cockroachdb/cockroach/issues/142809.

Closes #142809

Release note: None

### CODE REVIEW

File: pkg/kv/kvserver/client_raft_test.go [hunk 1]
```diff
@@ -4088,6 +4088,13 @@ func TestVoterRemovalWithoutDemotion(t *testing.T) {
 	defer leaktest.AfterTest(t)()
 	defer log.Scope(t).Close(t)
 
+	// This test modifies the range descriptor in the proposal filter, which is
+	// technically not allowed; see the comment in ReplicaState.Desc which talks
+	// about the RangeDescriptor needing to be immutable. As such, we're
+	// susceptible to bening test-only races, as seen in
```
Comment (kvoli) [inline pkg/kv/kvserver/client_raft_test.go:4094]: nit: benign.

**Review by kvoli — APPROVED** [review]

File: pkg/kv/kvserver/client_raft_test.go (hunk 1 above)
Comment (arulajmani) [reply pkg/kv/kvserver/client_raft_test.go]: Done.

**Review by arulajmani — COMMENTED** [review]
Thanks! 

bors r+
