### PR TITLE
roachtest: disable 4K block size intent resolution test

### LINKED ISSUE #137590: roachtest: perturbation/metamorphic/intents failed
roachtest.perturbation/metamorphic/intents [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_PerturbationNightlyGceBazel/18212032?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_PerturbationNightlyGceBazel/18212032?buildTab=artifacts#/perturbation/metamorphic/intents) on master @ [a653b4e4e6483cec7d65808ba4d55d8c63747a6e](https://github.com/cockroachdb/cockroach/commits/a653b4e4e6483cec7d65808ba4d55d8c63747a6e):

```
(assertions.go:363).Fail: 
	Error Trace:	pkg/cmd/roachtest/tests/perturbation/framework.go:671
	            				pkg/cmd/roachtest/test_runner.go:1314
	            				src/runtime/asm_amd64.s:1695
	Error:      	Should be true
	Test:       	perturbation/metamorphic/intents
	Messages:   	FAILURE: follower-read  : Increase 808160.2636 > 40.0000 BASE: 4.454562ms SCORE: 1h0m0s
	            	
	            	FAILURE: read           : Increase 788425.2170 > 40.0000 BASE: 4.566064ms SCORE: 1h0m0s
	            	
	            	FAILURE: write          : Increase 347611.6089 > 40.0000 BASE: 10.356386ms SCORE: 1h0m0s
(require.go:1950).True: FailNow called
test artifacts and logs in: /artifacts/perturbation/metamorphic/intents/run_1
```

Parameters:
 - <code>acMode=fullNormalElasticRepl</code>
 - <code>arch=amd64</code>
 - <code>blockSize=1024</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=16</code>
 - <code>diskBandwidthLimit=350MiB</code>
 - <code>disks=1</code>
 - <code>encrypted=false</code>
 - <code>fillDuration=10m0s</code>
 - <code>fs=ext4</code>
 - <code>leaseType=leader</code>
 - <code>localSSD=true</code>
 - <code>mem=standard</code>
 - <code>numNodes=12</code>
 - <code>numWorkloadNodes=1</code>
 - <code>perturbationDuration=30m0s</code>
 - <code>ratioOfMax=0.5</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>seed=477832759806050768</code>
 - <code>splits=100</code>
 - <code>ssd=1</code>
 - <code>validationDuration=5m0s</code>
 - <code>vcpu=16</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-18212032/perturbation-metamorphic-intents/1734418808499/1734422188988)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*perturbation/metamorphic/intents.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-45661

### PR DESCRIPTION
**Pull request by andrewbaptist**
With a 4K block size, the intent resolution test will cause unacceptable slowdowns. This commit changes the perturbation/*/intents to only test up to 1024 block sizes.

This also reduces the max perturbation duration to 10 minutes.

Informs: #139187
Informs: #139188
Informs: #137590 
Informs: #135934
Fixes: #137590

Epic: none

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/perturbation/intents.go [hunk 1]
```diff
@@ -33,7 +33,22 @@ func (i intents) setup() variations {
...
 func (i intents) setupMetamorphic(rng *rand.Rand) variations {
-	return i.setup().randomize(rng)
+	v := i.setup()
+	v = v.randomize(rng)
+
+	// TODO(139187): Large block sizes result in a big slowdown when the intents
+	// are written.
+	// TODO(139188): Large block sizes result in a big slowdown when the intents
+	// are resolved.
+	if v.blockSize > 1024 {
```
Comment (pav-kv) [inline pkg/cmd/roachtest/tests/perturbation/intents.go:43]: optional: `v.blockSize = min(v.blockSize, 1024)` for brevity
Same below.

File: pkg/cmd/roachtest/tests/perturbation/intents.go [hunk 2]
```diff
@@ -33,7 +33,22 @@ func (i intents) setup() variations {
 }
 
 func (i intents) setupMetamorphic(rng *rand.Rand) variations {
-	return i.setup().randomize(rng)
+	v := i.setup()
+	v = v.randomize(rng)
+
+	// TODO(139187): Large block sizes result in a big slowdown when the intents
```
Comment (pav-kv) [inline pkg/cmd/roachtest/tests/perturbation/intents.go:39]: nit: `TODO(#139187)`
Passim.

**Review by pav-kv — APPROVED** [review]

File: pkg/cmd/roachtest/tests/perturbation/intents.go (hunk 1 above)
Comment (andrewbaptist) [reply pkg/cmd/roachtest/tests/perturbation/intents.go]: Good idea - I'm going to switch to this style for all of these as it is probably easier to read.

**Comment by andrewbaptist** [comment]
TFTR!

bors r=pav-kv
