### PR TITLE
backupccl: altering backup schedule no longer resumes schedule

### LINKED ISSUE #128995: ALTER BACKUP SCHEDULE should not automatically resume schedules
**Describe the problem**

When running `ALTER BACKUP SCHEDULE` and changing the collection URI or recurrence, the schedules are automatically resumed.

**To Reproduce**

1. Create a backup schedule
2. Pause the schedule
3. Run an `ALTER BACKUP SCHEDULE` that changes either recurrence or collection URI

**Expected behavior**
The paused schedule will not automatically resume. There are situations where the user may want to edit a paused schedule and not necessarily resume it. We already have ‘RESUME SCHEDULE` so this automatic behavior is unnecessary.

Jira issue: CRDB-41322

### PR DESCRIPTION
**Pull request by kev-cao**
Previously, altering a backup schedule's recurrence or collection URI would resume the schedule even if it was paused. As we already have `RESUME SCHEDULE`, this is not necessary and can lead to unexpected surprises for the user. The new behavior is upon altering a paused schedule, the schedules remain paused regardless of if the collection URI or the recurrence is changed.

However, in the event that the collection URI is altered for a pair of active schedules, the incremental will still be paused until a full backup is fully completed.

Fixes: #128995

Epic: None

Release note (backward-incompatible change): Altering a paused backup schedule's recurrence or location no longer resumes the schedule.

### CODE REVIEW

File: pkg/backup/alter_backup_schedule.go [hunk 1]
```diff
@@ -399,13 +399,18 @@ func processRecurrence(
...
+		} else {
+			return incJob.SetSchedule(recurrence)
 		}
 	} else {
-		if err := fullJob.SetSchedule(recurrence); err != nil {
-			return err
+		if fullJob.IsPaused() {
+			fullJob.SetScheduleExpr(recurrence)
+		} else {
+			return fullJob.SetSchedule(recurrence)
```
Comment (msbutler) [inline pkg/backup/alter_backup_schedule.go:413]: nit: rename `SetSchedule` to `SetScheduleAndNextRun`

File: pkg/backup/alter_backup_schedule.go [hunk 2]
```diff
@@ -573,14 +580,18 @@ func processInto(p sql.PlanHookState, spec *alterBackupScheduleSpec, s scheduleD
...
+	incPaused := s.incJob.IsPaused()
 	s.incJob.Pause()
 	s.incJob.SetScheduleStatus("Waiting for initial backup to complete")
 	s.fullArgs.UnpauseOnSuccess = s.incJob.ScheduleID()
 
-	// Kick off a full backup immediately so we can unpause incrementals.
-	// This mirrors the behavior of CREATE SCHEDULE FOR BACKUP.
-	env := sql.JobSchedulerEnv(p.ExecCfg().JobsKnobs())
-	s.fullJob.SetNextRun(env.Now())
+	// If the schedule was not already paused, kick off a full backup immediately
```
Comment (msbutler) [inline pkg/backup/alter_backup_schedule.go:588]: s/if the schedule/if the inc schedule/r

File: pkg/backup/alter_backup_schedule_test.go [hunk 3]
```diff
@@ -194,3 +194,88 @@ func TestAlterBackupScheduleSetsIncrementalClusterID(t *testing.T) {
...
+
+func TestAlterBackupScheduleDoesNotResumePausedSchedules(t *testing.T) {
+	defer leaktest.AfterTest(t)()
+	defer log.Scope(t).Close(t)
+
+	th, cleanup := newAlterSchedulesTestHelper(t, nil)
+	defer cleanup()
+
+	t.Run("standalone paused full backup is not resumed", func(t *testing.T) {
+		rows := th.sqlDB.QueryStr(t,
```
Comment (msbutler) [inline pkg/backup/alter_backup_schedule_test.go:206]: nit: this is a cleaner way to grab the schedule id:
```
var scheduleID int
QueryRow(stmt).Scan(&scheduleID)
```

File: pkg/backup/alter_backup_schedule_test.go [hunk 4]
```diff
@@ -194,3 +194,88 @@ func TestAlterBackupScheduleSetsIncrementalClusterID(t *testing.T) {
...
+			`CREATE SCHEDULE FOR BACKUP INTO 'nodelocal://1/backup/alter-schedule' RECURRING '@daily' FULL BACKUP ALWAYS;`)
+		require.Len(t, rows, 1)
+		scheduleID, err := strconv.Atoi(rows[0][0])
+		require.NoError(t, err)
+
+		th.sqlDB.Exec(t, fmt.Sprintf(`PAUSE SCHEDULE %d;`, scheduleID))
+		th.sqlDB.Exec(
+			t,
+			fmt.Sprintf(
+				`ALTER BACKUP SCHEDULE %d SET RECURRING '@hourly',
```
Comment (msbutler) [inline pkg/backup/alter_backup_schedule_test.go:216]: nit: bind the cmd to a local var so the Exec cmd can be one line.

File: pkg/backup/alter_backup_schedule_test.go [hunk 5]
```diff
@@ -194,3 +194,88 @@ func TestAlterBackupScheduleSetsIncrementalClusterID(t *testing.T) {
...
+SET INTO 'nodelocal://1/backup/alter-schedule-2';`,
+				scheduleID,
+			))
+
+		require.Equal(t, "PAUSED", getScheduleStatus(t, th, scheduleID))
```
Comment (msbutler) [inline pkg/backup/alter_backup_schedule_test.go:221]: check that the recurrence changed?

File: pkg/backup/alter_backup_schedule_test.go [hunk 6]
```diff
@@ -194,3 +194,88 @@ func TestAlterBackupScheduleSetsIncrementalClusterID(t *testing.T) {
...
+	})
+
+	t.Run("paused incremental and full backup pair is not resumed", func(t *testing.T) {
+		rows := th.sqlDB.QueryStr(t,
+			`CREATE SCHEDULE FOR BACKUP INTO 'nodelocal://1/backup-2/alter-schedule' RECURRING '@hourly' FULL BACKUP '@daily';`)
+		require.Len(t, rows, 2)
+		scheduleID1, err := strconv.Atoi(rows[0][0])
```
Comment (msbutler) [inline pkg/backup/alter_backup_schedule_test.go:228]: heh, this may be cleaner than using sqlDB.Query.

File: pkg/backup/alter_backup_schedule_test.go [hunk 7]
```diff
@@ -194,3 +194,88 @@ func TestAlterBackupScheduleSetsIncrementalClusterID(t *testing.T) {
...
+		scheduleID2, err := strconv.Atoi(rows[1][0])
+		require.NoError(t, err)
+
+		th.sqlDB.Exec(t, fmt.Sprintf(`PAUSE SCHEDULE %d;`, scheduleID1))
+		th.sqlDB.Exec(t, fmt.Sprintf(`PAUSE SCHEDULE %d;`, scheduleID2))
+
+		th.sqlDB.Exec(
+			t,
+			fmt.Sprintf(
+				`ALTER BACKUP SCHEDULE %d SET RECURRING '*/30 * * * *',
```
Comment (msbutler) [inline pkg/backup/alter_backup_schedule_test.go:239]: bind cmd to local var

File: pkg/backup/alter_backup_schedule_test.go [hunk 8]
```diff
@@ -194,3 +194,88 @@ func TestAlterBackupScheduleSetsIncrementalClusterID(t *testing.T) {
...
+SET FULL BACKUP '@hourly', SET INTO 'nodelocal://1/backup-2/alter-schedule-2';`,
+				scheduleID1,
+			),
+		)
+
+		require.Equal(t, "PAUSED", getScheduleStatus(t, th, scheduleID1))
+		require.Equal(t, "PAUSED", getScheduleStatus(t, th, scheduleID2))
```
Comment (msbutler) [inline pkg/backup/alter_backup_schedule_test.go:246]: check recurrence?

File: pkg/backup/alter_backup_schedule_test.go [hunk 9]
```diff
@@ -194,3 +194,88 @@ func TestAlterBackupScheduleSetsIncrementalClusterID(t *testing.T) {
...
+	)
+
+	require.Equal(t, "PAUSED", getScheduleStatus(t, th, incSchedID))
+	require.Equal(t, "ACTIVE", getScheduleStatus(t, th, fullSchedID))
+}
+
+func getScheduleStatus(t *testing.T, th *alterSchedulesTestHelper, id int) string {
+	t.Helper()
+	var status string
+	th.sqlDB.QueryRow(t, `SELECT schedule_status FROM [SHOW SCHEDULES] WHERE id=$1`, id).Scan(&status)
```
Comment (msbutler) [inline pkg/backup/alter_backup_schedule_test.go:279]: ah you could easily grab the new recurrence her via `Scan(&status,&recurrence)`

File: pkg/backup/alter_backup_schedule_test.go [hunk 10]
```diff
@@ -194,3 +194,88 @@ func TestAlterBackupScheduleSetsIncrementalClusterID(t *testing.T) {
...
+	require.NoError(t, err)
+	fullSchedID, err := strconv.Atoi(rows[1][0])
+	require.NoError(t, err)
+
+	th.sqlDB.Exec(
+		t,
+		fmt.Sprintf(`ALTER BACKUP SCHEDULE %d SET INTO 'nodelocal://1/backup/alter-schedule-2';`, fullSchedID),
+	)
+
+	require.Equal(t, "PAUSED", getScheduleStatus(t, th, incSchedID))
```
Comment (msbutler) [inline pkg/backup/alter_backup_schedule_test.go:272]: this isn't a change in behavior right?  If, however, the schedules were paused before altering the uri, do they stay paused?

File: pkg/backup/alter_backup_schedule.go [hunk 11]
```diff
@@ -433,9 +438,7 @@ func processFullBackupRecurrence(
 		}
 		// Copy the cadence from the incremental to the full, and delete the
 		// incremental.
-		if err := s.fullJob.SetSchedule(s.incJob.ScheduleExpr()); err != nil {
-			return scheduleDetails{}, err
-		}
+		s.fullJob.SetScheduleExpr(s.incJob.ScheduleExpr())
```
Comment (msbutler) [inline pkg/backup/alter_backup_schedule.go:441]: i'm having a really hard time understanding what `processFullBackupRecurrence` does. I would have expected it to change the `FULL BACKUP crontab`, but it has turned into a dirty kitchen sink. In a follow up pr, could you clean this logic up so mortals can understand what's going on? This clean up work is less important than backup compaction stuff.

**Review by msbutler — COMMENTED** [review]
nice!

File: pkg/backup/alter_backup_schedule_test.go (hunk 10 above)
Comment (kev-cao) [reply pkg/backup/alter_backup_schedule_test.go:272]: > the schedules were paused before altering the uri, do they stay paused?

And yes, they do now with this change

File: pkg/backup/alter_backup_schedule.go (hunk 11 above)
Comment (kev-cao) [reply pkg/backup/alter_backup_schedule.go:441]: Yeah for sure, it's definitely got a lot going on

File: pkg/backup/alter_backup_schedule_test.go (hunk 10 above)
Comment (msbutler) [reply pkg/backup/alter_backup_schedule_test.go:272]: i'd split out this additional test into a separate commit.

File: pkg/backup/alter_backup_schedule_test.go (hunk 3 above)
Comment (kev-cao) [reply pkg/backup/alter_backup_schedule_test.go:206]: If I'm not mistaken, `QueryRow().Scan` requires you to provide a location for every column in the row or else it errors. Although tbh I only did it this way because I copied it from above.

File: pkg/backup/alter_backup_schedule_test.go (hunk 9 above)
Comment (kev-cao) [reply pkg/backup/alter_backup_schedule_test.go:279]: Yup, updated!

File: pkg/backup/alter_backup_schedule_test.go (hunk 10 above)
Comment (kev-cao) [reply pkg/backup/alter_backup_schedule_test.go]: Sounds good, updated!

**Review by msbutler — APPROVED** [review]

**Comment by kev-cao** [comment]
TFTR!

bors r=msbutler
