### PR TITLE
schemachange: speed up slow schema changes

### LINKED ISSUE #47607: sql: add primary key on empty table very slow
**Describe the problem**

discover while trying reproduce #47512

**To Reproduce**

1. start fresh `cockroach start-single-node --insecure` (empty data)
2. create a file `create_users_table.sql` with content follow
```sql
drop table if exists "users" cascade;
create table "users" ("id" uuid not null, "name" varchar(255) not null, "email" varchar(255) not null, "password" varchar(255) not null, "remember_token" varchar(100) null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null, "deleted_at" timestamp(0) without time zone null);
alter table "users" add primary key ("id");
alter table "users" add constraint "users_email_unique" unique ("email");
```
3. run `cockroach sql --insecure < create_users_table.sql`

It take a whooping 30s to add primary key on empty table (╯°□°)╯︵ ┻━┻
```
NOTICE: primary key changes are finalized asynchronously; further schema changes on this table may be restricted until the job completes
ALTER TABLE

Time: 211.001799ms

ALTER TABLE

Time: 30.581253037s
```

**Expected behavior**
Should be much faster since the table is empty.

**Environment:**
 - CockroachDB version
```
Build Tag:    82294d1
Build Time:   2020/04/15 01:47:13
Distribution: CCL
Platform:     linux amd64 (x86_64-pc-linux-gnu)
Go Version:   go1.13.9
C Compiler:   4.2.1 Compatible Clang 3.8.0 (tags/RELEASE_380/final)
Build SHA-1:  82294d100ad1cb26b488f53e7241242d474d58d7
Build Type:   development
```
 - Server OS: ubuntu 20.04 dev
 - Client app `cockroach sql` (same version as server)

### PR DESCRIPTION
**Pull request by spaskob**
Touches #45150.
Fixes #47607.
Touches #47790.

Release note (performance improvement):
Before this a simple schema change could take 30s+.
The reason was that if the schema change is not first
in line in the table mutation queue it would return a
re-triable error and the jobs framework will re-adopt and
run it later. The problem is that the job adoption loop
is 30s.

To repro run this for some time:
```
cockroach sql --insecure --watch 1s -e 'drop table if exists users cascade; create table users (id uuid not null, name varchar(255) not null, email varchar(255) not null, password varchar(255) not null, remember_token varchar(100) null, created_at timestamp(0) without time zone null, updated_at timestamp(0) without time zone null, deleted_at timestamp(0) without time zone null); alter table users add primary key (id); alter table users add constraint users_email_unique unique (email);'
```

Instead of returning on re-triable errors we retry with exponential
backoff in the schema change code. This pattern of dealing with
re-triable errors in client job code is encouraged vs relying on the
registry because the latter leads to slowness and additionally to more
complicated test fixtures that rely on hacking with the internals of the
job registry,

### CODE REVIEW

File: pkg/sql/schema_changer.go [hunk 1]
```diff
@@ -1601,9 +1601,19 @@ func (r schemaChangeResumer) Resume(
...
+			MaxBackoff:     20 * time.Second,
+			Multiplier:     1.5,
+		}
+		var scErr error
+		for r := retry.StartWithCtx(ctx, opts); r.Next(); {
+			scErr = sc.exec(ctx)
+			if scErr == nil {
+				return nil
+			}
 			switch {
```
Comment (ajwerner) [inline pkg/sql/schema_changer.go:1615]: probably cleaner as:

```
switch scErr := sc.exec(ctx); scErr {
case nil:
    return nil
...
```

File: pkg/sql/schema_changer.go [hunk 2]
```diff
@@ -1618,18 +1628,16 @@ func (r schemaChangeResumer) Resume(
...
-				return jobs.NewRetryJobError(err.Error())
+				// including the schema change not having the first mutation in line.
 			default:
 				// All other errors lead to a failed job.
-				return err
+				return scErr
 			}
 		}
-		return nil
+		return jobs.NewRetryJobError(scErr.Error())
```
Comment (ajwerner) [inline pkg/sql/schema_changer.go:1640]: If you're here it probably means that your context was canceled. It's reasonably like that `scErr` is nil here which means this will panic.

File: pkg/sql/schema_changer.go [hunk 3]
```diff
@@ -1601,9 +1601,19 @@ func (r schemaChangeResumer) Resume(
 				return r.job.MakeSessionBoundInternalExecutor(ctx, sd)
 			},
 		}
-		if err := sc.exec(ctx); err != nil {
+		opts := retry.Options{
+			InitialBackoff: 100 * time.Millisecond,
+			MaxBackoff:     20 * time.Second,
+			Multiplier:     1.5,
+		}
+		var scErr error
```
Comment (ajwerner) [inline pkg/sql/schema_changer.go:1609]: I'm not sure it makes sense to retain this across iterations of the loop.

File: pkg/sql/schema_changer.go (hunk 1 above)
Comment (spaskob) [reply pkg/sql/schema_changer.go:1615]: done

File: pkg/sql/schema_changer.go (hunk 3 above)
Comment (spaskob) [reply pkg/sql/schema_changer.go:1609]: no but we need it after we exit the loop to return to registry the last error from the schema change

File: pkg/sql/schema_changer.go (hunk 2 above)
Comment (spaskob) [reply pkg/sql/schema_changer.go:1640]: well if scErr was nil, we would return inside the body of the loop

File: pkg/sql/schema_changer.go (hunk 3 above)
Comment (ajwerner) [reply pkg/sql/schema_changer.go:1613]: Makes sense.

**Review by ajwerner — APPROVED** [review]
LGTM
