### PR TITLE
sql/schemachanger: DROP INDEX could drop unrelated foreign keys

### LINKED ISSUE #107576: schema: can't drop a unique index on a table with the declarative schema changer when its being used to enforce a fk constraint for a column
Consider the following schema:
```sql
-- Create "directus_roles" table
CREATE TABLE "directus_roles"
  (
     "id"              UUID NOT NULL,
     "name"            CHARACTER varying(100) NOT NULL,
     "icon"            CHARACTER varying(30) NOT NULL DEFAULT
     'supervised_user_circle',
     "description"     TEXT NULL,
     "ip_access"       TEXT NULL,
     "enforce_tfa"     BOOLEAN NOT NULL DEFAULT FALSE,
     "module_list"     JSONB NULL,
     "collection_list" JSONB NULL,
     "admin_access"    BOOLEAN NOT NULL DEFAULT FALSE,
     "app_access"      BOOLEAN NOT NULL DEFAULT TRUE,
     PRIMARY KEY ("id")
  );

-- Create "directus_users" table
CREATE TABLE "directus_users"
  (
     "id"          UUID NOT NULL,
     "first_name"  CHARACTER varying(50) NULL,
     "last_name"   CHARACTER varying(50) NULL,
     "email"       CHARACTER varying(128) NOT NULL,
     "password"    CHARACTER varying(255) NULL,
     "location"    CHARACTER varying(255) NULL,
     "title"       CHARACTER varying(50) NULL,
     "description" TEXT NULL,
     "tags"        JSONB NULL,
     "avatar"      UUID NULL,
     "language"    CHARACTER varying(8) NULL DEFAULT 'en-US',
     "theme"       CHARACTER varying(20) NULL DEFAULT 'auto',
     "tfa_secret"  CHARACTER varying(255) NULL,
     "status"      CHARACTER varying(16) NOT NULL DEFAULT 'active',
     "role"        UUID NULL,
     "token"       CHARACTER varying(255) NULL,
     "last_access" TIMESTAMPTZ NULL,
     "last_page"   CHARACTER varying(255) NULL,
     PRIMARY KEY ("id"),
     CONSTRAINT "directus_users_role_foreign" FOREIGN KEY ("role") REFERENCES
     "directus_roles" ("id") ON UPDATE no action ON DELETE no action
  );

-- Create index "directus_users_email_unique" to table: "directus_users"
CREATE UNIQUE INDEX "directus_users_email_unique"
  ON "directus_users" ("email");

-- Create "languages" table
CREATE TABLE "languages"
  (
     "code"    CHARACTER varying(255) NOT NULL,
     "enabled" BOOLEAN NULL DEFAULT TRUE,
     "name"    CHARACTER varying(255) NULL,
     PRIMARY KEY ("code")
  );

-- Create "condition" table
CREATE TABLE "condition"
  (
     "aggregation"  CHARACTER varying(255) NULL,
     "date_created" TIMESTAMPTZ NULL,
     "date_updated" TIMESTAMPTZ NULL,
     "id"           UUID NOT NULL,
     "name"         CHARACTER varying(255) NULL,
     "user_created" UUID NULL,
     "user_updated" UUID NULL,
     PRIMARY KEY ("id"),
     CONSTRAINT "condition_user_created_foreign" FOREIGN KEY ("user_created")
     REFERENCES "directus_users" ("id") ON UPDATE no action ON DELETE no action,
     CONSTRAINT "condition_user_updated_foreign" FOREIGN KEY ("user_updated")
     REFERENCES "directus_users" ("id") ON UPDATE no action ON DELETE no action
  );

-- Create "menu" table
CREATE TABLE "menu"
  (
     "activity"     CHARACTER varying(255) NULL,
     "condition"    UUID NULL,
     "date_created" TIMESTAMPTZ NULL,
     "date_updated" TIMESTAMPTZ NULL,
     "id"           UUID NOT NULL,
     "name"         CHARACTER varying(255) NULL,
     "sort"         INTEGER NULL,
     "status"       CHARACTER varying(255) NOT NULL DEFAULT 'draft',
     "url"          CHARACTER varying(255) NULL,
     "user_created" UUID NULL,
     "user_updated" UUID NULL,
     PRIMARY KEY ("id"),
     CONSTRAINT "menu_condition_foreign" FOREIGN KEY ("condition") REFERENCES
     "condition" ("id") ON UPDATE no action ON DELETE SET NULL,
     CONSTRAINT "menu_user_created_foreign" FOREIGN KEY ("user_created")
     REFERENCES "directus_users" ("id") ON UPDATE no action ON DELETE no action,
     CONSTRAINT "menu_user_updated_foreign" FOREIGN KEY ("user_updated")
     REFERENCES "directus_users" ("id") ON UPDATE no action ON DELETE no action
  );

-- Create "menu_translations" table
CREATE TABLE "menu_translations"
  (
     "icon_antd"      CHARACTER varying(255) NULL,
     "id"             UUID NOT NULL,
     "languages_code" CHARACTER varying(255) NULL,
     "menu_id"        UUID NULL,
     "text"           CHARACTER varying(255) NULL,
     PRIMARY KEY ("id"),
     CONSTRAINT "menu_translations_languages_code_foreign" FOREIGN KEY (
     "languages_code") REFERENCES "languages" ("code") ON UPDATE no action ON
     DELETE SET NULL,
     CONSTRAINT "menu_translations_menu_id_foreign" FOREIGN KEY ("menu_id")
     REFERENCES "menu" ("id") ON UPDATE no action ON DELETE SET NULL
  ); 
```

On 23.1 the following does not work:
```sql
DROP INDEX "directus_users"@"directus_users_email_unique";
```

With error message:

```sql
root@localhost:26257/defaultdb> DROP INDEX "directus_users"@"directus_users_email_unique";
ERROR: "directus_users_email_unique" is referenced by foreign key from table "menu"
SQLSTATE: 2BP01
```

Even though `directus_users` is only referencing the id. If you set:
```sql
SET use_declarative_schema_changer=off;
```

The index is successfully dropped.

Jira issue: CRDB-30114

Epic CRDB-28665

### PR DESCRIPTION
**Pull request by fqazi**
Previously, when DROP INDEX was resolving and iterating over foreign keys, it did not validate that these foreign keys were related to the index we were dropping. As a result, if any table referred back to the target table with the index, we would analyze its foreign keys. If cascade wasn't specified this could incorrectly end up blocking the DROP INDEX on unrelated foreign key references assuming they need our index. Or worse with cascade we could remove foreign key constraints in other tables. To address this, this patch filters the back references to only look at ones related to the target table, which causes the correct set to be analuzed / dropped.

Fixes: #107576

Release note (bug fix): Dropping an index could end up failing or cleaning foreign keys (when CASCADE is specified) on other tables referencing the target table with this index.

### CODE REVIEW

File: pkg/sql/logictest/testdata/logic_test/drop_index [hunk 1]
```diff
@@ -464,3 +464,40 @@ t1_96731    t1_96731_pkey    PRIMARY KEY      PRIMARY KEY (i ASC)  true
 
 statement ok
 DROP TABLE t1_96731, t2_96731;
+
```
Comment (Xiang-Gu) [inline pkg/sql/logictest/testdata/logic_test/drop_index:467]: Can we use an easier-to-understand name for those tables/columns in the logic test? Like we discussed, the following will be minimal repro:
```
create table t1 (i int primary key, j int);
create unique index t1_j_key on t1(j);

create table t3 (j int, i int primary key);
create table t2 (i int primary key, j int, constraint "fk_j_t1_i" foreign key (j) references t1(i), constraint "fk_j_t3_i" foreign key (j) references t3(i);

drop index t1_j_key;
```

Comment (fqazi) [reply pkg/sql/logictest/testdata/logic_test/drop_index:467]: Let me adjust the names a bit, but I'm avoiding t1, etc.. because we get name collisions in these tests

File: pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go [hunk 2]
```diff
@@ -270,15 +270,18 @@ func maybeDropDependentFKConstraints(
...
 				current scpb.Status, target scpb.TargetStatus, e scpb.Element,
 			) {
 				b.Drop(e)
 			})
 	}
 
-	b.BackReferences(tableID).ForEach(func(
+	// Get foreign key back references referring to this table, previous we
+	// did not explicitly filter these out which could lead to us blocking
+	// the DROP INDEX or worse removing unrelated foreign keys.
```
Comment (Xiang-Gu) [inline pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go:283]: Do we want to put the history into the comment here? Maybe just say "Iterate over all FKs inbound to this table and decide whether we should drop them as a result of dropping this uniqueness-providing constraint"

File: pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go [hunk 3]
```diff
@@ -270,15 +270,18 @@ func maybeDropDependentFKConstraints(
 	// dropDependentFKConstraint is a helper function that drops a dependent
 	// FK constraint with ID `fkConstraintID`.
 	dropDependentFKConstraint := func(fkConstraintID catid.ConstraintID) {
-		b.BackReferences(tableID).Filter(hasConstraintIDAttrFilter(fkConstraintID)).
+		b.BackReferences(tableID).Filter(containsDescIDFilter(tableID)).Filter(hasConstraintIDAttrFilter(fkConstraintID)).
```
Comment (Xiang-Gu) [inline pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go:273]: I don't think this is necessary(?) since we already filtered FKs earlier (below) to only drop FKs inbound to this table.

Comment (fqazi) [reply pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go:273]: Since we are getting back-references again, isn't there a danger of accidentally operating on the wrong table with the same constraint ID? I think this might be too relaxed still actually

File: pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go (hunk 2 above)
Comment (fqazi) [reply pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go:283]: Good point. I'll simplify this to:

Iterate over all FKs inbound to this table and decide whether any other unique constraints will satisfy them if we were to drop the current unique constraint.

File: pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go (hunk 3 above)
Comment (Xiang-Gu) [reply pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go]: that's a good point! Yes, we should filter by descID

**Review by Xiang-Gu — APPROVED** [review]

**Comment by fqazi** [comment]
@Xiang-Gu TFTR!

bors r+

**Review by rafiss — COMMENTED** [review]
thanks for the fix! one thing i was wondering is why did this change not affect any of the plans in the `scplan` tests? shouldn't we see that the plans for DROP INDEX has changed?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107633#-:-NaNE5bP-LO7W40w4gOw:b-lkx61z)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @Xiang-Gu)
