### PR TITLE
backupccl: handle sequence ownership remapping logic for restore

### LINKED ISSUE #50781: sql: sequence owner dependencies are poorly handled in BACKUP/RESTORE
It looks like restoring tables or sequences with OWNED BY relationship can lead to broken dependencies. For example, if you restore a table which is a sequence owner but its owned sequence no longer exists, this prevents dropping the table.
```
root@:26257/defaultdb> create database d1;
root@:26257/defaultdb> create database d2;
root@:26257/defaultdb> create table d1.t (x int);
root@:26257/defaultdb> create sequence d2.s owned by d1.t.x;
root@:26257/defaultdb> backup database d1 to 'nodelocal://self/d1';
root@:26257/defaultdb> drop database d1 cascade;
root@:26257/defaultdb> drop sequence d2.s;
root@:26257/defaultdb> restore database d1 from 'nodelocal://self/d1';
root@:26257/defaultdb> drop table d1.t;
ERROR: table is being dropped
```
I think we need to handle this the same way we do other [dependencies](https://www.cockroachlabs.com/docs/stable/backup.html#object-dependencies) like foreign keys: if a user tries to restore a sequence owner and the owned sequence no longer exists, the restore should error out. We can also add a `skip_missing_sequence_owners` flag which lets the user skip adding the missing dependency.

### PR DESCRIPTION
**Pull request by arulajmani**
Previously, we would restore sequence descriptors/table descriptors as
is, without remapping the ownership dependency to the new IDs. This
meant sequence ownership was broken post restore. This PR fixes that.

When sequences with owners or tables that have columns that own
sequences are restored:
- If both the owned sequence and the owning table are being restored,
the ownership is remapped.
- If just the sequence is restored, the user receives an error to use
the `skip_missing_sequence_owners` flag. If the flag is provided, the
sequence is restored without any owner.
- If just the table is restored, the user receives an error to use the
`skip_missing_sequence_owners` flag. If the flag is provided, the table
is restored with the table column that previously owned the sequence no
longer owning that sequence.

Fixes #50781

Release note (enterprise change): Restore now has a new option
`skip_missing_sequence_owners` that must be supplied when restoring
only the table/sequence that was previously
a sequence owner/owned by a table.
Additionally, this fixes a bug where ownership relationships would not
be remapped after a restore.

### CODE REVIEW

File: pkg/ccl/backupccl/backup_test.go [hunk 1]
```diff
@@ -3616,6 +3616,174 @@ func TestBackupRestoreSequence(t *testing.T) {
...
+
+		newDB := sqlutils.MakeSQLRunner(tc.Conns[0])
+		kvDB := tc.Server(0).DB()
+		newDB.Exec(t, `CREATE DATABASE d`)
+		newDB.Exec(t, `USE d`)
+		newDB.ExpectErr(t, `pq: cannot restore sequence "seq" without referenced owner`,
+			`RESTORE TABLE seq FROM $1`, backupLoc)
+
+		newDB.Exec(t, `RESTORE TABLE seq FROM $1 WITH skip_missing_sequence_owners`, backupLoc)
+		seqDesc := sqlbase.TestingGetTableDescriptor(kvDB, keys.SystemSQLCodec, "d", "seq")
```
Comment (rohany) [inline pkg/ccl/backupccl/backup_test.go:3680]: So why do we allow this? aren't things just busted at this point?

File: pkg/ccl/backupccl/backup_test.go [hunk 2]
```diff
@@ -3616,6 +3616,174 @@ func TestBackupRestoreSequence(t *testing.T) {
...
+	backupLocD2 := LocalFoo + `/d2`
+	backupLocD3 := LocalFoo + `/d3`
+	// Setup for sequence ownership backup/restore tests in the same database.
+	origDB.Exec(t, `CREATE DATABASE d`)
+	origDB.Exec(t, `CREATE TABLE d.t(a int)`)
+	origDB.Exec(t, `CREATE SEQUENCE d.seq OWNED BY d.t.a`)
+	origDB.Exec(t, `BACKUP DATABASE d TO $1`, backupLoc)
+
+	// Setup for cross-database ownership backup-restore tests.
+	origDB.Exec(t, `CREATE DATABASE d2`)
```
Comment (rohany) [inline pkg/ccl/backupccl/backup_test.go:3636]: Would it be clearer to do this initialization closer to the tests that use them?

File: pkg/ccl/backupccl/backup_test.go [hunk 3]
```diff
@@ -3616,6 +3616,174 @@ func TestBackupRestoreSequence(t *testing.T) {
...
+
+	origDB.Exec(t, `CREATE SEQUENCE d2.seq OWNED BY d3.t.a`)
+
+	origDB.Exec(t, `CREATE SEQUENCE d3.seq OWNED BY d2.t.a`)
+	origDB.Exec(t, `CREATE SEQUENCE d3.seq2 OWNED BY d3.t.a`)
+
+	origDB.Exec(t, `BACKUP DATABASE d2 TO $1`, backupLocD2)
+	origDB.Exec(t, `BACKUP DATABASE d3 TO $1`, backupLocD3)
+
+	t.Run("test sequence owned by table in the same database", func(t *testing.T) {
```
Comment (rohany) [inline pkg/ccl/backupccl/backup_test.go:3650]: Overall, I'd like to see a few more comments on these tests -- like what are we trying to do, what should we see etc.

File: pkg/ccl/backupccl/backup_test.go [hunk 4]
```diff
@@ -3616,6 +3616,174 @@ func TestBackupRestoreSequence(t *testing.T) {
...
+			t.Fatal("unexpected/no sequence owner after restore")
+		}
+
+		if len(tableDesc.GetColumns()[0].OwnsSequenceIds) != 1 ||
+			tableDesc.GetColumns()[0].OwnsSequenceIds[0] != seqDesc.ID {
+			t.Fatal("unexpected/no sequence owned by column")
+		}
+	})
+
+	t.Run("test restoring two databases removes cross-database ownership dependency",
```
Comment (rohany) [inline pkg/ccl/backupccl/backup_test.go:3748]: This is really counterintuitive, but I guess any sort of cross database reference handling is strange.

**Review by rohany — COMMENTED** [review]
Overall this LGTM, but paul should take a look

File: pkg/ccl/backupccl/backup_test.go (hunk 4 above)
Comment (pbardea) [reply pkg/ccl/backupccl/backup_test.go:3748]: I'm not sure that it's super odd since that during the first restore you'd be explicitly removing the dependency.

I would like to see some tests restoring both databases at the same time and ensuring that the dependency is still there.

File: pkg/ccl/backupccl/backup_test.go [hunk 5]
```diff
@@ -3616,6 +3616,174 @@ func TestBackupRestoreSequence(t *testing.T) {
...
+		func(t *testing.T) {
+			tc := testcluster.StartTestCluster(t, singleNode, base.TestClusterArgs{ServerArgs: args})
+			defer tc.Stopper().Stop(context.Background())
+
+			newDB := sqlutils.MakeSQLRunner(tc.Conns[0])
+			kvDB := tc.Server(0).DB()
+
+			newDB.ExpectErr(t, `pq: cannot restore`,
```
Comment (pbardea) [inline pkg/ccl/backupccl/backup_test.go:3756]: Can we expand the error message here (and below) to be `pq: cannot restore sequence` to have more confidence that we're hitting the right error.

File: pkg/ccl/backupccl/backup_test.go (hunk 1 above)
Comment (pbardea) [reply pkg/ccl/backupccl/backup_test.go:3680]: Hmm, why would things be busted? I guess I'm confused at what the expected behavior of a sequence that had its owner removed is? I'd expect this would have the same effect as `ALTER SEQUENCE d.seq OWNED BY NONE`, which (naively) seems fine

File: pkg/ccl/backupccl/backup_test.go [hunk 6]
```diff
@@ -3616,6 +3616,174 @@ func TestBackupRestoreSequence(t *testing.T) {
...
+
+			seqDesc := sqlbase.TestingGetTableDescriptor(kvDB, keys.SystemSQLCodec, "d3", "seq")
+			if seqDesc.SequenceOpts.HasOwner() {
+				t.Fatal("unexpected sequence owner after restore")
+			}
+
+			// Sequence dependencies inside the database should still be preserved.
+			sd := sqlbase.TestingGetTableDescriptor(kvDB, keys.SystemSQLCodec, "d3", "seq2")
+			td := sqlbase.TestingGetTableDescriptor(kvDB, keys.SystemSQLCodec, "d3", "t")
+			if !sd.SequenceOpts.HasOwner() || sd.SequenceOpts.SequenceOwner.OwnerTableID != td.ID {
```
Comment (pbardea) [inline pkg/ccl/backupccl/backup_test.go:3777]: Maybe we could do:
```
require.True(t, sd.SequenceOpts.HasOwner())
require.Equal(t, td.ID, sd.SequenceOpts.SequenceOwner.OwnerTableID)
```
so that if this test fails, it's a bit clearer what is going wrong (same elsewhere in the tests).

File: pkg/ccl/backupccl/backup_test.go [hunk 7]
```diff
@@ -3616,6 +3616,174 @@ func TestBackupRestoreSequence(t *testing.T) {
...
+	args := base.TestServerArgs{ExternalIODir: dir}
+
+	backupLoc := LocalFoo + `/d`
+	backupLocD2 := LocalFoo + `/d2`
+	backupLocD3 := LocalFoo + `/d3`
+	// Setup for sequence ownership backup/restore tests in the same database.
+	origDB.Exec(t, `CREATE DATABASE d`)
+	origDB.Exec(t, `CREATE TABLE d.t(a int)`)
+	origDB.Exec(t, `CREATE SEQUENCE d.seq OWNED BY d.t.a`)
+	origDB.Exec(t, `BACKUP DATABASE d TO $1`, backupLoc)
```
Comment (pbardea) [inline pkg/ccl/backupccl/backup_test.go:3633]: Could we also add a test where we restore all tables back into a different database on the same cluster: something like `CREATE DATABASE restore_db; RESTORE d.* FROM $1 WITH into_db='restore_db';` and check that the dependency still holds.

**Review by pbardea — COMMENTED** [review]
Thanks for grabbing this! Implementation generally looks good - just left a few test related comments.

**Review by arulajmani — COMMENTED** [review]
TFTRs! This should be RFAL 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50949#-:-MB_xw2Q-U9wFNn_rG3f:b-darw0k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea and @rohany)

___
*[pkg/ccl/backupccl/backup_test.go, line 3633 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50949#-MBGsVb18Cpwh5ltQDdr-r1-3633:-MB_kBk19Tku-92tiCL3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fc943ee4302722da04bd7f7f5e51d78a22ef342/pkg/ccl/backupccl/backup_test.go#L3633)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Could we also add a test where we restore all tables back into a different database on the same cluster: something like `CREATE DATABASE restore_db; RESTORE d.* FROM $1 WITH into_db='restore_db';` and check that the dependency still holds.
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/backup_test.go, line 3636 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50949#-MBGsVb18Cpwh5ltQDdr-r1-3636:-MB_i_4QC9KmPHTI2WZm:b-om0ld2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fc943ee4302722da04bd7f7f5e51d78a22ef342/pkg/ccl/backupccl/backup_test.go#L3636)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Would it be clearer to do this initialization closer to the tests that use them?
</blockquote></details>

Moved down.
___
*[pkg/ccl/backupccl/backup_test.go, line 3650 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50949#-MBGsVb18Cpwh5ltQDdr-r1-3650:-MB_kD1lAZdnUzZoIUos:b-j0u2ul) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fc943ee4302722da04bd7f7f5e51d78a22ef342/pkg/ccl/backupccl/backup_test.go#L3650)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Overall, I'd like to see a few more comments on these tests -- like what are we trying to do, what should we see etc.
</blockquote></details>

Added comment up top for all tests. 
___
*[pkg/ccl/backupccl/backup_test.go, line 3680 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50949#-MBGsVb18Cpwh5ltQDdr-r1-3680:-MB_PLY_CjwT-HOGAOAB:bovpinr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fc943ee4302722da04bd7f7f5e51d78a22ef342/pkg/ccl/backupccl/backup_test.go#L3680)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Hmm, why would things be busted? I guess I'm confused at what the expected behavior of a sequence that had its owner removed is? I'd expect this would have the same effect as `ALTER SEQUENCE d.seq OWNED BY NONE`, which (naively) seems fine
</blockquote></details>

I don't think things are busted if the owner table doesn't exist. A sequence that is owned by a table can be used by another table as well -- so I don't think it's correct to not allow restoring sequences which have owners when the owner is not being restored. 

Currently, passing the `skip_missing_sequence_owners` option will have the same effect as `ALTER SEQUENCE d.seq OWNED BY NONE`. This seems fine to me if we document what `skip_missing_sequence_owners` does. 
___
*[pkg/ccl/backupccl/backup_test.go, line 3748 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50949#-MBGsVb18Cpwh5ltQDdr-r1-3748:-MB_RsxG58gF6z4bzbar:b3kg08m) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fc943ee4302722da04bd7f7f5e51d78a22ef342/pkg/ccl/backupccl/backup_test.go#L3748)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I'm not sure that it's super odd since that during the first restore you'd be explicitly removing the dependency.

I would like to see some tests restoring both databases at the same time and ensuring that the dependency is still there.
</blockquote></details>

This follows how we handle FK cross database references. Added a test to restore both dbs at the same time.
___
*[pkg/ccl/backupccl/backup_test.go, line 3756 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50949#-MBGsVb18Cpwh5ltQDdr-r1-3756:-MB_SKzSCS4nlx63u0qY:b4ph9hn) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fc943ee4302722da04bd7f7f5e51d78a22ef342/pkg/ccl/backupccl/backup_test.go#L3756)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Can we expand the error message here (and below) to be `pq: cannot restore sequence` to have more confidence that we're hitting the right error.
</blockquote></details>

I had that earlier, but it seems that there isn't a deterministic way to know what is restored first -- the table or the sequence. As both the databases contain a sequence and a table with ownership dependencies, depending on what is processed first the error will be different. 

I do agree that it'd be nice to have confidence we're hitting the correct error message, but not sure how we can do it deterministically. 
___
*[pkg/ccl/backupccl/backup_test.go, line 3777 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50949#-MBGsVb18Cpwh5ltQDdr-r1-3777:-MB_Vgri2-CZID6T-rOe:bdbkw8a) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fc943ee4302722da04bd7f7f5e51d78a22ef342/pkg/ccl/backupccl/backup_test.go#L3777)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Maybe we could do:
```
require.True(t, sd.SequenceOpts.HasOwner())
require.Equal(t, td.ID, sd.SequenceOpts.SequenceOwner.OwnerTableID)
```
so that if this test fails, it's a bit clearer what is going wrong (same elsewhere in the tests).
</blockquote></details>

This is neat! Done.

**Review by pbardea — APPROVED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50949)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @pbardea, and @rohany)

___
*[pkg/ccl/backupccl/backup_test.go, line 3756 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50949#-MBGsVb18Cpwh5ltQDdr-r1-3756:-MBdbV1w-ZL7smjmep7W:b4dbddt) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fc943ee4302722da04bd7f7f5e51d78a22ef342/pkg/ccl/backupccl/backup_test.go#L3756)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I had that earlier, but it seems that there isn't a deterministic way to know what is restored first -- the table or the sequence. As both the databases contain a sequence and a table with ownership dependencies, depending on what is processed first the error will be different. 

I do agree that it'd be nice to have confidence we're hitting the correct error message, but not sure how we can do it deterministically. 
</blockquote></details>

Fair enough, I could imagine that we could provide a regex here that would match either a table depending on a sequence, or a sequence depending on a view if we wanted to make sure it was one of the two errors.
___
*[pkg/ccl/backupccl/backup_test.go, line 3663 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50949#-MBdb2S06R6z96AOD3vU:-MBdb2S06R6z96AOD3vV:b98mkhc) ([raw file](https://github.com/cockroachdb/cockroach/blob/106bd1dbcf6ee997299f1ffa2db7e51c5df30352/pkg/ccl/backupccl/backup_test.go#L3663)):*
> ```Go
> 
> 	t.Run("test restoring sequence when table does not exist", func(t *testing.T) {
> 		// When restoring a sequence that is owned by a table, but the owning table
> ```

minor nit: the rest of this file has descriptions like this before the `t.Run` call. Could we move them there for consistency?

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50949)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea and @rohany)

___
*[pkg/ccl/backupccl/backup_test.go, line 3756 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50949#-MBGsVb18Cpwh5ltQDdr-r1-3756:-MBewTRJBzRVZsMyxaA8:b-tze0l6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fc943ee4302722da04bd7f7f5e51d78a22ef342/pkg/ccl/backupccl/backup_test.go#L3756)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Fair enough, I could imagine that we could provide a regex here that would match either a table depending on a sequence, or a sequence depending on a view if we wanted to make sure it was one of the two errors.
</blockquote></details>

I like this better, changed!

**Comment by arulajmani** [comment]
Thanks for the reviews. 

bors r=pbardea
