### PR TITLE
sql: `SET DEFAULT NULL` means a nil default expr instead of "NULL"

### LINKED ISSUE #91069: Unable to alter column type with DEFAULT NULL
**Describe the problem**

Attempting to reduce the size of a fixed-size varchar column results in error message.

**To Reproduce**

```
CREATE TABLE t (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	s VARCHAR(64) NULL
);

ALTER TABLE t ALTER COLUMN s SET DEFAULT NULL;

ALTER TABLE t ALTER COLUMN s TYPE VARCHAR(32);
```

The final command gives this error message:

```
ERROR: relation "t" (119): computed column "s_1" cannot also have a DEFAULT expression
```

The type change works fine if I replace the `SET DEFAULT` to `DROP DEFAULT`.  Is this intended behaviour?

**Expected behavior**
The `ALTER COLUMN` should just work as the intention implies.

**Environment:**
 - Observed on all 22.1 versions.

Jira issue: CRDB-21094

### PR DESCRIPTION
**Pull request by Xiang-Gu**
Previously, `SET DEFAULT NULL` resulted in a column whose DefaultExpr is "NULL". This is problematic when used with `ALTER COLUMN TYPE` where a temporary computed column will be created, hence violating validation that "a computed column cannot have default expression". This PR fixes that by setting DefaultExpr to nil when `SET DEFAULT NULL`.

Fixes #91069 
Release note (bug fix): Fixed a bug described in #91069.

### CODE REVIEW

File: pkg/sql/alter_table.go [hunk 1]
```diff
@@ -953,6 +953,10 @@ func applyColumnMutation(
 		); err != nil {
 			return err
 		}
+		if col.HasNullDefault() {
+			// `SET DEFAULT NULL` means a nil default expression.
+			col.ColumnDesc().DefaultExpr = nil
+		}
```
Comment (postamar) [inline pkg/sql/alter_table.go:959]: Dumb question perhaps but shouldn't this logic rather be in `updateNonComputedColExpr`? It feels like this should also apply to `ON UPDATE` expressions.

**Review by postamar — APPROVED** [review]
LGTM modulo the `ON UPDATE` case if applicable. 

Regarding backports: this doesn't feel like a severe-enough bug to warrant a backport to release-22.2.0, just release-22.2 should be enough. This means the patch will make it into 22.2.1.

**Review by ajwerner — COMMENTED** [review]
I checked in postgres, and this is the right thing to do. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91078#-:-NFoIO__-H9LZbKko2kQ:b-hcuh5f)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

___
*[`pkg/sql/alter_table.go` line 959 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91078#-NFoHBpRA9f3HHgvURv6-r1-959:-NFoKWHA0haJJGEQWZ7r:bo0vrar) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cbce60cb894dbd71d303d34e6a848650be9088a/pkg/sql/alter_table.go#L959)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Dumb question perhaps but shouldn't this logic rather be in `updateNonComputedColExpr`? It feels like this should also apply to `ON UPDATE` expressions.
</blockquote></details>

I disagree that this should apply to `ON UPDATE`. This has supremely different semantics with `ON UPDATE`. Consider:

```
demo@127.0.0.1:26257/movr> create table foo (i int primary key, j int default null on update null);
CREATE TABLE
demo@127.0.0.1:26257/movr> insert into foo(i) values (1);
INSERT 1
demo@127.0.0.1:26257/movr> select * from foo;
  i |  j
----+-------
  1 | NULL
(1 row)
demo@127.0.0.1:26257/movr> update foo set j = 1 where j is null;
UPDATE 1
demo@127.0.0.1:26257/movr> select * from foo;
  i | j
----+----
  1 | 1
(1 row)
demo@127.0.0.1:26257/movr> update foo set i = 2 where i = 1;
UPDATE 1
demo@127.0.0.1:26257/movr> select * from foo;
  i |  j
----+-------
  2 | NULL
(1 row)
demo@127.0.0.1:26257/movr> alter table foo alter column j drop on update;
ALTER TABLE
demo@127.0.0.1:26257/movr> update foo set j = 1 where j is null;
UPDATE 1
demo@127.0.0.1:26257/movr> update foo set i = 1 where i = 2;
UPDATE 1
demo@127.0.0.1:26257/movr> select * from foo;
  i | j
----+----
  1 | 1
```

**Review by Xiang-Gu — COMMENTED** [review]
@postamar the user that reported this issue is on v22.1. I think we should backport it to v22.1 for them?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91078#-:-NFoN5-nD3i1mwGrWcEc:b7u9k3q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[`pkg/sql/alter_table.go` line 959 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91078#-NFoHBpRA9f3HHgvURv6-r1-959:-NFoMVA_6b2ArQAoPJSQ:b-bnwhrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cbce60cb894dbd71d303d34e6a848650be9088a/pkg/sql/alter_table.go#L959)):*
> Dumb question perhaps but shouldn't this logic rather be in updateNonComputedColExpr? It feels like this should also apply to ON UPDATE expressions.

I think `ON UPDATE NULL` and  `OnUpdateExpr = nil` is very different, as the former means to update to null and the latter means no action. Andrew's example showed this. That's why I chose not to add the logic inside `updateNonComputedColExpr`

**Comment by postamar** [comment]
Alright never mind about ON UPDATE then.

By all means backport to release-22.1, just don't backport to release-22.2.0, that's all.
