### PR TITLE
jobs: fix bug in the InfoStorage read path

### LINKED ISSUE #99101: roachtest: backup/mixed-version failed [querying `system.job_info`: unexpected multiple results]
roachtest.backup/mixed-version [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/9162369?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/9162369?buildTab=artifacts#/backup/mixed-version) on master @ [b89fa2cc4bc1fb9447ab1009b34b6f354f9618f0](https://github.com/cockroachdb/cockroach/commits/b89fa2cc4bc1fb9447ab1009b34b6f354f9618f0):

```
test artifacts and logs in: /artifacts/backup/mixed-version/run_1
(mixedversion.go:366).Run: mixed-version test failure while running step 24 (run "plan and run backups"): waiting for job to finish: job 849727133401219074: current status "running", waiting for "succeeded"
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #78399 roachtest: backup/mixed-version failed [C-test-failure O-roachtest O-robot T-disaster-recovery branch-release-22.1]
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backup/mixed-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-25702

### PR DESCRIPTION
**Pull request by adityamaru**
In a previous PR we dropped the LIMIT 1 clause
from the read path in InfoStorage under the assumption that for a joID, infoKey we will always have atmost one row. While still true for all users interacting with InfoStorage via the accessors, this assumption might not hold
during upgrades. Jobs start writing their payload and progress to the job_info table once V23_1CreateSystemJobInfoTable is active. If a job is still running when the cluster steps through V23_1JobInfoTableIsBackfilled then the job will have duplicate entries for the payload and prgress rows. This is because we blindly backfill the contents of the `jobs` table into the `job_info` table without clearing previous entries corresponding to the job.

To guard against this case we introduce a LIMIT 1 clause to the read query so that we always get the most recently written row corresponding to a jobID and info_key.

Fixes: #99101

Release note: None

### CODE REVIEW

File: pkg/jobs/job_info_storage.go [hunk 1]
```diff
@@ -82,7 +82,7 @@ func (i InfoStorage) get(ctx context.Context, infoKey []byte) ([]byte, bool, err
 	row, err := i.txn.QueryRowEx(
 		ctx, "job-info-get", i.txn.KV(),
 		sessiondata.NodeUserSessionDataOverride,
-		"SELECT value FROM system.job_info WHERE job_id = $1 AND info_key = $2",
+		"SELECT value FROM system.job_info WHERE job_id = $1 AND info_key = $2 LIMIT 1",
```
Comment (knz) [inline pkg/jobs/job_info_storage.go:85]: May i recommend "order by written desc limit 1" because otherwise you're relying on implicit behaviors in the query optimizer

File: pkg/ccl/jobsccl/jobs_info_storage_test.go [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+//
+// Use of this software is governed by the Business Source License
+// included in the file licenses/BSL.txt.
+//
+// As of the Change Date specified in that file, in accordance with
+// the Business Source License, use of this software will be governed
+// by the Apache License, Version 2.0, included in the file
+// licenses/APL.txt.
+
+package jobsccl
```
Comment (dt) [inline pkg/ccl/jobsccl/jobs_info_storage_test.go:11]: we _are_ allowed to make bsl test -> ccl deps these days so I'm not sure this new package is strictly necessary

**Review by dt — APPROVED** [review]

File: pkg/jobs/job_info_storage.go (hunk 1 above)
Comment (adityamaru) [reply pkg/jobs/job_info_storage.go]: done!

File: pkg/ccl/jobsccl/jobs_info_storage_test.go (hunk 2 above)
Comment (adityamaru) [reply pkg/ccl/jobsccl/jobs_info_storage_test.go]: old habits die hard, done!

**Comment by adityamaru** [comment]
TFTR!

bors r=dt

**Comment by adityamaru** [comment]
blathers backport 23.1

File: pkg/jobs/job_info_storage.go [hunk 3]
```diff
@@ -82,7 +82,7 @@ func (i InfoStorage) get(ctx context.Context, infoKey []byte) ([]byte, bool, err
 	row, err := i.txn.QueryRowEx(
 		ctx, "job-info-get", i.txn.KV(),
 		sessiondata.NodeUserSessionDataOverride,
-		"SELECT value FROM system.job_info WHERE job_id = $1 AND info_key = $2",
+		"SELECT value FROM system.job_info WHERE job_id = $1 AND info_key = $2 ORDER BY written LIMIT 1",
```
Comment (knz) [inline pkg/jobs/job_info_storage.go:85]: Didn't you want `ORDER BY written DESC`? Presumably if there are multiple rows you want the latest one written, not the first.

Comment (adityamaru) [reply pkg/jobs/job_info_storage.go:85]: I did, fixing it up. Thanks for flagging 🙌
