### PR TITLE
sql: step txn after restoring from a savepoint for exception handling

### LINKED ISSUE #156412: sql: assertion failure caused by routine with exception handler
**Describe the problem**

The following is a slightly modified case from plpqsql_block:

```
CREATE TABLE t122278 (pk INT PRIMARY KEY);
CREATE FUNCTION f(n INT) RETURNS INT AS $$
  BEGIN
    BEGIN
      IF n = 0 THEN
        RETURN 1 // 0;
      END IF;
    EXCEPTION
      WHEN division_by_zero THEN
        RETURN (SELECT 100 + count(*) FROM t122278);
    END;
    RETURN 1 // 0;
  EXCEPTION
    WHEN division_by_zero THEN
      RETURN (SELECT 200 + count(*) FROM t122278);
  END
$$ LANGUAGE PLpgSQL;

BEGIN;
INSERT INTO t122278 values (1);
SELECT f(0);
COMMIT;
```

On master, it will fail with the following assertion failed error:

```
ERROR: internal error: read sequence number 3 but sequence number is ignored [{3 3}] after savepoint rollback
SQLSTATE: XX000
DETAIL: stack trace:
pkg/kv/kvclient/kvcoord/txn_interceptor_seq_num_allocator.go:185: checkReadSeqNotIgnoredLocked()
pkg/kv/kvclient/kvcoord/txn_interceptor_seq_num_allocator.go:82: SendLocked()
pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go:266: SendLocked()
pkg/kv/kvclient/kvcoord/txn_coord_sender.go:570: Send()
pkg/kv/db.go:1167: sendUsingSender()
pkg/kv/txn.go:1381: Send()
pkg/sql/row/kv_batch_fetcher.go:283: func2()
pkg/sql/row/kv_batch_fetcher.go:646: fetch()
pkg/sql/row/kv_batch_fetcher.go:934: nextBatch()
pkg/sql/row/kv_batch_fetcher.go:801: NextBatch()
pkg/sql/row/kv_fetcher.go:314: nextKV()
pkg/sql/row/kv_fetcher.go:335: NextKV()
pkg/sql/colfetcher/cfetcher.go:775: NextBatch()
pkg/sql/colfetcher/colbatch_scan.go:240: Next()
pkg/sql/colexec/colexecutils/cancel_checker.go:54: Next()
pkg/sql/colexec/count.go:46: Next()
pkg/sql/colexec/colexecutils/operator.go:152: Next()
bazel-out/darwin_arm64-fastbuild/bin/pkg/sql/colexec/colexecprojconst/proj_const_right_ops.eg.go:4037: Next()
pkg/sql/colexec/colexecbase/simple_project.go:113: Next()
pkg/sql/colexec/materializer.go:246: next()
pkg/sql/colexec/materializer.go:271: nextAdapter()
pkg/sql/colexecerror/error.go:162: CatchVectorizedRuntimeError()
pkg/sql/colexec/materializer.go:277: Next()
pkg/sql/colflow/flow_coordinator.go:119: next()
pkg/sql/colflow/flow_coordinator.go:136: nextAdapter()
pkg/sql/colexecerror/error.go:162: CatchVectorizedRuntimeError()
pkg/sql/colflow/flow_coordinator.go:141: Next()
pkg/sql/execinfra/base.go:193: Run()
pkg/sql/execinfra/processorsbase.go:752: Run()
pkg/sql/flowinfra/flow.go:574: Run()
pkg/sql/colflow/vectorized_flow.go:301: Run()
pkg/sql/distsql_running.go:1072: Run()

HINT: You have encountered an unexpected error.

Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.

If you would rather not post publicly, please contact us directly
using the support form.

We appreciate your feedback
```

The most proximate cause is that when Stepping is enabled, RollbackSavepoint puts the transaction in a state where the readSeq is part of the ignored set, expecting that the caller will Step() the transaction.

However, in this case, no future step is going to happen before we try to send another batch using the transaction.

It isn't clear to me is what we should be doing in this case, so I've assigned this T-sql-queries for their opinion.

Related: #156366 which would make it even easier to hit this case and is where I encountered the bug initially.

Jira issue: CRDB-55988

### PR DESCRIPTION
**Pull request by DrewKimball**
PL/pgSQL routines use a savepoint to revert any modifications that happened within a block that has an exception handler. It was previously possible to trigger an assertion failure because `RollbackToSavepoint` can leave the read sequence number within the range of ignored sequence numbers. If the user-provided exception handling code contained non-volatile reads, we wouldn't step the read sequence number.

This commit fixes the bug by stepping the txn after restoring the savepoint during exception handling.

Fixes #156412

Release note (bug fix): Fixed a bug that could cause an internal error in some cases for PL/pgSQL routines that perform database reads within an exception block.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> @yuzefovich reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/156902)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @michae2)

___
*[`pkg/kv/txn.go` line 1829 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/156902#-OdGKFIu0LhvOV941Hya:-OdGKFIu0LhvOV941Hyb:b-g9n8hy) ([raw file](https://github.com/cockroachdb/cockroach/blob/9768d80723a8e733630cb6b1af131f52d3d65025/pkg/kv/txn.go#L1829)):*
> ```Go
> // This method is only valid when called on RootTxns.
> //
> // NB: after calling RollbackToSavepoint, the transaction's read sequence number
> ```

Hm, we should check with KV team about this. Currently it doesn't look like we do this in other places - e.g. in `dispatchReadCommittedStmtToExecutionEngine` within the retry loop we create a savepoint and then roll back to it if we hit a retry error, and even though we clear that error from the txn, we don't step the txn. Is that a bug, or is there something different from the routine usage of the txn?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/156902)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @michae2, and @stevendanna)

___
*[`pkg/kv/txn.go` line 1829 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/156902#-OdGKFIu0LhvOV941Hya:-OdGqKGo6d8a2IGuFaRv:beqorou) ([raw file](https://github.com/cockroachdb/cockroach/blob/9768d80723a8e733630cb6b1af131f52d3d65025/pkg/kv/txn.go#L1829)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Hm, we should check with KV team about this. Currently it doesn't look like we do this in other places - e.g. in `dispatchReadCommittedStmtToExecutionEngine` within the retry loop we create a savepoint and then roll back to it if we hit a retry error, and even though we clear that error from the txn, we don't step the txn. Is that a bug, or is there something different from the routine usage of the txn?
</blockquote></details>

BTW we've seen this error in sentry (#139827 in PREPARE and #144383 in COPY) as well as on serverless last week (also in COPY).

Looks like there is some active related work in #156366. We should ask @stevendanna to weigh in on the approach here.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/156902)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @michae2, and @stevendanna)

___
*[`pkg/kv/txn.go` line 1829 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/156902#-OdGKFIu0LhvOV941Hya:-OdHevOa5My4NIo8SWn1:bwrvyu9) ([raw file](https://github.com/cockroachdb/cockroach/blob/9768d80723a8e733630cb6b1af131f52d3d65025/pkg/kv/txn.go#L1829)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

BTW we've seen this error in sentry (#139827 in PREPARE and #144383 in COPY) as well as on serverless last week (also in COPY).

Looks like there is some active related work in #156366. We should ask @stevendanna to weigh in on the approach here.
</blockquote></details>

Indeed, we have bugs in those spots too. What happens is that on the main query path we unconditionally [step](https://github.com/cockroachdb/cockroach/blob/05c6218cc548c914bcf0925bde1d1a9000854056/pkg/sql/conn_executor_exec.go#L1026) the txn before every stmt, but COPY and PREPARE don't hit that path.

File: pkg/kv/txn.go [hunk 1]
```diff
@@ -1825,6 +1825,9 @@ func (txn *Txn) CreateSavepoint(ctx context.Context) (SavepointToken, error) {
 // and can be reused later (e.g. to release or roll back again).
 //
 // This method is only valid when called on RootTxns.
+//
+// NB: after calling RollbackToSavepoint, the transaction's read sequence number
+// must be stepped by calling Step() before any further reads are performed.
```
Comment (stevendanna) [inline pkg/kv/txn.go]: I wonder if it is viable to change how RollbackToSavepoint works. If we adopted my PR here: #156366 and then changed RollbackToSavepoint to _always_ step the read sequence what problems might we cause?

Comment (DrewKimball) [reply pkg/kv/txn.go]: That behavior seems more intuitive for users of txns with stepping enabled. The only case I'm aware of where we want to keep an older sequence number is after returning from a volatile routine, and for that we already explicitly restore the sequence number.

**Review by yuzefovich — APPROVED** [review]
We discussed this in KV / SQL pod, and Steven will look into cleaning up the API around this, but as a bug fix, this seems good. :lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/156902#-:-OdKNZEq0kfQDblt3AYD:b-1uogas)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @stevendanna)

___
*[`pkg/kv/txn.go` line 1830 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/156902#-OdKNGMh7OjwVgAlTWWT:-OdKNGMh7OjwVgAlTWWU:b-ku90d2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9768d80723a8e733630cb6b1af131f52d3d65025/pkg/kv/txn.go#L1830)):*
> ```Go
> //
> // NB: after calling RollbackToSavepoint, the transaction's read sequence number
> // must be stepped by calling Step() before any further reads are performed.
> ```

nit: I think we can hit an assertion when doing writes too, so I'd reword the comment to be "before any further requests are performed".

**Review by michae2 — APPROVED** [review]
:lgtm: Nice!

> @michae2 reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/156902#-:-OdKOUId41N36_TCBSS0:b-8gk8uj)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball and @stevendanna)

**Review by mgartner — APPROVED** [review]
Great find!

> @mgartner reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/156902#-:-OdL0p_70Ib_9ExSc5dj:b-9nd34g)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball and @stevendanna)

**Review by stevendanna — APPROVED** [review]
Really appreciate y'all jumping on this one!

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/156902)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner, @michae2, @stevendanna, and @yuzefovich)

___
*[`pkg/kv/txn.go` line 1830 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/156902#-OdKNGMh7OjwVgAlTWWT:-Oexb59l9H26IpWTBLfO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9768d80723a8e733630cb6b1af131f52d3d65025/pkg/kv/txn.go#L1830)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: I think we can hit an assertion when doing writes too, so I'd reword the comment to be "before any further requests are performed".
</blockquote></details>

Done.

File: pkg/kv/txn.go (hunk 1 above)
Comment (michae2) [reply pkg/kv/txn.go]: If RollbackToSavepoint were to always step the read sequence, it would break swap mutations which are followed by additional reads in the same statement. But I do think we want to adopt https://github.com/cockroachdb/cockroach/pull/156366. (See https://github.com/cockroachdb/cockroach/issues/160579.)
