### PR TITLE
storageccl: use the new PebbleIterator in ExternalSSTReader

### LINKED ISSUE #84240: roachtest: backupTPCC failed
roachtest.backupTPCC [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/5718837?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/5718837?buildTab=artifacts#/backupTPCC) on master @ [571bfa3afb3858ae84d8a8fcdbb0a38e058402a5](https://github.com/cockroachdb/cockroach/commits/571bfa3afb3858ae84d8a8fcdbb0a38e058402a5):

```
test artifacts and logs in: /artifacts/backupTPCC/run_1
	monitor.go:127,backup.go:1095,test_runner.go:896: monitor failure: monitor task failed: dial tcp 34.139.144.3:26257: connect: connection refused
		(1) attached stack trace
		  -- stack trace:
		  | main.(*monitorImpl).WaitE
		  | 	main/pkg/cmd/roachtest/monitor.go:115
		  | main.(*monitorImpl).Wait
		  | 	main/pkg/cmd/roachtest/monitor.go:123
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerBackup.func4
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/backup.go:1095
		  | [...repeated from below...]
		Wraps: (2) monitor failure
		Wraps: (3) attached stack trace
		  -- stack trace:
		  | main.(*monitorImpl).wait.func2
		  | 	main/pkg/cmd/roachtest/monitor.go:171
		  | runtime.goexit
		  | 	GOROOT/src/runtime/asm_amd64.s:1581
		Wraps: (4) monitor task failed
		Wraps: (5) dial tcp 34.139.144.3:26257
		Wraps: (6) connect
		Wraps: (7) connection refused
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *net.OpError (6) *os.SyscallError (7) syscall.Errno
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/bulk-io
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backupTPCC.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-17540

### PR DESCRIPTION
**Pull request by msbutler**
This PR refactors all call sites of ExternalSSTReader(), to support using the
new PebbleIterator, which has baked in range key support. Most notably, this
PR replaces the multiIterator used in the restore data processor with the
PebbleSSTIterator.

This patch is apart of a larger effort to teach backup and restore about MVCC
bulk operations. Next, the readAsOfIterator will need to learn how to
deal with range keys.

Informs https://github.com/cockroachdb/cockroach/issues/71155

This PR addresses a bug created in https://github.com/cockroachdb/cockroach/pull/83984: loop variables in
ExternalSSTReader were captured by reference, leading to roachtest failures
(https://github.com/cockroachdb/cockroach/issues/84240, https://github.com/cockroachdb/cockroach/issues/84162).

Informs #71155

Fixes: https://github.com/cockroachdb/cockroach/issues/84240, https://github.com/cockroachdb/cockroach/issues/84162, https://github.com/cockroachdb/cockroach/issues/84181

Release note: none

### CODE REVIEW

File: pkg/ccl/storageccl/external_sst_reader.go [hunk 1]
```diff
@@ -76,44 +90,73 @@ func ExternalSSTReader(
...
+			// the decrypting reader has its own internal block buffer.
+			if err := raw.readAndCacheSuffix(remoteCacheSize); err != nil {
+				f.Close(ctx)
+				return nil, err
+			}
+			reader = raw
+		}
+		readers = append(readers, reader)
+	}
+	return storage.NewPebbleSSTIterator(readers, iterOps)
```
Comment (erikgrinaker) [inline pkg/ccl/storageccl/external_sst_reader.go:159]: Note the order here in case there are conflicting keys. If the exact same Pebble key (that is, the same key/timestamp combination) exists in multiple files, the first one takes precedence. Not sure if we prevent that from happening, or what order the input files are in, but worth considering.

File: pkg/ccl/storageccl/external_sst_reader.go [hunk 2]
```diff
@@ -76,44 +90,73 @@ func ExternalSSTReader(
...
-		},
+// ExternalSSTReader returns a PebbleSSTIterator for the SSTs in external storage,
+// optionally decrypting with the supplied parameters.
+//
+// ctx is captured and used throughout the life of the returned iterator, until
+// the iterator's Close() method is called.
+func ExternalSSTReader(
+	ctx context.Context,
+	e []cloud.ExternalStorage,
+	filenames []string,
```
Comment (erikgrinaker) [inline pkg/ccl/storageccl/external_sst_reader.go:106]: nit: seems like we'd want to bundle these in a struct.

File: pkg/ccl/storageccl/external_sst_reader.go [hunk 3]
```diff
@@ -76,44 +90,73 @@ func ExternalSSTReader(
...
+	encryption *roachpb.FileEncryptionOptions,
+	iterOps storage.IterOptions,
```
Comment (erikgrinaker) [inline pkg/ccl/storageccl/external_sst_reader.go:108]:
```suggestion
	iterOpts storage.IterOptions,
```

**Review by erikgrinaker — APPROVED** [review]
Looks good at a high level.

File: pkg/ccl/storageccl/external_sst_reader.go [hunk 4]
```diff
@@ -76,44 +90,73 @@ func ExternalSSTReader(
...
+	if !remoteSSTs.Get(&e[0].Settings().SV) {
+		return newMemPebbleSSTReader(ctx, e, filenames, encryption, iterOps)
 	}
+	remoteCacheSize := remoteSSTSuffixCacheSize.Get(&e[0].Settings().SV)
+	readers := make([]sstable.ReadableFile, 0, len(filenames))
 
-	var reader sstable.ReadableFile = raw
+	for i, basename := range filenames {
+		// prevent capturing the loop variables by reference when defining openAt below.
+		basename := basename
```
Comment (msbutler) [inline pkg/ccl/storageccl/external_sst_reader.go:121]: @jbowens if I comment these local vars out, the unit test I wrote in the PR still passes :(. You mentioned that the roachtest failures occur at block boundaries. I assume this occurs when pebbleIterator.Iter.ExternalFiles[i].ReadAt is called. Do you have any tips at how I could construct the SSTs in the unit test to ensure the test hits block boundaries? Maybe this is overkill, since we no know the bug is squashed and the test still adds good coverage.

File: pkg/ccl/storageccl/external_sst_reader.go (hunk 1 above)
Comment (msbutler) [reply pkg/ccl/storageccl/external_sst_reader.go]: Added a note to the function docstring to reflect this.

File: pkg/ccl/storageccl/external_sst_reader.go (hunk 2 above)
Comment (msbutler) [reply pkg/ccl/storageccl/external_sst_reader.go]: Done.

File: pkg/ccl/storageccl/external_sst_reader.go (hunk 3 above)
Comment (msbutler) [reply pkg/ccl/storageccl/external_sst_reader.go]: Done.

File: pkg/ccl/storageccl/external_sst_reader.go (hunk 4 above)
Comment (jbowens) [reply pkg/ccl/storageccl/external_sst_reader.go]: Does it trigger if you vary the number of keys per-file, eg, 10, 100, 1000?

Comment (msbutler) [reply pkg/ccl/storageccl/external_sst_reader.go]: nope. I also changed the sst's to partially overlap, and still no repro. They currently look like this: 
```
// t3               a500--------------------a10000
//
// t2      a50--------------a1000
//
// t1   a0----a100
```

**Comment by msbutler** [comment]
bors r=erikgrinaker
