### PR TITLE
catalog/ingesting: disallow writing cross database references

### LINKED ISSUE #138230: catalog/ingesting: WriteDescriptors allows tables to be written with cross database references
In this [draft pr](https://github.com/cockroachdb/cockroach/pull/138229), I've updated a unit test which successfully writes the table `data` to the defaultdb which references the type `udt` which lives in the `db1` database. I think this `WriteDescriptors` call should fail, to align with behavior in a sql shell:
```
demo@127.0.0.1:26257/movr> CREATE TYPE db1.udt AS ENUM ('a', 'b', 'c');
CREATE TYPE

Time: 3ms total (execution 3ms / network 0ms)

demo@127.0.0.1:26257/movr> CREATE TABLE data (pk INT PRIMARY KEY, val1 db1.udt);
ERROR: cross database type references are not supported: db1.public.udt
SQLSTATE: 0A000
```

As the test shows, after the problem table is written, the user can drop the user defined type, so the table has a missing type reference. This bug feels similar to https://github.com/cockroachdb/cockroach/pull/105579

cc @fqazi who probably has the most context on ExternalCatalog, where this unit test lives.

Jira issue: CRDB-45961

### PR DESCRIPTION
**Pull request by fqazi**
Previously, the ingest API supported writing cross database references, which could allow tables to be ingested in a manner that is deprecated. To avoid issues, this patch adds an error when cross database references of any kind are detected.

Fixes: #138230

Release note: None

Note: This functionality is only blocked for LDR, since backup / restore and imports have to work with cross database references until we fully remove them.

### CODE REVIEW

File: pkg/sql/catalog/ingesting/write_descs.go [hunk 1]
```diff
@@ -51,7 +52,9 @@ func WriteDescriptors(
 	extra []roachpb.KeyValue,
 	inheritParentName string,
 	includePublicSchemaCreatePriv bool,
+	deprecatedAllowCrossDatabaseRefs bool,
```
Comment (rafiss) [inline pkg/sql/catalog/ingesting/write_descs.go:55]: nit: would this variable be more clear if it were named `allowCrossDatabaseRefs`?

can we mention in the comment that the flag is only present since we need to continue supporting RESTOREs of clusters that had cross DB references before they were disallowed?

**Review by rafiss — APPROVED** [review]
nice work! let's get @msbutler to review this too

**Review by msbutler — APPROVED** [review]
Thanks for doing this!

**Comment by fqazi** [comment]
@msbutler @rafiss TFTR!

bors r+
