### PR TITLE
sqlproxyccl: deflake TestDeleteTenant

### LINKED ISSUE #86077: ccl/sqlproxyccl/tenant: TestDeleteTenant failed
ccl/sqlproxyccl/tenant.TestDeleteTenant [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/6079885?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/6079885?buildTab=artifacts#/) on master @ [0dd438d3dc0b42543890455945a7a6b42811def1](https://github.com/cockroachdb/cockroach/commits/0dd438d3dc0b42543890455945a7a6b42811def1):

```
=== RUN   TestDeleteTenant
    test_log_scope.go:162: test logs captured to: /artifacts/tmp/_tmp/a6458abb05e6ab358f897a749cce5d50/logTestDeleteTenant1748159223
    directory_cache_test.go:506: starting tenant 50
    directory_cache_test.go:511: tenant 50 started
    directory_cache_test.go:320: 
        	Error Trace:	directory_cache_test.go:320
        	Error:      	Should be empty, but was [tenant_id:50 addr:"127.0.0.1:46875" state:RUNNING stateTimestamp:<seconds:1660369353 nanos:353356988 > ]
        	Test:       	TestDeleteTenant
    panic.go:500: -- test log scope end --
--- FAIL: TestDeleteTenant (1.66s)
```
<p>Parameters: <code>TAGS=bazel,gss</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-experience @cockroachdb/server
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestDeleteTenant.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-18557

### PR DESCRIPTION
**Pull request by jeffswenson**
There is a small race condition in the tenant directory cache.

1. If ReportFailure is called, the tenant dir rebuilds the cache by listing the available pods.
2. There is a watch attempting to push events to the cache. If an event was generated before the most recent list, the watch event can roll back cache state.

This race is okay in production because when the sql proxy tries to dial the stale pod, the dial will fail and the proxy will refresh the list again.

This change adjusts the test to work like production. If the list is stale, ReportFailure is retried to refresh the list of pods.

Fixes: #86077

### CODE REVIEW

File: pkg/ccl/sqlproxyccl/tenant/directory_cache_test.go [hunk 1]
```diff
@@ -496,11 +496,29 @@ func TestDeleteTenant(t *testing.T) {
...
+			return errors.Newf("expected 0 pods found %v", pods)
+		}
+
+		return nil
+	})
 
 	// Ensure that tenant has no valid IP addresses.
-	pods, err = dir.TryLookupTenantPods(ctx, tenantID)
 	require.NoError(t, err)
 	require.Empty(t, pods)
```
Comment (jaylim-crl) [inline pkg/ccl/sqlproxyccl/tenant/directory_cache_test.go:523]: Do we still need these?

File: pkg/ccl/sqlproxyccl/tenant/directory_cache_test.go [hunk 2]
```diff
@@ -496,11 +496,29 @@ func TestDeleteTenant(t *testing.T) {
 		process.Stopper.Stop(ctx)
 	}
 
-	// Report failure connecting to the pod to force refresh of addrs.
-	require.NoError(t, dir.ReportFailure(ctx, tenantID, addr))
+	// There is a rare race condition where the watch event can overwrite
```
Comment (jaylim-crl) [inline pkg/ccl/sqlproxyccl/tenant/directory_cache_test.go:499]: I also recalled that if we wanted to fully mimic production, we should update WatchPods to stream a list of pods that the server knows about.

**Review by jaylim-crl — APPROVED** [review]
LGTM

File: pkg/ccl/sqlproxyccl/tenant/directory_cache_test.go (hunk 1 above)
Comment (JeffSwenson) [reply pkg/ccl/sqlproxyccl/tenant/directory_cache_test.go]: Fixed

File: pkg/ccl/sqlproxyccl/tenant/directory_cache_test.go (hunk 2 above)
Comment (JeffSwenson) [reply pkg/ccl/sqlproxyccl/tenant/directory_cache_test.go:499]: That is a case we should test, but it's a bit orthogonal to the test directory server in general. The test directory server always starts empty, so there are no watch events to propagate.

Comment (jaylim-crl) [reply pkg/ccl/sqlproxyccl/tenant/directory_cache_test.go:499]: > The test directory server always starts empty

There are some tests that simulate a crash of the tenant directory server, or the Watch API closing early.
