### PR TITLE
backupccl: tenants should be restored in their correct state

### LINKED ISSUE #87915: backupccl: cluster restore incorrectly restores an inactive tenant as active
In https://github.com/cockroachdb/cockroach/pull/78597 we're working on probabilistically running a cluster backup+restore at  different stages of a logic test. As part of a test run of `tenant_usage` I noticed the following behaviour:

```
SELECT crdb_internal.create_tenant(5);
SELECT crdb_internal.destroy_tenant(5);

root@localhost:26257/defaultdb> select * from system.tenants;
  id | active |    info
-----+--------+-------------
   5 |   f    | \x08051002
(1 row)

BACKUP INTO 'nodelocal://1/foo';
```

Start a new server:

```
root@localhost:26257/defaultdb> restore from latest in 'nodelocal://1/';
        job_id       |  status   | fraction_completed | rows | index_entries | bytes
---------------------+-----------+--------------------+------+---------------+--------
  796307925929263105 | succeeded |                  1 |   22 |            89 | 31866
(1 row)


Time: 5.227s total (execution 5.227s / network 0.000s)

root@localhost:26257/defaultdb> select * from system.tenants;
  id | active |    info
-----+--------+-------------
   5 |   t    | \x08051000
(1 row)
```

Notice the active bit post-restore is now true.

### PR DESCRIPTION
**Pull request by adityamaru**
Previously, all backed up tenants were unconditionally moved through an `ADD` and then `ACTIVE` state during a cluster/tenant restore. This behaviour appears incorrect. If the tenant was backed up in and adding or dropped state then it should be restored in the same state as well.

This change only moves `ACTIVE` backed up tenants through an `ADD` and then `ACTIVE` state thereby fixing this bug.

Fixes: #87915

Release note (bug fix): Cluster and tenant restores of dropped or adding tenants would incorrectly activate those tenants during restore.

### CODE REVIEW

File: pkg/ccl/backupccl/restore_job.go [hunk 1]
```diff
@@ -2042,8 +2052,20 @@ func (r *restoreResumer) publishDescriptors(
...
 
 	for _, tenant := range details.Tenants {
-		if err := sql.ActivateTenant(ctx, r.execCfg, txn, tenant.ID); err != nil {
-			return err
+		switch tenant.State {
+		case descpb.TenantInfo_ACTIVE:
+			// If the tenant was backed up in an `ACTIVE` state then we must activate
+			// the tenant as the final step of the restore. The tenant has already
+			// been created at an earlier stage in the restore in an `ADD` state.
+			tenant.State = descpb.TenantInfo_ADD
```
Comment (dt) [inline pkg/ccl/backupccl/restore_job.go:2060]: what does this assignment do?

Comment (adityamaru) [reply pkg/ccl/backupccl/restore_job.go]: oops, deleted.

**Review by dt — APPROVED** [review]

**Comment by adityamaru** [comment]
TFTR!

bors r=dt
