### PR TITLE
sql: skip flaky ngpsql roachtests

### LINKED ISSUE #153691: roachtest: npgsql failed
**Note:** This build has runtime assertions enabled. If the same failure was hit in a run without assertions enabled, there should be a similar failure without this message. If there isn&#39;t one, then this failure is likely due to an assertion violation or (assertion) timeout.

roachtest.npgsql [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/20483883?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/20483883?buildTab=artifacts#/npgsql) on master @ [2b99f4ed4065e4eedb87171ce35918f728e76cec](https://github.com/cockroachdb/cockroach/commits/2b99f4ed4065e4eedb87171ce35918f728e76cec):

```
(orm_helpers.go:225).summarizeFailed: 
Tests run on Cockroach v25.4.0-alpha.2-dev-2b99f4ed4065e4eedb87171ce35918f728e76cec
Tests run against npgsql v7.0.2
3315 Total Tests Run
2680 tests passed
635 tests failed
271 tests skipped
3 tests ignored
0 tests passed unexpectedly
1 test failed unexpectedly
0 tests expected failed but skipped
0 tests expected failed but not run
---
--- FAIL: Npgsql.Tests.CopyTests(Multiplexing).Import_string_array -  (unexpected)
For a full summary look at the npgsql artifacts 
An updated blocklist (npgsqlBlocklist) is available in the artifacts' npgsql log
test artifacts and logs in: /artifacts/npgsql/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=azure</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>metamorphicBufferedSender=true</code>
 - <code>metamorphicLeases=leader</code>
 - <code>metamorphicWriteBuffering=true</code>
 - <code>runtimeAssertionsBuild=true</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for azure clusters_</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*npgsql.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-54558

### LINKED ISSUE #154004: roachtest: npgsql failed [one flaky test that should be ignored]
**Note:** This build has runtime assertions enabled. If the same failure was hit in a run without assertions enabled, there should be a similar failure without this message. If there isn&#39;t one, then this failure is likely due to an assertion violation or (assertion) timeout.

roachtest.npgsql [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20509899?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20509899?buildTab=artifacts#/npgsql) on release-25.2.6-rc @ [e9b11cf62097fae46d98b46d128f47e88b4fac55](https://github.com/cockroachdb/cockroach/commits/e9b11cf62097fae46d98b46d128f47e88b4fac55):

```
(orm_helpers.go:224).summarizeFailed: 
Tests run on Cockroach v25.2.6-dev-e9b11cf62097fae46d98b46d128f47e88b4fac55
Tests run against npgsql v7.0.2
3315 Total Tests Run
2679 tests passed
636 tests failed
271 tests skipped
3 tests ignored
0 tests passed unexpectedly
1 test failed unexpectedly
0 tests expected failed but skipped
0 tests expected failed but not run
---
--- FAIL: Npgsql.Tests.CopyTests(Multiplexing).Prepended_messages -  (unexpected)
For a full summary look at the npgsql artifacts 
An updated blocklist (npgsqlBlocklist) is available in the artifacts' npgsql log
test artifacts and logs in: /artifacts/npgsql/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>metamorphicBufferedSender=true</code>
 - <code>metamorphicLeases=expiration</code>
 - <code>runtimeAssertionsBuild=true</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20509899/npgsql/1758709743881/1758710055987)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #153691 roachtest: npgsql failed [B-runtime-assertions-enabled C-test-failure O-roachtest O-robot P-2 T-sql-foundations branch-master]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*npgsql.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-54717

### PR DESCRIPTION
**Pull request by bghal**
The tests are timing out.

```
  Failed Import_string_array [30 s]
  Stack Trace:
```

```
  Failed Prepended_messages [30 s]
  Stack Trace:
```

Fixes: #154004 
Fixes: #153691

Release note: None

### CODE REVIEW

File: pkg/sql/logictest/testdata/logic_test/alter_sequence [hunk 1]
```diff
@@ -395,3 +395,64 @@ SHOW CREATE SEQUENCE seq_alter_no_min_max_des
 ----
 table_name                create_statement
 seq_alter_no_min_max_des  CREATE SEQUENCE public.seq_alter_no_min_max_des MINVALUE -9223372036854775808 MAXVALUE -1 INCREMENT -1 START -5;
+
+subtest issue-52552
```
Comment (rafiss) [inline pkg/sql/logictest/testdata/logic_test/alter_sequence]: i think the sequence changes were included accidentally

**Review by rafiss — APPROVED** [review]

File: pkg/cmd/roachtest/tests/npgsql_blocklist.go [hunk 2]
```diff
@@ -664,4 +664,5 @@ var npgsqlIgnoreList = blocklist{
 	`Npgsql.Tests.ConnectionTests(Multiplexing).Fail_connect_then_succeed(True)`:                     "flaky",
 	`Npgsql.Tests.TransactionTests(NonMultiplexing).Failed_transaction_on_close_with_custom_timeout`: "flaky",
 	`Npgsql.Tests.TransactionTests(Multiplexing).Failed_transaction_on_close_with_custom_timeout`:    "flaky",
+	`Npgsql.Tests.CopyTests(Multiplexing).Prepended_messages`:                                        "flaky",
```
Comment (rafiss) [inline pkg/cmd/roachtest/tests/npgsql_blocklist.go]: as long as we're here, could you also skip another flaky test that came up in https://github.com/cockroachdb/cockroach/issues/153691 ?

```
Npgsql.Tests.CopyTests(Multiplexing).Import_string_array
```

Also, please keep the list ordered alphabetically.

**Comment by bghal** [comment]
blathers auth-check

**Review by rafiss — APPROVED** [review]
lgtm!

bors r+
