### PR TITLE
roachtest: deflake mixed-version backup/restore roachtest

### LINKED ISSUE #154611: roachtest: backup-restore/mixed-version failed
roachtest.backup-restore/mixed-version [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20547929?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20547929?buildTab=artifacts#/backup-restore/mixed-version) on master @ [b02bf5dafd2ab20233511b485fcadff53227819d](https://github.com/cockroachdb/cockroach/commits/b02bf5dafd2ab20233511b485fcadff53227819d):

```
(mixedversion.go:896).Run: mixed-version test failure while running step 85 (run "verify some backups"): mixed-version: error restoring backup: error waiting for job to finish: job 1111885224421097475 failed with error: version mismatch for descriptor 257, expected version 1, got 2
test artifacts and logs in: /artifacts/backup-restore/mixed-version/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>mvtDeploymentMode=shared-process</code>
 - <code>mvtVersions=v24.3.20 → v25.1.10 → v25.2.6 → v25.3.2 → v25.4.0-alpha.2-dev-b02bf5dafd2ab20233511b485fcadff53227819d (master)</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20547929/backup-restore-mixed-version/1759386408907/1759391046097)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #154350 roachtest: backup-restore/mixed-version failed [A-disaster-recovery C-test-failure O-roachtest O-robot T-disaster-recovery release-blocker]
- #153635 roachtest: backup-restore/mixed-version failed [A-disaster-recovery C-test-failure O-roachtest O-robot P-3 T-disaster-recovery branch-release-25.3.2-rc]
- #150550 roachtest: backup-restore/mixed-version failed [A-disaster-recovery B-runtime-assertions-enabled C-test-failure O-roachtest O-robot P-2 T-disaster-recovery branch-release-25.3]
- #148349 roachtest: backup-restore/mixed-version failed [A-disaster-recovery B-runtime-assertions-enabled C-test-failure O-roachtest O-robot P-3 T-disaster-recovery branch-release-25.2]
- #125677 roachtest: backup-restore/mixed-version failed [C-test-failure O-roachtest O-robot P-3 T-disaster-recovery branch-release-23.1]
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backup-restore/mixed-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-55031

### LINKED ISSUE #154850: roachtest: backup-restore/mixed-version failed
roachtest.backup-restore/mixed-version [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20563522?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20563522?buildTab=artifacts#/backup-restore/mixed-version) on master @ [14ff833383127fa428b913c5281a8a6c862e2a41](https://github.com/cockroachdb/cockroach/commits/14ff833383127fa428b913c5281a8a6c862e2a41):

```
(mixedversion.go:896).Run: mixed-version test failure while running step 84 (run "verify some backups"): mixed-version: error restoring backup: error waiting for job to finish: job 1113023681349746690 failed with error: version mismatch for descriptor 363, expected version 1, got 2
test artifacts and logs in: /artifacts/backup-restore/mixed-version/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=true</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>mvtDeploymentMode=system-only</code>
 - <code>mvtVersions=v24.3.20 → v25.1.10 → v25.2.6 → v25.4.0-alpha.2-dev-14ff833383127fa428b913c5281a8a6c862e2a41 (master)</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20563522/backup-restore-mixed-version/1759731273826/1759738463582)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #148349 roachtest: backup-restore/mixed-version failed [A-disaster-recovery B-runtime-assertions-enabled C-test-failure O-roachtest O-robot P-3 T-disaster-recovery branch-release-25.2]
- #125677 roachtest: backup-restore/mixed-version failed [C-test-failure O-roachtest O-robot P-3 T-disaster-recovery branch-release-23.1]
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backup-restore/mixed-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-55164

### PR DESCRIPTION
**Pull request by kev-cao**
As part of the 25.4 migration, all descriptors are rewritten to use the new serialization format. If this occurs during a restore, the restore will fail due to version mismatches. This test deflakes our mixed-version backup-restore roachtests to rerun the restore if it encounters that error.

Fixes: #154611

Fixes: #154850

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/mixed_version_backup.go [hunk 1]
```diff
@@ -1327,9 +1327,27 @@ func (d *BackupRestoreTestDriver) runRestore(
 	if err := d.testUtils.QueryRow(ctx, rng, restoreStmt).Scan(&jobID); err != nil {
 		return nil, "", fmt.Errorf("backup %s: error in restore statement: %w", bc.name, err)
 	}
-	if err := d.testUtils.waitForJobSuccess(ctx, l, rng, jobID, internalSystemJobs); err != nil {
-		return nil, "", err
+	if jobErr := d.testUtils.waitForJobSuccess(ctx, l, rng, jobID, internalSystemJobs); jobErr != nil {
+		if !strings.Contains(jobErr.Error(), "version mismatch for descriptor") {
```
Comment (msbutler) [inline pkg/cmd/roachtest/tests/mixed_version_backup.go]: nit: is there a way to easily inspect the test plan to check that the 25.4 upgrade is planned for the test? If it is not planned, then the test should fail.

Comment (kev-cao) [reply pkg/cmd/roachtest/tests/mixed_version_backup.go]: Added a little blurb to check for the mixed-version plan state

File: pkg/cmd/roachtest/tests/mixed_version_backup.go [hunk 2]
```diff
@@ -1267,8 +1267,9 @@ func (d *BackupRestoreTestDriver) verifyBackupCollection(
 	bc *backupCollection,
 	checkFiles bool,
 	internalSystemJobs bool,
+	mvHelper *mixedversion.Helper,
```
Comment (msbutler) [inline pkg/cmd/roachtest/tests/mixed_version_backup.go:1271]: could we instead pass the `clusterVersion` object, and do an equality check on that? that seems cleaner than passing the whole helper and less finicky than string matching.

Comment (kev-cao) [reply pkg/cmd/roachtest/tests/mixed_version_backup.go:1271]: I was thinking that explicitly handling this for mixed version tests was better since this error is only harmless in the context of a mixed version state. If it were just a cluster version, you could erroneously end up ignoring the error for a 25.4 cluster that wasn't in a mixed version state.

Comment (msbutler) [reply pkg/cmd/roachtest/tests/mixed_version_backup.go:1271]: i see. in that case it is fine to pass the helper. but could we do a cluster version comparison instead of string comparison?

Comment (kev-cao) [reply pkg/cmd/roachtest/tests/mixed_version_backup.go:1271]: Yeah I'll investigate it further when I'm back. I wasn't sure how well version comparison would work due to differences in patch releases, but I'm sure there's a way to do ordinal release version comparison only.

Comment (msbutler) [reply pkg/cmd/roachtest/tests/mixed_version_backup.go:1271]: the `AtLeast` operator is your friend: https://github.com/msbutler/cockroach/blob/master/pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go#L82

Comment (kev-cao) [reply pkg/cmd/roachtest/tests/mixed_version_backup.go:1271]: Oh I was thinking that would require an update to the test at 26.1 since we'd have to do 25.4 <= x < 26.1 (unless I constructed the 26.1 version manually for the comparison).

Comment (msbutler) [reply pkg/cmd/roachtest/tests/mixed_version_backup.go:1271]: i'm not following. I was thinking that we should only retry this if mvt helper plans to go through the 25.4 upgrade, i.e.:
`mvHelper.System.ToVersion>=25.4 & mvHelper.System.FromVersion<25.4`

Comment (kev-cao) [reply pkg/cmd/roachtest/tests/mixed_version_backup.go:1271]: Updated!

File: pkg/cmd/roachtest/tests/mixed_version_backup.go [hunk 3]
```diff
@@ -1327,9 +1330,32 @@ func (d *BackupRestoreTestDriver) runRestore(
...
 		return nil, "", fmt.Errorf("backup %s: error in restore statement: %w", bc.name, err)
 	}
-	if err := d.testUtils.waitForJobSuccess(ctx, l, rng, jobID, internalSystemJobs); err != nil {
-		return nil, "", err
+	if jobErr := d.testUtils.waitForJobSuccess(ctx, l, rng, jobID, internalSystemJobs); jobErr != nil {
+		v25_4 := version.MajorVersion{Year: 25, Ordinal: 4}
+		isUpgradeTo25_4 := mvHelper.System.ToVersion.Major().Equals(v25_4) &&
+			mvHelper.System.FromVersion.Major().LessThan(v25_4)
+
+		if mvHelper == nil || !isUpgradeTo25_4 {
```
Comment (msbutler) [inline pkg/cmd/roachtest/tests/mixed_version_backup.go]: this nil check needs to happen before you grab `mvhelper.System`

File: pkg/cmd/roachtest/tests/mixed_version_backup.go [hunk 4]
```diff
@@ -1327,9 +1330,32 @@ func (d *BackupRestoreTestDriver) runRestore(
 	if err := d.testUtils.QueryRow(ctx, rng, restoreStmt).Scan(&jobID); err != nil {
 		return nil, "", fmt.Errorf("backup %s: error in restore statement: %w", bc.name, err)
 	}
-	if err := d.testUtils.waitForJobSuccess(ctx, l, rng, jobID, internalSystemJobs); err != nil {
-		return nil, "", err
+	if jobErr := d.testUtils.waitForJobSuccess(ctx, l, rng, jobID, internalSystemJobs); jobErr != nil {
+		v25_4 := version.MajorVersion{Year: 25, Ordinal: 4}
+		isUpgradeTo25_4 := mvHelper.System.ToVersion.Major().Equals(v25_4) &&
```
Comment (msbutler) [inline pkg/cmd/roachtest/tests/mixed_version_backup.go:1338]: should it be GreaterThanOrEquals, in case the test does multiple major version upgrades beyond 25.4?

Comment (kev-cao) [reply pkg/cmd/roachtest/tests/mixed_version_backup.go:1338]: I think this is only a concern in the 25.4 upgrade? The migration only occurs during the migration to 25.4, so if you are in a restore past 25.4, you don't have to worry about descriptor versions upgrading midway through the restore.

Comment (msbutler) [reply pkg/cmd/roachtest/tests/mixed_version_backup.go:1338]: i think `mvHelper.System.ToVersion` implies the major version the test harness will _eventually_ upgrade the test to. if the test harness says the cluster starts pre 25.4 and will upgrade past 25.4, there is a chance this restore hit this upgrade.

all that being said, i'm fine leaving this as is.

Comment (kev-cao) [reply pkg/cmd/roachtest/tests/mixed_version_backup.go:1338]: Ah gotcha — for now I'll merge this in just to get this PR closed out, but I'll keep an eye on this test to see if it continues to flake.

**Review by msbutler — APPROVED** [review]

**Comment by kev-cao** [comment]
TFTR!

bors r=msbutler
