### PR TITLE
sql: deflake TestErrorDuringExtendedProtocolCommit

### LINKED ISSUE #75549: sql/tests: TestErrorDuringExtendedProtocolCommit failed
sql/tests.TestErrorDuringExtendedProtocolCommit [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4215034&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4215034&tab=artifacts#/) on master @ [5216fba6daf341de084498b544d4b89e97e54d6c](https://github.com/cockroachdb/cockroach/commits/5216fba6daf341de084498b544d4b89e97e54d6c):

```
=== RUN   TestErrorDuringExtendedProtocolCommit
    autocommit_extended_protocol_test.go:117: 
        	Error Trace:	autocommit_extended_protocol_test.go:117
        	Error:      	An error is expected but got nil.
        	Test:       	TestErrorDuringExtendedProtocolCommit
--- FAIL: TestErrorDuringExtendedProtocolCommit (1.62s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
Parameters in this failure:

- TAGS=bazel,gss
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestErrorDuringExtendedProtocolCommit.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #82010: sql/tests: TestErrorDuringExtendedProtocolCommit failed
sql/tests.TestErrorDuringExtendedProtocolCommit [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=5303229&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=5303229&tab=artifacts#/) on release-22.1 @ [4e5b7aef63f7594f7d56eb24362b9bf78b39e9a2](https://github.com/cockroachdb/cockroach/commits/4e5b7aef63f7594f7d56eb24362b9bf78b39e9a2):

```
=== RUN   TestErrorDuringExtendedProtocolCommit
    autocommit_extended_protocol_test.go:117: 
        	Error Trace:	autocommit_extended_protocol_test.go:117
        	Error:      	An error is expected but got nil.
        	Test:       	TestErrorDuringExtendedProtocolCommit
--- FAIL: TestErrorDuringExtendedProtocolCommit (1.64s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
Parameters in this failure:

- TAGS=bazel,gss
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #75549 sql/tests: TestErrorDuringExtendedProtocolCommit failed [C-test-failure O-robot T-sql-experience branch-master]
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestErrorDuringExtendedProtocolCommit.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-16168

### LINKED ISSUE #100480: sql/tests: TestErrorDuringExtendedProtocolCommit failed
sql/tests.TestErrorDuringExtendedProtocolCommit [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9399698?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9399698?buildTab=artifacts#/) on release-23.1 @ [38c8a2ad8091c3cff0f5be67a4d11e2b9d6fe521](https://github.com/cockroachdb/cockroach/commits/38c8a2ad8091c3cff0f5be67a4d11e2b9d6fe521):

```
I230403 14:54:30.303537 7674 jobs/registry.go:617  [T1,n1] 691  active version is 1000022.2-98
I230403 14:54:30.312715 7674 upgrade/upgrademanager/manager.go:708  [T1,n1] 692  running Upgrade to 1000022.2-94: "create statement_activity and transaction_activity tables"
I230403 14:54:30.312824 9294 jobs/adopt.go:261  [T1,n1] 693  job 853486044068511745: resuming execution
I230403 14:54:30.331885 9587 jobs/registry.go:1522  [T1,n1] 694  MIGRATION job 853486044068511745: stepping through state running
I230403 14:54:30.341434 9587 jobs/registry.go:1522  [T1,n1] 695  MIGRATION job 853486044068511745: stepping through state succeeded
I230403 14:54:30.369502 7674 jobs/wait.go:145  [T1,n1] 696  waited for 1 [853486044068511745] queued jobs to complete 56.710237ms
I230403 14:54:30.369722 7674 upgrade/upgrademanager/manager.go:270  [T1,n1] 697  running permanent upgrade for version 1000022.2-98
I230403 14:54:30.388847 7674 jobs/registry.go:617  [T1,n1] 698  active version is 1000022.2-98
I230403 14:54:30.396171 7674 upgrade/upgrademanager/manager.go:708  [T1,n1] 699  running Upgrade to 1000022.2-98: "change TTL for SQL Stats system tables"
I230403 14:54:30.396272 9614 jobs/adopt.go:261  [T1,n1] 700  job 853486044347695105: resuming execution
I230403 14:54:30.409987 9667 jobs/registry.go:1522  [T1,n1] 701  MIGRATION job 853486044347695105: stepping through state running
I230403 14:54:30.424543 9676 1@util/log/event_log.go:32  [T1,n1,job=MIGRATION id=853486044347695105,upgrade=1000022.2-98,intExec=set-SQLStatsTables-TTL] 702 ={"Timestamp":1680533670420018477,"EventType":"set_zone_config","Statement":"ALTER TABLE \"\".system.statement_statistics CONFIGURE ZONE USING \"gc.ttlseconds\" = $1","Tag":"CONFIGURE ZONE","User":"root","DescriptorID":42,"ApplicationName":"$ internal-set-SQLStatsTables-TTL","PlaceholderValues":["3600"],"Target":"TABLE system.public.statement_statistics","Options":["\"gc.ttlseconds\" = 3600"]}
I230403 14:54:30.428385 9539 1@util/log/event_log.go:32  [T1,n1,job=MIGRATION id=853486044347695105,upgrade=1000022.2-98,intExec=set-SQLStatsTables-TTL] 703 ={"Timestamp":1680533670425015166,"EventType":"set_zone_config","Statement":"ALTER TABLE \"\".system.transaction_statistics CONFIGURE ZONE USING \"gc.ttlseconds\" = $1","Tag":"CONFIGURE ZONE","User":"root","DescriptorID":43,"ApplicationName":"$ internal-set-SQLStatsTables-TTL","PlaceholderValues":["3600"],"Target":"TABLE system.public.transaction_statistics","Options":["\"gc.ttlseconds\" = 3600"]}
I230403 14:54:30.431242 9701 1@util/log/event_log.go:32  [T1,n1,job=MIGRATION id=853486044347695105,upgrade=1000022.2-98,intExec=set-SQLStatsTables-TTL] 704 ={"Timestamp":1680533670428634606,"EventType":"set_zone_config","Statement":"ALTER TABLE \"\".system.statement_activity CONFIGURE ZONE USING \"gc.ttlseconds\" = $1","Tag":"CONFIGURE ZONE","User":"root","DescriptorID":60,"ApplicationName":"$ internal-set-SQLStatsTables-TTL","PlaceholderValues":["3600"],"Target":"TABLE system.public.statement_activity","Options":["\"gc.ttlseconds\" = 3600"]}
I230403 14:54:30.434534 9597 1@util/log/event_log.go:32  [T1,n1,job=MIGRATION id=853486044347695105,upgrade=1000022.2-98,intExec=set-SQLStatsTables-TTL] 705 ={"Timestamp":1680533670431485277,"EventType":"set_zone_config","Statement":"ALTER TABLE \"\".system.transaction_activity CONFIGURE ZONE USING \"gc.ttlseconds\" = $1","Tag":"CONFIGURE ZONE","User":"root","DescriptorID":61,"ApplicationName":"$ internal-set-SQLStatsTables-TTL","PlaceholderValues":["3600"],"Target":"TABLE system.public.transaction_activity","Options":["\"gc.ttlseconds\" = 3600"]}
I230403 14:54:30.436042 9667 jobs/registry.go:1522  [T1,n1] 706  MIGRATION job 853486044347695105: stepping through state succeeded
I230403 14:54:30.454091 7674 jobs/wait.go:145  [T1,n1] 707  waited for 1 [853486044347695105] queued jobs to complete 57.854983ms
I230403 14:54:30.454144 7674 server/server_sql.go:1591  [T1,n1] 708  done ensuring all necessary startup migrations have run
I230403 14:54:30.454390 9551 jobs/job_scheduler.go:407  [T1,n1] 709  waiting 2m0s before scheduled jobs daemon start
I230403 14:54:30.454591 9749 kv/kvclient/rangefeed/rangefeedcache/watcher.go:335  [T1,n1] 710  tenant-settings-watcher: established range feed cache
I230403 14:54:30.455515 9689 kv/kvclient/rangefeed/rangefeedcache/watcher.go:335  [T1,n1] 711  tenant-capability-watcher: established range feed cache
I230403 14:54:30.456711 8648 13@kv/kvserver/replicate_queue.go:842  [T1,n1,replicate,s1,r58/1:/Table/5{7-8}] 712  error processing replica: 0 of 1 live stores are able to take a new replica for the range (1 already has a voter, 0 already have a non-voter); likely not enough nodes in cluster
I230403 14:54:30.457156 9779 13@kv/kvserver/replicate_queue.go:842  [T1,n1,replicate,s1,r12/1:/Table/{8-11}] 713  error processing replica: 0 of 1 live stores are able to take a new replica for the range (1 already has a voter, 0 already have a non-voter); likely not enough nodes in cluster
I230403 14:54:30.457231 9689 multitenant/tenantcapabilities/tenantcapabilitieswatcher/watcher.go:148  [T1,n1] 714  received results of a full table scan for tenant capabilities
I230403 14:54:30.458111 9747 server/auto_upgrade.go:78  [T1,n1] 715  no need to upgrade, cluster already at the newest version
I230403 14:54:30.460567 8714 13@kv/kvserver/replicate_queue.go:842  [T1,n1,replicate,s1,r52/1:/Table/5{1-2}] 716  error processing replica: 0 of 1 live stores are able to take a new replica for the range (1 already has a voter, 0 already have a non-voter); likely not enough nodes in cluster
I230403 14:54:30.461662 9553 sql/syntheticprivilegecache/cache.go:195  [T1,n1] 717  warmed privileges for virtual tables in 7.234511ms
I230403 14:54:30.478886 8636 13@kv/kvserver/replicate_queue.go:842  [T1,n1,replicate,s1,r4/1:/System{/tsd-tse}] 718  error processing replica: 0 of 1 live stores are able to take a new replica for the range (1 already has a voter, 0 already have a non-voter); likely not enough nodes in cluster
I230403 14:54:30.487876 8053 3@pebble/event.go:734  [n1,s1,pebble] 719  [JOB 7] WAL created 000006
I230403 14:54:30.490568 7674 1@server/server_sql.go:1678  [T1,n1] 720  serving sql connections
I230403 14:54:30.491454 7674 testutils/testcluster/testcluster.go:1356  [-] 721  WaitForFullReplication
I230403 14:54:30.491484 7674 testutils/testcluster/testcluster.go:1360  [-] 722  WaitForFullReplication took: 208ns
I230403 14:54:30.491826 9811 2@rpc/context.go:2564  [T1,n1,rnode=1,raddr=127.0.0.1:36625,class=default,rpc] 723  connection is now ready
    autocommit_extended_protocol_test.go:187: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/sql/tests/autocommit_extended_protocol_test.go:187
        	Error:      	An error is expected but got nil.
        	Test:       	TestErrorDuringExtendedProtocolCommit
I230403 14:54:30.508934 7674 testutils/testcluster/testcluster.go:144  [-] 724  TestCluster quiescing nodes
W230403 14:54:30.509124 9427 kv/kvserver/intentresolver/intent_resolver.go:826  [-] 725  failed to gc transaction record: could not GC completed transaction anchored at /Table/15/1/853486043560902657/0: node unavailable; try another peer
I230403 14:54:30.509187 9811 rpc/context.go:2302  [T1,n1,rnode=1,raddr=127.0.0.1:36625,class=default,rpc] 726  connection heartbeat loop ended with err: <nil>
I230403 14:54:30.509294 7977 server/start_listen.go:103  [T1,n1] 727  server shutting down: instructing cmux to stop accepting
W230403 14:54:30.509638 8139 sql/sqlliveness/slinstance/slinstance.go:312  [n1] 728  exiting heartbeat loop
W230403 14:54:30.509689 8139 sql/sqlliveness/slinstance/slinstance.go:297  [n1] 729  exiting heartbeat loop
E230403 14:54:30.509706 8139 server/server_sql.go:505  [n1] 730  failed to run update of instance with new session ID: node unavailable; try another peer
I230403 14:54:30.510008 8527 jobs/registry.go:1522  [T1,n1] 731  AUTO SPAN CONFIG RECONCILIATION job 853486041506578433: stepping through state succeeded
E230403 14:54:30.510131 8527 jobs/registry.go:952  [T1,n1] 732  error getting live session: node unavailable; try another peer
E230403 14:54:30.512797 8318 sql/stats/automatic_stats.go:578  [T1,n1] 733  failed to get tables for automatic stats: get-tables: node unavailable; try another peer
I230403 14:54:30.512874 8318 sql/stats/automatic_stats.go:507  [T1,n1] 734  quiescing auto stats refresher
W230403 14:54:30.516696 9480 jobs/adopt.go:514  [T1,n1] 735  could not clear job claim: clear-job-claim: failed to send RPC: sending to all replicas failed; last error: ba: Scan [/Table/15/1/102,/Table/15/1/103), [txn: c7561e2a], [can-forward-ts] RPC error: node unavailable; try another peer
--- FAIL: TestErrorDuringExtendedProtocolCommit (1.13s)
```
<p>Parameters: <code>TAGS=bazel,gss</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #82010 sql/tests: TestErrorDuringExtendedProtocolCommit failed [C-test-failure O-robot T-sql-queries T-sql-sessions branch-release-22.1]
- #75549 sql/tests: TestErrorDuringExtendedProtocolCommit failed [C-test-failure O-robot T-sql-sessions branch-master]
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestErrorDuringExtendedProtocolCommit.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-26458

### PR DESCRIPTION
**Pull request by rafiss**
This uses the traceID to make sure that the error is injected for the correct auto-commit. Previously, internal queries could race with the query we want to error out on.

fixes https://github.com/cockroachdb/cockroach/issues/75549
backport fixes https://github.com/cockroachdb/cockroach/issues/100480
backport fixes https://github.com/cockroachdb/cockroach/issues/82010

Release note: None

### CODE REVIEW

File: pkg/sql/tests/autocommit_extended_protocol_test.go [hunk 1]
```diff
@@ -156,18 +158,22 @@ func TestErrorDuringExtendedProtocolCommit(t *testing.T) {
...
 			if strings.Contains(stmt, "SELECT 'cat'") {
 				shouldErrorOnAutoCommit.Set(true)
+				traceID = tracing.SpanFromContext(ctx).TraceID()
 			}
 		},
 		BeforeAutoCommit: func(ctx context.Context, stmt string) error {
 			if shouldErrorOnAutoCommit.Get() {
 				shouldErrorOnAutoCommit.Set(false)
-				return errors.New("injected error")
+				if traceID == tracing.SpanFromContext(ctx).TraceID() {
```
Comment (ecwall) [inline pkg/sql/tests/autocommit_extended_protocol_test.go:174]: Can you add a comment explaining why the traceID needs to match?

**Review by ecwall — APPROVED** [review]

File: pkg/sql/tests/autocommit_extended_protocol_test.go (hunk 1 above)
Comment (rafiss) [reply pkg/sql/tests/autocommit_extended_protocol_test.go:178]: done

**Comment by rafiss** [comment]
tftr!

bors r=ecwal

**Comment by mgartner** [comment]
blathers backport 23.1.0
