### PR TITLE
sql: fix double-call to res.SetErr() on network error

### LINKED ISSUE #23694: panic encountered when ctrl+c-ing a query
I have a 4 node roachprod cluster with a TPC-C 100 warehouse dataset, loaded with
` bin/workload fixtures load tpcc  --warehouses=100 'postgres://root@35.190.154.175:26257?sslmode=disable'`

I ran the following query:
`(SELECT ol_w_id, ol_d_id, ol_o_id FROM order_line WHERE ol_delivery_d IS NULL ORDER BY ol_w_id, ol_d_id, ol_o_id DESC)                                                         EXCEPT ALL                                                                                                                                                                                                  (SELECT o_w_id, o_d_id, o_id FROM "order"@primary ORDER BY o_w_id, o_d_id, o_id DESC)`

After approximately 10 seconds, I knew I had done something wrong in constructing my query since I wanted a query that finished quickly, so I ctrl+c-ed out. This caused the node to crash with the following log message:

```
E180310 00:22:29.377528 917 sql/conn_executor.go:512  [n1,client=10.142.0.10:60920,user=root] a SQL panic has occurred while executing "(SELECT ol_w_id, ol_d_id, ol_o_id FROM order_line WHERE ol_delivery_d IS NULL ORDER BY ol_w_id, ol_d_id, ol_o_id DESC) EXCEPT ALL (SELECT o_w_id, o_d_id, o_id FROM \"order\"@primary ORDER BY o_w_id, o_d_id, o_id DESC)": can't overwrite err: write tcp 10.142.0.9:26257->10.142.0.10:60920: write: connection reset by peer with err: write tcp 10.142.0.9:26257->10.142.0.10:60920: write: connection reset by peer
E180310 00:22:29.377757 917 util/log/crash_reporting.go:182  [n1,client=10.142.0.10:60920,user=root] a panic has occurred!
E180310 00:22:29.378065 917 util/log/crash_reporting.go:440  [n1,client=10.142.0.10:60920,user=root] Reported as error 8f4f265d29474b49881eea0716a63983
panic: can't overwrite err: write tcp 10.142.0.9:26257->10.142.0.10:60920: write: connection reset by peer with err: write tcp 10.142.0.9:26257->10.142.0.10:60920: write: connection reset by peer [recovered]
        panic: panic while executing 1 statements: (SELECT _, _, _ FROM _ WHERE _ IS _ ORDER BY _, _, _ DESC) EXCEPT ALL (SELECT _, _, _ FROM _@_ ORDER BY _, _, _ DESC); caused by can't overwrite err: write tcp 10.142.0.9:26257->10.142.0.10:60920: write: connection reset by peer with err: write tcp 10.142.0.9:26257->10.142.0.10:60920: write: connection reset by peer

goroutine 917 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc426576000, 0x2661c60, 0xc426a08500, 0x2038c00, 0xc426da0110)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:526 +0x365
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func2(0xc426576000, 0x2661c60, 0xc426a08500)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:487 +0x61
panic(0x2038c00, 0xc426da0110)
        /usr/local/go/src/runtime/panic.go:505 +0x229
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*commandResult).SetError(0xc4265c8c80, 0x2643460, 0xc424f10190)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/command_result.go:187 +0x134
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc426576000, 0x2661c60, 0xc420b2dac0, 0x26645a0, 0xc420b2da40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:556 +0x853
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc426576000, 0x2661c60, 0xc420b2dac0, 0x26645a0, 0xc420b2da40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:342 +0x9c7
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc426576000, 0x2661c60, 0xc420b2dac0, 0x26645a0, 0xc420b2da40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:83 +0x358
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc426576000, 0x2661c60, 0xc426a08500, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:908 +0x1cc8
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc4203d7dc0, 0x2661c60, 0xc426a08500, 0xc426573054, 0x8, 0xc426573009, 0x4, 0x0, 0x0, 0x264b120, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:489 +0xf53
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func3(0xc4203d7dc0, 0x2661c60, 0xc426a08500, 0xc420349500, 0x5400, 0x15000, 0xc420a42cd0, 0xc426e52690, 0xc426cd8c50, 0xc426e52680)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:260 +0xfc
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:259 +0xf14
(END)

```

The cockroach binary is the current head of the release-2.0 branch, so this is worrying:
```
Build Tag:    v2.0-beta.20180305-206-g2329ca0
Build Time:   2018/03/09 15:55:07
Distribution: CCL
Platform:     linux amd64
Go Version:   go1.10
C Compiler:   4.2.1 Compatible Clang 3.8.0 (tags/RELEASE_380/final)
Build SHA-1:  2329ca0f1e926bb7dba8abd558bc4631bbddd04c
Build Type:   development
```

Assigned to @jordanlewis for triage.

### PR DESCRIPTION
**Pull request by andreimatei**
sql: fix double-call to res.SetErr() on network error  …
Before this patch, when an attempt to write a query result to the
network was encountering a network error, we would call res.SetErr()
twice, which is prohibited and panicked. This happened when the DistSQL
engine was used, because execWithDistSQLEngine() was already setting the
error and some higher-level code was setting it again.
This was caused by inconsistent handling of communication errors between
the two engines - when executing with DistSQL, we would both set the
error on the result and also return it, whereas when executing with
local we would only return it, and then there was higher-level code
which set the error again. This patch makes the local execution behave
like DistSQL.

Fixes #23694

Release note: Fix a bug where closing a connection in the middle of
executing a query sometimes crashed the server.

### CODE REVIEW

**Comment by andreimatei** [comment]
Will cherry-pick this in 2.0.

File: pkg/server/config.go [hunk 1]
```diff
@@ -76,6 +76,8 @@ const (
 
 	minimumNetworkFileDescriptors     = 256
 	recommendedNetworkFileDescriptors = 5000
+
+	defaultConnResultsBufferBytes = 16 << 10
```
Comment (knz) [inline pkg/server/config.go]: nit: 

```go
defaultConnResultsBufferBytes = 16 << 10 // 16kib
```

**Review by knz — APPROVED** [review]

**Comment by andreimatei** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/server/config.go, line 80 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23753#-L7Qu-S9Vo91HZ-qtSPv-r2-80:-L7QzsPk6RJxBfqbKMMj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ac49a569ab8ae5e94c9539ffdc75b68d206e1df/pkg/server/config.go#L80)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: 

```go
defaultConnResultsBufferBytes = 16 << 10 // 16kib
```

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23753)*
